Repository vesoft-inc/nebula, pull requests merged in 2019-11, with the labels that each got.

#1197 Fixed the bug when using multi edge
  src/graph/GoExecutor.cpp
  src/graph/test/GoTest.cpp
Labels: ready-for-testing

#1146 Add error log and modify the oss domain name
  build_dep.sh
  docs/manual-CN/3.build-develop-and-administration/1.build/1.build-source-code.md
  docs/manual-EN/3.build-develop-and-administration/1.build/1.build-source-code.md
  src/graph/ExecutionPlan.cpp
  src/graph/InsertEdgeExecutor.cpp
  src/graph/InsertVertexExecutor.cpp
  src/meta/client/MetaClient.cpp
Labels: ready-for-testing

#1156 Update the load_data_interval_secs to be 1 second
  src/meta/client/MetaClient.cpp
Labels: ready-for-testing

#1196 [doc]fix query doc errors
  docs/manual-CN/2.query-language/0.README.md
  docs/manual-CN/2.query-language/1.data-types/data-types.md
  docs/manual-CN/2.query-language/4.statement-syntax/2.data-query-and-manipulation-statements/insert-vertex-syntax.md
  docs/manual-CN/2.query-language/4.statement-syntax/2.data-query-and-manipulation-statements/update-vertex-edge-syntax.md
  docs/manual-CN/2.query-language/4.statement-syntax/2.data-query-and-manipulation-statements/yield-syntax.md
  docs/manual-CN/2.query-language/4.statement-syntax/3.utility-statements/describe-syntax.md
  docs/manual-CN/2.query-language/4.statement-syntax/3.utility-statements/show-syntax.md
  docs/manual-CN/2.query-language/4.statement-syntax/3.utility-statements/use-syntax.md
  docs/manual-CN/2.query-language/4.statement-syntax/4.graph-algorithms/find-path-syntax.md
  docs/manual-EN/2.query-language/1.data-types/data-types.md
  docs/manual-EN/2.query-language/4.statement-syntax/2.data-query-and-manipulation-statements/insert-edge-syntax.md
  docs/manual-EN/2.query-language/4.statement-syntax/2.data-query-and-manipulation-statements/insert-vertex-syntax.md
  docs/manual-EN/2.query-language/4.statement-syntax/2.data-query-and-manipulation-statements/update-vertex-edge-syntax.md
  docs/manual-EN/2.query-language/4.statement-syntax/2.data-query-and-manipulation-statements/where-syntax.md
  docs/manual-EN/2.query-language/4.statement-syntax/2.data-query-and-manipulation-statements/yield-syntax.md
  docs/manual-EN/2.query-language/4.statement-syntax/3.utility-statements/describe-syntax.md
  docs/manual-EN/2.query-language/4.statement-syntax/3.utility-statements/show-syntax.md
  docs/manual-EN/2.query-language/4.statement-syntax/3.utility-statements/use-syntax.md
  docs/manual-EN/2.query-language/4.statement-syntax/4.graph-algorithms/find-path-syntax.md
Labels: ready-for-testing

#1193 [doc]Fix doc minor errors
  docs/manual-CN/2.query-language/3.language-structure/property-reference.md
  docs/manual-CN/2.query-language/4.statement-syntax/1.data-definition-statements/alter-tag-edge-syntax.md
  docs/manual-CN/2.query-language/4.statement-syntax/1.data-definition-statements/create-space-syntax.md
  docs/manual-CN/2.query-language/4.statement-syntax/1.data-definition-statements/create-tag-edge-syntax.md
  docs/manual-CN/2.query-language/4.statement-syntax/2.data-query-and-manipulation-statements/fetch-syntax.md
  docs/manual-CN/2.query-language/4.statement-syntax/2.data-query-and-manipulation-statements/go-syntax.md
  docs/manual-CN/3.build-develop-and-administration/3.deploy-and-administrations/server-administration/storage-service-administration/storage-metrics.md
  docs/manual-EN/2.query-language/3.language-structure/property-reference.md
  docs/manual-EN/2.query-language/3.language-structure/schema-object-names.md
  docs/manual-EN/2.query-language/3.language-structure/statement-composition.md
  docs/manual-EN/2.query-language/4.statement-syntax/1.data-definition-statements/alter-tag-edge-syntax.md
  docs/manual-EN/2.query-language/4.statement-syntax/1.data-definition-statements/create-space-syntax.md
  docs/manual-EN/2.query-language/4.statement-syntax/1.data-definition-statements/create-tag-edge-syntax.md
  docs/manual-EN/2.query-language/4.statement-syntax/1.data-definition-statements/drop-edge-syntax.md
  docs/manual-EN/2.query-language/4.statement-syntax/1.data-definition-statements/drop-tag-syntax.md
  docs/manual-EN/2.query-language/4.statement-syntax/2.data-query-and-manipulation-statements/fetch-syntax.md
  docs/manual-EN/2.query-language/4.statement-syntax/2.data-query-and-manipulation-statements/go-syntax.md
Labels: ready-for-testing

#1163 Push new tag of docker image when releasing nebula version
  .github/workflows/build.yaml
  .github/workflows/docker.yaml
  README.md
  docker/README.md
  docker/build-images.sh
Labels: ready-for-testing

#1200 Add local_ip option to etc/nebula-graphd.conf.default
  etc/nebula-graphd.conf.default
Labels: ready-for-testing

#1194 Scan through the last wal in case wal is cut off.
  src/kvstore/wal/FileBasedWal.cpp
  src/kvstore/wal/FileBasedWal.h
  src/kvstore/wal/test/FileBasedWalTest.cpp
Labels: ready-for-testing

#1204 Issue #1203 fixed the possible crash.
  src/graph/GoExecutor.cpp
Labels: ready-for-testing

#1201 Fixed a compile warning when using the Clang 8.0.
  src/common/filter/Expressions.cpp
  src/common/filter/Expressions.h
Labels: ready-for-testing

#1212 Fixed the possible crash(heap-use-after-free).
  src/meta/processors/configMan/SetConfigProcessor.cpp
Labels: ready-for-testing

#1208 [doc]sh to bash
  docs/manual-CN/1.overview/2.quick-start/1.get-started.md
  docs/manual-CN/1.overview/2.quick-start/2.trouble-shooting.md
  docs/manual-CN/3.build-develop-and-administration/1.build/1.build-source-code.md
  docs/manual-CN/3.build-develop-and-administration/1.build/2.build-by-docker.md
  docs/manual-CN/3.build-develop-and-administration/3.deploy-and-administrations/server-administration/storage-service-administration/storage-metrics.md
  docs/manual-CN/4.contributions/how-to-contribute.md
  docs/manual-EN/1.overview/2.quick-start/1.get-started.md
  docs/manual-EN/3.build-develop-and-administration/1.build/1.build-source-code.md
  docs/manual-EN/3.build-develop-and-administration/1.build/2.build-by-docker.md
  docs/manual-EN/3.build-develop-and-administration/3.deploy-and-administrations/deployment/deploy-cluster.md
  docs/manual-EN/3.build-develop-and-administration/3.deploy-and-administrations/server-administration/storage-service-administration/storage-metrics.md
  docs/manual-EN/4.contributions/how-to-contribute.md
Labels: ready-for-testing

#1202 [doc]update doc rc1
  docs/manual-CN/0.about-this-manual.md
  docs/manual-CN/1.overview/1.concepts/1.data-model.md
  docs/manual-CN/1.overview/1.concepts/2.nGQL-overview.md
  docs/manual-CN/1.overview/2.quick-start/1.get-started.md
  docs/manual-CN/1.overview/2.quick-start/2.trouble-shooting.md
  docs/manual-CN/1.overview/3.design-and-architecture/1.design-and-architecture.md
  docs/manual-CN/2.query-language/2.functions-and-operators/limit-syntax.md
  docs/manual-CN/3.build-develop-and-administration/1.build/1.build-source-code.md
  docs/manual-CN/3.build-develop-and-administration/3.deploy-and-administrations/server-administration/storage-service-administration/storage-balance.md
  docs/manual-EN/1.overview/2.quick-start/2.trouble-shooting.md
  docs/manual-EN/2.query-language/2.functions-and-operators/limit-syntax.md
  docs/manual-EN/3.build-develop-and-administration/1.build/1.build-source-code.md
  docs/manual-EN/3.build-develop-and-administration/3.deploy-and-administrations/server-administration/configuration-statements/configs-syntax.md
Labels: ready-for-testing

#1086 Support "show parts" command
  share/resources/completion.json
  src/common/network/NetworkUtils.cpp
  src/common/network/NetworkUtils.h
  src/common/network/test/NetworkUtilsTest.cpp
  src/graph/ShowExecutor.cpp
  src/graph/ShowExecutor.h
  src/graph/test/SchemaTest.cpp
  src/graph/test/TestEnv.cpp
  src/graph/test/TestEnv.h
  src/interface/meta.thrift
  src/meta/CMakeLists.txt
  src/meta/MetaServiceHandler.cpp
  src/meta/MetaServiceHandler.h
  src/meta/client/MetaClient.cpp
  src/meta/client/MetaClient.h
  src/meta/processors/partsMan/ListPartsProcessor.cpp
  src/meta/processors/partsMan/ListPartsProcessor.h
  src/meta/test/BalancerTest.cpp
  src/meta/test/ProcessorTest.cpp
  src/meta/test/TestUtils.h
  src/parser/AdminSentences.cpp
  src/parser/AdminSentences.h
  src/parser/parser.yy
  src/parser/scanner.lex
  src/parser/test/ParserTest.cpp
  src/parser/test/ScannerTest.cpp
Labels: ready-for-testing

#1205 fix leader was not elected in meta::TestUtils, change host expired time in millisecond
  src/meta/ActiveHostsMan.cpp
  src/meta/ActiveHostsMan.h
  src/meta/processors/admin/HBProcessor.cpp
  src/meta/processors/partsMan/ListHostsProcessor.cpp
  src/meta/test/ActiveHostsManTest.cpp
  src/meta/test/ConfigManTest.cpp
  src/meta/test/TestUtils.h
Labels: ready-for-testing

#1161 Update the interfaces about folly::future and fbthrift constructor
  src/graph/DeleteVertexExecutor.cpp
  src/kvstore/Part.cpp
  src/kvstore/raftex/Host.cpp
  src/kvstore/raftex/RaftPart.cpp
  src/meta/MetaHttpDownloadHandler.cpp
  src/meta/MetaHttpIngestHandler.cpp
  src/meta/client/MetaClient.cpp
  src/meta/processors/admin/AdminClient.cpp
  src/meta/processors/admin/Balancer.cpp
  src/meta/processors/usersMan/AuthenticationProcessor.cpp
  src/meta/test/AdminClientTest.cpp
  src/meta/test/AuthProcessorTest.cpp
  src/meta/test/BalanceIntegrationTest.cpp
  src/meta/test/HBProcessorTest.cpp
  src/meta/test/MetaClientTest.cpp
  src/meta/test/ProcessorTest.cpp
  src/meta/test/TestUtils.h
  src/storage/GetProcessor.cpp
  src/storage/QueryEdgeKeysProcessor.cpp
  src/storage/StorageHttpDownloadHandler.cpp
  src/storage/client/StorageClient.inl
  src/storage/test/AddEdgesTest.cpp
  src/storage/test/DeleteEdgesTest.cpp
  src/storage/test/QueryEdgeKeysTest.cpp
  src/storage/test/StorageClientTest.cpp
  src/tools/storage-perf/StoragePerfTool.cpp
Labels: ready-for-testing

#1207 Support id in show tags and show edges
  src/graph/ShowExecutor.cpp
  src/graph/test/SchemaTest.cpp
Labels: ready-for-testing

#1198 [doc]fix build and contribute chapter doc errors
  docs/manual-CN/3.build-develop-and-administration/1.build/1.build-source-code.md
  docs/manual-CN/3.build-develop-and-administration/1.build/2.build-by-docker.md
  docs/manual-CN/3.build-develop-and-administration/2.develop-and-interface/kv-interfaces.md
  docs/manual-CN/3.build-develop-and-administration/3.deploy-and-administrations/deployment/deploy-cluster-on-docker.md
  docs/manual-CN/3.build-develop-and-administration/3.deploy-and-administrations/deployment/deploy-cluster.md
  docs/manual-CN/3.build-develop-and-administration/3.deploy-and-administrations/server-administration/configuration-statements/configs-syntax.md
  docs/manual-CN/3.build-develop-and-administration/3.deploy-and-administrations/server-administration/storage-service-administration/data-import/download-and-ingest-sst-file.md
  docs/manual-CN/3.build-develop-and-administration/3.deploy-and-administrations/server-administration/storage-service-administration/storage-balance.md
  docs/manual-CN/3.build-develop-and-administration/3.deploy-and-administrations/server-administration/storage-service-administration/storage-metrics.md
  docs/manual-CN/4.contributions/contribute-to-documentation.md
  docs/manual-CN/4.contributions/cpp-coding-style.md
  docs/manual-EN/3.build-develop-and-administration/0.README.md
  docs/manual-EN/3.build-develop-and-administration/1.build/1.build-source-code.md
  docs/manual-EN/3.build-develop-and-administration/2.develop-and-interface/kv-interfaces.md
  docs/manual-EN/3.build-develop-and-administration/3.deploy-and-administrations/README.md
  docs/manual-EN/3.build-develop-and-administration/3.deploy-and-administrations/deployment/deploy-cluster-on-docker.md
  docs/manual-EN/3.build-develop-and-administration/3.deploy-and-administrations/deployment/deploy-cluster.md
  docs/manual-EN/3.build-develop-and-administration/3.deploy-and-administrations/server-administration/account-management-statements/drop-user-syntax.md
  docs/manual-EN/3.build-develop-and-administration/3.deploy-and-administrations/server-administration/configuration-statements/configs-syntax.md
  docs/manual-EN/3.build-develop-and-administration/3.deploy-and-administrations/server-administration/storage-service-administration/data-import/download-and-ingest-sst-file.md
  docs/manual-EN/3.build-develop-and-administration/3.deploy-and-administrations/server-administration/storage-service-administration/storage-balance.md
  docs/manual-EN/3.build-develop-and-administration/3.deploy-and-administrations/server-administration/storage-service-administration/storage-metrics.md
  docs/manual-EN/4.contributions/contribute-to-documentation.md
  src/tools/spark-sstfile-generator/README.md
Labels: ready-for-testing

#1168 Downgrade java client jdk version from 1.8 to 1.6
  src/client/java/pom.xml
  src/client/java/src/main/java/com/vesoft/nebula/graph/client/GraphClientImpl.java
  src/client/java/src/main/java/com/vesoft/nebula/graph/client/ResultSet.java
  src/tools/native-client/pom.xml
  src/tools/native-client/src/main/cpp/com_vesoft_client_NativeClient.h
  src/tools/native-client/src/main/java/com/vesoft/client/NativeClient.java
  src/tools/native-client/src/main/java/com/vesoft/client/NativeClientResourceLoader.java
Labels: ready-for-testing

#1172 Clear the code associated with Add/Remove Hosts
  src/graph/AddHostsExecutor.cpp
  src/graph/AddHostsExecutor.h
  src/graph/CMakeLists.txt
  src/graph/Executor.cpp
  src/graph/PermissionManager.h
  src/graph/RemoveHostsExecutor.cpp
  src/graph/RemoveHostsExecutor.h
  src/graph/test/UpdateTestBase.h
  src/interface/meta.thrift
  src/meta/CMakeLists.txt
  src/meta/MetaServiceHandler.cpp
  src/meta/MetaServiceHandler.h
  src/meta/client/MetaClient.cpp
  src/meta/client/MetaClient.h
  src/meta/processors/partsMan/AddHostsProcessor.cpp
  src/meta/processors/partsMan/AddHostsProcessor.h
  src/meta/processors/partsMan/ListHostsProcessor.cpp
  src/meta/processors/partsMan/RemoveHostsProcessor.cpp
  src/meta/processors/partsMan/RemoveHostsProcessor.h
  src/meta/test/MetaClientTest.cpp
  src/meta/test/ProcessorTest.cpp
  src/meta/test/TestUtils.h
  src/parser/AdminSentences.cpp
  src/parser/AdminSentences.h
  src/parser/Sentence.h
  src/parser/parser.yy
  src/parser/test/ParserTest.cpp
  src/storage/test/StorageClientTest.cpp
Labels: ready-for-testing

#1227 Support to create hard link for current WAL
  src/kvstore/raftex/RaftPart.cpp
  src/kvstore/raftex/RaftPart.h
  src/kvstore/wal/FileBasedWal.cpp
  src/kvstore/wal/FileBasedWal.h
  src/kvstore/wal/Wal.h
  src/kvstore/wal/test/FileBasedWalTest.cpp
Labels: ready-for-testing

#1242 Fix failed SchemaTest
  src/graph/test/SchemaTest.cpp
Labels: ready-for-testing

#1221 add gflags to control max_edge_returned_per_vertex
  src/storage/QueryBaseProcessor.cpp
  src/storage/QueryBaseProcessor.inl
  src/storage/test/QueryBoundTest.cpp
Labels: ready-for-testing

#1248 Enlarge the default block cache size
  src/kvstore/RocksEngineConfig.cpp
Labels: ready-for-testing

#1256 Change graphd/metad/storaged's vlog level config with default value 0.
  etc/nebula-metad.conf.default
  etc/nebula-storaged.conf.default
Labels: ready-for-testing

#749 Implement groupby
  share/resources/completion.json
  src/common/filter/Expressions.cpp
  src/common/filter/Expressions.h
  src/graph/AggregateFunction.h
  src/graph/CMakeLists.txt
  src/graph/Executor.cpp
  src/graph/Executor.h
  src/graph/FetchExecutor.cpp
  src/graph/GoExecutor.cpp
  src/graph/GroupByExecutor.cpp
  src/graph/GroupByExecutor.h
  src/graph/InterimResult.cpp
  src/graph/InterimResult.h
  src/graph/SchemaHelper.cpp
  src/graph/SchemaHelper.h
  src/graph/TraverseExecutor.cpp
  src/graph/YieldExecutor.cpp
  src/graph/YieldExecutor.h
  src/graph/test/GroupByLimitTest.cpp
  src/graph/test/YieldTest.cpp
  src/interface/common.thrift
  src/parser/Clauses.cpp
  src/parser/Clauses.h
  src/parser/Sentence.h
  src/parser/TraverseSentences.cpp
  src/parser/TraverseSentences.h
  src/parser/parser.yy
  src/parser/scanner.lex
  src/parser/test/ParserTest.cpp
Labels: R201910_RC2, ready-for-testing

#1238 Balance stop
  src/graph/BalanceExecutor.cpp
  src/graph/BalanceExecutor.h
  src/interface/meta.thrift
  src/kvstore/Part.cpp
  src/kvstore/raftex/RaftPart.cpp
  src/meta/client/MetaClient.cpp
  src/meta/client/MetaClient.h
  src/meta/processors/admin/BalancePlan.cpp
  src/meta/processors/admin/BalancePlan.h
  src/meta/processors/admin/BalanceProcessor.cpp
  src/meta/processors/admin/BalanceTask.cpp
  src/meta/processors/admin/BalanceTask.h
  src/meta/processors/admin/Balancer.cpp
  src/meta/processors/admin/Balancer.h
  src/meta/test/BalancerTest.cpp
  src/parser/AdminSentences.h
  src/parser/parser.yy
  src/parser/scanner.lex
  src/parser/test/ParserTest.cpp
  src/storage/AdminProcessor.h
Labels: ready-for-testing

#1241 Fix some bug during balance
  src/kvstore/raftex/Host.cpp
  src/kvstore/raftex/Host.h
  src/kvstore/raftex/RaftPart.cpp
  src/kvstore/raftex/test/LearnerTest.cpp
  src/kvstore/wal/FileBasedWal.cpp
  src/kvstore/wal/FileBasedWal.h
  src/kvstore/wal/test/FileBasedWalTest.cpp
  src/meta/processors/admin/AdminClient.cpp
  src/meta/test/ConfigManTest.cpp
Labels: ready-for-testing

#1240 [doc]rocksdb compaction flush
  docs/manual-CN/3.build-develop-and-administration/3.deploy-and-administrations/server-administration/configuration-statements/rocksdb-compaction-flush.md
  docs/manual-CN/README.md
  docs/manual-EN/3.build-develop-and-administration/3.deploy-and-administrations/server-administration/configuration-statements/rocksdb-compaction-flush.md
  docs/manual-EN/README.md
Labels: ready-for-testing

#1239 [doc]delete edge
  docs/manual-CN/2.query-language/4.statement-syntax/2.data-query-and-manipulation-statements/delete-edge-syntax.md
  docs/manual-CN/2.query-language/4.statement-syntax/2.data-query-and-manipulation-statements/delete-vertex-syntax.md
  docs/manual-CN/README.md
  docs/manual-EN/2.query-language/4.statement-syntax/2.data-query-and-manipulation-statements/delete-edge-syntax.md
  docs/manual-EN/README.md
Labels: ready-for-testing

#1247 [doc]proofread doc overview
  docs/manual-EN/0.about-this-manual.md
  docs/manual-EN/1.overview/1.concepts/1.data-model.md
  docs/manual-EN/1.overview/3.design-and-architecture/1.design-and-architecture.md
  docs/manual-EN/1.overview/3.design-and-architecture/2.storage-design.md
Labels: ready-for-testing

#1224 [doc]Get start update
  docs/manual-CN/1.overview/2.quick-start/1.get-started.md
  docs/manual-CN/2.query-language/4.statement-syntax/1.data-definition-statements/drop-tag-syntax.md
  docs/manual-CN/3.build-develop-and-administration/3.deploy-and-administrations/server-administration/storage-service-administration/storage-metrics.md
  docs/manual-EN/1.overview/2.quick-start/1.get-started.md
  docs/manual-EN/2.query-language/4.statement-syntax/1.data-definition-statements/drop-tag-syntax.md
  docs/manual-EN/3.build-develop-and-administration/3.deploy-and-administrations/server-administration/storage-service-administration/storage-metrics.md
Labels: ready-for-testing

#1237 [doc]add glog curl command EN
  docs/manual-CN/README.md
  docs/manual-EN/3.build-develop-and-administration/3.deploy-and-administrations/server-administration/configuration-statements/log.md
  docs/manual-EN/README.md
Labels: ready-for-testing

#1230 [doc] Fix docker deployment and csv importer related documents
  docs/manual-CN/3.build-develop-and-administration/1.build/1.build-source-code.md
  docs/manual-CN/3.build-develop-and-administration/1.build/2.build-by-docker.md
  docs/manual-CN/3.build-develop-and-administration/3.deploy-and-administrations/deployment/deploy-cluster-on-docker.md
  docs/manual-CN/3.build-develop-and-administration/3.deploy-and-administrations/server-administration/storage-service-administration/data-import/import-csv-file.md
  docs/manual-EN/3.build-develop-and-administration/1.build/2.build-by-docker.md
  docs/manual-EN/3.build-develop-and-administration/3.deploy-and-administrations/deployment/deploy-cluster-on-docker.md
  docs/manual-EN/3.build-develop-and-administration/3.deploy-and-administrations/server-administration/storage-service-administration/data-import/import-csv-file.md
  etc/nebula-metad.conf.default
Labels: ready-for-testing

#1217 fix leader info is not set when minority storage service is down
  src/kvstore/wal/test/FileBasedWalTest.cpp
  src/storage/client/StorageClient.h
  src/storage/test/StorageClientTest.cpp
Labels: ready-for-testing

#1265 Fix bug when ingesting files
  src/kvstore/NebulaStore.cpp
Labels: ready-for-testing

#1257 Refactored some code.
  src/meta/processors/partsMan/ListHostsProcessor.cpp
  src/storage/BaseProcessor.h
  src/storage/BaseProcessor.inl
Labels: ready-for-testing

#1219 Fix insert value should put order properties #1215
  src/graph/Executor.cpp
  src/graph/Executor.h
  src/graph/InsertEdgeExecutor.cpp
  src/graph/InsertEdgeExecutor.h
  src/graph/InsertVertexExecutor.cpp
  src/graph/InsertVertexExecutor.h
  src/graph/test/DataTest.cpp
Labels: ready-for-testing

#1276 Fixed possible data races.
  src/kvstore/NebulaStore.cpp
Labels: ready-for-testing

#1261 [doc]Balance stop
  docs/manual-CN/3.build-develop-and-administration/3.deploy-and-administrations/server-administration/storage-service-administration/storage-balance.md
  docs/manual-EN/3.build-develop-and-administration/3.deploy-and-administrations/server-administration/storage-service-administration/storage-balance.md
Labels: ready-for-testing

#1262 [doc]show parts
  docs/manual-CN/2.query-language/4.statement-syntax/3.utility-statements/show-syntax.md
  docs/manual-EN/2.query-language/4.statement-syntax/3.utility-statements/show-syntax.md
Labels: ready-for-testing

#1283 [doc]update TOC link
  docs/manual-CN/README.md
  docs/manual-EN/README.md
Labels: ready-for-testing

#1282 [doc] fix flush curl to default port
  docs/manual-CN/3.build-develop-and-administration/3.deploy-and-administrations/server-administration/configuration-statements/rocksdb-compaction-flush.md
  docs/manual-EN/3.build-develop-and-administration/2.develop-and-interface/kv-interfaces.md
  docs/manual-EN/3.build-develop-and-administration/3.deploy-and-administrations/server-administration/configuration-statements/rocksdb-compaction-flush.md
Labels: ready-for-testing

#1270 [doc]update java client link
  src/client/java/README.md
Labels: ready-for-testing

#1268 Add ConcurrentLRUCache
  src/common/base/ConcurrentLRUCache.h
  src/common/base/Status.h
  src/common/base/test/CMakeLists.txt
  src/common/base/test/ConcurrentLRUCacheTest.cpp
Labels: ready-for-testing

#1274 Fixed possible crash after storage service failed to start.
  src/daemons/StorageDaemon.cpp
Labels: ready-for-testing

#1267 [doc]update compaction and flush，TOC
  docs/manual-CN/1.overview/2.quick-start/3.supported-clients.md
  docs/manual-CN/3.build-develop-and-administration/3.deploy-and-administrations/server-administration/configuration-statements/rocksdb-compaction-flush.md
  docs/manual-CN/README.md
  docs/manual-EN/1.overview/2.quick-start/3.supported-clients.md
  docs/manual-EN/3.build-develop-and-administration/3.deploy-and-administrations/server-administration/configuration-statements/rocksdb-compaction-flush.md
  docs/manual-EN/README.md
Labels: ready-for-testing

#1260 [doc]unity nebula features with website
  README-CN.md
  README.md
Labels: ready-for-testing

#1251 [doc]`RETURN` syntax EN
  docs/manual-CN/README.md
  docs/manual-EN/2.query-language/4.statement-syntax/2.data-query-and-manipulation-statements/return-syntax.md
  docs/manual-EN/README.md
Labels: ready-for-testing

#1210 Support spark job using nebula client
  .gitignore
  src/client/java/pom.xml
  src/client/java/src/main/java/com/vesoft/nebula/graph/client/GraphClientImpl.java
  src/parser/TraverseSentences.h
  src/tools/spark-sstfile-generator/.gitignore
  src/tools/spark-sstfile-generator/build.sbt
  src/tools/spark-sstfile-generator/pom.xml
  src/tools/spark-sstfile-generator/src/main/resources/application.conf
  src/tools/spark-sstfile-generator/src/main/resources/data/json/building.json
  src/tools/spark-sstfile-generator/src/main/resources/data/json/course.json
  src/tools/spark-sstfile-generator/src/main/resources/data/json/like.json
  src/tools/spark-sstfile-generator/src/main/resources/data/json/select.json
  src/tools/spark-sstfile-generator/src/main/resources/data/json/student.json
  src/tools/spark-sstfile-generator/src/main/resources/log4j.properties
  src/tools/spark-sstfile-generator/src/main/scala/com/vesoft/nebula/tools/generator/v2/README.md
  src/tools/spark-sstfile-generator/src/main/scala/com/vesoft/nebula/tools/generator/v2/SparkClientGenerator.scala
  src/tools/spark-sstfile-generator/src/test/scala/com/vesoft/nebula/tools/generator/v2/ConfigTest.scala
Labels: ready-for-testing

#1103 Made length of string literals practically unlimited
  src/common/filter/test/ExpressionTest.cpp
  src/parser/GraphScanner.h
  src/parser/scanner.lex
Labels: ready-for-testing

#1231 fix Dockerfile.graphd port 3699 typo error
  docker/Dockerfile.graph
  docker/Dockerfile.graphd
Labels: ready-for-testing

#1151 Check variable existence in fetch
  docs/manual-CN/2.query-language/4.statement-syntax/2.data-query-and-manipulation-statements/fetch-syntax.md
  docs/manual-EN/2.query-language/4.statement-syntax/2.data-query-and-manipulation-statements/fetch-syntax.md
  src/graph/FetchEdgesExecutor.cpp
  src/graph/FetchVerticesExecutor.cpp
Labels: ready-for-testing

#1243 Support shrink storage by specifying host
  src/graph/BalanceExecutor.cpp
  src/interface/meta.thrift
  src/meta/client/MetaClient.cpp
  src/meta/client/MetaClient.h
  src/meta/processors/admin/BalancePlan.h
  src/meta/processors/admin/BalanceProcessor.cpp
  src/meta/processors/admin/BalanceTask.h
  src/meta/processors/admin/Balancer.cpp
  src/meta/processors/admin/Balancer.h
  src/meta/test/BalanceIntegrationTest.cpp
  src/meta/test/BalancerTest.cpp
  src/meta/test/ConfigManTest.cpp
  src/parser/AdminSentences.cpp
  src/parser/AdminSentences.h
  src/parser/parser.yy
  src/parser/test/ParserTest.cpp
Labels: ready-for-testing

#1291 Clean up schema manager interfaces
  src/meta/SchemaManager.h
  src/meta/ServerBasedSchemaManager.cpp
  src/meta/ServerBasedSchemaManager.h
  src/storage/test/AdHocSchemaManager.cpp
  src/storage/test/AdHocSchemaManager.h
Labels: ready-for-testing

#1233 Return variable if not empty
  src/graph/AlterEdgeExecutor.cpp
  src/graph/AlterTagExecutor.cpp
  src/graph/AssignmentExecutor.cpp
  src/graph/BalanceExecutor.cpp
  src/graph/CMakeLists.txt
  src/graph/ConfigExecutor.cpp
  src/graph/CreateEdgeExecutor.cpp
  src/graph/CreateSpaceExecutor.cpp
  src/graph/CreateTagExecutor.cpp
  src/graph/DeleteVertexExecutor.cpp
  src/graph/DescribeEdgeExecutor.cpp
  src/graph/DescribeSpaceExecutor.cpp
  src/graph/DescribeTagExecutor.cpp
  src/graph/DownloadExecutor.cpp
  src/graph/DropEdgeExecutor.cpp
  src/graph/DropSpaceExecutor.cpp
  src/graph/DropTagExecutor.cpp
  src/graph/ExecutionPlan.cpp
  src/graph/Executor.cpp
  src/graph/Executor.h
  src/graph/FetchExecutor.cpp
  src/graph/FindPathExecutor.cpp
  src/graph/GoExecutor.cpp
  src/graph/GroupByExecutor.cpp
  src/graph/IngestExecutor.cpp
  src/graph/InsertEdgeExecutor.cpp
  src/graph/InsertVertexExecutor.cpp
  src/graph/InterimResult.h
  src/graph/LimitExecutor.cpp
  src/graph/OrderByExecutor.cpp
  src/graph/PipeExecutor.cpp
  src/graph/ReturnExecutor.cpp
  src/graph/ReturnExecutor.h
  src/graph/SequentialExecutor.cpp
  src/graph/SequentialExecutor.h
  src/graph/SetExecutor.cpp
  src/graph/ShowExecutor.cpp
  src/graph/UpdateEdgeExecutor.cpp
  src/graph/UpdateVertexExecutor.cpp
  src/graph/UseExecutor.cpp
  src/graph/YieldExecutor.cpp
  src/graph/test/GoTest.cpp
  src/parser/CMakeLists.txt
  src/parser/Clauses.cpp
  src/parser/ProcessControlSentences.cpp
  src/parser/ProcessControlSentences.h
  src/parser/Sentence.h
  src/parser/SequentialSentences.h
  src/parser/parser.yy
  src/parser/scanner.lex
  src/parser/test/ParserTest.cpp
Labels: ready-for-testing

#1286 [doc] fix port to default 12000
  docs/manual-CN/3.build-develop-and-administration/3.deploy-and-administrations/server-administration/storage-service-administration/storage-metrics.md
  docs/manual-EN/3.build-develop-and-administration/3.deploy-and-administrations/server-administration/storage-service-administration/storage-metrics.md
Labels: ready-for-testing

#1235 [doc] add glog curl command
  docs/manual-CN/3.build-develop-and-administration/3.deploy-and-administrations/server-administration/configuration-statements/log.md
Labels: ready-for-testing

#1246 [doc]Add return doc.
  docs/manual-CN/2.query-language/4.statement-syntax/2.data-query-and-manipulation-statements/return-syntax.md
Labels: ready-for-testing

#1264 Log batch write for asyncAtomicOp used scan->insert->delete
  src/kvstore/LogEncoder.cpp
  src/kvstore/LogEncoder.h
  src/kvstore/Part.cpp
  src/kvstore/test/LogEncoderTest.cpp
Labels: ready-for-testing

#1253 Strengthen the update vertex/edge
  src/graph/UpdateEdgeExecutor.cpp
  src/graph/UpdateVertexExecutor.cpp
  src/graph/test/UpdateTest.cpp
Labels: ready-for-testing

#1294 Support vertex cache on storage side
  src/common/base/ConcurrentLRUCache.h
  src/common/base/test/ConcurrentLRUCacheTest.cpp
  src/storage/AddVerticesProcessor.cpp
  src/storage/AddVerticesProcessor.h
  src/storage/CommonUtils.h
  src/storage/DeleteVertexProcessor.cpp
  src/storage/DeleteVertexProcessor.h
  src/storage/QueryBaseProcessor.cpp
  src/storage/QueryBaseProcessor.h
  src/storage/QueryBaseProcessor.inl
  src/storage/QueryBoundProcessor.h
  src/storage/QueryStatsProcessor.h
  src/storage/QueryVertexPropsProcessor.h
  src/storage/StorageServiceHandler.cpp
  src/storage/StorageServiceHandler.h
  src/storage/UpdateVertexProcessor.cpp
  src/storage/UpdateVertexProcessor.h
  src/storage/test/CMakeLists.txt
  src/storage/test/QueryBoundTest.cpp
  src/storage/test/TestUtils.h
  src/storage/test/VertexCacheTest.cpp
Labels: ready-for-testing

#1308 Fix GitHub Actions failure and upload release assets automatically
  .github/workflows/build.yaml
  .github/workflows/docker.yaml
  .github/workflows/package.yaml
  .github/workflows/release.yaml
  .gitignore
  ci/scripts/upload-github-release-asset.sh
  package/package.sh
  src/common/fs/test/FileUtilsTest.cpp
Labels: ready-for-testing

#1273 support expression in update configs
  share/resources/gflags.json
  src/common/base/Status.cpp
  src/common/base/Status.h
  src/graph/ConfigExecutor.cpp
  src/graph/test/ConfigTest.cpp
  src/kvstore/PartManager.cpp
  src/kvstore/RocksEngineConfig.cpp
  src/meta/client/MetaClient.cpp
  src/meta/processors/BaseProcessor.h
  src/meta/processors/configMan/SetConfigProcessor.cpp
  src/meta/processors/configMan/SetConfigProcessor.h
  src/meta/test/MetaClientTest.cpp
  src/parser/MutateSentences.cpp
  src/parser/MutateSentences.h
  src/parser/test/ParserTest.cpp
Labels: ready-for-testing

#1038 Support geo.
  CMakeLists.txt
  src/common/filter/CMakeLists.txt
  src/common/filter/Expressions.h
  src/common/filter/FunctionManager.cpp
  src/common/filter/geo/GeoFilter.cpp
  src/common/filter/geo/GeoFilter.h
  src/common/filter/geo/GeoIndex.cpp
  src/common/filter/geo/GeoIndex.h
  src/common/filter/geo/GeoParams.cpp
  src/common/filter/geo/GeoParams.h
  src/graph/GoExecutor.cpp
  src/graph/GraphFlags.h
  src/graph/test/CMakeLists.txt
  src/graph/test/GeoTest.cpp
  src/graph/test/TraverseTestBase.h
Labels: ready-for-testing

#1331 To restore the type
  src/interface/common.thrift
Labels: ready-for-testing

#1327 Fix crash when input has no data.
  src/graph/InterimResult.h
  src/graph/TraverseExecutor.cpp
  src/graph/YieldExecutor.cpp
  src/graph/test/YieldTest.cpp
Labels: ready-for-testing

#1300 [doc]update log level
  docs/manual-CN/3.build-develop-and-administration/3.deploy-and-administrations/server-administration/configuration-statements/log.md
  docs/manual-EN/3.build-develop-and-administration/3.deploy-and-administrations/server-administration/configuration-statements/log.md
Labels: ready-for-testing

#1288 [doc]Doc supplement
  docs/manual-CN/1.overview/1.concepts/1.data-model.md
  docs/manual-CN/2.query-language/4.statement-syntax/2.data-query-and-manipulation-statements/delete-edge-syntax.md
  docs/manual-CN/2.query-language/4.statement-syntax/2.data-query-and-manipulation-statements/fetch-syntax.md
  docs/manual-CN/2.query-language/4.statement-syntax/2.data-query-and-manipulation-statements/insert-edge-syntax.md
  docs/manual-CN/3.build-develop-and-administration/3.deploy-and-administrations/server-administration/configuration-statements/configs-syntax.md
  docs/manual-CN/3.build-develop-and-administration/3.deploy-and-administrations/server-administration/configuration-statements/rocksdb-compaction-flush.md
  docs/manual-CN/3.build-develop-and-administration/3.deploy-and-administrations/server-administration/storage-service-administration/storage-balance.md
  docs/manual-EN/1.overview/1.concepts/1.data-model.md
  docs/manual-EN/2.query-language/4.statement-syntax/2.data-query-and-manipulation-statements/delete-edge-syntax.md
  docs/manual-EN/2.query-language/4.statement-syntax/2.data-query-and-manipulation-statements/fetch-syntax.md
  docs/manual-EN/2.query-language/4.statement-syntax/2.data-query-and-manipulation-statements/insert-edge-syntax.md
  docs/manual-EN/3.build-develop-and-administration/3.deploy-and-administrations/server-administration/configuration-statements/configs-syntax.md
  docs/manual-EN/3.build-develop-and-administration/3.deploy-and-administrations/server-administration/storage-service-administration/storage-balance.md
Labels: ready-for-testing

#1324 [doc] change default partition num and add hardware requirement
  docs/manual-CN/1.overview/2.quick-start/1.get-started.md
  docs/manual-CN/3.build-develop-and-administration/1.build/1.build-source-code.md
  docs/manual-EN/1.overview/2.quick-start/1.get-started.md
  docs/manual-EN/3.build-develop-and-administration/1.build/1.build-source-code.md
Labels: ready-for-testing

#1335 Fixed buffer overflow in GraphScanner
  src/parser/GraphScanner.h
Labels: defect-p1, ready-for-testing

#860 Support default value when create tag and edge.
  src/dataman/ResultSchemaProvider.cpp
  src/dataman/ResultSchemaProvider.h
  src/graph/Executor.cpp
  src/graph/Executor.h
  src/graph/InsertEdgeExecutor.cpp
  src/graph/InsertEdgeExecutor.h
  src/graph/InsertVertexExecutor.cpp
  src/graph/InsertVertexExecutor.h
  src/graph/SchemaHelper.cpp
  src/graph/test/DataTest.cpp
  src/graph/test/SchemaTest.cpp
  src/interface/common.thrift
  src/meta/MetaServiceUtils.cpp
  src/meta/MetaServiceUtils.h
  src/meta/NebulaSchemaProvider.cpp
  src/meta/NebulaSchemaProvider.h
  src/meta/SchemaProviderIf.h
  src/meta/client/MetaClient.cpp
  src/meta/client/MetaClient.h
  src/meta/processors/customKV/GetProcessor.cpp
  src/meta/processors/customKV/MultiGetProcessor.cpp
  src/meta/processors/customKV/ScanProcessor.cpp
  src/meta/processors/schemaMan/CreateEdgeProcessor.cpp
  src/meta/processors/schemaMan/CreateTagProcessor.cpp
  src/meta/test/BalanceIntegrationTest.cpp
  src/meta/test/MetaClientTest.cpp
  src/meta/test/ProcessorTest.cpp
  src/meta/test/TestUtils.h
  src/parser/MaintainSentences.h
  src/parser/parser.yy
  src/parser/scanner.lex
  src/parser/test/ParserTest.cpp
  src/parser/test/ScannerTest.cpp
Labels: ready-for-testing

#1342 [hot-fix] Fixed possible crash of storage client when getting leader address.
  src/storage/client/StorageClient.h
Labels: defect-p1, ready-for-testing

#1309 [doc]Proofreading doc en 2
  docs/manual-CN/2.query-language/2.functions-and-operators/limit-syntax.md
  docs/manual-CN/2.query-language/2.functions-and-operators/order-by-function.md
  docs/manual-CN/2.query-language/3.language-structure/pipe-syntax.md
  docs/manual-CN/2.query-language/4.statement-syntax/2.data-query-and-manipulation-statements/delete-edge-syntax.md
  docs/manual-CN/2.query-language/4.statement-syntax/2.data-query-and-manipulation-statements/insert-vertex-syntax.md
  docs/manual-CN/2.query-language/4.statement-syntax/2.data-query-and-manipulation-statements/return-syntax.md
  docs/manual-CN/2.query-language/4.statement-syntax/2.data-query-and-manipulation-statements/where-syntax.md
  docs/manual-CN/2.query-language/4.statement-syntax/2.data-query-and-manipulation-statements/yield-syntax.md
  docs/manual-CN/2.query-language/4.statement-syntax/3.utility-statements/describe-syntax.md
  docs/manual-EN/2.query-language/2.functions-and-operators/limit-syntax.md
  docs/manual-EN/2.query-language/2.functions-and-operators/operator-precedence.md
  docs/manual-EN/2.query-language/2.functions-and-operators/order-by-function.md
  docs/manual-EN/2.query-language/3.language-structure/comment-syntax.md
  docs/manual-EN/2.query-language/3.language-structure/literal-values/numeric-literals.md
  docs/manual-EN/2.query-language/3.language-structure/literal-values/string-literals.md
  docs/manual-EN/2.query-language/3.language-structure/pipe-syntax.md
  docs/manual-EN/2.query-language/4.statement-syntax/2.data-query-and-manipulation-statements/delete-edge-syntax.md
  docs/manual-EN/2.query-language/4.statement-syntax/2.data-query-and-manipulation-statements/insert-vertex-syntax.md
  docs/manual-EN/2.query-language/4.statement-syntax/2.data-query-and-manipulation-statements/return-syntax.md
  docs/manual-EN/2.query-language/4.statement-syntax/2.data-query-and-manipulation-statements/where-syntax.md
  docs/manual-EN/2.query-language/4.statement-syntax/3.utility-statements/describe-syntax.md
  docs/manual-EN/3.build-develop-and-administration/3.deploy-and-administrations/server-administration/account-management-statements/drop-user-syntax.md
Labels: ready-for-testing

#1311 [doc] add import-csv-example
  docs/manual-EN/1.overview/2.quick-start/4.import-csv-file.md
Labels: ready-for-testing

#1330 [hot-fix] update default configs
  etc/nebula-metad.conf.default
  etc/nebula-storaged.conf.default
  share/resources/gflags.json
  src/graph/test/SchemaTest.cpp
  src/kvstore/RocksEngineConfig.cpp
  src/kvstore/raftex/RaftPart.cpp
  src/meta/processors/partsMan/CreateSpaceProcessor.cpp
Labels: ready-for-testing

#1343 Fix input & output in graph.
  src/graph/FetchExecutor.cpp
  src/graph/GroupByExecutor.cpp
  src/graph/GroupByExecutor.h
  src/graph/LimitExecutor.cpp
  src/graph/LimitExecutor.h
  src/graph/OrderByExecutor.cpp
  src/graph/SetExecutor.cpp
  src/graph/test/DeleteVertexTest.cpp
  src/graph/test/FetchEdgesTest.cpp
  src/graph/test/FetchVerticesTest.cpp
  src/graph/test/FindPathTest.cpp
  src/graph/test/GeoTest.cpp
  src/graph/test/GroupByLimitTest.cpp
  src/graph/test/OrderByTest.cpp
  src/graph/test/SetTest.cpp
  src/graph/test/YieldTest.cpp
Labels: ready-for-testing

#1344 [doc]Connect prometheus
  docs/manual-CN/3.build-develop-and-administration/3.deploy-and-administrations/deployment/connect-prometheus.md
  docs/manual-CN/README.md
  docs/manual-EN/3.build-develop-and-administration/3.deploy-and-administrations/deployment/connect-prometheus.md
  docs/manual-EN/README.md
Labels: ready-for-testing

#1341 [hot-fix] speed up storage init
  src/kvstore/NebulaStore.cpp
Labels: R201910_RC2, ready-for-testing

#1279 [doc]Spark writer
  docs/manual-CN/3.build-develop-and-administration/3.deploy-and-administrations/server-administration/storage-service-administration/data-import/spark-writer.md
  docs/manual-CN/README.md
  docs/manual-EN/3.build-develop-and-administration/3.deploy-and-administrations/server-administration/storage-service-administration/data-import/spark-writer.md
  docs/manual-EN/README.md
Labels: ready-for-testing

#1334 [doc]unify format
  docs/manual-CN/2.query-language/2.functions-and-operators/set-operations.md
  docs/manual-CN/2.query-language/3.language-structure/property-reference.md
  docs/manual-CN/2.query-language/4.statement-syntax/1.data-definition-statements/create-space-syntax.md
  docs/manual-CN/2.query-language/4.statement-syntax/1.data-definition-statements/create-tag-edge-syntax.md
  docs/manual-CN/2.query-language/4.statement-syntax/2.data-query-and-manipulation-statements/go-syntax.md
  docs/manual-CN/2.query-language/4.statement-syntax/2.data-query-and-manipulation-statements/insert-edge-syntax.md
  docs/manual-CN/2.query-language/4.statement-syntax/2.data-query-and-manipulation-statements/insert-vertex-syntax.md
  docs/manual-CN/3.build-develop-and-administration/1.build/1.build-source-code.md
  docs/manual-EN/2.query-language/2.functions-and-operators/set-operations.md
  docs/manual-EN/2.query-language/3.language-structure/property-reference.md
  docs/manual-EN/2.query-language/4.statement-syntax/1.data-definition-statements/create-space-syntax.md
  docs/manual-EN/2.query-language/4.statement-syntax/1.data-definition-statements/create-tag-edge-syntax.md
  docs/manual-EN/2.query-language/4.statement-syntax/2.data-query-and-manipulation-statements/go-syntax.md
  docs/manual-EN/2.query-language/4.statement-syntax/2.data-query-and-manipulation-statements/insert-edge-syntax.md
  docs/manual-EN/2.query-language/4.statement-syntax/2.data-query-and-manipulation-statements/insert-vertex-syntax.md
Labels: ready-for-testing

#1338 [doc]proofread doc part 3 and 4
  docs/manual-CN/3.build-develop-and-administration/1.build/1.build-source-code.md
  docs/manual-CN/3.build-develop-and-administration/3.deploy-and-administrations/server-administration/configuration-statements/configs-syntax.md
  docs/manual-CN/3.build-develop-and-administration/3.deploy-and-administrations/server-administration/configuration-statements/log.md
  docs/manual-CN/3.build-develop-and-administration/3.deploy-and-administrations/server-administration/storage-service-administration/data-import/download-and-ingest-sst-file.md
  docs/manual-CN/3.build-develop-and-administration/3.deploy-and-administrations/server-administration/storage-service-administration/storage-balance.md
  docs/manual-EN/3.build-develop-and-administration/1.build/1.build-source-code.md
  docs/manual-EN/3.build-develop-and-administration/1.build/2.build-by-docker.md
  docs/manual-EN/3.build-develop-and-administration/3.deploy-and-administrations/server-administration/configuration-statements/configs-syntax.md
  docs/manual-EN/3.build-develop-and-administration/3.deploy-and-administrations/server-administration/configuration-statements/log.md
  docs/manual-EN/3.build-develop-and-administration/3.deploy-and-administrations/server-administration/storage-service-administration/data-import/download-and-ingest-sst-file.md
  docs/manual-EN/3.build-develop-and-administration/3.deploy-and-administrations/server-administration/storage-service-administration/storage-balance.md
Labels: ready-for-testing

#1349 Go reversely.
  src/graph/FindPathExecutor.cpp
  src/graph/GoExecutor.cpp
  src/graph/GoExecutor.h
  src/graph/test/GoTest.cpp
  src/parser/Clauses.cpp
  src/parser/Clauses.h
  src/parser/parser.yy
  src/storage/QueryBaseProcessor.inl
  src/storage/test/QueryEdgePropsTest.cpp
  src/storage/test/StorageClientTest.cpp
Labels: ready-for-testing

#1354 [doc]update READMEs
  README-CN.md
  README.md
  docker/README.md
  scripts/README.md
  share/README.md
  src/README.md
  src/client/go/README.md
  src/client/java/README.md
  src/tools/importer/README.md
  src/tools/spark-sstfile-generator/README.md
  src/tools/storage-perf/README.md
Labels: ready-for-testing

#1350 [doc]Fix doc headings
  docs/manual-EN/1.overview/0.introduction.md
  docs/manual-EN/1.overview/1.concepts/2.nGQL-overview.md
  docs/manual-EN/1.overview/2.quick-start/1.get-started.md
  docs/manual-EN/1.overview/2.quick-start/2.trouble-shooting.md
  docs/manual-EN/1.overview/2.quick-start/4.import-csv-file.md
  docs/manual-EN/1.overview/3.design-and-architecture/1.design-and-architecture.md
  docs/manual-EN/1.overview/3.design-and-architecture/2.storage-design.md
  docs/manual-EN/2.query-language/1.data-types/type-conversion.md
  docs/manual-EN/2.query-language/2.functions-and-operators/comparison-functions-and-operators.md
  docs/manual-EN/2.query-language/2.functions-and-operators/group-by-function.md
  docs/manual-EN/2.query-language/2.functions-and-operators/order-by-function.md
  docs/manual-EN/2.query-language/3.language-structure/identifier-case-sensitivity.md
  docs/manual-EN/2.query-language/3.language-structure/literal-values/numeric-literals.md
  docs/manual-EN/2.query-language/3.language-structure/property-reference.md
  docs/manual-EN/2.query-language/4.statement-syntax/1.data-definition-statements/create-tag-edge-syntax.md
  docs/manual-EN/2.query-language/4.statement-syntax/2.data-query-and-manipulation-statements/update-vertex-edge-syntax.md
  docs/manual-EN/2.query-language/4.statement-syntax/2.data-query-and-manipulation-statements/yield-syntax.md
  docs/manual-EN/3.build-develop-and-administration/1.build/1.build-source-code.md
  docs/manual-EN/3.build-develop-and-administration/2.develop-and-interface/kv-interfaces.md
  docs/manual-EN/3.build-develop-and-administration/3.deploy-and-administrations/deployment/deploy-cluster.md
  docs/manual-EN/4.contributions/contribute-to-documentation.md
  docs/manual-EN/4.contributions/cpp-coding-style.md
  docs/manual-EN/4.contributions/developer-documentation-style-guide.md
  docs/manual-EN/4.contributions/how-to-contribute.md
  docs/manual-EN/README.md
Labels: ready-for-testing

#1287 Fix race condition between rollback and iterator in WAL module
  src/kvstore/wal/FileBasedWal.cpp
  src/kvstore/wal/FileBasedWal.h
  src/kvstore/wal/FileBasedWalIterator.cpp
  src/kvstore/wal/FileBasedWalIterator.h
  src/kvstore/wal/test/FileBasedWalTest.cpp
Labels: R201910_RC2, ready-for-testing

#1340 [hot-fix] Fixed possible crash when calling metaclient.
  src/kvstore/NebulaStore.cpp
  src/kvstore/PartManager.cpp
  src/kvstore/PartManager.h
  src/meta/client/MetaClient.cpp
  src/meta/client/MetaClient.h
  src/meta/test/MetaClientTest.cpp
  src/storage/client/StorageClient.cpp
  src/storage/client/StorageClient.h
  src/storage/test/StorageClientTest.cpp
Labels: defect-p1, ready-for-testing

#1353 Update operations return leader info when leader change event happens
  src/storage/BaseProcessor.h
  src/storage/BaseProcessor.inl
  src/storage/UpdateEdgeProcessor.cpp
  src/storage/UpdateVertexProcessor.cpp
Labels: ready-for-testing

#1301 Add StatsManager in graphd
  src/common/filter/test/CMakeLists.txt
  src/common/stats/CMakeLists.txt
  src/common/stats/Stats.cpp
  src/common/stats/Stats.h
  src/common/stats/StatsManager.cpp
  src/daemons/CMakeLists.txt
  src/graph/DeleteVertexExecutor.cpp
  src/graph/ExecutionContext.h
  src/graph/ExecutionEngine.cpp
  src/graph/ExecutionEngine.h
  src/graph/ExecutionPlan.cpp
  src/graph/Executor.cpp
  src/graph/Executor.h
  src/graph/FetchEdgesExecutor.cpp
  src/graph/FetchExecutor.cpp
  src/graph/FetchExecutor.h
  src/graph/FetchVerticesExecutor.cpp
  src/graph/FindPathExecutor.cpp
  src/graph/GoExecutor.cpp
  src/graph/GraphStats.h
  src/graph/InsertEdgeExecutor.cpp
  src/graph/InsertVertexExecutor.cpp
  src/graph/UpdateEdgeExecutor.cpp
  src/graph/UpdateVertexExecutor.cpp
  src/graph/YieldExecutor.cpp
  src/graph/YieldExecutor.h
  src/graph/test/CMakeLists.txt
  src/graph/test/TraverseTestBase.h
  src/graph/test/YieldTest.cpp
  src/kvstore/plugins/hbase/test/CMakeLists.txt
  src/kvstore/test/CMakeLists.txt
  src/meta/MetaServiceHandler.h
  src/meta/MetaStats.h
  src/meta/client/MetaClient.cpp
  src/meta/client/MetaClient.h
  src/meta/processors/BaseProcessor.h
  src/meta/processors/admin/HBProcessor.h
  src/meta/test/CMakeLists.txt
  src/parser/test/CMakeLists.txt
  src/storage/AddEdgesProcessor.h
  src/storage/AddVerticesProcessor.h
  src/storage/BaseProcessor.h
  src/storage/DeleteVertexProcessor.h
  src/storage/GetProcessor.h
  src/storage/PutProcessor.h
  src/storage/QueryBaseProcessor.h
  src/storage/QueryBoundProcessor.h
  src/storage/QueryEdgePropsProcessor.h
  src/storage/QueryStatsProcessor.h
  src/storage/QueryVertexPropsProcessor.h
  src/storage/StorageServiceHandler.h
  src/storage/StorageStats.h
  src/storage/UpdateEdgeProcessor.h
  src/storage/UpdateVertexProcessor.h
  src/storage/client/StorageClient.cpp
  src/storage/client/StorageClient.h
  src/storage/client/StorageClient.inl
  src/storage/test/CMakeLists.txt
  src/tools/native-client/CMakeLists.txt
  src/tools/storage-perf/CMakeLists.txt
Labels: ready-for-testing
