Repository vesoft-inc/nebula, pull requests merged in 2019-08, with the labels that each got.

#504 Add config manager to store configurations that could be changed during the runtime
  src/common/base/Status.cpp
  src/common/base/Status.h
  src/common/filter/Expressions.h
  src/daemons/CMakeLists.txt
  src/daemons/MetaDaemon.cpp
  src/daemons/StorageDaemon.cpp
  src/graph/CMakeLists.txt
  src/graph/ConfigExecutor.cpp
  src/graph/ConfigExecutor.h
  src/graph/ExecutionContext.cpp
  src/graph/ExecutionContext.h
  src/graph/ExecutionEngine.cpp
  src/graph/ExecutionEngine.h
  src/graph/Executor.cpp
  src/graph/ShowExecutor.h
  src/graph/test/CMakeLists.txt
  src/graph/test/ConfigTest.cpp
  src/graph/test/TestBase.h
  src/graph/test/TestEnv.cpp
  src/graph/test/TestEnv.h
  src/interface/meta.thrift
  src/meta/CMakeLists.txt
  src/meta/ClientBasedGflagsManager.cpp
  src/meta/ClientBasedGflagsManager.h
  src/meta/GflagsManager.cpp
  src/meta/GflagsManager.h
  src/meta/KVBasedGflagsManager.cpp
  src/meta/KVBasedGflagsManager.h
  src/meta/MetaServiceHandler.cpp
  src/meta/MetaServiceHandler.h
  src/meta/MetaServiceUtils.cpp
  src/meta/MetaServiceUtils.h
  src/meta/client/MetaClient.cpp
  src/meta/client/MetaClient.h
  src/meta/processors/BaseProcessor.h
  src/meta/processors/Common.h
  src/meta/processors/configMan/GetConfigProcessor.cpp
  src/meta/processors/configMan/GetConfigProcessor.h
  src/meta/processors/configMan/ListConfigsProcessor.cpp
  src/meta/processors/configMan/ListConfigsProcessor.h
  src/meta/processors/configMan/RegConfigProcessor.cpp
  src/meta/processors/configMan/RegConfigProcessor.h
  src/meta/processors/configMan/SetConfigProcessor.cpp
  src/meta/processors/configMan/SetConfigProcessor.h
  src/meta/test/CMakeLists.txt
  src/meta/test/ConfigManTest.cpp
  src/parser/AdminSentences.cpp
  src/parser/AdminSentences.h
  src/parser/Sentence.h
  src/parser/parser.yy
  src/parser/scanner.lex
  src/parser/test/ParserTest.cpp
  src/parser/test/ScannerTest.cpp
Labels: ready-for-testing

#652 Fix the same name tag and edge in same space #598
  package/make_srpm.sh
  package/nebula.spec
  src/graph/ShowExecutor.cpp
  src/graph/test/SchemaTest.cpp
  src/interface/meta.thrift
  src/meta/client/MetaClient.cpp
  src/meta/processors/schemaMan/CreateEdgeProcessor.cpp
  src/meta/processors/schemaMan/CreateTagProcessor.cpp
  src/meta/test/ProcessorTest.cpp
Labels: ready-for-testing

#640 Fix get wrong data when multi tags have same prop name
  src/dataman/RowReader.cpp
  src/dataman/RowReader.h
  src/graph/GoExecutor.cpp
  src/graph/GoExecutor.h
  src/graph/test/DataTest.cpp
  src/storage/QueryBaseProcessor.inl
Labels: ready-for-testing

#703 fix wal rollback bug
  src/kvstore/wal/FileBasedWal.cpp
  src/kvstore/wal/test/FileBasedWalTest.cpp
Labels: ready-for-testing

#687 clusterid_support, first commit
  src/common/base/ThriftTypes.h
  src/daemons/MetaDaemon.cpp
  src/daemons/StorageDaemon.cpp
  src/graph/test/TestEnv.cpp
  src/interface/common.thrift
  src/interface/meta.thrift
  src/interface/raftex.thrift
  src/meta/CMakeLists.txt
  src/meta/ClusterManager.cpp
  src/meta/ClusterManager.h
  src/meta/MetaServiceHandler.cpp
  src/meta/MetaServiceHandler.h
  src/meta/client/MetaClient.cpp
  src/meta/client/MetaClient.h
  src/meta/processors/admin/HBProcessor.cpp
  src/meta/processors/admin/HBProcessor.h
  src/meta/test/CMakeLists.txt
  src/meta/test/ClusterManagerTest.cpp
  src/meta/test/MetaClientTest.cpp
  src/meta/test/TestUtils.h
  src/storage/test/StorageClientTest.cpp
Labels: feature, ready-for-testing

#709 Eliminate duplicate definitions in PrimaryExpression
  src/common/filter/Expressions.cpp
  src/common/filter/Expressions.h
Labels: ready-for-testing

#728 issue #727 crashed by PartsTest in nebula_store_test.
  src/kvstore/test/NebulaStoreTest.cpp
Labels: defect, ready-for-testing

#683 Support variable/pipe reference in WHERE and YIELD
  src/common/filter/Expressions.cpp
  src/common/filter/Expressions.h
  src/graph/GoExecutor.cpp
  src/graph/GoExecutor.h
  src/graph/InterimResult.cpp
  src/graph/InterimResult.h
  src/graph/test/GoTest.cpp
Labels: ready-for-testing

#643 [manual] add language structure section
  docs/get-started.md
  docs/manual_doc/Data_Types/Nemeric_Types.md
  docs/manual_doc/Data_Types/String_Types.md
  docs/manual_doc/Functions_and_Operators/Comparison_Functions_and_Operators.md
  docs/manual_doc/Functions_and_Operators/Functions_and_Operator_Reference.md
  docs/manual_doc/Functions_and_Operators/Logical_Operators.md
  docs/manual_doc/Functions_and_Operators/Operator_Precedence.md
  docs/manual_doc/Functions_and_Operators/Type_Conversion.md
  docs/manual_doc/Language_Structure/Comment_Syntax.md
  docs/manual_doc/Language_Structure/Expression.md
  docs/manual_doc/Language_Structure/Identifier_Case_Sensitivity.md
  docs/manual_doc/Language_Structure/Literal_Values/Boolean_Literals.md
  docs/manual_doc/Language_Structure/Literal_Values/NULL_Values.md
  docs/manual_doc/Language_Structure/Literal_Values/Numeric_Literals.md
  docs/manual_doc/Language_Structure/Literal_Values/String_Literals.md
  docs/manual_doc/Language_Structure/Schema_Object_Names.md
  docs/manual_doc/Language_Structure/Statement_Composition.md
  docs/manual_doc/Language_Structure/User-Defined_Variables.md
  docs/manual_doc/Statement_Syntax/DATA_Manipulation_Statements/GO_Syntax.md
  docs/manual_doc/Statement_Syntax/DATA_Manipulation_Statements/INSERT_EDGE_Syntax.md
  docs/manual_doc/Statement_Syntax/DATA_Manipulation_Statements/INSERT_VERTEX_Syntax.md
  docs/manual_doc/Statement_Syntax/DATA_Manipulation_Statements/PIPE_Syntax.md
  docs/manual_doc/Statement_Syntax/DATA_Manipulation_Statements/WHERE_Syntax.md
  docs/manual_doc/Statement_Syntax/DATA_Manipulation_Statements/YIELD_Syntax.md
  docs/manual_doc/Statement_Syntax/Data_Administration_Statements/Account_Management_Statements/Drop_User_Syntax.md
  docs/manual_doc/Statement_Syntax/Data_Administration_Statements/Configuration_Statements/Variables_Syntax.md
  docs/manual_doc/Statement_Syntax/Data_Definition_Statements/ALTER_TAG_or_EDGE_Syntax.md
  docs/manual_doc/Statement_Syntax/Data_Definition_Statements/Create_Space_Syntax.md
  docs/manual_doc/Statement_Syntax/Data_Definition_Statements/Create_TAG_or_EDGE_Syntax.md
  docs/manual_doc/Statement_Syntax/Data_Definition_Statements/Drop_Edge_Syntax.md
  docs/manual_doc/Statement_Syntax/Data_Definition_Statements/Drop_Space_Syntax.md
  docs/manual_doc/Statement_Syntax/Data_Definition_Statements/Drop_Tag_Syntax.md
  docs/manual_doc/Statement_Syntax/Data_Definition_Statements/Show_Syntax.md
  docs/manual_doc/Statement_Syntax/Utility_Statements/DESCRIBE_syntax.md
  docs/manual_doc/Statement_Syntax/Utility_Statements/USE_syntax.md
  docs/manul_doc/Functions_and_Operators/Operators.md
Labels: ready-for-testing

#726 Meta Server init fail when leader change
  src/meta/ClusterManager.cpp
  src/meta/ClusterManager.h
Labels: defect, ready-for-testing

#706 Fix bunch of bugs in write test.
  src/common/thrift/ThriftClientManager.h
  src/common/thrift/ThriftClientManager.inl
  src/daemons/MetaDaemon.cpp
  src/daemons/StorageDaemon.cpp
  src/kvstore/NebulaStore.cpp
  src/kvstore/NebulaStore.h
  src/kvstore/Part.cpp
  src/kvstore/Part.h
  src/kvstore/raftex/Host.cpp
  src/kvstore/raftex/RaftPart.cpp
  src/kvstore/raftex/RaftPart.h
  src/kvstore/raftex/RaftexService.cpp
  src/kvstore/raftex/RaftexService.h
  src/kvstore/raftex/test/LeaderElectionTest.cpp
  src/kvstore/raftex/test/LogAppendTest.cpp
  src/kvstore/raftex/test/RaftexTestBase.cpp
  src/kvstore/raftex/test/TestShard.cpp
  src/kvstore/raftex/test/TestShard.h
  src/kvstore/test/NebulaStoreTest.cpp
  src/kvstore/wal/FileBasedWal.cpp
  src/kvstore/wal/FileBasedWal.h
  src/kvstore/wal/FileBasedWalIterator.cpp
  src/kvstore/wal/Wal.h
  src/meta/test/TestUtils.h
  src/storage/client/StorageClient.h
  src/storage/client/StorageClient.inl
  src/storage/test/StorageClientTest.cpp
  src/storage/test/TestUtils.h
Labels: ready-for-testing

#723 Nebula Service Script
  scripts/graph.hosts
  scripts/meta.hosts
  scripts/services.sh
  scripts/storage.hosts
Labels: ready-for-testing

#546 fix unreachable code and imcomplete UT in FileUtils
  src/common/fs/FileUtils.cpp
  src/common/fs/test/FileUtilsTest.cpp
Labels: defect, ready-for-testing

#658 Implementation of fetch prop
  src/common/filter/Expressions.cpp
  src/common/filter/Expressions.h
  src/common/filter/test/ExpressionTest.cpp
  src/dataman/test/NebulaCodecTest.cpp
  src/graph/CMakeLists.txt
  src/graph/Executor.cpp
  src/graph/FetchEdgesExecutor.cpp
  src/graph/FetchEdgesExecutor.h
  src/graph/FetchExecutor.cpp
  src/graph/FetchExecutor.h
  src/graph/FetchVerticesExecutor.cpp
  src/graph/FetchVerticesExecutor.h
  src/graph/GoExecutor.cpp
  src/graph/InterimResult.cpp
  src/graph/InterimResult.h
  src/graph/TraverseExecutor.cpp
  src/graph/TraverseExecutor.h
  src/graph/test/CMakeLists.txt
  src/graph/test/FetchEdgesTest.cpp
  src/graph/test/FetchVerticesTest.cpp
  src/graph/test/GoTest.cpp
  src/parser/MutateSentences.h
  src/parser/Sentence.h
  src/parser/TraverseSentences.cpp
  src/parser/TraverseSentences.h
  src/parser/parser.yy
  src/parser/scanner.lex
  src/storage/QueryBaseProcessor.inl
  src/storage/QueryBoundProcessor.cpp
  src/storage/test/QueryBoundTest.cpp
Labels: feature, ready-for-testing

#737 [Minor] Using Scalafmt to format scala source code
  src/tools/spark-sstfile-generator/.scalafmt.conf
  src/tools/spark-sstfile-generator/build.sbt
  src/tools/spark-sstfile-generator/project/Commons.scala
  src/tools/spark-sstfile-generator/project/assembly.sbt
  src/tools/spark-sstfile-generator/project/plugins.sbt
  src/tools/spark-sstfile-generator/src/main/scala/com/vesoft/tools/DataTypeCompatibility.scala
  src/tools/spark-sstfile-generator/src/main/scala/com/vesoft/tools/FNVHash.scala
  src/tools/spark-sstfile-generator/src/main/scala/com/vesoft/tools/MappingConfiguration.scala
  src/tools/spark-sstfile-generator/src/main/scala/com/vesoft/tools/PropertyValueAndTypeWritable.scala
  src/tools/spark-sstfile-generator/src/main/scala/com/vesoft/tools/SparkSstFileGenerator.scala
  src/tools/spark-sstfile-generator/src/main/scala/com/vesoft/tools/SstFileOutputFormat.scala
  src/tools/spark-sstfile-generator/src/test/scala/com/vesoft/tools/MappingConfigurationTest.scala
  src/tools/spark-sstfile-generator/src/test/scala/com/vesoft/tools/SparkSstFileGeneratorTest.scala
Labels: ready-for-testing

#732 Fix crash problem when stop storage/meta daemon
  src/daemons/CMakeLists.txt
  src/daemons/MetaDaemon.cpp
  src/daemons/StorageDaemon.cpp
  src/kvstore/NebulaStore.cpp
  src/kvstore/NebulaStore.h
  src/kvstore/raftex/RaftexService.cpp
  src/meta/client/MetaClient.cpp
  src/meta/client/MetaClient.h
  src/storage/CMakeLists.txt
  src/storage/StorageServer.cpp
  src/storage/StorageServer.h
  src/storage/test/StorageClientTest.cpp
Labels: ready-for-testing

#702 Update perf tool
  src/storage/test/StorageClientTest.cpp
  src/tools/storage-perf/StoragePerfTool.cpp
Labels: ready-for-testing

#740 Fixed data dependency issue between multiple statements
  src/graph/AlterEdgeExecutor.cpp
  src/graph/AlterEdgeExecutor.h
  src/graph/AlterTagExecutor.cpp
  src/graph/AlterTagExecutor.h
  src/graph/AssignmentExecutor.cpp
  src/graph/CreateEdgeExecutor.cpp
  src/graph/CreateEdgeExecutor.h
  src/graph/CreateTagExecutor.cpp
  src/graph/CreateTagExecutor.h
  src/graph/DescribeEdgeExecutor.cpp
  src/graph/DescribeTagExecutor.cpp
  src/graph/DownloadExecutor.cpp
  src/graph/DropEdgeExecutor.cpp
  src/graph/DropTagExecutor.cpp
  src/graph/GoExecutor.cpp
  src/graph/GoExecutor.h
  src/graph/IngestExecutor.cpp
  src/graph/InsertEdgeExecutor.cpp
  src/graph/InsertEdgeExecutor.h
  src/graph/InsertVertexExecutor.cpp
  src/graph/InsertVertexExecutor.h
  src/graph/PipeExecutor.cpp
  src/graph/ShowExecutor.cpp
  src/graph/test/SchemaTest.cpp
Labels: ready-for-testing

#696 Implementation of set op.
  src/dataman/RowSetWriter.cpp
  src/dataman/RowSetWriter.h
  src/graph/CMakeLists.txt
  src/graph/Executor.cpp
  src/graph/InterimResult.cpp
  src/graph/InterimResult.h
  src/graph/PipeExecutor.cpp
  src/graph/PipeExecutor.h
  src/graph/SetExecutor.cpp
  src/graph/SetExecutor.h
  src/graph/TraverseExecutor.cpp
  src/graph/test/CMakeLists.txt
  src/graph/test/OrderByTest.cpp
  src/graph/test/SetTest.cpp
  src/parser/MaintainSentences.h
  src/parser/MutateSentences.h
  src/parser/TraverseSentences.cpp
  src/parser/TraverseSentences.h
  src/parser/parser.yy
  src/parser/scanner.lex
  src/parser/test/ParserTest.cpp
  src/parser/test/ScannerTest.cpp
Labels: ready-for-testing

#669 Issue#424 to make `Expression::eval` to be able to do error handle
  src/common/filter/Expressions.cpp
  src/common/filter/Expressions.h
  src/common/filter/test/ExpressionTest.cpp
  src/graph/ConfigExecutor.cpp
  src/graph/FetchEdgesExecutor.cpp
  src/graph/FetchExecutor.cpp
  src/graph/FetchVerticesExecutor.cpp
  src/graph/GoExecutor.cpp
  src/graph/GoExecutor.h
  src/graph/InsertEdgeExecutor.cpp
  src/graph/InsertVertexExecutor.cpp
  src/graph/YieldExecutor.cpp
  src/graph/test/TestEnv.cpp
  src/parser/AdminSentences.cpp
  src/storage/QueryBaseProcessor.inl
Labels: ready-for-testing

#719 Enhance Java Importer
  src/client/java/pom.xml
  src/tools/importer/README.md
  src/tools/importer/build.sh
  src/tools/importer/pom.xml
  src/tools/importer/run.sh
  src/tools/importer/src/main/java/com/vesoft/nebula/importer/Importer.java
  src/tools/importer/src/main/resources/log4j.properties
Labels: ready-for-testing

#746 [Doc] Cluster deployment
  docs/deploy-cluster.md
  etc/nebula-storaged.conf.default
  scripts/services.sh
  src/graph/GraphFlags.cpp
  src/kvstore/RocksEngine.cpp
  src/kvstore/RocksEngineConfig.cpp
  src/kvstore/RocksEngineConfig.h
  src/kvstore/raftex/RaftPart.cpp
  src/kvstore/raftex/test/LearnerTest.cpp
  src/kvstore/raftex/test/LogAppendTest.cpp
  src/kvstore/raftex/test/LogCASTest.cpp
  src/kvstore/raftex/test/LogCommandTest.cpp
  src/kvstore/raftex/test/RaftCase.cpp
  src/kvstore/raftex/test/RaftexTestBase.cpp
  src/kvstore/test/NebulaStoreTest.cpp
  src/meta/ClusterManager.cpp
  src/storage/test/QueryBoundBenchmark.cpp
Labels: ready-for-testing

#755 Fixed confusing error message for function call expression
  src/common/filter/FunctionManager.cpp
Labels: ready-for-testing

#713 fix a problem when set flags in all module.
  src/meta/ClientBasedGflagsManager.cpp
  src/meta/GflagsManager.cpp
  src/meta/KVBasedGflagsManager.cpp
  src/meta/processors/configMan/SetConfigProcessor.cpp
  src/meta/processors/configMan/SetConfigProcessor.h
  src/meta/test/ConfigManTest.cpp
Labels: ready-for-testing

#758 Replace DCHECK_NOTNULL with DCHECK in TraverseExecutor.
  src/graph/TraverseExecutor.cpp
Labels: ready-for-testing

#760 Issue 756 fixed the graphd crashed.
  src/graph/GoExecutor.cpp
Labels: ready-for-testing

#739 Make metad works stable on multi replicas cluster
  src/common/base/Status.h
  src/daemons/MetaDaemon.cpp
  src/graph/test/DataTest.cpp
  src/graph/test/SchemaTest.cpp
  src/graph/test/TestEnv.cpp
  src/graph/test/TraverseTestBase.h
  src/interface/meta.thrift
  src/kvstore/raftex/RaftPart.cpp
  src/meta/ActiveHostsMan.cpp
  src/meta/ActiveHostsMan.h
  src/meta/CMakeLists.txt
  src/meta/ClusterIdMan.h
  src/meta/ClusterManager.cpp
  src/meta/ClusterManager.h
  src/meta/MetaServiceHandler.h
  src/meta/client/MetaClient.cpp
  src/meta/client/MetaClient.h
  src/meta/processors/BaseProcessor.h
  src/meta/processors/admin/BalanceProcessor.cpp
  src/meta/processors/admin/Balancer.cpp
  src/meta/processors/admin/HBProcessor.cpp
  src/meta/processors/admin/HBProcessor.h
  src/meta/processors/partsMan/CreateSpaceProcessor.cpp
  src/meta/processors/partsMan/ListHostsProcessor.cpp
  src/meta/test/ActiveHostsManTest.cpp
  src/meta/test/BalancerTest.cpp
  src/meta/test/CMakeLists.txt
  src/meta/test/ClusterIdManTest.cpp
  src/meta/test/ClusterManagerTest.cpp
  src/meta/test/HBProcessorTest.cpp
  src/meta/test/MetaClientTest.cpp
  src/meta/test/ProcessorTest.cpp
  src/meta/test/TestUtils.h
  src/storage/StorageServer.cpp
  src/storage/StorageServer.h
  src/storage/test/StorageClientTest.cpp
Labels: ready-for-testing

#769 Fixed crash problem due to meta not ready
  src/daemons/GraphDaemon.cpp
  src/graph/ExecutionEngine.cpp
  src/graph/GraphService.cpp
  src/graph/GraphService.h
  src/graph/test/TestUtils.h
Labels: ready-for-testing

#770 fix ConfigTest occasional failure
  src/graph/test/ConfigTest.cpp
Labels: ready-for-testing

#496 Support show create tag/edge xxx, show create space xxx SQL
  docs/nGQL-tutorial.md
  src/graph/AlterTagExecutor.cpp
  src/graph/DescribeSpaceExecutor.cpp
  src/graph/DescribeSpaceExecutor.h
  src/graph/ShowExecutor.cpp
  src/graph/ShowExecutor.h
  src/graph/test/SchemaTest.cpp
  src/meta/processors/schemaMan/AlterTagProcessor.cpp
  src/meta/test/ProcessorTest.cpp
  src/parser/AdminSentences.cpp
  src/parser/AdminSentences.h
  src/parser/MaintainSentences.h
  src/parser/parser.yy
  src/parser/test/ParserTest.cpp
Labels: ready-for-testing

#656 adjust the field order of EdgeKey
  src/interface/storage.thrift
  src/storage/test/QueryEdgePropsTest.cpp
Labels: ready-for-testing

#763 [Doc] Fix deploy cluster doc
  docs/deploy-cluster.md
  src/kvstore/raftex/test/LogAppendTest.cpp
Labels: ready-for-testing

#764 update Readme
  docs/README.md
Labels: ready-for-testing

#690 Implement wal gc
  src/kvstore/NebulaStore.cpp
  src/kvstore/raftex/RaftPart.cpp
  src/kvstore/wal/FileBasedWal.cpp
  src/kvstore/wal/FileBasedWal.h
  src/kvstore/wal/Wal.h
  src/kvstore/wal/test/FileBasedWalTest.cpp
Labels: ready-for-testing

#772 Improved nebula.service
  scripts/nebula.service
Labels: ready-for-testing

#787 add logo in README.md
  README.md
  docs/logo.png
  docs/manual_doc/Language_Structure/Identifier_Case_Sensitivity.md
  docs/manual_doc/Statement_Syntax/Data_Definition_Statements/Create_Space_Syntax.md
Labels: ready-for-testing

#773 [Issues-771]Fix code style
  src/kvstore/NebulaStore.cpp
Labels: ready-for-testing

#797 [docs] add 'create tag/edgetype' statement and 'show syntax' docs
  docs/get-started.md
  docs/manual-doc/statement-syntax/data-definition-statements/create-tag-edge-syntax.md
  docs/manual-doc/statement-syntax/data-definition-statements/show-syntax.md
Labels: ready-for-testing

#794 Return error msg for find and match sentence
  src/graph/CMakeLists.txt
  src/graph/Executor.cpp
  src/graph/FindExecutor.cpp
  src/graph/FindExecutor.h
  src/graph/MatchExecutor.cpp
  src/graph/MatchExecutor.h
  src/graph/TraverseExecutor.cpp
  src/graph/test/DataTest.cpp
Labels: ready-for-testing

#785 add Chinese docs
  docs/cn_doc/cn-README.md
  docs/cn_doc/cn-contribute-to-documentation.md
  docs/cn_doc/cn-get-started.md
  docs/cn_doc/cn-how-to-contribute.md
  docs/cn_doc/cn-nGQL-tutorial.md
  docs/how-to-contribute.md
Labels: ready-for-testing

#793 Cn2
  docs/cn-doc/cn-README.md
  docs/cn-doc/cn-contribute-to-documentation.md
  docs/cn-doc/cn-get-started.md
  docs/cn-doc/cn-how-to-contribute.md
  docs/cn-doc/cn-nGQL-tutorial.md
  docs/cn-manual-doc/Language_Structure/Comment_Syntax.md
  docs/cn-manual-doc/Language_Structure/Expression.md
  docs/cn-manual-doc/Language_Structure/Identifier_Case_Sensitivity.md
  docs/cn-manual-doc/Language_Structure/Keywords_and_Reserved_Words.md
  docs/cn-manual-doc/Language_Structure/Property_Reference.md
  docs/cn-manual-doc/Language_Structure/Schema_Object_Names.md
  docs/cn-manual-doc/Language_Structure/Statement_Composition.md
  docs/cn-manual-doc/Language_Structure/User-Defined_Variables.md
  docs/cn-manual-doc/cn_Statement_Syntax/DATA_Manipulation_Statements/Go_Syntax.md
  docs/cn-manual-doc/cn_Statement_Syntax/DATA_Manipulation_Statements/INSERT_EDGE_Syntax.md
  docs/cn-manual-doc/cn_Statement_Syntax/DATA_Manipulation_Statements/INSERT_VERTEX_Syntax.md
  docs/cn-manual-doc/cn_Statement_Syntax/DATA_Manipulation_Statements/PIPE_Syntax.md
  docs/cn-manual-doc/cn_Statement_Syntax/DATA_Manipulation_Statements/WHERE_Syntax.md
  docs/cn-manual-doc/cn_Statement_Syntax/DATA_Manipulation_Statements/YIELD_Syntax.md
  docs/cn-manual-doc/cn_Statement_Syntax/DATA_Manipulation_Statements/fetch_Syntax.md
  docs/cn-manual-doc/cn_Statement_Syntax/cn_Data_Administration_Statements/cn_Account_Management_Statements/Drop_User_Syntax.md
  docs/cn-manual-doc/cn_Statement_Syntax/cn_Data_Administration_Statements/cn_Configuration_Statements/cn_Variables_Syntax.md
  docs/cn-manual-doc/cn_Statement_Syntax/cn_Data_Definition_Statements/Create_Space_Syntax.md
  docs/cn-manual-doc/cn_Statement_Syntax/cn_Data_Definition_Statements/Create_Tag_Edge_Syntax.md
  docs/cn-manual-doc/cn_Statement_Syntax/cn_Data_Definition_Statements/Drop_Edge_Syntax.md
  docs/cn-manual-doc/cn_Statement_Syntax/cn_Data_Definition_Statements/Drop_Space_Syntax.md
  docs/cn-manual-doc/cn_Statement_Syntax/cn_Data_Definition_Statements/Drop_Tag_Syntax.md
  docs/cn-manual-doc/cn_Statement_Syntax/cn_Data_Definition_Statements/Show_Syntax.md
  docs/cn-manual-doc/cn_Statement_Syntax/cn_Data_Definition_Statements/cn_Alter_Tag_Edge_Syntax.md
Labels: ready-for-testing

#791 Translate manual docs into CN (Partial).
  docs/cn_manual_doc/Data_Types/Nemeric_Types.md
  docs/cn_manual_doc/Data_Types/String_Types.md
  docs/cn_manual_doc/Functions_and_Operators/Comparison_Functions_and_Operators.md
  docs/cn_manual_doc/Functions_and_Operators/Functions_and_Operator_Reference.md
  docs/cn_manual_doc/Functions_and_Operators/Group_By_Function.md
  docs/cn_manual_doc/Functions_and_Operators/Logical_Operators.md
  docs/cn_manual_doc/Functions_and_Operators/Operator_Precedence.md
  docs/cn_manual_doc/Functions_and_Operators/Order_By_Function.md
  docs/cn_manual_doc/Functions_and_Operators/Set_Operation.md
  docs/cn_manual_doc/Functions_and_Operators/Type_Conversion.md
  docs/cn_manual_doc/Language_Structure/Literal_Values/Boolean_Literals.md
  docs/cn_manual_doc/Language_Structure/Literal_Values/NULL_Values.md
  docs/cn_manual_doc/Language_Structure/Literal_Values/Numeric_Literals.md
  docs/cn_manual_doc/Language_Structure/Literal_Values/String_Literals.md
  docs/cn_manual_doc/Statement_Syntax/Utility_Statements/DESCRIBE_syntax.md
  docs/cn_manual_doc/Statement_Syntax/Utility_Statements/USE_syntax.md
  docs/manual-doc/language-structure/literal-values/string-literals.md
Labels: ready-for-testing

#801 doc translation into Chinese
  docs/cn-doc/how-to-build.md
Labels: ready-for-testing

#700 Issue#655 support for building with Clang
  CMakeLists.txt
  src/common/base/test/EitherOrTest.cpp
  src/console/CliManager.cpp
  src/dataman/RowUpdater.cpp
  src/dataman/RowWriter.cpp
  src/graph/GoExecutor.cpp
  src/graph/ShowExecutor.h
  src/interface/CMakeLists.txt
  src/kvstore/raftex/test/LogAppendTest.cpp
  src/meta/client/MetaClient.cpp
  src/meta/processors/BaseProcessor.inl
  src/meta/processors/admin/AdminClient.cpp
  src/meta/processors/admin/BalancePlan.cpp
  src/meta/test/AdminClientTest.cpp
  src/meta/test/MetaHttpDownloadHandlerTest.cpp
  src/parser/TraverseSentences.cpp
  src/storage/QueryBaseProcessor.inl
  src/storage/client/StorageClient.h
Labels: ready-for-testing

#805 Extend FileUtils::makeDir with customized permission mode
  src/common/fs/FileUtils.cpp
  src/common/fs/FileUtils.h
Labels: ready-for-testing

#807 Updatedoc
  README-CN.md
  README-EN.md
  README.md
  docs/deploy-cluster.md
  docs/get-started.md
  docs/how-to-build.md
  docs/how-to-contribute.md
  docs/manual-CN/contribute-to-documentation.md
  docs/manual-CN/functions-and-operators/logical-operators.md
  docs/manual-CN/functions-and-operators/operator-precedence.md
  docs/manual-CN/get-started.md
  docs/manual-CN/how-to-build.md
  docs/manual-CN/how-to-contribute.md
  docs/manual-CN/language-structure/identifier-case-sensitivity.md
  docs/manual-CN/language-structure/literal-values/string-literals.md
  docs/manual-CN/language-structure/property-reference.md
  docs/manual-CN/language-structure/schema-object-names.md
  docs/manual-CN/statement-syntax/data-definition-statements/create-space-syntax.md
  docs/manual-CN/statement-syntax/data-definition-statements/create-tag-edge-syntax.md
  docs/manual-CN/statement-syntax/data-definition-statements/show-syntax.md
  docs/manual-CN/statement-syntax/data-manipulation-statements/fetch-syntax.md
  docs/manual-EN/functions-and-operators/logical-operators.md
  docs/manual-EN/functions-and-operators/set-operations.md
  docs/manual-EN/language-structure/literal-values/string-literals.md
  docs/manual-EN/statement-syntax/data-definition-statements/create-space-syntax.md
  docs/manual-EN/statement-syntax/data-definition-statements/drop-space-syntax.md
  docs/manual-EN/statement-syntax/data-definition-statements/drop-tag-syntax.md
  docs/manual-EN/statement-syntax/data-manipulation-statements/fetch-syntax.md
  docs/manual-EN/statement-syntax/data-manipulation-statements/insert-edge-syntax.md
  docs/manual-EN/statement-syntax/data-manipulation-statements/insert-vertex-syntax.md
  docs/manual-EN/statement-syntax/data-manipulation-statements/pipe-syntax.md
  docs/manual-EN/statement-syntax/data-manipulation-statements/where-syntax.md
Labels: ready-for-testing

#811 comment ngql tutorial
  README-CN.md
  docs/manual-CN/get-started.md
  docs/manual-CN/nGQL-tutorial.md
  docs/nGQL-tutorial.md
Labels: ready-for-testing

#806 Do self-checking in ProcessUtils::isPidAvailable
  src/common/process/ProcessUtils.cpp
  src/common/process/ProcessUtils.h
  src/common/process/test/ProcessTest.cpp
Labels: ready-for-testing

#754 Fixed incorrect rate metric in StatsManager
  src/common/http/test/CMakeLists.txt
  src/common/stats/StatsManager.cpp
  src/common/stats/StatsManager.h
  src/common/stats/StatsManager.inl
  src/common/stats/test/CMakeLists.txt
  src/common/stats/test/StatsManagerTest.cpp
  src/webservice/test/CMakeLists.txt
Labels: ready-for-testing

#800 Extend CAS in Raft
  src/kvstore/KVStore.h
  src/kvstore/NebulaStore.cpp
  src/kvstore/NebulaStore.h
  src/kvstore/Part.cpp
  src/kvstore/Part.h
  src/kvstore/plugins/hbase/HBaseStore.h
  src/kvstore/raftex/RaftPart.cpp
  src/kvstore/raftex/RaftPart.h
  src/kvstore/raftex/test/LogCASTest.cpp
  src/kvstore/raftex/test/LogCommandTest.cpp
  src/kvstore/raftex/test/TestShard.cpp
  src/kvstore/raftex/test/TestShard.h
Labels: ready-for-testing

#821 Fix crash problem when create space in multiple replica meta env
  src/meta/processors/BaseProcessor.h
  src/meta/processors/BaseProcessor.inl
  src/meta/processors/partsMan/CreateSpaceProcessor.cpp
  src/meta/processors/schemaMan/CreateEdgeProcessor.cpp
  src/meta/processors/schemaMan/CreateTagProcessor.cpp
  src/meta/processors/usersMan/AuthenticationProcessor.cpp
Labels: ready-for-testing

#761 Added introduction on building from source
  CMakeLists.txt
  docs/how-to-build.md
Labels: ready-for-testing

#820 fsync upon closing WAL files
  src/kvstore/wal/FileBasedWal.cpp
Labels: ready-for-testing

#824 Fix MetaClient busy loop when it can't connect to MetaServer
  src/meta/client/MetaClient.cpp
  src/meta/client/MetaClient.h
Labels: ready-for-testing

#803 Add storage_perf and services.sh into install
  package/nebula.spec
  scripts/CMakeLists.txt
  src/tools/storage-perf/CMakeLists.txt
Labels: ready-for-testing

#814 Add retry for meta client
  src/meta/client/MetaClient.cpp
  src/meta/client/MetaClient.h
  src/meta/test/MetaClientTest.cpp
Labels: ready-for-testing

#662 Implemented type casting
  .gitignore
  src/common/filter/Expressions.cpp
  src/common/filter/Expressions.h
  src/graph/test/YieldTest.cpp
Labels: ready-for-testing

#837 Fix nGQL tutorial's comment and table
  docs/nGQL-tutorial.md
Labels: ready-for-testing

#721 Enhance StoragePerf
  src/tools/storage-perf/README.md
  src/tools/storage-perf/StoragePerfTool.cpp
Labels: ready-for-testing

#729 Changed the WAL to call write() on every log message
  src/kvstore/NebulaStore.cpp
  src/kvstore/NebulaStore.h
  src/kvstore/Part.cpp
  src/kvstore/Part.h
  src/kvstore/raftex/RaftPart.cpp
  src/kvstore/raftex/RaftPart.h
  src/kvstore/raftex/test/LeaderElectionTest.cpp
  src/kvstore/raftex/test/LearnerTest.cpp
  src/kvstore/raftex/test/LogAppendTest.cpp
  src/kvstore/raftex/test/LogCASTest.cpp
  src/kvstore/raftex/test/LogCommandTest.cpp
  src/kvstore/raftex/test/RaftCase.cpp
  src/kvstore/raftex/test/RaftexTestBase.cpp
  src/kvstore/raftex/test/RaftexTestBase.h
  src/kvstore/raftex/test/TestShard.cpp
  src/kvstore/raftex/test/TestShard.h
  src/kvstore/wal/BufferFlusher.cpp
  src/kvstore/wal/BufferFlusher.h
  src/kvstore/wal/CMakeLists.txt
  src/kvstore/wal/FileBasedWal.cpp
  src/kvstore/wal/FileBasedWal.h
  src/kvstore/wal/FileBasedWalIterator.cpp
  src/kvstore/wal/InMemoryLogBuffer.cpp
  src/kvstore/wal/InMemoryLogBuffer.h
  src/kvstore/wal/Wal.h
  src/kvstore/wal/test/FileBasedWalTest.cpp
Labels: ready-for-testing

#849 Cleanup load config interval secs
  .gitignore
  docs/deploy-cluster.md
  docs/manual-CN/statement-syntax/data-administration-statements/configuration-statements/variables-syntax.md
  docs/manual-EN/statement-syntax/data-administration-statements/configuration-statements/variables-syntax.md
  src/graph/test/ConfigTest.cpp
  src/meta/GflagsManager.cpp
  src/parser/test/ParserTest.cpp
Labels: ready-for-testing

#792 Fix graph failed to register config to meta.
  package/nebula.spec
  share/CMakeLists.txt
  share/resources/completion.json
  share/resources/gflags.json
  src/graph/CMakeLists.txt
  src/graph/ExecutionEngine.cpp
  src/graph/test/ConfigTest.cpp
  src/interface/meta.thrift
  src/kvstore/plugins/hbase/test/CMakeLists.txt
  src/kvstore/test/CMakeLists.txt
  src/meta/CMakeLists.txt
  src/meta/ClientBasedGflagsManager.cpp
  src/meta/ClientBasedGflagsManager.h
  src/meta/GflagsManager.cpp
  src/meta/GflagsManager.h
  src/meta/KVBasedGflagsManager.cpp
  src/meta/KVBasedGflagsManager.h
  src/meta/client/MetaClient.cpp
  src/meta/client/MetaClient.h
  src/meta/test/CMakeLists.txt
  src/meta/test/ConfigManTest.cpp
  src/storage/StorageServer.cpp
  src/storage/test/CMakeLists.txt
  src/tools/storage-perf/CMakeLists.txt
Labels: ready-for-testing

#854 [Fix] Insert multi version tag and edge's order error
  src/common/base/NebulaKeyUtils.cpp
  src/common/base/NebulaKeyUtils.h
  src/graph/test/DataTest.cpp
  src/storage/AddEdgesProcessor.cpp
  src/storage/AddVerticesProcessor.cpp
  src/storage/QueryBaseProcessor.inl
  src/storage/QueryBoundProcessor.cpp
Labels: ready-for-testing

#731 Leader balance
  src/graph/BalanceExecutor.cpp
  src/graph/BalanceExecutor.h
  src/graph/CMakeLists.txt
  src/graph/Executor.cpp
  src/graph/ShowExecutor.cpp
  src/graph/test/SchemaTest.cpp
  src/interface/meta.thrift
  src/interface/storage.thrift
  src/kvstore/Common.h
  src/kvstore/KVEngine.h
  src/kvstore/KVStore.h
  src/kvstore/LogEncoder.cpp
  src/kvstore/LogEncoder.h
  src/kvstore/NebulaStore.cpp
  src/kvstore/NebulaStore.h
  src/kvstore/Part.cpp
  src/kvstore/Part.h
  src/kvstore/PartManager.h
  src/kvstore/plugins/hbase/HBaseStore.cpp
  src/kvstore/plugins/hbase/HBaseStore.h
  src/kvstore/raftex/RaftPart.cpp
  src/kvstore/raftex/RaftPart.h
  src/kvstore/raftex/test/CMakeLists.txt
  src/kvstore/raftex/test/LeaderTransferTest.cpp
  src/kvstore/raftex/test/RaftexTestBase.cpp
  src/kvstore/raftex/test/RaftexTestBase.h
  src/kvstore/raftex/test/TestShard.cpp
  src/kvstore/raftex/test/TestShard.h
  src/kvstore/test/NebulaStoreTest.cpp
  src/meta/CMakeLists.txt
  src/meta/MetaServiceHandler.cpp
  src/meta/MetaServiceHandler.h
  src/meta/client/MetaClient.cpp
  src/meta/client/MetaClient.h
  src/meta/processors/admin/AdminClient.cpp
  src/meta/processors/admin/AdminClient.h
  src/meta/processors/admin/Balancer.cpp
  src/meta/processors/admin/Balancer.h
  src/meta/processors/admin/LeaderBalanceProcessor.cpp
  src/meta/processors/admin/LeaderBalanceProcessor.h
  src/meta/processors/partsMan/ListHostsProcessor.cpp
  src/meta/processors/partsMan/ListHostsProcessor.h
  src/meta/test/BalanceIntegrationTest.cpp
  src/meta/test/BalancerTest.cpp
  src/meta/test/CMakeLists.txt
  src/meta/test/MetaClientTest.cpp
  src/meta/test/TestUtils.h
  src/parser/AdminSentences.cpp
  src/parser/AdminSentences.h
  src/parser/Sentence.h
  src/parser/parser.yy
  src/parser/scanner.lex
  src/parser/test/ParserTest.cpp
  src/parser/test/ScannerTest.cpp
  src/storage/AdminProcessor.h
  src/storage/StorageServiceHandler.cpp
  src/storage/StorageServiceHandler.h
Labels: ready-for-testing

#859 temporarily disabled two leader transfer ut, they will be fixed in #795
  src/kvstore/PartManager.h
  src/kvstore/test/NebulaStoreTest.cpp
  src/meta/processors/admin/Balancer.h
  src/meta/test/BalanceIntegrationTest.cpp
Labels: ready-for-testing

#850 Use smart pointer make function to construct objects
  src/kvstore/CompactionFilter.h
  src/kvstore/plugins/hbase/test/TestUtils.h
  src/kvstore/wal/FileBasedWal.cpp
  src/meta/SchemaManager.cpp
  src/storage/CompactionFilter.h
  src/storage/StorageServer.cpp
  src/storage/test/TestUtils.h
Labels: ready-for-testing

#861 Fixed improper setting of networking IO threads in Graphd
  src/daemons/GraphDaemon.cpp
Labels: ready-for-testing

#819 Fix java client
  .linters/java/nebula_java_style_checks.xml
  CMakeLists.txt
  docs/how-to-build.md
  src/client/java/CMakeLists.txt
  src/client/java/README.md
  src/client/java/build.sh
  src/client/java/pom.xml
  src/client/java/src/main/java/com/vesoft/nebula/graph/client/ConnectionException.java
  src/client/java/src/main/java/com/vesoft/nebula/graph/client/GraphClient.java
  src/client/java/src/main/java/com/vesoft/nebula/graph/client/GraphClientIface.java
  src/client/java/src/main/java/com/vesoft/nebula/graph/client/GraphClientImpl.java
  src/client/java/src/main/java/com/vesoft/nebula/graph/client/NGQLException.java
  src/tools/importer/CMakeLists.txt
  src/tools/importer/README.md
  src/tools/importer/build.sh
  src/tools/importer/pom.xml
  src/tools/importer/run.sh
  src/tools/importer/src/main/java/com/vesoft/nebula/importer/Importer.java
  src/tools/native-client/pom.xml
  src/tools/spark-sstfile-generator/build.sbt
Labels: ready-for-testing

#730 spark-sstfile-generator comments reviews
  src/tools/spark-sstfile-generator/README.md
  src/tools/spark-sstfile-generator/src/main/scala/com/vesoft/tools/DataTypeCompatibility.scala
  src/tools/spark-sstfile-generator/src/main/scala/com/vesoft/tools/FNVHash.scala
  src/tools/spark-sstfile-generator/src/main/scala/com/vesoft/tools/MappingConfiguration.scala
  src/tools/spark-sstfile-generator/src/main/scala/com/vesoft/tools/PropertyValueAndTypeWritable.scala
  src/tools/spark-sstfile-generator/src/main/scala/com/vesoft/tools/SparkSstFileGenerator.scala
  src/tools/spark-sstfile-generator/src/main/scala/com/vesoft/tools/SstFileOutputFormat.scala
Labels: ready-for-testing
