Repository vesoft-inc/nebula, pull requests merged in 2019-07, with the labels that each got.

#537 Implementation of Order by
  src/dataman/RowSetReader.h
  src/graph/CMakeLists.txt
  src/graph/Executor.cpp
  src/graph/InterimResult.cpp
  src/graph/InterimResult.h
  src/graph/OrderByExecutor.cpp
  src/graph/OrderByExecutor.h
  src/graph/TraverseExecutor.cpp
  src/graph/test/CMakeLists.txt
  src/graph/test/GoTest.cpp
  src/graph/test/OrderByTest.cpp
  src/graph/test/TestBase.h
  src/graph/test/TraverseTestBase.h
  src/parser/MaintainSentences.cpp
  src/parser/MaintainSentences.h
  src/parser/Sentence.h
  src/parser/TraverseSentences.cpp
  src/parser/TraverseSentences.h
  src/parser/parser.yy
  src/parser/scanner.lex
  src/parser/test/ParserTest.cpp
  src/parser/test/ScannerTest.cpp
Labels: ready-for-testing

#556 Switched to using WallClock
  src/common/filter/FunctionManager.cpp
  src/common/filter/test/CMakeLists.txt
  src/common/time/TimeUtils.h
  src/kvstore/CompactionFilter.h
  src/kvstore/LogEncoder.cpp
  src/meta/ActiveHostsMan.cpp
  src/meta/ActiveHostsMan.h
  src/meta/processors/admin/HBProcessor.cpp
  src/meta/processors/admin/HBProcessor.h
  src/meta/processors/schemaMan/AlterEdgeProcessor.cpp
  src/meta/processors/schemaMan/AlterTagProcessor.cpp
  src/meta/processors/schemaMan/CreateEdgeProcessor.cpp
  src/meta/processors/schemaMan/CreateTagProcessor.cpp
  src/meta/test/ActiveHostsManTest.cpp
  src/meta/test/HBProcessorTest.cpp
  src/meta/test/ProcessorTest.cpp
  src/meta/test/TestUtils.h
  src/parser/test/CMakeLists.txt
  src/storage/AddEdgesProcessor.cpp
  src/storage/AddVerticesProcessor.cpp
Labels: ready-for-testing

#559 Disable failed UT in data_test
  src/graph/test/DataTest.cpp
Labels: ready-for-testing

#550 merge host info from kvstore
  src/meta/ActiveHostsMan.cpp
  src/meta/ActiveHostsMan.h
  src/meta/test/ActiveHostsManTest.cpp
Labels: ready-for-testing

#429 Fixed unary minus integer bug and support to take function call as vid
  src/common/filter/Expressions.h
  src/common/filter/test/ExpressionTest.cpp
  src/graph/GoExecutor.cpp
  src/graph/InsertEdgeExecutor.cpp
  src/graph/InsertVertexExecutor.cpp
  src/graph/InterimResult.cpp
  src/graph/InterimResult.h
  src/graph/test/YieldTest.cpp
  src/parser/Clauses.cpp
  src/parser/Clauses.h
  src/parser/MutateSentences.cpp
  src/parser/MutateSentences.h
  src/parser/parser.yy
  src/parser/scanner.lex
  src/parser/test/ParserTest.cpp
  src/parser/test/ScannerTest.cpp
Labels: ready-for-testing

#555 Faster logging
  src/common/base/Base.cpp
  src/common/base/Base.h
  src/common/base/Logging.h
  src/common/base/test/CMakeLists.txt
  src/common/base/test/LoggingBenchmark.cpp
  src/daemons/MetaDaemon.cpp
  src/daemons/StorageDaemon.cpp
Labels: ready-for-testing

#543 Added support to single quoted string literals
  src/parser/scanner.lex
  src/parser/test/ScannerTest.cpp
Labels: ready-for-testing

#512 Added docs/nGQL-tutorial.md
  docs/README.md
  docs/contribute-to-documentation.md
  docs/nGQL-tutorial.md
Labels: ready-for-testing

#573 Removed 'required' keyword in hbase.thrift and other minors
  src/common/test/CMakeLists.txt
  src/common/test/ServerContext.h
  src/common/test/TestServerContext.cpp
  src/graph/Executor.h
  src/kvstore/plugins/hbase/hbase.thrift
  src/meta/SchemaProviderIf.h
Labels: ready-for-testing

#516 Balance skeleton on meta.
  src/interface/meta.thrift
  src/interface/storage.thrift
  src/kvstore/test/CMakeLists.txt
  src/meta/CMakeLists.txt
  src/meta/MetaServiceHandler.cpp
  src/meta/MetaServiceHandler.h
  src/meta/MetaServiceUtils.cpp
  src/meta/client/MetaClient.cpp
  src/meta/client/MetaClient.h
  src/meta/processors/BaseProcessor.h
  src/meta/processors/Common.h
  src/meta/processors/admin/AdminClient.cpp
  src/meta/processors/admin/AdminClient.h
  src/meta/processors/admin/BalancePlan.cpp
  src/meta/processors/admin/BalancePlan.h
  src/meta/processors/admin/BalanceProcessor.cpp
  src/meta/processors/admin/BalanceProcessor.h
  src/meta/processors/admin/BalanceTask.cpp
  src/meta/processors/admin/BalanceTask.h
  src/meta/processors/admin/Balancer.cpp
  src/meta/processors/admin/Balancer.h
  src/meta/test/BalancerTest.cpp
  src/meta/test/CMakeLists.txt
Labels: feature, ready-for-testing

#586 Fix init bug in nebula store
  src/kvstore/NebulaStore.cpp
  src/kvstore/NebulaStore.h
  src/kvstore/RocksEngineConfig.cpp
  src/kvstore/test/NebulaStoreTest.cpp
Labels: ready-for-testing

#590 get-started.md add build user's owner graph
  docs/get-started.md
  docs/nGQL.md
Labels: ready-for-testing

#570 fix crash problem when webservice start failed
  src/daemons/GraphDaemon.cpp
  src/daemons/MetaDaemon.cpp
  src/daemons/StorageDaemon.cpp
  src/webservice/WebService.cpp
Labels: ready-for-testing

#505 Fix empty prop of tag and edge
  src/common/filter/Expressions.cpp
  src/common/filter/test/ExpressionTest.cpp
  src/graph/CMakeLists.txt
  src/graph/test/CMakeLists.txt
  src/graph/test/DataTest.cpp
  src/graph/test/GoTest.cpp
  src/graph/test/OrderByTest.cpp
  src/graph/test/SchemaTest.cpp
  src/graph/test/TraverseTestBase.h
  src/parser/MutateSentences.h
  src/parser/parser.yy
  src/parser/test/ParserTest.cpp
Labels: ready-for-testing

#596 To speed up compiling with ccache
  CMakeLists.txt
Labels: ready-for-testing

#588 To be able to build under GCC 9.1
  src/kvstore/plugins/hbase/HBaseStore.cpp
  src/parser/CMakeLists.txt
  third-party/folly/build.sh
  third-party/rocksdb/build.sh
Labels: ready-for-testing

#576 Support multi copies for kvstore
  src/daemons/MetaDaemon.cpp
  src/daemons/StorageDaemon.cpp
  src/graph/test/TestEnv.cpp
  src/kvstore/KVStore.h
  src/kvstore/NebulaStore.cpp
  src/kvstore/NebulaStore.h
  src/kvstore/Part.cpp
  src/kvstore/Part.h
  src/kvstore/PartManager.h
  src/kvstore/plugins/hbase/HBaseStore.h
  src/kvstore/raftex/RaftPart.cpp
  src/kvstore/raftex/RaftPart.h
  src/kvstore/test/NebulaStoreTest.cpp
  src/kvstore/wal/FileBasedWal.cpp
  src/meta/ActiveHostsMan.cpp
  src/meta/client/MetaClient.cpp
  src/meta/client/MetaClient.h
  src/meta/test/ProcessorTest.cpp
  src/meta/test/TestUtils.h
  src/storage/BaseProcessor.inl
  src/storage/test/StorageClientTest.cpp
  src/storage/test/TestUtils.h
Labels: ready-for-testing

#568 Fix bugs in RAFT
  src/kvstore/raftex/RaftPart.cpp
  src/kvstore/raftex/RaftPart.h
Labels: ready-for-testing

#552 Support command with RAFT
  src/kvstore/raftex/RaftPart.cpp
  src/kvstore/raftex/RaftPart.h
  src/kvstore/raftex/test/CMakeLists.txt
  src/kvstore/raftex/test/LogCommandTest.cpp
  src/kvstore/raftex/test/TestShard.cpp
  src/kvstore/raftex/test/TestShard.h
Labels: ready-for-testing

#603 Fixed dangling pointer in Balancer
  src/meta/processors/admin/Balancer.cpp
Labels: ready-for-testing

#592 fix font
  docs/README.md
  docs/contribute-to-documentation.md
  docs/get-started.md
  docs/nGQL-tutorial.md
Labels: ready-for-testing

#601 fix bug for column data type check
  src/graph/SchemaHelper.cpp
  src/parser/MaintainSentences.h
  src/parser/parser.yy
  src/parser/test/ParserTest.cpp
Labels: ready-for-testing

#606 Make heartbeat to be a special empty log
  src/kvstore/Part.cpp
  src/kvstore/raftex/RaftPart.cpp
  src/kvstore/raftex/RaftPart.h
  src/kvstore/raftex/test/LogAppendTest.cpp
  src/kvstore/raftex/test/LogCASTest.cpp
  src/kvstore/raftex/test/LogCommandTest.cpp
  src/kvstore/raftex/test/TestShard.cpp
  src/kvstore/raftex/test/TestShard.h
Labels: defect, ready-for-testing

#572 To deal with illegal characters in parser
  src/parser/scanner.lex
  src/parser/test/ParserTest.cpp
  src/parser/test/ScannerTest.cpp
Labels: ready-for-testing

#582 To link executables with -no-pie
  CMakeLists.txt
Labels: ready-for-testing

#610 Fix command is all comment
  CMakeLists.txt
  src/common/base/Status.h
  src/console/CmdProcessor.cpp
  src/graph/ExecutionPlan.cpp
  src/graph/test/SchemaTest.cpp
  src/interface/graph.thrift
  src/parser/GQLParser.h
  src/parser/parser.yy
  src/parser/scanner.lex
  src/parser/test/ParserTest.cpp
Labels: ready-for-testing

#547 Added docs on installing from source
  docs/get-started.md
Labels: ready-for-testing

#597 Implementation of Distinct
  src/common/filter/Expressions.h
  src/graph/GoExecutor.cpp
  src/graph/GoExecutor.h
  src/graph/test/GoTest.cpp
  src/parser/Clauses.cpp
  src/parser/Clauses.h
  src/parser/parser.yy
  src/parser/scanner.lex
  src/parser/test/ParserTest.cpp
Labels: ready-for-testing

#594 Fixed bug on variable reference
  src/graph/AssignmentExecutor.cpp
  src/graph/test/CMakeLists.txt
  src/graph/test/GoTest.cpp
  src/parser/parser.yy
Labels: ready-for-testing

#622 Fixed UpgradedHolder-related race condition in ActiveHostsMan
  src/graph/test/CMakeLists.txt
  src/meta/ActiveHostsMan.cpp
Labels: ready-for-testing

#620 Fix bug about stopping twice for part
  src/kvstore/NebulaStore.cpp
Labels: ready-for-testing

#618 Formalized release version
  docs/README.md
  docs/get-started.md
Labels: ready-for-testing

#575 To detect TTY in nebula console
  src/console/CliManager.cpp
  src/console/CliManager.h
Labels: ready-for-testing

#615 Improve console humanized output
  src/console/CliManager.cpp
  src/console/CliManager.h
  src/console/CmdProcessor.cpp
  src/console/CmdProcessor.h
  src/graph/ExecutionPlan.cpp
  src/interface/graph.thrift
Labels: ready-for-testing

#569 Fixed bug on overflown number literals in scanner
  src/parser/scanner.lex
  src/parser/test/ScannerTest.cpp
Labels: ready-for-testing

#519 Implement download procedure
  src/common/CMakeLists.txt
  src/common/hdfs/CMakeLists.txt
  src/common/hdfs/HdfsCommandHelper.cpp
  src/common/hdfs/HdfsCommandHelper.h
  src/common/hdfs/HdfsHelper.h
  src/common/hdfs/test/CMakeLists.txt
  src/common/hdfs/test/HdfsHelperTest.cpp
  src/common/network/NetworkUtils.cpp
  src/common/network/NetworkUtils.h
  src/common/network/test/NetworkUtilsBenchmark.cpp
  src/common/network/test/NetworkUtilsTest.cpp
  src/daemons/CMakeLists.txt
  src/daemons/GraphDaemon.cpp
  src/daemons/MetaDaemon.cpp
  src/daemons/StorageDaemon.cpp
  src/graph/CMakeLists.txt
  src/graph/DownloadExecutor.cpp
  src/graph/DownloadExecutor.h
  src/graph/Executor.cpp
  src/graph/test/CMakeLists.txt
  src/graph/test/TestEnv.cpp
  src/kvstore/raftex/test/RaftexTestBase.cpp
  src/kvstore/test/NebulaStoreTest.cpp
  src/meta/CMakeLists.txt
  src/meta/MetaHttpDownloadHandler.cpp
  src/meta/MetaHttpDownloadHandler.h
  src/meta/MetaHttpStatusHandler.cpp
  src/meta/MetaHttpStatusHandler.h
  src/meta/client/MetaClient.cpp
  src/meta/client/MetaClient.h
  src/meta/test/CMakeLists.txt
  src/meta/test/MetaClientTest.cpp
  src/meta/test/MetaHttpDownloadHandlerTest.cpp
  src/meta/test/MetaHttpStatusHandlerTest.cpp
  src/meta/test/MockHdfsHelper.h
  src/meta/test/ProcessorTest.cpp
  src/meta/test/TestUtils.h
  src/parser/MutateSentences.cpp
  src/parser/MutateSentences.h
  src/parser/Sentence.h
  src/parser/parser.yy
  src/parser/scanner.lex
  src/parser/test/ParserTest.cpp
  src/parser/test/ScannerTest.cpp
  src/storage/CMakeLists.txt
  src/storage/StorageHttpDownloadHandler.cpp
  src/storage/StorageHttpDownloadHandler.h
  src/storage/StorageHttpStatusHandler.cpp
  src/storage/StorageHttpStatusHandler.h
  src/storage/test/CMakeLists.txt
  src/storage/test/MockHdfsHelper.h
  src/storage/test/QueryBoundTest.cpp
  src/storage/test/StorageClientTest.cpp
  src/storage/test/StorageHttpDownloadHandlerTest.cpp
  src/storage/test/StorageHttpStatusHandlerTest.cpp
  src/webservice/Common.h
  src/webservice/WebService.cpp
Labels: ready-for-testing

#607 Fixes on unreserved keywords
  src/parser/parser.yy
  src/parser/test/ParserTest.cpp
Labels: ready-for-testing

#553 Implement admin client for balancer
  src/daemons/CMakeLists.txt
  src/interface/storage.thrift
  src/meta/CMakeLists.txt
  src/meta/processors/admin/AdminClient.cpp
  src/meta/processors/admin/AdminClient.h
  src/meta/processors/admin/BalanceTask.cpp
  src/meta/test/AdminClientTest.cpp
  src/meta/test/BalanceIntegrationTest.cpp
  src/meta/test/CMakeLists.txt
  src/storage/AdminProcessor.h
  src/storage/StorageServiceHandler.cpp
  src/storage/StorageServiceHandler.h
Labels: ready-for-testing

#633 Support check hadoop path in hadoop helper
  src/common/hdfs/HdfsCommandHelper.cpp
  src/common/hdfs/HdfsCommandHelper.h
  src/common/hdfs/HdfsHelper.h
  src/meta/MetaHttpDownloadHandler.cpp
  src/meta/test/MockHdfsHelper.h
  src/storage/StorageHttpDownloadHandler.cpp
  src/storage/test/MockHdfsHelper.h
Labels: ready-for-testing

#638 Fix crash when vertex not exist.
  src/graph/GoExecutor.cpp
  src/graph/test/GoTest.cpp
Labels: defect, ready-for-testing

#635 update query grammar
  docs/get-started.md
  docs/nGQL-tutorial.md
Labels: ready-for-testing

#604 Remove the raftlock_ when appending logs into raft queue
  src/kvstore/raftex/RaftPart.cpp
  src/kvstore/raftex/RaftPart.h
Labels: Enhancement, ready-for-testing

#619 Add preProcessor for each log before it being writen into WAL
  src/kvstore/Part.cpp
  src/kvstore/Part.h
  src/kvstore/raftex/RaftPart.cpp
  src/kvstore/raftex/RaftPart.h
  src/kvstore/raftex/test/TestShard.h
  src/kvstore/wal/FileBasedWal.cpp
  src/kvstore/wal/FileBasedWal.h
  src/kvstore/wal/test/FileBasedWalTest.cpp
Labels: ready-for-testing

#642 add nebula home page reference in README.md
  docs/README.md
  docs/nGQL-tutorial.md
Labels: ready-for-testing

#648 delete CHECK in schema provider
  src/dataman/NebulaCodecImpl.cpp
  src/graph/Executor.cpp
  src/graph/InsertVertexExecutor.cpp
  src/kvstore/plugins/hbase/HBaseStore.cpp
  src/meta/NebulaSchemaProvider.cpp
  src/meta/test/MetaClientTest.cpp
  src/storage/QueryBaseProcessor.inl
Labels: ready-for-testing

#614 fix raft ut
  src/kvstore/raftex/test/LogCommandTest.cpp
  src/kvstore/raftex/test/RaftexTestBase.cpp
Labels: ready-for-testing

#409 Implement filter in storage
  src/common/base/Base.h
  src/common/base/NebulaKeyUtils.h
  src/common/filter/Expressions.h
  src/daemons/CMakeLists.txt
  src/dataman/RowReader.h
  src/graph/GoExecutor.cpp
  src/interface/storage.thrift
  src/meta/test/CMakeLists.txt
  src/storage/Collector.h
  src/storage/CommonUtils.h
  src/storage/QueryBaseProcessor.h
  src/storage/QueryBaseProcessor.inl
  src/storage/QueryBoundProcessor.cpp
  src/storage/QueryBoundProcessor.h
  src/storage/QueryEdgePropsProcessor.cpp
  src/storage/QueryEdgePropsProcessor.h
  src/storage/QueryStatsProcessor.cpp
  src/storage/QueryStatsProcessor.h
  src/storage/QueryVertexPropsProcessor.cpp
  src/storage/test/AdHocSchemaManager.cpp
  src/storage/test/AdHocSchemaManager.h
  src/storage/test/CMakeLists.txt
  src/storage/test/QueryBoundTest.cpp
  src/tools/storage-perf/CMakeLists.txt
Labels: ready-for-testing

#660 Added CNAME file in docs
  docs/CNAME
Labels: ready-for-testing

#595 Fixed a bug where the storage service might crash (#583)
  src/daemons/StorageDaemon.cpp
  src/kvstore/PartManager.cpp
  src/meta/client/MetaClient.cpp
  src/meta/client/MetaClient.h
Labels: ready-for-testing

#630 Fixed false negative report when variable holds empty result
  src/graph/GoExecutor.cpp
  src/graph/VariableHolder.cpp
  src/graph/VariableHolder.h
  src/graph/test/GoTest.cpp
  src/graph/test/TestBase.h
Labels: ready-for-testing

#578 Fixed or adjusted permissions on installed files
  etc/CMakeLists.txt
  scripts/CMakeLists.txt
  share/CMakeLists.txt
  src/daemons/CMakeLists.txt
Labels: ready-for-testing

#663 Fix crash when call hash.
  src/common/filter/FunctionManager.cpp
  src/graph/test/YieldTest.cpp
Labels: ready-for-testing

#665 Fix unstable nebula_store_test(#664)
  src/kvstore/NebulaStore.cpp
  src/kvstore/RocksEngine.h
Labels: ready-for-testing

#661 Fixed recursive unary expression
  src/common/filter/test/ExpressionTest.cpp
  src/parser/parser.yy
Labels: ready-for-testing

#639 Display version and modify the packaging script
  CMakeLists.txt
  package/make_srpm.sh
  package/nebula.spec
  src/common/base/Base.cpp
  src/common/hdfs/CMakeLists.txt
  src/console/CliManager.cpp
  src/meta/client/MetaClient.cpp
Labels: ready-for-testing

#666 change confusing expression in get-started
  docs/get-started.md
Labels: ready-for-testing

#670 Fixed thrift generator
  cmake/ThriftGenerate.cmake
Labels: ready-for-testing

#647 wait for metaserer ready
  src/daemons/StorageDaemon.cpp
  src/graph/ExecutionEngine.cpp
  src/graph/test/TestEnv.cpp
  src/kvstore/PartManager.h
  src/meta/client/MetaClient.cpp
  src/meta/client/MetaClient.h
  src/meta/test/MetaClientTest.cpp
  src/storage/test/StorageClientTest.cpp
Labels: feature, ready-for-testing

#674 fix inconsistent names
  docs/get-started.md
Labels: ready-for-testing

#682 Fix use-after-free problem in UT
  src/graph/test/TestEnv.cpp
Labels: ready-for-testing

#680 Sanitized CMAKE files
  CMakeLists.txt
  cmake/ThriftGenerate.cmake
  src/client/cpp/CMakeLists.txt
  src/common/base/test/CMakeLists.txt
  src/common/concurrent/CMakeLists.txt
  src/common/concurrent/test/CMakeLists.txt
  src/common/filter/CMakeLists.txt
  src/common/filter/test/CMakeLists.txt
  src/common/fs/CMakeLists.txt
  src/common/fs/test/CMakeLists.txt
  src/common/hdfs/CMakeLists.txt
  src/common/hdfs/test/CMakeLists.txt
  src/common/network/CMakeLists.txt
  src/common/network/test/CMakeLists.txt
  src/common/process/CMakeLists.txt
  src/common/process/test/CMakeLists.txt
  src/common/stats/CMakeLists.txt
  src/common/stats/test/CMakeLists.txt
  src/common/thread/CMakeLists.txt
  src/common/thread/test/CMakeLists.txt
  src/common/thrift/CMakeLists.txt
  src/common/time/CMakeLists.txt
  src/common/time/test/CMakeLists.txt
  src/console/CMakeLists.txt
  src/daemons/CMakeLists.txt
  src/dataman/CMakeLists.txt
  src/dataman/RowUpdater.cpp
  src/dataman/RowWriter.cpp
  src/dataman/SchemaWriter.cpp
  src/dataman/test/CMakeLists.txt
  src/graph/CMakeLists.txt
  src/graph/test/CMakeLists.txt
  src/kvstore/CMakeLists.txt
  src/kvstore/plugins/CMakeLists.txt
  src/kvstore/plugins/hbase/CMakeLists.txt
  src/kvstore/plugins/hbase/test/CMakeLists.txt
  src/kvstore/raftex/CMakeLists.txt
  src/kvstore/raftex/test/CMakeLists.txt
  src/kvstore/test/CMakeLists.txt
  src/kvstore/wal/CMakeLists.txt
  src/kvstore/wal/test/CMakeLists.txt
  src/meta/CMakeLists.txt
  src/meta/test/CMakeLists.txt
  src/parser/CMakeLists.txt
  src/parser/test/CMakeLists.txt
  src/storage/CMakeLists.txt
  src/storage/test/CMakeLists.txt
  src/tools/native-client/CMakeLists.txt
  src/tools/storage-perf/CMakeLists.txt
  src/webservice/CMakeLists.txt
  src/webservice/test/CMakeLists.txt
Labels: ready-for-testing

#673 Set default third-party install path and modify how-to-build.md
  CMakeLists.txt
  docs/how-to-build.md
Labels: ready-for-testing

#684 Fix use-after-free problem in BalancerPlan
  src/meta/processors/admin/BalancePlan.cpp
Labels: ready-for-testing

#675 Implement leader change logic
  src/storage/client/StorageClient.cpp
  src/storage/client/StorageClient.h
  src/storage/client/StorageClient.inl
  src/storage/test/StorageClientTest.cpp
  src/tools/storage-perf/StoragePerfTool.cpp
Labels: ready-for-testing

#688 [user manual] add functions and operators
  docs/manul_doc/Functions_and_Operators/Comparison_Functions_and_Operators.md
  docs/manul_doc/Functions_and_Operators/Functions_and_Operator_Reference.md
  docs/manul_doc/Functions_and_Operators/Logical_Operators.md
  docs/manul_doc/Functions_and_Operators/Operator_Precedence.md
  docs/manul_doc/Functions_and_Operators/Operators.md
  docs/manul_doc/Functions_and_Operators/Type_Conversion.md
  docs/manul_doc/Language_Structure/Identifier_Case_Sensitivity.md
  docs/manul_doc/Language_Structure/Schema_Object_Names.md
Labels: ready-for-testing

#681 [Raft] Add some ut, fix some bugs.
  src/kvstore/raftex/RaftPart.cpp
  src/kvstore/raftex/test/CMakeLists.txt
  src/kvstore/raftex/test/LearnerTest.cpp
  src/kvstore/raftex/test/LogAppendTest.cpp
  src/kvstore/raftex/test/LogCASTest.cpp
  src/kvstore/raftex/test/LogCommandTest.cpp
  src/kvstore/raftex/test/RaftCase.cpp
  src/kvstore/raftex/test/RaftexTestBase.cpp
  src/kvstore/raftex/test/RaftexTestBase.h
  src/kvstore/raftex/test/TestShard.cpp
  src/kvstore/raftex/test/TestShard.h
Labels: ready-for-testing

#627 fix crash when thrift service port has been used
  src/common/base/SignalHandler.cpp
  src/common/base/SignalHandler.h
  src/daemons/GraphDaemon.cpp
  src/daemons/MetaDaemon.cpp
  src/daemons/StorageDaemon.cpp
  src/kvstore/NebulaStore.cpp
  src/kvstore/NebulaStore.h
  src/kvstore/raftex/RaftexService.cpp
  src/kvstore/raftex/RaftexService.h
  src/kvstore/raftex/test/RaftexTestBase.cpp
  src/kvstore/test/NebulaStoreTest.cpp
  src/meta/test/TestUtils.h
  src/storage/test/TestUtils.h
Labels: ready-for-testing

#704 Add flag to control thrift workers number
  src/daemons/StorageDaemon.cpp
Labels: ready-for-testing

#689 Fix failed data_test/go_test.
  src/graph/test/TestEnv.cpp
  src/kvstore/NebulaStore.cpp
  src/kvstore/NebulaStore.h
  src/kvstore/test/NebulaStoreTest.cpp
Labels: ready-for-testing

#649 Remove requests queue inside Host
  src/kvstore/raftex/Host.cpp
  src/kvstore/raftex/Host.h
  src/kvstore/raftex/RaftPart.cpp
  src/kvstore/raftex/RaftPart.h
  src/kvstore/test/NebulaStoreTest.cpp
Labels: ready-for-testing
