Repository vesoft-inc/nebula, pull requests merged in 2020-10, with the labels that each got.

#2364 correct code comments
  src/common/filter/geo/GeoParams.h
Labels: ready-for-testing

#2360 fix typo
  src/kvstore/raftex/RaftPart.cpp
Labels: ready-for-testing

#2359 Fix fetch * return wrong result when the vertex with empty props tag
  src/graph/FetchVerticesExecutor.cpp
  src/graph/test/DataTest.cpp
Labels: bug/bugfix, ready-for-testing

#2348 Remove discard Spark Writer
  src/tools/spark-sstfile-generator/build.sbt
  src/tools/spark-sstfile-generator/mapping-schema.json
  src/tools/spark-sstfile-generator/mapping.json
  src/tools/spark-sstfile-generator/pom.xml
  src/tools/spark-sstfile-generator/project/Commons.scala
  src/tools/spark-sstfile-generator/project/assembly.sbt
  src/tools/spark-sstfile-generator/project/build.properties
  src/tools/spark-sstfile-generator/project/plugins.sbt
  src/tools/spark-sstfile-generator/src/main/scala/com/vesoft/tools/DataTypeCompatibility.scala
  src/tools/spark-sstfile-generator/src/main/scala/com/vesoft/tools/FNVHash.scala
  src/tools/spark-sstfile-generator/src/main/scala/com/vesoft/tools/MappingConfiguration.scala
  src/tools/spark-sstfile-generator/src/main/scala/com/vesoft/tools/PropertyValueAndTypeWritable.scala
  src/tools/spark-sstfile-generator/src/main/scala/com/vesoft/tools/SparkSstFileGenerator.scala
  src/tools/spark-sstfile-generator/src/main/scala/com/vesoft/tools/SstFileOutputFormat.scala
Labels: ready-for-testing

#2339 Add ubuntu2004 and centos8 package and tar package
  .github/workflows/package.yaml
  .github/workflows/release.yaml
  cmake/CPackage.cmake
  package/package.sh
Labels: doc required, ready-for-testing

#2370 correct code-commenting
  src/common/stats/StatsManager.h
  src/kvstore/raftex/RaftPart.h
Labels: ready-for-testing

#2376 Fixed filter error for index scan
  src/graph/test/LookupTest.cpp
  src/storage/index/IndexPolicyMaker.cpp
Labels: ready-for-testing

#2377 Try to use whole key bloom filter when insert data with index
  src/storage/BaseProcessor.h
  src/storage/BaseProcessor.inl
  src/storage/mutate/AddEdgesProcessor.cpp
  src/storage/mutate/AddVerticesProcessor.cpp
  src/storage/test/IndexTest.cpp
Labels: ready-for-testing

#2374 code-commenting problem
  src/meta/client/MetaClient.cpp
  src/meta/client/MetaClient.h
Labels: ready-for-testing
