Repository vesoft-inc/nebula, pull requests merged in 2020-07, with the labels that each got.

#2199 Fixed issue using unreserved aliased keyword as label
  src/graph/test/SchemaTest.cpp
  src/parser/parser.yy
  src/parser/scanner.lex
  src/parser/test/ScannerTest.cpp
Labels: ready-for-testing

#2202 Correct/go record out of range
  src/graph/GoExecutor.cpp
  src/graph/test/GoTest.cpp
Labels: bug/bugfix, ready-for-testing

#2155 Fix show create can't execute
  src/graph/SchemaHelper.cpp
  src/graph/ShowExecutor.cpp
  src/graph/test/IndexTest.cpp
  src/graph/test/SchemaTest.cpp
  src/graph/test/TTLTest.cpp
Labels: bug/bugfix, ready-for-testing

#2196 Support no username and password are required
  src/console/CMakeLists.txt
  src/console/CliManager.cpp
  src/console/CliManager.h
  src/console/NebulaConsole.cpp
Labels: doc required, ready-for-testing

#2188 fix default batch from 2 to 512
  src/tools/spark-sstfile-generator/src/main/scala/com/vesoft/nebula/tools/generator/v2/SparkClientGenerator.scala
Labels: ready-for-testing

#2146 Add warning msg
  src/console/CmdProcessor.cpp
  src/graph/DropSpaceExecutor.cpp
  src/graph/DropSpaceExecutor.h
  src/interface/graph.thrift
Labels: ready-for-testing

#2114 Modify permissions for configuration files
  package/postinst
  package/rpm_postinst
Labels: ready-for-testing

#2183 fixed rebuild index status information disrupted.
  src/graph/test/IndexTest.cpp
  src/meta/processors/indexMan/DropEdgeIndexProcessor.cpp
  src/meta/processors/indexMan/DropTagIndexProcessor.cpp
Labels: next-release, ready-for-testing

#2193 fix a potential raft term error
  src/kvstore/raftex/Host.cpp
  src/kvstore/raftex/RaftPart.cpp
  src/kvstore/raftex/RaftPart.h
Labels: ready-for-testing

#2209 Fix find path can't use uuid
  src/graph/FindPathExecutor.cpp
  src/graph/test/FindPathTest.cpp
  src/parser/Clauses.cpp
  src/parser/Clauses.h
Labels: ready-for-testing

#2205 Revert "Fixed issue using unreserved aliased keyword as label (#2199)"
  src/graph/test/SchemaTest.cpp
  src/parser/parser.yy
  src/parser/scanner.lex
  src/parser/test/ScannerTest.cpp
Labels: ready-for-testing

#2203 Correct/go back trace overlap
  src/graph/GoExecutor.cpp
  src/graph/GoExecutor.h
  src/graph/InterimResult.h
  src/graph/test/GoTest.cpp
Labels: bug/bugfix, ready-for-testing

#2215 Fixed build of native client
  src/jni/CMakeLists.txt
  src/tools/native-client/CMakeLists.txt
  src/tools/native-client/pom.xml
Labels: ready-for-testing

#2214 Enable frame pointer by default
  CMakeLists.txt
  third-party/CMakeLists.txt
Labels: ready-for-testing

#2063 Remove out inline coverage information in CI.
  .github/workflows/build.yaml
  .github/workflows/pull_request.yaml
Labels: ready-for-testing

#2217 Failed to stop storaged forever if try to stop it before kvstore inited
  src/storage/StorageServer.cpp
  src/storage/StorageServer.h
Labels: ready-for-testing

#2208 Build with -rdynamic
  CMakeLists.txt
Labels: ready-for-testing

#2223 Fix native client.
  src/tools/native-client/CMakeLists.txt
Labels: ready-for-testing

#2124 Correct the index write benchmark
  src/storage/test/StorageIndexWriteBenchmark.cpp
Labels: ready-for-testing

#2060 delete the code never run
  src/kvstore/raftex/RaftPart.cpp
Labels: ready-for-testing

#2119 Add the default configuration for gflags flag mode.
  src/meta/GflagsManager.cpp
  src/meta/client/MetaClient.cpp
Labels: Enhancement, ready-for-testing

#1958 Add the field about compatibility in pull request template.
  .github/pull_request_template.md
Labels: ready-for-testing

#2221 update vertex and edge benchmark
  src/storage/test/AddAndUpdateVertexAndEdgeBenchmark.cpp
  src/storage/test/CMakeLists.txt
Labels: ready-for-testing

#1946 Modify packaging script to support static link sanitizer.
  package/package.sh
Labels: ready-for-testing

#2085 Using function instead of macro to reduce compile consumption.
  src/parser/test/ScannerTest.cpp
Labels: ready-for-testing

#2230 SparkClientGenerator escape double quote and backlash for string field
  src/tools/spark-sstfile-generator/src/main/scala/com/vesoft/nebula/tools/generator/v2/SparkClientGenerator.scala
Labels: ready-for-testing

#2226 Support StatsManager::readAllValue include p99
  src/common/stats/StatsManager.cpp
  src/common/stats/test/StatsManagerTest.cpp
Labels: ready-for-testing

#2231 update benckmark result
  src/storage/test/AddAndUpdateVertexAndEdgeBenchmark.cpp
Labels: ready-for-testing

#2058 Check/create edge index
  src/common/base/Status.h
  src/graph/CreateEdgeIndexExecutor.cpp
  src/meta/processors/indexMan/CreateEdgeIndexProcessor.cpp
Labels: Enhancement, ready-for-testing

#2187 fix SparkClientGenerator when reading file, wrong columns
  src/tools/spark-sstfile-generator/src/main/scala/com/vesoft/nebula/tools/generator/v2/SparkClientGenerator.scala
Labels: ready-for-testing

#2224 fix unstable raft ut
  src/kvstore/raftex/RaftPart.cpp
  src/kvstore/raftex/RaftPart.h
  src/meta/test/BalanceIntegrationTest.cpp
  src/tools/storage-perf/StoragePerfTool.cpp
Labels: ready-for-testing

#1695 Check the index have existed although the name not the same
  src/graph/test/IndexTest.cpp
  src/meta/processors/BaseProcessor.h
  src/meta/processors/BaseProcessor.inl
  src/meta/processors/indexMan/CreateEdgeIndexProcessor.cpp
  src/meta/processors/indexMan/CreateTagIndexProcessor.cpp
  src/meta/test/MetaClientTest.cpp
  src/meta/test/ProcessorTest.cpp
Labels: defect-p3, ready-for-testing

#2236 set rocksdb_disable_wal to false by default
  etc/nebula-metad.conf.production
  etc/nebula-storaged.conf.default
  etc/nebula-storaged.conf.production
  kubernetes/helm/templates/configmap.yaml
  src/kvstore/RocksEngineConfig.cpp
Labels: ready-for-testing

#2238 Fix the memroy leak in the parser when parse admin job operation.
  src/parser/parser.yy
Labels: bug/bugfix, ready-for-testing

#2139 Limit total partitions
  src/graph/test/CMakeLists.txt
  src/graph/test/PartitionTest.cpp
  src/interface/meta.thrift
  src/meta/client/MetaClient.cpp
  src/meta/processors/partsMan/CreateSpaceProcessor.cpp
  src/meta/processors/partsMan/CreateSpaceProcessor.h
Labels: ready-for-testing

#2225 go sentence support integer/timestamp type to start traverse.
  src/graph/InterimResult.cpp
  src/graph/test/GoTest.cpp
Labels: ready-for-testing

#2235 fixed expression check for invalid edge
  src/storage/query/QueryBaseProcessor.inl
Labels: ready-for-testing

#2240 fix meta can't be stopped
  src/daemons/MetaDaemon.cpp
Labels: ready-for-testing

#2222 rewrite fetch prop on vertex: 1. support input/variable/multi-vertex-id/multi-tags. 2. keep order of input.
  .gitignore
  src/graph/CloudAuthenticator.cpp
  src/graph/FetchEdgesExecutor.cpp
  src/graph/FetchVerticesExecutor.cpp
  src/graph/FetchVerticesExecutor.h
  src/graph/TraverseExecutor.cpp
  src/graph/test/FetchVerticesTest.cpp
  src/meta/SchemaManager.h
  src/meta/ServerBasedSchemaManager.cpp
  src/meta/ServerBasedSchemaManager.h
  src/meta/client/MetaClient.cpp
  src/meta/client/MetaClient.h
  src/parser/Clauses.cpp
  src/parser/Clauses.h
  src/parser/TraverseSentences.cpp
  src/parser/TraverseSentences.h
  src/parser/parser.yy
  src/parser/test/ParserTest.cpp
  src/storage/test/AdHocSchemaManager.h
Labels: feature, ready-for-testing

#2239 rename max_parts_num and set the default value of max_parts_num to 16…
  src/graph/test/PartitionTest.cpp
  src/meta/processors/partsMan/CreateSpaceProcessor.cpp
Labels: ready-for-testing

#2244 Fixed a bug in the packaging script.
  package/package.sh
Labels: ready-for-testing

#2246 update
  README.md
Labels: ready-for-testing

#2243 Support to enable rocksdbs statistics
  etc/nebula-storaged.conf.default
  etc/nebula-storaged.conf.production
  src/kvstore/RocksEngineConfig.cpp
  src/kvstore/RocksEngineConfig.h
  src/kvstore/test/RocksEngineConfigTest.cpp
Labels: ready-for-testing

#2254 Add more information when opening wal failed
  src/kvstore/wal/FileBasedWal.cpp
Labels: ready-for-testing

#2251 compaction threads/rate limiter
  src/kvstore/RocksEngineConfig.cpp
Labels: ready-for-testing

#2249 fix VertexHolder::getDefaultProp performance issue.
  src/dataman/RowReader.cpp
  src/dataman/RowReader.h
  src/dataman/RowSetReader.h
  src/dataman/RowUpdater.cpp
  src/dataman/RowUpdater.h
  src/graph/FetchVerticesExecutor.cpp
  src/graph/GoExecutor.cpp
  src/graph/GoExecutor.h
  src/storage/mutate/AddEdgesProcessor.cpp
  src/storage/mutate/AddVerticesProcessor.cpp
  src/storage/mutate/DeleteEdgesProcessor.cpp
  src/storage/mutate/DeleteVerticesProcessor.cpp
  src/storage/mutate/UpdateEdgeProcessor.cpp
  src/storage/mutate/UpdateVertexProcessor.cpp
  src/storage/query/QueryBaseProcessor.h
  src/storage/query/QueryBaseProcessor.inl
  src/storage/query/QueryBoundProcessor.cpp
  src/storage/query/QueryStatsProcessor.cpp
Labels: ready-for-testing

#2253 remove lru partid as hint.
  src/storage/index/IndexExecutor.inl
  src/storage/mutate/AddVerticesProcessor.cpp
  src/storage/mutate/DeleteVerticesProcessor.cpp
  src/storage/mutate/UpdateVertexProcessor.cpp
  src/storage/query/QueryBaseProcessor.inl
  src/storage/query/QueryVertexPropsProcessor.cpp
Labels: ready-for-testing

#2237 Using icord to avoid dynamic allocation and speed up write.
  src/common/filter/Expressions.cpp
  src/common/filter/Expressions.h
  src/dataman/RowWriter.h
Labels: ready-for-testing

#2262 Exposing rocksdb statistics through webservice
  src/kvstore/RocksEngineConfig.cpp
  src/storage/CMakeLists.txt
  src/storage/StorageServer.cpp
  src/storage/http/StorageHttpStatsHandler.cpp
  src/storage/http/StorageHttpStatsHandler.h
  src/storage/test/CMakeLists.txt
  src/storage/test/StorageHttpStatsHandlerTest.cpp
  src/webservice/GetStatsHandler.h
Labels: ready-for-testing
