Repository vesoft-inc/nebula, pull requests merged in 2020-04, with the labels that each got.

#1972 upload package to oss
  .github/workflows/build.yaml
  .github/workflows/package.yaml
  .github/workflows/release.yaml
  ci/scripts/upload-oss.sh
Labels: ready-for-testing

#1985 fixed unstable testcase for rebuild index
  src/graph/test/IndexTest.cpp
Labels: ready-for-testing

#2033 Fix unable to stop while storage is doing compaction
  src/kvstore/KVEngine.h
  src/kvstore/KVStore.h
  src/kvstore/NebulaStore.cpp
  src/kvstore/NebulaStore.h
  src/kvstore/RocksEngine.cpp
  src/kvstore/RocksEngine.h
  src/kvstore/plugins/hbase/HBaseStore.h
  src/meta/processors/admin/CreateSnapshotProcessor.cpp
  src/meta/processors/admin/DropSnapshotProcessor.cpp
  src/meta/processors/partsMan/CreateSpaceProcessor.cpp
  src/meta/processors/partsMan/DropSpaceProcessor.cpp
  src/storage/StorageServer.cpp
Labels: ready-for-testing

#2025 Fix the error when vertex/edge not exist if update.
  src/graph/UpdateEdgeExecutor.cpp
  src/graph/UpdateVertexExecutor.cpp
  src/storage/CommonUtils.h
  src/storage/mutate/UpdateEdgeProcessor.cpp
  src/storage/mutate/UpdateEdgeProcessor.h
  src/storage/mutate/UpdateVertexProcessor.cpp
  src/storage/mutate/UpdateVertexProcessor.h
Labels: bug-fix, rc4-cherrypick, ready-for-testing

#2013 Sampling apply to all edges starting from a vertex.
  src/storage/query/QueryBaseProcessor.h
  src/storage/query/QueryBaseProcessor.inl
  src/storage/query/QueryBoundProcessor.cpp
  src/storage/query/QueryBoundProcessor.h
  src/storage/query/QueryStatsProcessor.cpp
  src/storage/test/QueryBoundTest.cpp
Labels: rc4-cherrypick, ready-for-testing

#2042 Fix crash when fetch YIELD clause has input prop and input is empty
  src/graph/TraverseExecutor.cpp
  src/graph/test/FetchVerticesTest.cpp
Labels: bug, rc4-cherrypick, ready-for-testing

#2031 remove bigint because we dont support it
  .linters/cpp/checkKeyword.py
  src/common/filter/Expressions.cpp
  src/common/filter/Expressions.h
  src/parser/parser.yy
  src/parser/scanner.lex
  src/parser/test/ScannerTest.cpp
  src/parser/test/fuzzing/nebula.dict
Labels: bug-fix, ready-for-testing

#2038 Correct issue 2009 which the timestamp default value for edge not treat.
  src/graph/test/SchemaTest.cpp
  src/meta/processors/schemaMan/CreateEdgeProcessor.cpp
  src/meta/processors/schemaMan/CreateTagProcessor.cpp
Labels: bug-fix, rc4-cherrypick, ready-for-testing

#2051 RC4 Cherrypick #2031 #2042 #2025 #2013 #2038
  .linters/cpp/checkKeyword.py
  src/common/filter/Expressions.cpp
  src/common/filter/Expressions.h
  src/graph/TraverseExecutor.cpp
  src/graph/UpdateEdgeExecutor.cpp
  src/graph/UpdateVertexExecutor.cpp
  src/graph/test/FetchVerticesTest.cpp
  src/graph/test/SchemaTest.cpp
  src/meta/processors/schemaMan/CreateEdgeProcessor.cpp
  src/meta/processors/schemaMan/CreateTagProcessor.cpp
  src/parser/parser.yy
  src/parser/scanner.lex
  src/parser/test/ScannerTest.cpp
  src/parser/test/fuzzing/nebula.dict
  src/storage/CommonUtils.h
  src/storage/mutate/UpdateEdgeProcessor.cpp
  src/storage/mutate/UpdateEdgeProcessor.h
  src/storage/mutate/UpdateVertexProcessor.cpp
  src/storage/mutate/UpdateVertexProcessor.h
  src/storage/query/QueryBaseProcessor.h
  src/storage/query/QueryBaseProcessor.inl
  src/storage/query/QueryBoundProcessor.cpp
  src/storage/query/QueryBoundProcessor.h
  src/storage/query/QueryStatsProcessor.cpp
  src/storage/test/QueryBoundTest.cpp
Labels: ready-for-testing

#2023 Fix timestamp type for default value
  src/graph/Executor.cpp
  src/graph/Executor.h
  src/graph/InsertEdgeExecutor.cpp
  src/graph/InsertVertexExecutor.cpp
  src/graph/SchemaHelper.cpp
  src/graph/SchemaHelper.h
  src/graph/test/DataTest.cpp
  src/graph/test/SchemaTest.cpp
  src/parser/MaintainSentences.h
Labels: rc4-cherrypick, ready-for-testing

#2049 Avoid memory leak with thread local PerfContext in rocksdb 6.7.3
  third-party/externals/rocksdb.cmake
Labels: ready-for-testing

#2045 Modify ASAN_SYMBOLIZER_PATH
  .github/workflows/build.yaml
  .github/workflows/pull_request.yaml
Labels: ready-for-testing

#1956 Simplify index storage
  src/graph/LookupExecutor.cpp
  src/graph/LookupExecutor.h
  src/graph/test/LookupTest.cpp
  src/interface/storage.thrift
  src/storage/CMakeLists.txt
  src/storage/StorageServiceHandler.cpp
  src/storage/StorageServiceHandler.h
  src/storage/client/StorageClient.cpp
  src/storage/client/StorageClient.h
  src/storage/index/IndexExecutor.h
  src/storage/index/IndexExecutor.inl
  src/storage/index/LookUpEdgeIndexProcessor.cpp
  src/storage/index/LookUpEdgeIndexProcessor.h
  src/storage/index/LookUpIndexProcessor.cpp
  src/storage/index/LookUpIndexProcessor.h
  src/storage/index/LookUpVertexIndexProcessor.h
  src/storage/test/IndexScanTest.cpp
  src/storage/test/StorageLookupBenchmark.cpp
Labels: alert/break, ready-for-testing

#1930 [doc]kw-reserved-words
  docs/manual-CN/2.query-language/3.language-structure/.keywords-and-reserved-words.md
  docs/manual-CN/2.query-language/3.language-structure/keywords-and-reserved-words.md
  docs/manual-CN/README.md
  docs/manual-EN/2.query-language/3.language-structure/.keywords-and-reserved-words.md
  docs/manual-EN/2.query-language/3.language-structure/keywords-and-reserved-words.md
  docs/manual-EN/README.md
Labels: nGQL, ready-for-testing

#2056 [doc]roadmap added
  README-CN.md
  README.md
Labels: ready-for-testing

#1665 Disabled strict aliasing by default
  CMakeLists.txt
Labels: ready-for-testing

#2037 [doc] change doc link to doc site
  CONTRIBUTING.md
  README-CN.md
  README.md
Labels: ready-for-testing

#2015 [doc]update TTL example in create tag doc
  docs/manual-CN/2.query-language/4.statement-syntax/1.data-definition-statements/create-tag-edge-syntax.md
  docs/manual-EN/2.query-language/4.statement-syntax/1.data-definition-statements/create-tag-edge-syntax.md
Labels: ready-for-testing

#1629 Refactor the expression test to reduce the symbol count
  src/common/filter/Expressions.h
  src/common/filter/test/ExpressionTest.cpp
Labels: ready-for-testing

#2073 Supports older version of schema for index write
  src/graph/test/IndexTest.cpp
  src/storage/BaseProcessor.h
  src/storage/BaseProcessor.inl
  src/storage/admin/RebuildEdgeIndexProcessor.cpp
  src/storage/admin/RebuildTagIndexProcessor.cpp
  src/storage/mutate/AddEdgesProcessor.cpp
  src/storage/mutate/AddVerticesProcessor.cpp
  src/storage/mutate/DeleteEdgesProcessor.cpp
  src/storage/mutate/DeleteVerticesProcessor.cpp
  src/storage/mutate/UpdateEdgeProcessor.cpp
  src/storage/mutate/UpdateVertexProcessor.cpp
Labels: ready-for-testing

#2068 [doc]add-checklist-in-pr-template
  .github/pull_request_template.md
Labels: ready-for-testing

#2079 double support scientific notation.
  src/parser/scanner.lex
  src/parser/test/ScannerTest.cpp
Labels: documentation, ready-for-testing

#1964 Support cloud account authentication
  etc/nebula-graphd.conf.default
  etc/nebula-graphd.conf.production
  src/common/encryption/Base64.cpp
  src/common/encryption/Base64.h
  src/common/encryption/CMakeLists.txt
  src/common/http/HttpClient.cpp
  src/common/http/HttpClient.h
  src/common/permission/PermissionManager.cpp
  src/common/session/Session.h
  src/graph/CMakeLists.txt
  src/graph/CloudAuthenticator.cpp
  src/graph/CloudAuthenticator.h
  src/graph/GraphFlags.cpp
  src/graph/GraphFlags.h
  src/graph/GraphService.cpp
  src/graph/GraphService.h
  src/graph/test/CMakeLists.txt
  src/graph/test/CloudAccountAuthTest.cpp
  src/meta/client/MetaClient.cpp
  src/meta/client/MetaClient.h
Labels: ready-for-testing

#1960 Support check code when collect execution result
  src/tools/spark-sstfile-generator/src/main/scala/com/vesoft/nebula/tools/generator/v2/SparkClientGenerator.scala
Labels: ready-for-testing

#2066 Modified the Go client's generation parameters
  cmake/ThriftGenerate.cmake
Labels: ready-for-testing

#2054 Modify oss sub dir and add doc.
  ci/scripts/upload-oss.sh
  docs/manual-CN/3.build-develop-and-administration/3.deploy-and-administrations/deployment/install-with-rpm-deb.md
Labels: ready-for-testing

#2077 Add operator contains.
  src/common/filter/Expressions.cpp
  src/common/filter/Expressions.h
  src/common/filter/test/ExpressionTest.cpp
  src/graph/test/GoTest.cpp
  src/parser/parser.yy
  src/parser/scanner.lex
  src/parser/test/ScannerTest.cpp
Labels: documentation, ready-for-testing

#2088 Optimize registerStats performance
  src/common/stats/StatsManager.cpp
Labels: ready-for-testing

#2070 Disabled PCH by default
  CMakeLists.txt
Labels: ready-for-testing

#1869 console security
  src/console/CliManager.cpp
Labels: ready-for-testing

#2078 [doc]update-CN-forum-link
  README-CN.md
Labels: ready-for-testing

#2094 Fixed SO_REUSEPORT
  src/daemons/GraphDaemon.cpp
Labels: ready-for-testing

#2095 Modify download domain name
  docs/manual-CN/1.overview/2.quick-start/1.get-started.md
  docs/manual-EN/1.overview/2.quick-start/1.get-started.md
  third-party/build-third-party.sh
  third-party/install-gcc.sh
  third-party/install-third-party.sh
Labels: ready-for-testing

#1977 Make enable_reservoir_sampling mutable.
  share/resources/gflags.json
Labels: ready-for-testing

#2108 Strict check the validation of console arguments.
  src/console/NebulaConsole.cpp
Labels: ready-for-testing
