Repository vesoft-inc/nebula, pull requests merged in 2020-05, with the labels that each got.

#2109 support cloud auth
  src/graph/CloudAuthenticator.cpp
  src/graph/test/CloudAccountAuthTest.cpp
Labels: ready-for-testing

#2107 [doc]update-readme
  README-CN.md
  README.md
Labels: ready-for-testing

#2111 To improve 'Show roles in space'
  src/graph/ShowExecutor.cpp
  src/graph/test/PermissionTest.cpp
Labels: documentation, ready-for-testing

#2112 fix typo
  src/common/base/ConcurrentLRUCache.h
Labels: ready-for-testing

#1933 [raft] fix follower would start election even leader exists
  src/kvstore/raftex/Host.cpp
Labels: ready-for-testing

#2110 Fix YIELD sentence loss vid type
  src/graph/YieldExecutor.cpp
  src/graph/test/YieldTest.cpp
Labels: bug-fix, ready-for-testing

#2105 Catch the json parsing exception then cloud auth.
  src/graph/CloudAuthenticator.cpp
Labels: bug-fix, ready-for-testing

#2030 fix leader change unstable UT
  src/storage/test/CheckpointTest.cpp
  src/storage/test/CompactionTest.cpp
  src/storage/test/TestUtils.h
Labels: ready-for-testing

#2116 Fix crash when inputs has empty data.
  src/graph/GroupByExecutor.cpp
  src/graph/InterimResult.h
  src/graph/ReturnExecutor.cpp
  src/graph/test/FetchEdgesTest.cpp
  src/graph/test/FetchVerticesTest.cpp
  src/graph/test/FindPathTest.cpp
  src/graph/test/GoTest.cpp
  src/graph/test/GroupByLimitTest.cpp
  src/graph/test/OrderByTest.cpp
  src/graph/test/YieldTest.cpp
Labels: bug-fix, ready-for-testing

#2093 modify etc configs for production usage
  etc/nebula-metad.conf.default
  etc/nebula-metad.conf.production
  etc/nebula-storaged.conf.default
  etc/nebula-storaged.conf.production
Labels: ready-for-testing

#2115 Use "-- " as comment prefix
  src/graph/test/YieldTest.cpp
  src/parser/scanner.lex
  src/parser/test/ParserTest.cpp
Labels: documentation, ready-for-testing

#1992 Fix meta would send empty raft snapshot
  etc/nebula-metad.conf.production
  src/common/utils/NebulaKeyUtils.cpp
  src/common/utils/NebulaKeyUtils.h
  src/kvstore/KVEngine.h
  src/kvstore/Part.cpp
  src/kvstore/RocksEngine.cpp
  src/kvstore/RocksEngine.h
  src/kvstore/RocksEngineConfig.cpp
  src/kvstore/RocksEngineConfig.h
  src/kvstore/SnapshotManagerImpl.cpp
Labels: ready-for-testing

#2123 github action add cloud branch
  .github/workflows/pull_request.yaml
Labels: ready-for-testing

#2128 Flush rocksdb before clean expired wal
  src/kvstore/NebulaStore.cpp
  src/kvstore/NebulaStore.h
  src/kvstore/raftex/RaftPart.cpp
  src/kvstore/raftex/RaftPart.h
Labels: ready-for-testing

#2131 Fix type error when yield a variable prop.
  src/graph/TraverseExecutor.cpp
  src/graph/test/YieldTest.cpp
Labels: ready-for-testing

#2117 fix get pid
  scripts/utils.sh
Labels: bug-fix, ready-for-testing

#2101 Correct the forever loop when go zero steps in cycle.
  src/graph/GoExecutor.cpp
  src/graph/test/GoTest.cpp
  src/parser/test/ParserTest.cpp
Labels: bug-fix, ready-for-testing

#1965 Refactor StoragePerfTool
  src/tools/storage-perf/StoragePerfTool.cpp
Labels: ready-for-testing

#1355 Added the wal_sync configuration option
  src/common/fs/FileUtils.cpp
  src/kvstore/raftex/RaftPart.cpp
  src/kvstore/wal/FileBasedWal.cpp
  src/kvstore/wal/FileBasedWal.h
Labels: ready-for-testing

#2122 Fix the dst vertex use default value when use the nonexistent tag
  src/graph/GoExecutor.cpp
  src/graph/test/GoTest.cpp
Labels: bug-fix, ready-for-testing

#2130 [doc] change code of conduct
  CODE_OF_CONDUCT.md
Labels: ready-for-testing

#2084 Try to compile coverage version with all core.
  .github/workflows/pull_request.yaml
Labels: ready-for-testing

#2086 Check the rand function parameter range.
  src/common/base/Status.h
  src/common/filter/Expressions.cpp
  src/common/filter/Expressions.h
  src/common/filter/FunctionManager.cpp
  src/common/filter/FunctionManager.h
  src/common/filter/test/ExpressionTest.cpp
Labels: bug-fix, ready-for-testing

#2092 Skip the space check for grant when authority type is cloud
  src/meta/processors/usersMan/AuthenticationProcessor.cpp
Labels: ready-for-testing

#2089 Workaround for #2087, which lose the data when join with duplicate in…
  src/graph/GoExecutor.cpp
  src/graph/GoExecutor.h
  src/graph/test/GoTest.cpp
Labels: bug-fix, ready-for-testing

#2132 Fixed an error when using Clang and opening ENABLE_UBSAN.
  CMakeLists.txt
Labels: ready-for-testing

#2003 Correc the alter default value dont't affected.
  src/graph/SchemaHelper.cpp
  src/graph/SchemaHelper.h
  src/graph/test/SchemaTest.cpp
  src/meta/MetaServiceUtils.cpp
  src/meta/MetaServiceUtils.h
  src/meta/processors/BaseProcessor.h
  src/meta/processors/BaseProcessor.inl
  src/meta/processors/schemaMan/AlterEdgeProcessor.cpp
  src/meta/processors/schemaMan/AlterTagProcessor.cpp
  src/meta/processors/schemaMan/CreateEdgeProcessor.cpp
  src/meta/processors/schemaMan/CreateTagProcessor.cpp
Labels: bug-fix, rc4-cherrypick, ready-for-testing

#2091 Support `GO M TO N STEPS` which record the data in go traversal.
  src/graph/FindPathExecutor.cpp
  src/graph/GoExecutor.cpp
  src/graph/GoExecutor.h
  src/graph/test/GoTest.cpp
  src/graph/test/TestBase.h
  src/parser/Clauses.cpp
  src/parser/Clauses.h
  src/parser/parser.yy
  src/parser/test/ParserTest.cpp
  src/storage/client/StorageClient.h
Labels: doc required, feature, nGQL, ready-for-testing

#2137 Pick #2092 from master to cloud
  src/meta/processors/usersMan/AuthenticationProcessor.cpp
Labels: ready-for-testing

#2136 [cherrypick] v1.0 cherrypick #2091
  src/graph/FindPathExecutor.cpp
  src/graph/GoExecutor.cpp
  src/graph/GoExecutor.h
  src/graph/test/GoTest.cpp
  src/graph/test/TestBase.h
  src/parser/Clauses.cpp
  src/parser/Clauses.h
  src/parser/parser.yy
  src/parser/test/ParserTest.cpp
  src/storage/client/StorageClient.h
Labels: ready-for-testing

#2140 increase job mgr default internal threads from 3 to 10.
  src/meta/processors/jobMan/JobManager.cpp
Labels: ready-for-testing

#2141 [Cherrypick] #2140
  src/meta/processors/jobMan/JobManager.cpp
Labels: ready-for-testing

#2144 Add package description
  cmake/CPackage.cmake
Labels: ready-for-testing

#2145 cherrypick #2144
  cmake/CPackage.cmake
Labels: ready-for-testing

#2148 Let the m to n steps return the data even if can't reach n steps.
  src/graph/GoExecutor.cpp
  src/graph/test/GoTest.cpp
Labels: ready-for-testing
