Repository vesoft-inc/nebula, pull requests merged in 2020-03, with the labels that each got.

#1830 Issue #1827 Fixed an error when using update sentence.
  src/graph/UpdateEdgeExecutor.cpp
  src/graph/UpdateEdgeExecutor.h
  src/graph/UpdateVertexExecutor.cpp
  src/graph/UpdateVertexExecutor.h
Labels: ready-for-testing

#1752 [doc]add bidirect
  docs/manual-CN/2.query-language/4.statement-syntax/2.data-query-and-manipulation-statements/go-syntax.md
  docs/manual-EN/2.query-language/4.statement-syntax/2.data-query-and-manipulation-statements/go-syntax.md
Labels: nGQL, ready-for-testing

#1317 [urgent] Support delete vertices
  src/graph/CMakeLists.txt
  src/graph/DeleteEdgesExecutor.cpp
  src/graph/DeleteEdgesExecutor.h
  src/graph/DeleteVertexExecutor.cpp
  src/graph/DeleteVerticesExecutor.cpp
  src/graph/DeleteVerticesExecutor.h
  src/graph/Executor.cpp
  src/graph/test/CMakeLists.txt
  src/graph/test/DeleteVertexTest.cpp
  src/graph/test/DeleteVerticesTest.cpp
  src/graph/test/FetchVerticesTest.cpp
  src/graph/test/TraverseTestBase.h
  src/interface/storage.thrift
  src/parser/Clauses.h
  src/parser/MutateSentences.cpp
  src/parser/MutateSentences.h
  src/parser/parser.yy
  src/parser/test/ParserTest.cpp
  src/storage/BaseProcessor.h
  src/storage/BaseProcessor.inl
  src/storage/CMakeLists.txt
  src/storage/StorageServiceHandler.cpp
  src/storage/StorageServiceHandler.h
  src/storage/client/StorageClient.cpp
  src/storage/client/StorageClient.h
  src/storage/mutate/AddEdgesProcessor.cpp
  src/storage/mutate/AddVerticesProcessor.cpp
  src/storage/mutate/DeleteEdgesProcessor.cpp
  src/storage/mutate/DeleteEdgesProcessor.h
  src/storage/mutate/DeleteVertexProcessor.cpp
  src/storage/mutate/DeleteVertexProcessor.h
  src/storage/mutate/DeleteVerticesProcessor.cpp
  src/storage/mutate/DeleteVerticesProcessor.h
  src/storage/mutate/UpdateEdgeProcessor.cpp
  src/storage/mutate/UpdateVertexProcessor.cpp
  src/storage/query/QueryEdgeKeysProcessor.cpp
  src/storage/query/QueryEdgeKeysProcessor.h
  src/storage/test/CMakeLists.txt
  src/storage/test/DeleteVerticesTest.cpp
  src/storage/test/IndexTest.cpp
  src/storage/test/QueryEdgeKeysTest.cpp
  src/storage/test/StorageClientTest.cpp
Labels: ready-for-testing

#1841 Check if inputs has duplicate column.
  src/dataman/SchemaWriter.cpp
  src/graph/FetchEdgesExecutor.cpp
  src/graph/FetchExecutor.cpp
  src/graph/FetchExecutor.h
  src/graph/FetchVerticesExecutor.cpp
  src/graph/FindPathExecutor.cpp
  src/graph/FindPathExecutor.h
  src/graph/GoExecutor.cpp
  src/graph/GoExecutor.h
  src/graph/GroupByExecutor.cpp
  src/graph/GroupByExecutor.h
  src/graph/InterimResult.cpp
  src/graph/InterimResult.h
  src/graph/LimitExecutor.cpp
  src/graph/LimitExecutor.h
  src/graph/LookupExecutor.h
  src/graph/OrderByExecutor.cpp
  src/graph/OrderByExecutor.h
  src/graph/TraverseExecutor.cpp
  src/graph/TraverseExecutor.h
  src/graph/YieldExecutor.cpp
  src/graph/YieldExecutor.h
  src/graph/test/FetchEdgesTest.cpp
  src/graph/test/FetchVerticesTest.cpp
  src/graph/test/FindPathTest.cpp
  src/graph/test/GoTest.cpp
  src/graph/test/GroupByLimitTest.cpp
  src/graph/test/OrderByTest.cpp
  src/graph/test/YieldTest.cpp
Labels: ready-for-testing

#1840 support return partial result in get of kv interfaces
  src/common/base/Status.h
  src/interface/storage.thrift
  src/kvstore/Common.h
  src/kvstore/KVEngine.h
  src/kvstore/KVStore.h
  src/kvstore/NebulaStore.cpp
  src/kvstore/NebulaStore.h
  src/kvstore/RocksEngine.cpp
  src/kvstore/RocksEngine.h
  src/kvstore/plugins/hbase/HBaseClient.cpp
  src/kvstore/plugins/hbase/HBaseClient.h
  src/kvstore/plugins/hbase/HBaseStore.cpp
  src/kvstore/plugins/hbase/HBaseStore.h
  src/kvstore/plugins/hbase/test/HBaseClientTest.cpp
  src/kvstore/plugins/hbase/test/HBaseStoreTest.cpp
  src/meta/processors/BaseProcessor.inl
  src/storage/BaseProcessor.inl
  src/storage/StorageServiceHandler.cpp
  src/storage/client/StorageClient.cpp
  src/storage/client/StorageClient.h
  src/storage/kv/GetProcessor.cpp
  src/storage/kv/GetProcessor.h
  src/storage/test/CMakeLists.txt
  src/storage/test/KVTest.cpp
  src/storage/test/UpdateEdgeTest.cpp
  src/storage/test/UpdateVertexTest.cpp
Labels: ready-for-testing

#1832 Fix issue 1590.
  src/common/base/Base.h
  src/common/filter/Expressions.cpp
Labels: ready-for-testing

#1822 Stop scanning the data if sending snapshot failed
  src/dataman/RowReader.cpp
  src/kvstore/NebulaStore.cpp
  src/kvstore/RocksEngineConfig.cpp
  src/kvstore/SnapshotManagerImpl.cpp
  src/kvstore/raftex/RaftPart.cpp
  src/kvstore/raftex/SnapshotManager.cpp
  src/kvstore/raftex/SnapshotManager.h
  src/kvstore/raftex/test/TestShard.h
  src/kvstore/wal/FileBasedWal.cpp
  src/kvstore/wal/InMemoryLogBuffer.h
  src/meta/processors/admin/Balancer.cpp
Labels: ready-for-testing

#1855 fixed lookup bug for double free
  src/storage/index/LookUpEdgeIndexProcessor.cpp
  src/storage/index/LookUpVertexIndexProcessor.cpp
Labels: ready-for-testing

#1795 [doc]add advance gremlin
  docs/manual-CN/5.appendix/gremlin-ngql.md
  docs/manual-EN/5.appendix/gremlin-ngql.md
Labels: nGQL, ready-for-testing

#1724 Fix update logic after store properties on in-edges.
  src/graph/UpdateEdgeExecutor.cpp
  src/graph/UpdateEdgeExecutor.h
  src/graph/test/UpdateTest.cpp
  src/storage/mutate/UpdateEdgeProcessor.cpp
Labels: ready-for-testing

#1756 lease read, check has committed logs in this term, modify collectN eval
  src/common/base/CollectNSucceeded.inl
  src/kvstore/NebulaStore.cpp
  src/kvstore/raftex/Host.cpp
  src/kvstore/raftex/Host.h
  src/kvstore/raftex/RaftPart.cpp
  src/kvstore/raftex/RaftPart.h
Labels: ready-for-testing

#1878 [doc] update Ranking length in doc
  docs/manual-CN/1.overview/3.design-and-architecture/2.storage-design.md
  docs/manual-EN/1.overview/3.design-and-architecture/2.storage-design.md
Labels: ready-for-testing

#1862 [doc] cypher v.s. ngql add query result
  docs/manual-CN/5.appendix/cypher-ngql.md
  docs/manual-EN/5.appendix/cypher-ngql.md
Labels: ready-for-testing

#1852 [doc]comment out go upto
  docs/manual-CN/1.overview/1.concepts/2.nGQL-overview.md
  docs/manual-EN/1.overview/1.concepts/2.nGQL-overview.md
Labels: ready-for-testing

#1759 [doc]update delete vertices
  docs/manual-CN/2.query-language/4.statement-syntax/2.data-query-and-manipulation-statements/delete-vertex-syntax.md
  docs/manual-EN/2.query-language/4.statement-syntax/2.data-query-and-manipulation-statements/delete-vertex-syntax.md
Labels: nGQL, ready-for-testing

#1746 Reservoir sampling.
  src/common/CMakeLists.txt
  src/common/algorithm/CMakeLists.txt
  src/common/algorithm/ReservoirSampling.cpp
  src/common/algorithm/ReservoirSampling.h
  src/common/algorithm/test/CMakeLists.txt
  src/common/algorithm/test/ReservoirSamplingTest.cpp
  src/graph/FetchVerticesExecutor.cpp
  src/kvstore/RocksEngine.h
  src/storage/query/QueryBaseProcessor.cpp
  src/storage/query/QueryBaseProcessor.h
  src/storage/query/QueryBaseProcessor.inl
  src/storage/test/QueryBoundBenchmark.cpp
  src/storage/test/QueryBoundTest.cpp
Labels: ready-for-testing

#1860 Delete vertices with get neighbor
  src/graph/DeleteVerticesExecutor.cpp
  src/graph/GoExecutor.cpp
  src/graph/TraverseExecutor.cpp
  src/graph/test/DeleteVerticesTest.cpp
  src/interface/storage.thrift
  src/storage/CMakeLists.txt
  src/storage/StorageServiceHandler.cpp
  src/storage/StorageServiceHandler.h
  src/storage/client/StorageClient.cpp
  src/storage/client/StorageClient.h
  src/storage/query/QueryEdgeKeysProcessor.cpp
  src/storage/query/QueryEdgeKeysProcessor.h
  src/storage/test/CMakeLists.txt
  src/storage/test/QueryEdgeKeysTest.cpp
  src/storage/test/QueryVertexPropsTest.cpp
  src/storage/test/StorageClientTest.cpp
Labels: ready-for-testing

#1856 Feature/coverage action
  .github/workflows/build.yaml
  .github/workflows/pull_request.yaml
  CMakeLists.txt
  README-CN.md
  README.md
Labels: ready-for-testing

#1867 Fix graph client print bad when auth failed.
  src/client/cpp/GraphClient.cpp
Labels: ready-for-testing

#1879 [doc]remove yields
  docs/manual-CN/1.overview/2.quick-start/2.FAQ.md
  docs/manual-CN/2.query-language/4.statement-syntax/2.data-query-and-manipulation-statements/go-syntax.md
  docs/manual-EN/2.query-language/4.statement-syntax/2.data-query-and-manipulation-statements/go-syntax.md
Labels: ready-for-testing

#1473 Helm chart for nebula
  kubernetes/helm/.helmignore
  kubernetes/helm/Chart.yaml
  kubernetes/helm/templates/NOTES.txt
  kubernetes/helm/templates/_helpers.tpl
  kubernetes/helm/templates/configmap.yaml
  kubernetes/helm/templates/deployment.yaml
  kubernetes/helm/templates/ingress-configmap.yaml 
  kubernetes/helm/templates/pdb.yaml
  kubernetes/helm/templates/service.yaml
  kubernetes/helm/templates/statefulset.yaml
  kubernetes/helm/values.yaml
Labels: ready-for-testing

#1898 fix pull request re-run failed
  .github/workflows/build.yaml
  .github/workflows/docker.yaml
  .github/workflows/package.yaml
  .github/workflows/pull_request.yaml
  .github/workflows/release.yaml
Labels: ready-for-testing

#1899 Add some unreserved keywords
  src/parser/parser.yy
  src/parser/test/ParserTest.cpp
Labels: ready-for-testing

#1881 Correct the checkpoint testing which write before all leaders elected.
  src/storage/test/CheckpointTest.cpp
  src/storage/test/TestUtils.h
Labels: bug-fix, ready-for-testing

#1850 Check if schema exists and ignore the bad data when query vertex/edge.
  src/graph/FetchVerticesExecutor.cpp
  src/storage/query/QueryEdgePropsProcessor.cpp
  src/storage/query/QueryVertexPropsProcessor.cpp
Labels: bug-fix, ready-for-testing

#1842 User manager for graph layer
  src/common/CMakeLists.txt
  src/common/base/Status.h
  src/common/base/ThriftTypes.h
  src/common/encryption/CMakeLists.txt
  src/common/encryption/MD5Utils.cpp
  src/common/encryption/MD5Utils.h
  src/daemons/CMakeLists.txt
  src/daemons/MetaDaemon.cpp
  src/graph/CMakeLists.txt
  src/graph/Executor.cpp
  src/graph/PrivilegeExecutor.cpp
  src/graph/PrivilegeExecutor.h
  src/graph/ShowExecutor.cpp
  src/graph/ShowExecutor.h
  src/graph/UserExecutor.cpp
  src/graph/UserExecutor.h
  src/graph/test/CMakeLists.txt
  src/graph/test/SchemaTest.cpp
  src/graph/test/UserTest.cpp
  src/interface/common.thrift
  src/interface/meta.thrift
  src/meta/MetaServiceHandler.cpp
  src/meta/MetaServiceHandler.h
  src/meta/MetaServiceUtils.cpp
  src/meta/MetaServiceUtils.h
  src/meta/RootUserMan.h
  src/meta/client/MetaClient.cpp
  src/meta/client/MetaClient.h
  src/meta/processors/BaseProcessor.h
  src/meta/processors/BaseProcessor.inl
  src/meta/processors/partsMan/DropSpaceProcessor.cpp
  src/meta/processors/usersMan/AuthenticationProcessor.cpp
  src/meta/processors/usersMan/AuthenticationProcessor.h
  src/meta/test/AuthProcessorTest.cpp
  src/meta/test/TestUtils.h
  src/parser/AdminSentences.cpp
  src/parser/AdminSentences.h
  src/parser/UserSentences.cpp
  src/parser/UserSentences.h
  src/parser/parser.yy
  src/parser/scanner.lex
  src/parser/test/ParserTest.cpp
  src/parser/test/ScannerTest.cpp
Labels: ready-for-testing

#1904 Fix spark config in doc
  docs/manual-CN/3.build-develop-and-administration/3.deploy-and-administrations/server-administration/storage-service-administration/data-import/spark-writer.md
  docs/manual-EN/3.build-develop-and-administration/3.deploy-and-administrations/server-administration/storage-service-administration/data-import/spark-writer.md
Labels: ready-for-testing

#1903 [doc]comment connect prometheus in TOC
  docs/manual-CN/README.md
Labels: ready-for-testing

#1883 [doc]get-start-add-contact
  docs/manual-CN/1.overview/2.quick-start/1.get-started.md
  docs/manual-EN/1.overview/2.quick-start/1.get-started.md
Labels: ready-for-testing

#1721 [doc]improve storage design.md English version
  docs/manual-CN/1.overview/3.design-and-architecture/2.storage-design.md
  docs/manual-EN/1.overview/3.design-and-architecture/2.storage-design.md
Labels: ready-for-testing

#1895 Fixed GCC build to support gold linker and package third-party with v…
  third-party/build-gcc.sh
  third-party/build-third-party.sh
Labels: ready-for-testing

#1914 Fix exit-on-failure in build-third-party.sh
  third-party/build-third-party.sh
Labels: ready-for-testing

#1887 Update the test's cmake
  src/graph/test/CMakeLists.txt
  src/kvstore/raftex/test/CMakeLists.txt
  src/kvstore/test/CMakeLists.txt
  src/meta/test/CMakeLists.txt
  src/parser/test/CMakeLists.txt
  src/storage/test/CMakeLists.txt
Labels: ready-for-testing

#1882 Check duplicate field when create the index
  src/graph/test/IndexTest.cpp
  src/graph/test/SchemaTest.cpp
  src/meta/processors/indexMan/CreateEdgeIndexProcessor.cpp
  src/meta/processors/indexMan/CreateTagIndexProcessor.cpp
  src/meta/test/MetaClientTest.cpp
  src/meta/test/ProcessorTest.cpp
Labels: ready-for-testing

#1857 Modify lexical error messages
  src/parser/parser.yy
  src/parser/scanner.lex
  src/parser/test/ParserTest.cpp
  src/parser/test/ScannerTest.cpp
Labels: ready-for-testing

#1896 Correct the return error when update filter out.
  src/graph/UpdateEdgeExecutor.cpp
  src/graph/UpdateVertexExecutor.cpp
  src/graph/test/UpdateTest.cpp
  src/graph/test/UpdateTestBase.h
  src/interface/storage.thrift
  src/kvstore/Common.h
  src/kvstore/Part.cpp
  src/storage/CommonUtils.h
  src/storage/mutate/UpdateEdgeProcessor.cpp
  src/storage/mutate/UpdateEdgeProcessor.h
  src/storage/mutate/UpdateVertexProcessor.cpp
  src/storage/mutate/UpdateVertexProcessor.h
Labels: alert/break, bug-fix, ready-for-testing

#1912 Fix package/build/release failed
  .github/workflows/build.yaml
  .github/workflows/package.yaml
  .github/workflows/pull_request.yaml
  .github/workflows/release.yaml
  src/meta/test/CMakeLists.txt
Labels: ready-for-testing

#1920 rename kubernetes/helm/templates/ingress-configmap.yaml
  kubernetes/helm/templates/ingress-configmap.yaml
Labels: ready-for-testing

#1884 Fix we don't support balance remove in single replica
  src/kvstore/raftex/RaftPart.cpp
  src/meta/processors/admin/BalancePlan.cpp
  src/meta/processors/admin/BalancePlan.h
  src/meta/processors/admin/BalanceProcessor.cpp
  src/meta/processors/admin/BalanceTask.cpp
  src/meta/processors/admin/BalanceTask.h
  src/meta/processors/admin/Balancer.cpp
  src/meta/processors/admin/Balancer.h
  src/meta/test/BalancerTest.cpp
  src/meta/test/TestUtils.h
  src/storage/admin/AdminProcessor.h
Labels: bug-fix, ready-for-testing

#1908 add production conf into install
  etc/CMakeLists.txt
Labels: ready-for-testing

#1917 [doc]User management
  docs/manual-CN/3.build-develop-and-administration/3.deploy-and-administrations/server-administration/account-management-statements/create-user-syntax.md
  docs/manual-CN/3.build-develop-and-administration/3.deploy-and-administrations/server-administration/account-management-statements/grant-role-syntax.md
  docs/manual-CN/3.build-develop-and-administration/3.deploy-and-administrations/server-administration/account-management-statements/revoke-syntax.md
  docs/manual-CN/README.md
  docs/manual-EN/3.build-develop-and-administration/3.deploy-and-administrations/server-administration/account-management-statements/create-user-syntax.md
  docs/manual-EN/3.build-develop-and-administration/3.deploy-and-administrations/server-administration/account-management-statements/grant-role-syntax.md
  docs/manual-EN/3.build-develop-and-administration/3.deploy-and-administrations/server-administration/account-management-statements/revoke-syntax.md
  docs/manual-EN/README.md
Labels: ready-for-testing

#1773 Fix get edge_type failed
  src/common/filter/Expressions.cpp
  src/graph/GoExecutor.cpp
  src/graph/test/GoTest.cpp
Labels: bug-fix, ready-for-testing

#1894 [doc] rebuild index
  docs/manual-CN/2.query-language/4.statement-syntax/1.data-definition-statements/index.md
  docs/manual-EN/2.query-language/4.statement-syntax/1.data-definition-statements/index.md
Labels: ready-for-testing

#1915 [doc]Reservoir-sampling doc
  docs/manual-CN/3.build-develop-and-administration/3.deploy-and-administrations/server-administration/configuration-statements/configs-syntax.md
  docs/manual-EN/3.build-develop-and-administration/3.deploy-and-administrations/server-administration/configuration-statements/configs-syntax.md
Labels: ready-for-testing

#1907 [doc]show-more-fields-desc-schema
  docs/manual-CN/2.query-language/4.statement-syntax/3.utility-statements/describe-syntax.md
  docs/manual-EN/2.query-language/4.statement-syntax/3.utility-statements/describe-syntax.md
Labels: not ready for review, ready-for-testing

#1910 [doc]upsert-when
  docs/manual-CN/2.query-language/4.statement-syntax/2.data-query-and-manipulation-statements/update-vertex-edge-syntax.md
  docs/manual-CN/2.query-language/4.statement-syntax/2.data-query-and-manipulation-statements/upsert-syntax.md
  docs/manual-CN/README.md
  docs/manual-EN/2.query-language/4.statement-syntax/2.data-query-and-manipulation-statements/update-vertex-edge-syntax.md
  docs/manual-EN/2.query-language/4.statement-syntax/2.data-query-and-manipulation-statements/upsert-syntax.md
  docs/manual-EN/README.md
Labels: ready-for-testing

#1934 [doc] TTL cn
  docs/manual-CN/2.query-language/4.statement-syntax/1.data-definition-statements/TTL.md
Labels: ready-for-testing

#1788 Support install to other dir and package to one or multi packages
  CMakeLists.txt
  cmake/CPackage.cmake
  etc/CMakeLists.txt
  package/make_srpm.sh
  package/nebula.spec
  package/package.sh
  package/postinst
  package/rpm_postinst
  scripts/CMakeLists.txt
  share/CMakeLists.txt
  src/console/CMakeLists.txt
  src/daemons/CMakeLists.txt
  src/tools/db-dump/CMakeLists.txt
  src/tools/simple-kv-verify/CMakeLists.txt
  src/tools/storage-perf/CMakeLists.txt
Labels: ready-for-testing

#1938 fix sometimes graph crash when look up
  src/graph/LookupExecutor.cpp
Labels: ready-for-testing

#1916 Fix some typo. Add more cases about integer hex oct range checking.
  src/parser/parser.yy
  src/parser/scanner.lex
  src/parser/test/ParserTest.cpp
  src/parser/test/ScannerTest.cpp
Labels: bug-fix, ready-for-testing

#1834 Check if props exists when go or fetch.
  src/graph/FetchEdgesExecutor.cpp
  src/graph/FetchEdgesExecutor.h
  src/graph/FetchExecutor.cpp
  src/graph/FetchVerticesExecutor.cpp
  src/graph/FetchVerticesExecutor.h
  src/graph/GoExecutor.cpp
  src/graph/GoExecutor.h
  src/graph/test/FetchEdgesTest.cpp
  src/graph/test/FetchVerticesTest.cpp
  src/graph/test/GoTest.cpp
Labels: ready-for-testing

#1873 User permission manager
  etc/nebula-graphd.conf.default
  etc/nebula-graphd.conf.production
  src/common/CMakeLists.txt
  src/common/base/Status.cpp
  src/common/permission/CMakeLists.txt
  src/common/permission/PermissionManager.cpp
  src/common/permission/PermissionManager.h
  src/common/session/CMakeLists.txt
  src/common/session/Session.cpp
  src/common/session/Session.h
  src/daemons/CMakeLists.txt
  src/graph/CMakeLists.txt
  src/graph/ClientSession.cpp
  src/graph/ClientSession.h
  src/graph/DescribeSpaceExecutor.cpp
  src/graph/DescribeSpaceExecutor.h
  src/graph/ExecutionEngine.cpp
  src/graph/ExecutionEngine.h
  src/graph/ExecutionPlan.cpp
  src/graph/GraphFlags.cpp
  src/graph/GraphFlags.h
  src/graph/GraphService.cpp
  src/graph/GraphService.h
  src/graph/PasswordAuthenticator.cpp
  src/graph/PasswordAuthenticator.h
  src/graph/PermissionCheck.cpp
  src/graph/PermissionCheck.h
  src/graph/PrivilegeExecutor.cpp
  src/graph/PrivilegeExecutor.h
  src/graph/RequestContext.h
  src/graph/SequentialExecutor.cpp
  src/graph/SequentialExecutor.h
  src/graph/SessionManager.cpp
  src/graph/SessionManager.h
  src/graph/ShowExecutor.cpp
  src/graph/SimpleAuthenticator.h
  src/graph/UseExecutor.cpp
  src/graph/UseExecutor.h
  src/graph/test/CMakeLists.txt
  src/graph/test/PermissionTest.cpp
  src/graph/test/TestEnv.cpp
  src/graph/test/TestEnv.h
  src/graph/test/UserTest.cpp
  src/interface/common.thrift
  src/interface/graph.thrift
  src/interface/meta.thrift
  src/meta/MetaServiceHandler.cpp
  src/meta/MetaServiceHandler.h
  src/meta/MetaServiceUtils.cpp
  src/meta/MetaServiceUtils.h
  src/meta/RootUserMan.h
  src/meta/client/MetaClient.cpp
  src/meta/client/MetaClient.h
  src/meta/processors/BaseProcessor.inl
  src/meta/processors/usersMan/AuthenticationProcessor.cpp
  src/meta/processors/usersMan/AuthenticationProcessor.h
  src/meta/test/AuthProcessorTest.cpp
  src/parser/Sentence.h
Labels: ready-for-testing

#1937 fix fetch prop on * vertexID with ttl
  src/graph/test/CMakeLists.txt
  src/graph/test/SchemaTest.cpp
  src/graph/test/TTLTest.cpp
  src/storage/query/QueryVertexPropsProcessor.cpp
  src/storage/query/QueryVertexPropsProcessor.h
Labels: bug-fix, ready-for-testing

#1941 Modify the Dockerfile which package docker
  docker/Dockerfile.console
  docker/Dockerfile.graph
  docker/Dockerfile.graphd
  docker/Dockerfile.metad
  docker/Dockerfile.storaged
Labels: ready-for-testing

#1861 When the compiler is GCC, use static link libasan and libubsan.
  CMakeLists.txt
Labels: ready-for-testing

#1948 upgrade rocksdb to 6.7.3
  third-party/externals/rocksdb.cmake
Labels: ready-for-testing

#1951 Detect OS type and exit if not built in Linux
  CMakeLists.txt
  cmake/LinkerConfig.cmake
  third-party/install-third-party.sh
Labels: ready-for-testing

#1929 [doc] user-permission-mng
  docs/manual-CN/3.build-develop-and-administration/3.deploy-and-administrations/server-administration/account-management-statements/alter-user-syntax.md
  docs/manual-CN/3.build-develop-and-administration/3.deploy-and-administrations/server-administration/account-management-statements/built-in-roles.md
  docs/manual-CN/3.build-develop-and-administration/3.deploy-and-administrations/server-administration/account-management-statements/change-password.md
  docs/manual-CN/README.md
  docs/manual-EN/3.build-develop-and-administration/3.deploy-and-administrations/server-administration/account-management-statements/alter-user-syntax.md
  docs/manual-EN/3.build-develop-and-administration/3.deploy-and-administrations/server-administration/account-management-statements/built-in-roles.md
  docs/manual-EN/3.build-develop-and-administration/3.deploy-and-administrations/server-administration/account-management-statements/change-password.md
  docs/manual-EN/README.md
Labels: ready-for-testing

#1939 [doc] ttl doc modification
  docs/manual-CN/2.query-language/4.statement-syntax/1.data-definition-statements/TTL.md
  docs/manual-EN/2.query-language/4.statement-syntax/1.data-definition-statements/TTL.md
Labels: ready-for-testing

#1909 Let action not fail fast.
  .github/workflows/build.yaml
  .github/workflows/pull_request.yaml
Labels: ready-for-testing

#1953 Remove removePrefix interface in kvstore
  src/kvstore/KVEngine.h
  src/kvstore/KVStore.h
  src/kvstore/LogEncoder.h
  src/kvstore/NebulaStore.cpp
  src/kvstore/NebulaStore.h
  src/kvstore/Part.cpp
  src/kvstore/Part.h
  src/kvstore/RocksEngine.cpp
  src/kvstore/RocksEngine.h
  src/kvstore/plugins/hbase/HBaseStore.h
  src/storage/BaseProcessor.h
  src/storage/BaseProcessor.inl
  src/storage/mutate/DeleteVerticesProcessor.cpp
Labels: ready-for-testing

#1864 Using admin client in MetaServiceHandler
  src/meta/MetaServiceHandler.cpp
  src/meta/processors/admin/CreateSnapshotProcessor.cpp
  src/meta/processors/admin/CreateSnapshotProcessor.h
  src/meta/processors/admin/DropSnapshotProcessor.cpp
  src/meta/processors/admin/DropSnapshotProcessor.h
  src/meta/processors/admin/SnapShot.h
  src/storage/admin/CreateCheckpointProcessor.cpp
  src/storage/admin/DropCheckpointProcessor.cpp
Labels: ready-for-testing

#1954 [doc] fix typo
  docs/manual-CN/2.query-language/4.statement-syntax/2.data-query-and-manipulation-statements/delete-vertex-syntax.md
  docs/manual-CN/3.build-develop-and-administration/3.deploy-and-administrations/server-administration/account-management-statements/grant-role-syntax.md
  docs/manual-CN/3.build-develop-and-administration/3.deploy-and-administrations/server-administration/account-management-statements/revoke-syntax.md
  docs/manual-EN/2.query-language/4.statement-syntax/2.data-query-and-manipulation-statements/delete-vertex-syntax.md
  docs/manual-EN/3.build-develop-and-administration/3.deploy-and-administrations/server-administration/account-management-statements/grant-role-syntax.md
  docs/manual-EN/3.build-develop-and-administration/3.deploy-and-administrations/server-administration/account-management-statements/revoke-syntax.md
  docs/manual-EN/3.build-develop-and-administration/3.deploy-and-administrations/server-administration/storage-service-administration/job-manager.md
Labels: ready-for-testing

#1924 [doc]show statements
  docs/manual-CN/2.query-language/4.statement-syntax/3.utility-statements/show-statements/show-charset-syntax.md
  docs/manual-CN/2.query-language/4.statement-syntax/3.utility-statements/show-statements/show-collation-syntax.md
  docs/manual-CN/2.query-language/4.statement-syntax/3.utility-statements/show-statements/show-configs-syntax.md
  docs/manual-CN/2.query-language/4.statement-syntax/3.utility-statements/show-statements/show-create-space-syntax.md
  docs/manual-CN/2.query-language/4.statement-syntax/3.utility-statements/show-statements/show-create-tag-edge-syntax.md
  docs/manual-CN/2.query-language/4.statement-syntax/3.utility-statements/show-statements/show-hosts-syntax.md
  docs/manual-CN/2.query-language/4.statement-syntax/3.utility-statements/show-statements/show-indexes-syntax.md
  docs/manual-CN/2.query-language/4.statement-syntax/3.utility-statements/show-statements/show-parts-syntax.md
  docs/manual-CN/2.query-language/4.statement-syntax/3.utility-statements/show-statements/show-roles-syntax.md
  docs/manual-CN/2.query-language/4.statement-syntax/3.utility-statements/show-statements/show-snapshots-syntax.md
  docs/manual-CN/2.query-language/4.statement-syntax/3.utility-statements/show-statements/show-spaces-syntax.md
  docs/manual-CN/2.query-language/4.statement-syntax/3.utility-statements/show-statements/show-tags-edges-syntax.md
  docs/manual-CN/2.query-language/4.statement-syntax/3.utility-statements/show-statements/show-users-syntax.md
  docs/manual-CN/2.query-language/4.statement-syntax/3.utility-statements/show-syntax.md
  docs/manual-CN/README.md
  docs/manual-EN/2.query-language/4.statement-syntax/3.utility-statements/show-statements/show-charset-syntax.md
  docs/manual-EN/2.query-language/4.statement-syntax/3.utility-statements/show-statements/show-collation-syntax.md
  docs/manual-EN/2.query-language/4.statement-syntax/3.utility-statements/show-statements/show-configs-syntax.md
  docs/manual-EN/2.query-language/4.statement-syntax/3.utility-statements/show-statements/show-create-space-syntax.md
  docs/manual-EN/2.query-language/4.statement-syntax/3.utility-statements/show-statements/show-create-tag-edge-syntax.md
  docs/manual-EN/2.query-language/4.statement-syntax/3.utility-statements/show-statements/show-hosts-syntax.md
  docs/manual-EN/2.query-language/4.statement-syntax/3.utility-statements/show-statements/show-indexes-syntax.md
  docs/manual-EN/2.query-language/4.statement-syntax/3.utility-statements/show-statements/show-parts-syntax.md
  docs/manual-EN/2.query-language/4.statement-syntax/3.utility-statements/show-statements/show-roles-syntax.md
  docs/manual-EN/2.query-language/4.statement-syntax/3.utility-statements/show-statements/show-snapshots-syntax.md
  docs/manual-EN/2.query-language/4.statement-syntax/3.utility-statements/show-statements/show-spaces-syntax.md
  docs/manual-EN/2.query-language/4.statement-syntax/3.utility-statements/show-statements/show-tags-edges-syntax.md
  docs/manual-EN/2.query-language/4.statement-syntax/3.utility-statements/show-statements/show-users-syntax.md
  docs/manual-EN/2.query-language/4.statement-syntax/3.utility-statements/show-syntax.md
  docs/manual-EN/README.md
Labels: ready-for-testing

#1906 [doc]customized dir
  docs/manual-CN/3.build-develop-and-administration/1.build/1.build-source-code.md
  docs/manual-CN/3.build-develop-and-administration/3.deploy-and-administrations/deployment/install-with-rpm-deb.md
  docs/manual-EN/3.build-develop-and-administration/1.build/1.build-source-code.md
  docs/manual-EN/3.build-develop-and-administration/3.deploy-and-administrations/deployment/install-with-rpm-deb.md
Labels: ready-for-testing

#1962 Fixed a bug caused by not filtering the versions of edges
  src/meta/client/MetaClient.cpp
  src/meta/client/MetaClient.h
  src/meta/processors/schemaMan/ListEdgesProcessor.cpp
Labels: defect-p3, ready-for-testing

#1957 [doc]modify job manger doc
  docs/manual-CN/3.build-develop-and-administration/3.deploy-and-administrations/server-administration/configuration-statements/.rocksdb-compaction-flush.md
  docs/manual-CN/3.build-develop-and-administration/3.deploy-and-administrations/server-administration/storage-service-administration/job-manager.md
  docs/manual-CN/README.md
  docs/manual-EN/3.build-develop-and-administration/3.deploy-and-administrations/server-administration/configuration-statements/.rocksdb-compaction-flush.md
  docs/manual-EN/3.build-develop-and-administration/3.deploy-and-administrations/server-administration/storage-service-administration/job-manager.md
  docs/manual-EN/README.md
Labels: ready-for-testing

#1970 Fix delete verticse crash
  src/storage/mutate/DeleteEdgesProcessor.cpp
  src/storage/mutate/DeleteVerticesProcessor.cpp
Labels: bug-fix, ready-for-testing

#1973 Fix the read performance issue after delete range with rocksdb-5.15.10
  src/storage/BaseProcessor.h
  src/storage/BaseProcessor.inl
  src/storage/mutate/DeleteEdgesProcessor.cpp
  src/storage/mutate/DeleteVerticesProcessor.cpp
Labels: ready-for-testing

#1979 [Cherrypick] RC4 #1970 #1962
  src/meta/client/MetaClient.cpp
  src/meta/client/MetaClient.h
  src/meta/processors/schemaMan/ListEdgesProcessor.cpp
  src/storage/mutate/DeleteEdgesProcessor.cpp
  src/storage/mutate/DeleteVerticesProcessor.cpp
Labels: ready-for-testing

#1978 Remove the LOG(FATAL) when encountering the unknown log.
  src/kvstore/Part.cpp
Labels: ready-for-testing

#1980 Improved customer friendliness for user permission.
  src/common/base/Status.cpp
  src/interface/meta.thrift
  src/meta/client/MetaClient.cpp
  src/meta/processors/usersMan/AuthenticationProcessor.cpp
  src/meta/test/AuthProcessorTest.cpp
Labels: ready-for-testing

#1988 RC4 Cherrypick #1953 #1973 #1978
  src/kvstore/KVEngine.h
  src/kvstore/KVStore.h
  src/kvstore/LogEncoder.h
  src/kvstore/NebulaStore.cpp
  src/kvstore/NebulaStore.h
  src/kvstore/Part.cpp
  src/kvstore/Part.h
  src/kvstore/RocksEngine.cpp
  src/kvstore/RocksEngine.h
  src/kvstore/plugins/hbase/HBaseStore.h
  src/storage/BaseProcessor.h
  src/storage/BaseProcessor.inl
  src/storage/mutate/DeleteEdgesProcessor.cpp
  src/storage/mutate/DeleteVerticesProcessor.cpp
Labels: ready-for-testing

#1981 [doc]Upgrade spark package download address
  docs/manual-CN/3.build-develop-and-administration/3.deploy-and-administrations/server-administration/storage-service-administration/data-import/spark-writer.md
  docs/manual-EN/3.build-develop-and-administration/3.deploy-and-administrations/server-administration/storage-service-administration/data-import/spark-writer.md
Labels: ready-for-testing

#1976 fix-typo-in-doc
  docs/manual-CN/README.md
  docs/manual-EN/README.md
Labels: ready-for-testing

#1969 [doc]modify commands in build doc
  docs/manual-CN/3.build-develop-and-administration/1.build/1.build-source-code.md
  docs/manual-EN/3.build-develop-and-administration/1.build/1.build-source-code.md
Labels: ready-for-testing

#1945 Modify graphd log level
  src/graph/ExecutionPlan.cpp
  src/graph/FetchEdgesExecutor.cpp
  src/graph/FetchVerticesExecutor.cpp
  src/graph/GoExecutor.cpp
  src/graph/GroupByExecutor.cpp
  src/graph/LimitExecutor.cpp
  src/graph/LookupExecutor.cpp
  src/graph/OrderByExecutor.cpp
  src/graph/ReturnExecutor.cpp
  src/graph/UpdateEdgeExecutor.cpp
  src/graph/UpdateVertexExecutor.cpp
  src/graph/YieldExecutor.cpp
Labels: ready-for-testing

#1959 use bloom filter, add event listener to collect stats of compaction, improve update rocksdb options
  src/common/base/Configuration.cpp
  src/common/base/Configuration.h
  src/kvstore/EventListner.h
  src/kvstore/NebulaStore.cpp
  src/kvstore/PartManager.cpp
  src/kvstore/RocksEngineConfig.cpp
  src/kvstore/raftex/RaftPart.cpp
  src/meta/processors/configMan/SetConfigProcessor.cpp
  src/meta/test/ConfigManTest.cpp
Labels: ready-for-testing

#2002 Update the interface atomicOp to support empty string
  src/kvstore/raftex/RaftPart.cpp
  src/kvstore/raftex/RaftPart.h
  src/kvstore/raftex/test/LogCASTest.cpp
  src/kvstore/raftex/test/TestShard.cpp
  src/kvstore/raftex/test/TestShard.h
  src/storage/mutate/AddEdgesProcessor.cpp
  src/storage/mutate/AddVerticesProcessor.cpp
  src/storage/mutate/DeleteEdgesProcessor.cpp
  src/storage/mutate/DeleteEdgesProcessor.h
  src/storage/mutate/DeleteVerticesProcessor.cpp
  src/storage/mutate/DeleteVerticesProcessor.h
  src/storage/mutate/UpdateEdgeProcessor.cpp
  src/storage/mutate/UpdateVertexProcessor.cpp
Labels: ready-for-testing

#1968 Update to rc4
  src/jni/java/pom.xml
  src/tools/spark-sstfile-generator/pom.xml
Labels: ready-for-testing

#1983 remove unreasonable error message
  src/meta/client/MetaClient.cpp
Labels: ready-for-testing

#1993 [doc]pr-commit-msg
  docs/manual-CN/4.contributions/pull-request-commit-message-guidelines.md
  docs/manual-EN/4.contributions/pull-request-commit-message-guidelines.md
Labels: ready-for-testing

#2006 [doc]modify ttl query
  docs/manual-CN/2.query-language/4.statement-syntax/1.data-definition-statements/TTL.md
  docs/manual-EN/2.query-language/4.statement-syntax/1.data-definition-statements/TTL.md
Labels: ready-for-testing

#1943 Let merge coverage report faster by fastcov instead of lcov.
  .github/workflows/build.yaml
  .github/workflows/pull_request.yaml
Labels: ready-for-testing

#1922 Auto check keyword
  .linters/cpp/checkKeyword.py
  .linters/cpp/hooks/pre-commit.sh
  src/graph/test/SchemaTest.cpp
  src/parser/parser.yy
  src/parser/scanner.lex
  src/parser/test/ParserTest.cpp
Labels: ready-for-testing

#2024 Fix coredump for update if encountering bad format row
  src/dataman/RowReader.cpp
  src/kvstore/Common.h
  src/storage/CommonUtils.h
  src/storage/mutate/UpdateEdgeProcessor.cpp
  src/storage/mutate/UpdateVertexProcessor.cpp
  src/storage/test/UpdateEdgeTest.cpp
  src/storage/test/UpdateVertexTest.cpp
Labels: ready-for-testing

#2029 Check reader is null or not before using it
  src/storage/CompactionFilter.h
  src/storage/admin/RebuildEdgeIndexProcessor.cpp
  src/storage/admin/RebuildTagIndexProcessor.cpp
  src/storage/index/IndexExecutor.inl
  src/storage/mutate/AddEdgesProcessor.cpp
  src/storage/mutate/AddVerticesProcessor.cpp
  src/storage/mutate/DeleteEdgesProcessor.cpp
  src/storage/mutate/DeleteVerticesProcessor.cpp
  src/storage/query/QueryBaseProcessor.inl
  src/storage/query/QueryEdgePropsProcessor.cpp
  src/storage/query/QueryVertexPropsProcessor.cpp
  src/storage/query/ScanEdgeProcessor.cpp
  src/storage/query/ScanVertexProcessor.cpp
  src/storage/test/UpdateEdgeTest.cpp
Labels: rc4-cherrypick, ready-for-testing

#2012 fix go without yield return errror result
  src/graph/test/TTLTest.cpp
  src/meta/MetaServiceUtils.cpp
  src/parser/parser.yy
  src/storage/query/QueryBaseProcessor.inl
Labels: rc4-cherrypick, ready-for-testing

#2001 fixed bug for delete vertex without edge
  src/graph/DeleteVerticesExecutor.cpp
  src/graph/test/DeleteVerticesTest.cpp
Labels: defect-p2, rc4-cherrypick, ready-for-testing

#2000 Add alias check for lookup
  src/graph/LookupExecutor.cpp
  src/graph/LookupExecutor.h
  src/graph/test/LookupTest.cpp
Labels: rc4-cherrypick, ready-for-testing

#2007 fix bug 1990/1991
  src/meta/client/MetaClient.cpp
  src/meta/processors/jobMan/JobManager.cpp
  src/meta/test/JobManagerTest.cpp
Labels: rc4-cherrypick, ready-for-testing
