Repository vesoft-inc/nebula, pull requests merged in 2020-06, with the labels that each got.

#2152 Fix a bug which returns the history version data in query_bound.
  src/storage/query/QueryBaseProcessor.inl
  src/storage/test/QueryBoundTest.cpp
Labels: ready-for-testing

#2156 upsert statement when insert, the condition is always true NG-99
  src/graph/test/UpdateTest.cpp
  src/storage/mutate/UpdateEdgeProcessor.cpp
  src/storage/mutate/UpdateVertexProcessor.cpp
  src/storage/test/IndexTest.cpp
  src/storage/test/UpdateVertexTest.cpp
Labels: doc required, ready-for-testing

#2157 Build RocksDB with LZ4 and BZip2
  third-party/CMakeLists.txt
  third-party/externals/rocksdb.cmake
Labels: ready-for-testing

#2150 fix leader will try to send snapshot by mistake, fix clean wal
  src/kvstore/NebulaStore.cpp
  src/kvstore/raftex/Host.cpp
  src/kvstore/raftex/RaftPart.cpp
Labels: bug, ready-for-testing

#2154 Return keys when tag edge has no prop
  src/graph/FetchEdgesExecutor.cpp
  src/graph/FetchVerticesExecutor.cpp
  src/graph/test/DataTest.cpp
Labels: ready-for-testing

#1633 Get default value from cache
  src/common/utils/CMakeLists.txt
  src/common/utils/ConvertTimeType.cpp
  src/common/utils/ConvertTimeType.h
  src/daemons/CMakeLists.txt
  src/dataman/ResultSchemaProvider.cpp
  src/dataman/ResultSchemaProvider.h
  src/dataman/RowUpdater.cpp
  src/dataman/RowUpdater.h
  src/dataman/SchemaWriter.cpp
  src/dataman/SchemaWriter.h
  src/dataman/test/RowUpdaterTest.cpp
  src/graph/Executor.cpp
  src/graph/Executor.h
  src/graph/InsertEdgeExecutor.cpp
  src/graph/InsertEdgeExecutor.h
  src/graph/InsertVertexExecutor.cpp
  src/graph/InsertVertexExecutor.h
  src/graph/SchemaHelper.cpp
  src/graph/SchemaHelper.h
  src/graph/test/CMakeLists.txt
  src/graph/test/UpdateTest.cpp
  src/graph/test/UpdateTestBase.h
  src/jni/src/datamanlite/NebulaSchemaProvider.h
  src/jni/src/datamanlite/SchemaProviderIf.h
  src/meta/NebulaSchemaProvider.cpp
  src/meta/NebulaSchemaProvider.h
  src/meta/SchemaProviderIf.h
  src/meta/client/MetaClient.cpp
  src/meta/test/CMakeLists.txt
  src/parser/MaintainSentences.h
  src/storage/mutate/UpdateEdgeProcessor.cpp
  src/storage/mutate/UpdateEdgeProcessor.h
  src/storage/mutate/UpdateVertexProcessor.cpp
  src/storage/mutate/UpdateVertexProcessor.h
  src/storage/test/AdHocSchemaManager.cpp
  src/storage/test/AdHocSchemaManager.h
  src/storage/test/CMakeLists.txt
  src/storage/test/TestUtils.h
  src/tools/simple-kv-verify/CMakeLists.txt
  src/tools/storage-perf/CMakeLists.txt
Labels: ready-for-testing

#2158 Add more version Info in status webservice
  docker/Dockerfile.console
  docker/Dockerfile.graph
  docker/Dockerfile.graphd
  docker/Dockerfile.metad
  docker/Dockerfile.storaged
  src/webservice/StatusHandler.cpp
Labels: ready-for-testing

#2168 Revert the 2087 workaround.
  src/graph/GoExecutor.cpp
  src/graph/GoExecutor.h
  src/graph/test/GoTest.cpp
Labels: ready-for-testing

#2173 [cherrypick]Revert the 2087 workaround. (#2168)
  src/graph/GoExecutor.cpp
  src/graph/GoExecutor.h
  src/graph/test/GoTest.cpp
Labels: ready-for-testing

#2163 fix typo
  src/graph/UpdateEdgeExecutor.cpp
  src/graph/UpdateVertexExecutor.cpp
Labels: ready-for-testing

#2174 Fix db dump.
  src/tools/db-dump/DbDumper.cpp
Labels: ready-for-testing

#2176 Fix warnings in GCC 10.1
  src/common/filter/FunctionManager.cpp
Labels: ready-for-testing

#2177 Support to disable block cache
  src/kvstore/RocksEngineConfig.cpp
Labels: ready-for-testing

#2175 Correct/issue2087 go cover input NG-141
  src/common/filter/Expressions.cpp
  src/common/filter/Expressions.h
  src/graph/GoExecutor.cpp
  src/graph/GoExecutor.h
  src/graph/InterimResult.cpp
  src/graph/InterimResult.h
  src/graph/test/GoTest.cpp
Labels: alert/break, bug, ready-for-testing

#2181 Fix missing debug info of libstdc++ when build with Clang
  CMakeLists.txt
Labels: ready-for-testing

#2165 meta client thread local access.
  src/kvstore/NebulaStore.cpp
  src/meta/client/MetaClient.cpp
  src/meta/client/MetaClient.h
Labels: ready-for-testing

#2184 fix compaction filter doesn't work in manual compaction
  share/resources/gflags.json
  src/graph/test/TestEnv.h
  src/graph/test/UpdateTest.cpp
  src/kvstore/CompactionFilter.h
  src/kvstore/NebulaStore.cpp
  src/storage/CompactionFilter.h
  src/storage/StorageFlags.cpp
  src/storage/StorageFlags.h
  src/storage/mutate/AddEdgesProcessor.cpp
  src/storage/mutate/AddVerticesProcessor.cpp
  src/storage/mutate/UpdateEdgeProcessor.cpp
  src/storage/mutate/UpdateEdgeProcessor.h
  src/storage/mutate/UpdateVertexProcessor.cpp
  src/storage/mutate/UpdateVertexProcessor.h
  src/storage/test/DeleteEdgesTest.cpp
Labels: ready-for-testing

#2179 Support to config compression algorithm
  etc/nebula-storaged.conf.default
  etc/nebula-storaged.conf.production
  src/kvstore/RocksEngineConfig.cpp
  src/kvstore/RocksEngineConfig.h
  src/kvstore/test/RocksEngineConfigTest.cpp
Labels: ready-for-testing

#2129 Reduced queueing latency
  src/storage/StorageServiceHandler.cpp
  src/storage/StorageServiceHandler.h
Labels: ready-for-testing

#2186 fix update after alter
  src/graph/test/UpdateTest.cpp
  src/storage/mutate/UpdateEdgeProcessor.cpp
  src/storage/mutate/UpdateVertexProcessor.cpp
Labels: bug/bugfix, next-release, ready-for-testing

#2194 plugin feature [POC-55]
  src/common/base/Status.h
  src/common/base/ThriftTypes.h
  src/common/permission/PermissionManager.cpp
  src/graph/CMakeLists.txt
  src/graph/ExecutionContext.h
  src/graph/ExecutionEngine.cpp
  src/graph/ExecutionEngine.h
  src/graph/Executor.cpp
  src/graph/GraphFlags.cpp
  src/graph/GraphFlags.h
  src/graph/GraphService.cpp
  src/graph/GraphService.h
  src/graph/InstallPluginExecutor.cpp
  src/graph/InstallPluginExecutor.h
  src/graph/LdapAuthenticator.cpp
  src/graph/LdapAuthenticator.h
  src/graph/PermissionCheck.cpp
  src/graph/PluginManager.cpp
  src/graph/PluginManager.h
  src/graph/ShowExecutor.cpp
  src/graph/ShowExecutor.h
  src/graph/UninstallPluginExecutor.cpp
  src/graph/UninstallPluginExecutor.h
  src/graph/test/CMakeLists.txt
  src/graph/test/LdapAuthTest.cpp
  src/interface/common.thrift
  src/interface/meta.thrift
  src/meta/CMakeLists.txt
  src/meta/MetaServiceHandler.cpp
  src/meta/MetaServiceHandler.h
  src/meta/MetaServiceUtils.cpp
  src/meta/MetaServiceUtils.h
  src/meta/client/MetaClient.cpp
  src/meta/client/MetaClient.h
  src/meta/processors/BaseProcessor.h
  src/meta/processors/BaseProcessor.inl
  src/meta/processors/Common.h
  src/meta/processors/admin/GetPluginProcessor.cpp
  src/meta/processors/admin/GetPluginProcessor.h
  src/meta/processors/admin/InstallPluginProcessor.cpp
  src/meta/processors/admin/InstallPluginProcessor.h
  src/meta/processors/admin/ListPluginsProcessor.cpp
  src/meta/processors/admin/ListPluginsProcessor.h
  src/meta/processors/admin/UninstallPluginProcessor.cpp
  src/meta/processors/admin/UninstallPluginProcessor.h
  src/meta/test/CMakeLists.txt
  src/meta/test/PluginTest.cpp
  src/parser/AdminSentences.cpp
  src/parser/AdminSentences.h
  src/parser/Sentence.h
  src/parser/parser.yy
  src/parser/scanner.lex
  src/parser/test/ParserTest.cpp
  src/parser/test/ScannerTest.cpp
Labels: ready-for-testing

#2195 modify some log level when get default value
  src/dataman/ResultSchemaProvider.cpp
  src/dataman/RowReader.h
  src/jni/src/datamanlite/NebulaSchemaProvider.cpp
  src/meta/NebulaSchemaProvider.cpp
Labels: ready-for-testing
