Repository vesoft-inc/nebula, pull requests merged in 2020-09, with the labels that each got.

#2324 Modify the CMakeLists.txt of building jni
  src/jni/CMakeLists.txt
  src/jni/README.md
  src/jni/src/datamanlite/CMakeLists.txt
Labels: ready-for-testing

#2335 bug fix: delete vertices processor may core, if this vertex also have edges and index
  src/common/utils/NebulaKeyUtils.h
  src/storage/mutate/DeleteVerticesProcessor.cpp
  src/storage/test/DeleteVerticesTest.cpp
Labels: ready-for-testing

#2334 show hosts in order.
  src/graph/ShowExecutor.cpp
Labels: ready-for-testing

#2318 Improved snapshot creation logic.
  src/kvstore/NebulaStore.cpp
  src/kvstore/RocksEngine.cpp
  src/kvstore/raftex/RaftPart.cpp
  src/kvstore/wal/FileBasedWal.cpp
  src/meta/processors/admin/AdminClient.cpp
  src/meta/processors/admin/CreateSnapshotProcessor.cpp
Labels: ready-for-testing

#2274 Add prefix bloom filter support
  etc/nebula-storaged.conf.default
  etc/nebula-storaged.conf.production
  src/kvstore/RocksEngine.cpp
  src/kvstore/RocksEngineConfig.cpp
  src/kvstore/RocksEngineConfig.h
  src/storage/test/CMakeLists.txt
  src/storage/test/PrefixBloomFilterBenchmark.cpp
  src/storage/test/QueryVertexPropsTest.cpp
Labels: ready-for-testing

#2337 add edge rank & fix test case
  src/graph/test/DeleteVerticesTest.cpp
  src/graph/test/FetchEdgesTest.cpp
  src/graph/test/GoTest.cpp
  src/graph/test/GroupByLimitTest.cpp
  src/graph/test/SetTest.cpp
  src/graph/test/TraverseTestBase.h
  src/graph/test/YieldTest.cpp
Labels: ready-for-testing

#2341 fixed error for lookup after alter tag add column
  src/graph/test/IndexTest.cpp
  src/storage/BaseProcessor.inl
Labels: ready-for-testing

#2327 [RAFT] Refactor leader election logic
  src/kvstore/raftex/RaftPart.cpp
  src/kvstore/raftex/RaftPart.h
Labels: raft, ready-for-testing

#2305 Minor changes in raft, fix unstable ut, update GetNeighbors benchmark
  share/resources/gflags.json
  src/kvstore/NebulaStore.cpp
  src/kvstore/raftex/Host.cpp
  src/kvstore/raftex/RaftPart.cpp
  src/kvstore/raftex/RaftPart.h
  src/kvstore/raftex/test/RaftexTestBase.cpp
  src/kvstore/test/NebulaStoreTest.cpp
  src/kvstore/wal/FileBasedWal.cpp
  src/storage/test/GetNeighborsBenchmark.cpp
Labels: ready-for-testing

#2332 bug fix: shutdown meta server before job manager init, may core
  src/daemons/MetaDaemon.cpp
  src/meta/processors/jobMan/JobManager.cpp
  src/meta/processors/jobMan/JobManager.h
  src/meta/test/JobManagerTest.cpp
Labels: ready-for-testing

#2277 To improve index scan logic since string range scan disabled.
  src/common/utils/NebulaKeyUtils.h
  src/graph/LookupExecutor.cpp
  src/graph/LookupExecutor.h
  src/graph/test/IndexTest.cpp
  src/graph/test/LookupTest.cpp
  src/graph/test/LookupTestBase.h
  src/graph/test/TestEnv.h
  src/storage/BaseProcessor.h
  src/storage/index/IndexExecutor.h
  src/storage/index/IndexExecutor.inl
  src/storage/index/IndexPolicyMaker.cpp
  src/storage/index/IndexPolicyMaker.h
  src/storage/test/IndexScanTest.cpp
Labels: ready-for-testing

#2283 Disable index range scan of string data type in graph layer
  src/graph/LookupExecutor.cpp
  src/graph/LookupExecutor.h
  src/graph/test/LookupTest.cpp
Labels: doc required, ready-for-testing

#2346 Support to build jni under MasOS
  src/jni/CMakeLists.txt
  src/jni/src/CMakeLists.txt
Labels: ready-for-testing
