Repository vesoft-inc/nebula, pull requests merged in 2020-08, with the labels that each got.

#2266 fix remove duplicate part in a host
  src/kvstore/NebulaStore.cpp
Labels: ready-for-testing

#2258 fix double quote in index
  src/tools/spark-sstfile-generator/src/main/scala/com/vesoft/nebula/tools/generator/v2/SparkClientGenerator.scala
Labels: ready-for-testing

#2232 Enhance the failover logic for balance procedure.
  src/interface/storage.thrift
  src/kvstore/NebulaStore.cpp
  src/kvstore/NebulaStore.h
  src/kvstore/Part.cpp
  src/kvstore/PartManager.cpp
  src/kvstore/PartManager.h
  src/kvstore/raftex/RaftPart.cpp
  src/kvstore/raftex/test/MemberChangeTest.cpp
  src/meta/processors/admin/AdminClient.cpp
  src/meta/processors/admin/BalancePlan.cpp
  src/meta/processors/admin/BalanceTask.cpp
  src/storage/admin/AdminProcessor.h
Labels: ready-for-testing

#2273 Remove lock in FunctionManager
  src/common/filter/FunctionManager.cpp
  src/common/filter/FunctionManager.h
Labels: ready-for-testing

#2270 Add GetNeighborsBenchmark
  src/storage/test/CMakeLists.txt
  src/storage/test/GetNeighborsBenchmark.cpp
Labels: ready-for-testing

#2271 Fix build jni error
  src/jni/src/datamanlite/NebulaSchemaProvider.h
Labels: ready-for-testing

#2276 raft lease is always valid when replica is one
  src/kvstore/raftex/RaftPart.cpp
Labels: ready-for-testing

#2275 fix bugs for "graph_update_vertex_error_qps"
  src/graph/UpdateVertexExecutor.cpp
Labels: ready-for-testing

#2278 check pid before init glog
  src/daemons/GraphDaemon.cpp
  src/daemons/MetaDaemon.cpp
  src/daemons/StorageDaemon.cpp
Labels: ready-for-testing

#2281 Fixed bug of snapshot from chaos test.
  src/meta/MetaServiceUtils.cpp
  src/meta/MetaServiceUtils.h
  src/meta/processors/admin/AdminClient.cpp
  src/meta/processors/admin/AdminClient.h
  src/meta/processors/admin/CreateSnapshotProcessor.cpp
  src/meta/processors/admin/SnapShot.cpp
  src/meta/processors/admin/SnapShot.h
  src/meta/test/AdminClientTest.cpp
Labels: ready-for-testing

#2289 fix multi daemon can't start on same node
  src/daemons/GraphDaemon.cpp
  src/daemons/MetaDaemon.cpp
  src/daemons/StorageDaemon.cpp
Labels: ready-for-testing

#2265 sst download/ingest
  src/common/hdfs/CMakeLists.txt
  src/common/hdfs/HdfsCommandHelper.cpp
  src/common/hdfs/HdfsCommandHelper.h
  src/common/hdfs/HdfsHelper.h
  src/common/hdfs/test/CMakeLists.txt
  src/common/hdfs/test/HdfsHelperTest.cpp
  src/common/http/HttpClient.cpp
  src/common/process/ProcessUtils.cpp
  src/graph/DownloadExecutor.cpp
  src/graph/IngestExecutor.cpp
  src/kvstore/KVStore.h
  src/kvstore/NebulaStore.cpp
  src/kvstore/NebulaStore.h
  src/kvstore/RocksEngine.cpp
  src/kvstore/RocksEngineConfig.cpp
  src/kvstore/plugins/hbase/HBaseStore.cpp
  src/kvstore/plugins/hbase/HBaseStore.h
  src/meta/MetaHttpDownloadHandler.cpp
  src/meta/MetaHttpDownloadHandler.h
  src/meta/MetaHttpIngestHandler.cpp
  src/meta/MetaHttpIngestHandler.h
  src/meta/test/MetaHttpDownloadHandlerTest.cpp
  src/parser/MutateSentences.cpp
  src/parser/MutateSentences.h
  src/parser/parser.yy
  src/parser/test/ParserTest.cpp
  src/storage/http/StorageHttpDownloadHandler.cpp
  src/storage/http/StorageHttpDownloadHandler.h
  src/storage/http/StorageHttpIngestHandler.cpp
  src/storage/http/StorageHttpIngestHandler.h
  src/storage/test/StorageHttpDownloadHandlerTest.cpp
  src/storage/test/StorageHttpIngestHandlerTest.cpp
Labels: ready-for-testing

#2268 Go on with go optimization
  src/graph/GoExecutor.cpp
  src/graph/GoExecutor.h
  src/storage/mutate/UpdateEdgeProcessor.h
  src/storage/mutate/UpdateVertexProcessor.h
  src/storage/query/QueryBaseProcessor.h
  src/storage/query/QueryBaseProcessor.inl
  src/storage/query/QueryBoundProcessor.cpp
  src/storage/query/QueryBoundProcessor.h
  src/storage/query/QueryEdgePropsProcessor.h
  src/storage/query/QueryStatsProcessor.cpp
  src/storage/query/QueryStatsProcessor.h
Labels: ready-for-testing

#2295 fix scanner typo error
  src/parser/scanner.lex
  src/parser/test/ScannerTest.cpp
Labels: ready-for-testing

#2296 MetaClientTest.HeartbeatTest may be hung if target port already been used
  src/meta/test/MetaClientTest.cpp
Labels: ready-for-testing

#2298 Fix not init argv
  src/daemons/GraphDaemon.cpp
  src/daemons/MetaDaemon.cpp
  src/daemons/StorageDaemon.cpp
Labels: ready-for-testing

#2287 fix error for checkpoint when space doesn't exist in storageNode.
  src/meta/MetaServiceUtils.cpp
  src/meta/MetaServiceUtils.h
  src/meta/processors/admin/SnapShot.cpp
  src/meta/processors/admin/SnapShot.h
Labels: ready-for-testing

#2297 Remove proposed term in raft election
  src/interface/raftex.thrift
  src/kvstore/raftex/Host.cpp
  src/kvstore/raftex/RaftPart.cpp
  src/kvstore/raftex/RaftPart.h
Labels: ready-for-testing

#2292 fix go ... | go ... join bug.
  src/graph/GoExecutor.cpp
  src/graph/GoExecutor.h
  src/graph/test/GoTest.cpp
  src/graph/test/TestBase.h
Labels: ready-for-testing

#2291 Make some rocksdb's option dynamically changeable
  src/kvstore/PartManager.cpp
Labels: ready-for-testing

#2307 Improve action workflow configuration
  .github/workflows/build.yaml
  .github/workflows/docker.yaml
  .github/workflows/package.yaml
  .github/workflows/pull_request.yaml
  .github/workflows/release.yaml
  README.md
  ci/ccache.conf
Labels: ready-for-testing

#2290 Add warning msg for partially performed
  src/graph/DropSpaceExecutor.cpp
  src/graph/DropSpaceExecutor.h
  src/graph/ExecutionContext.h
  src/graph/ExecutionPlan.cpp
  src/graph/FetchEdgesExecutor.cpp
  src/graph/FetchVerticesExecutor.cpp
  src/graph/FindPathExecutor.cpp
  src/graph/GoExecutor.cpp
  src/graph/GoExecutor.h
  src/graph/LookupExecutor.cpp
Labels: ready-for-testing

#2267 Fix the wrong usage for LRUCache
  src/common/base/ConcurrentLRUCache.h
  src/common/base/test/ConcurrentLRUCacheTest.cpp
  src/storage/mutate/AddVerticesProcessor.cpp
  src/storage/mutate/AddVerticesProcessor.h
Labels: defect-p2, ready-for-testing

#2312 fix scan don't return result after add enable_multi_versions
  src/storage/query/ScanEdgeProcessor.cpp
  src/storage/query/ScanVertexProcessor.cpp
Labels: ready-for-testing

#2303 Move the prepare processing of findpath to execute
  .github/workflows/pull_request.yaml
  src/graph/FindPathExecutor.cpp
  src/graph/FindPathExecutor.h
  src/graph/test/FindPathTest.cpp
Labels: defect-p3, ready-for-testing

#2321 Revert "Remove proposed term in raft election"
  src/interface/raftex.thrift
  src/kvstore/raftex/Host.cpp
  src/kvstore/raftex/RaftPart.cpp
  src/kvstore/raftex/RaftPart.h
Labels: raft, ready-for-testing

#2316 [RAFT] fix raft snapshot by mistake
  src/common/base/Logging.h
  src/kvstore/EventListner.h
  src/kvstore/Part.cpp
  src/kvstore/raftex/Host.cpp
  src/kvstore/raftex/Host.h
  src/kvstore/raftex/RaftPart.cpp
Labels: raft, ready-for-testing
