Repository vesoft-inc/nebula, pull requests merged in 2020-02, with the labels that each got.

#1698 Relax warning levels on thrift and parser
  cmake/ThriftGenerate.cmake
  src/parser/CMakeLists.txt
Labels: ready-for-testing

#1696 Fixed session timeout
  etc/nebula-graphd.conf.default
  src/graph/GraphFlags.cpp
  src/graph/SessionManager.cpp
Labels: ready-for-testing

#1700 Report error if schema null, hot fix for issue 1699.
  src/graph/FetchVerticesExecutor.cpp
Labels: bug-fix, ready-for-testing

#1708 Remove the duplicate definition of IndexID.
  src/common/base/ThriftTypes.h
  src/interface/common.thrift
Labels: ready-for-testing

#1711 cherry pick (#1700)
  src/graph/FetchVerticesExecutor.cpp
Labels: ready-for-testing

#1627 simple preheat for storage client in graph service
  src/meta/client/MetaClient.cpp
  src/meta/client/MetaClient.h
  src/storage/client/StorageClient.h
  src/storage/test/StorageClientTest.cpp
Labels: ready-for-testing

#1713 Using tuple to replace the nested pair
  src/kvstore/LogEncoder.cpp
  src/kvstore/LogEncoder.h
Labels: ready-for-testing

#1717 Support properties on in-edge
  src/graph/GoExecutor.cpp
  src/graph/GoExecutor.h
  src/graph/InsertEdgeExecutor.cpp
  src/graph/UpdateEdgeExecutor.cpp
  src/graph/test/GoTest.cpp
  src/storage/query/QueryBaseProcessor.inl
  src/storage/test/QueryBoundTest.cpp
Labels: ready-for-testing

#1437 index scan
  CMakeLists.txt
  src/common/base/NebulaKeyUtils.h
  src/common/base/test/NebulaKeyUtilsTest.cpp
  src/common/filter/Expressions.h
  src/interface/storage.thrift
  src/storage/CMakeLists.txt
  src/storage/StorageServiceHandler.cpp
  src/storage/StorageServiceHandler.h
  src/storage/client/StorageClient.cpp
  src/storage/client/StorageClient.h
  src/storage/client/StorageClient.inl
  src/storage/index/IndexExecutor.cpp
  src/storage/index/IndexExecutor.h
  src/storage/index/IndexExecutor.inl
  src/storage/index/IndexPolicyMaker.cpp
  src/storage/index/IndexPolicyMaker.h
  src/storage/index/LookUpEdgeIndexProcessor.cpp
  src/storage/index/LookUpEdgeIndexProcessor.h
  src/storage/index/LookUpVertexIndexProcessor.cpp
  src/storage/index/LookUpVertexIndexProcessor.h
  src/storage/test/CMakeLists.txt
  src/storage/test/IndexScanTest.cpp
Labels: ready-for-testing

#1736 print more info if crash again
  src/common/base/NebulaKeyUtils.h
Labels: ready-for-testing

#1741 Remove discard spark doc and upgrade java client's version
  src/tools/spark-sstfile-generator/README.md
  src/tools/spark-sstfile-generator/pom.xml
Labels: ready-for-testing

#1735 Fix PR action for only updating documents
  .github/workflows/build.yaml
  .github/workflows/pull_request.yaml
Labels: ready-for-testing

#1743 [doc] use statement updated
  docs/manual-CN/2.query-language/4.statement-syntax/3.utility-statements/use-syntax.md
  docs/manual-EN/2.query-language/4.statement-syntax/3.utility-statements/use-syntax.md
Labels: ready-for-testing

#1733 [doc] where statement updated
  docs/manual-CN/2.query-language/4.statement-syntax/2.data-query-and-manipulation-statements/where-syntax.md
  docs/manual-EN/2.query-language/4.statement-syntax/2.data-query-and-manipulation-statements/where-syntax.md
Labels: ready-for-testing

#1723 [doc]group-by statement updated
  docs/manual-CN/2.query-language/2.functions-and-operators/group-by-function.md
  docs/manual-EN/2.query-language/2.functions-and-operators/group-by-function.md
Labels: ready-for-testing

#1720 [doc] added a link for graph studio
  README-CN.md
  README.md
Labels: ready-for-testing

#1718 [doc] order-by statement updated
  docs/manual-CN/2.query-language/2.functions-and-operators/order-by-function.md
  docs/manual-EN/2.query-language/2.functions-and-operators/order-by-function.md
Labels: ready-for-testing

#1716 [doc] return syntax updated
  docs/manual-CN/2.query-language/4.statement-syntax/2.data-query-and-manipulation-statements/return-syntax.md
  docs/manual-EN/2.query-language/4.statement-syntax/2.data-query-and-manipulation-statements/return-syntax.md
Labels: ready-for-testing

#1715 [doc] fetch statement updated
  docs/manual-CN/2.query-language/4.statement-syntax/2.data-query-and-manipulation-statements/fetch-syntax.md
  docs/manual-EN/2.query-language/4.statement-syntax/2.data-query-and-manipulation-statements/fetch-syntax.md
Labels: ready-for-testing

#1744 [doc] find_path statement updated
  docs/manual-CN/2.query-language/4.statement-syntax/4.graph-algorithms/find-path-syntax.md
  docs/manual-EN/2.query-language/4.statement-syntax/4.graph-algorithms/find-path-syntax.md
Labels: ready-for-testing

#1668 [doc]fix stale links
  docs/manual-EN/1.overview/2.quick-start/2.FAQ.md
  docs/manual-EN/README.md
Labels: ready-for-testing

#1742 [doc] yield statement updated
  docs/manual-CN/2.query-language/4.statement-syntax/2.data-query-and-manipulation-statements/yield-syntax.md
  docs/manual-EN/2.query-language/4.statement-syntax/2.data-query-and-manipulation-statements/yield-syntax.md
Labels: ready-for-testing

#1679 index check when alter or drop tag|edge
  src/interface/meta.thrift
  src/meta/processors/BaseProcessor.h
  src/meta/processors/BaseProcessor.inl
  src/meta/processors/schemaMan/AlterEdgeProcessor.cpp
  src/meta/processors/schemaMan/AlterTagProcessor.cpp
  src/meta/processors/schemaMan/DropEdgeProcessor.cpp
  src/meta/processors/schemaMan/DropEdgeProcessor.h
  src/meta/processors/schemaMan/DropTagProcessor.cpp
  src/meta/processors/schemaMan/DropTagProcessor.h
  src/meta/test/ProcessorTest.cpp
Labels: ready-for-testing

#1584 support TTL in storage
  src/dataman/RowReader.h
  src/dataman/RowSetReader.h
  src/storage/CMakeLists.txt
  src/storage/CommonUtils.cpp
  src/storage/CommonUtils.h
  src/storage/CompactionFilter.h
  src/storage/query/QueryBaseProcessor.h
  src/storage/query/QueryBaseProcessor.inl
  src/storage/query/QueryEdgePropsProcessor.cpp
  src/storage/query/QueryVertexPropsProcessor.cpp
  src/storage/test/CMakeLists.txt
  src/storage/test/CompactionTest.cpp
  src/storage/test/QueryEdgePropsTest.cpp
  src/storage/test/QueryVertexPropsTest.cpp
  src/storage/test/TestUtils.h
Labels: ready-for-testing

#1755 [doc]add index check doc when alter schema
  docs/manual-CN/2.query-language/4.statement-syntax/1.data-definition-statements/alter-tag-edge-syntax.md
  docs/manual-CN/2.query-language/4.statement-syntax/1.data-definition-statements/drop-edge-syntax.md
  docs/manual-CN/2.query-language/4.statement-syntax/1.data-definition-statements/drop-tag-syntax.md
  docs/manual-EN/2.query-language/4.statement-syntax/1.data-definition-statements/alter-tag-edge-syntax.md
  docs/manual-EN/2.query-language/4.statement-syntax/1.data-definition-statements/drop-edge-syntax.md
  docs/manual-EN/2.query-language/4.statement-syntax/1.data-definition-statements/drop-tag-syntax.md
Labels: ready-for-testing

#1753 [doc] property_reference updated
  docs/manual-CN/2.query-language/3.language-structure/property-reference.md
  docs/manual-EN/2.query-language/3.language-structure/property-reference.md
Labels: ready-for-testing

#1751 [doc] pipe updated
  docs/manual-CN/2.query-language/3.language-structure/pipe-syntax.md
  docs/manual-EN/2.query-language/3.language-structure/pipe-syntax.md
Labels: ready-for-testing

#1749 [doc] uuid updated
  docs/manual-CN/2.query-language/2.functions-and-operators/uuid.md
  docs/manual-EN/2.query-language/2.functions-and-operators/uuid.md
Labels: ready-for-testing

#1748 [doc] logical operators updated
  docs/manual-CN/2.query-language/2.functions-and-operators/logical-operators.md
  docs/manual-EN/2.query-language/2.functions-and-operators/logical-operators.md
Labels: ready-for-testing

#1747 [doc] readme in en manual updated
  docs/manual-EN/README.md
Labels: ready-for-testing

#1731 [doc] Go statement updated
  docs/manual-CN/2.query-language/4.statement-syntax/2.data-query-and-manipulation-statements/go-syntax.md
  docs/manual-EN/2.query-language/4.statement-syntax/2.data-query-and-manipulation-statements/go-syntax.md
Labels: ready-for-testing

#1722 [doc] limit statement updated
  docs/manual-CN/2.query-language/2.functions-and-operators/limit-syntax.md
  docs/manual-EN/2.query-language/2.functions-and-operators/limit-syntax.md
Labels: ready-for-testing

#1424 Add Job manager
  src/common/http/HttpClient.cpp
  src/common/http/HttpClient.h
  src/daemons/MetaDaemon.cpp
  src/graph/AdminJobExecutor.cpp
  src/graph/AdminJobExecutor.h
  src/graph/CMakeLists.txt
  src/graph/Executor.cpp
  src/interface/meta.thrift
  src/meta/CMakeLists.txt
  src/meta/MetaServiceHandler.cpp
  src/meta/MetaServiceHandler.h
  src/meta/client/MetaClient.cpp
  src/meta/client/MetaClient.h
  src/meta/processors/jobMan/AdminJobProcessor.cpp
  src/meta/processors/jobMan/AdminJobProcessor.h
  src/meta/processors/jobMan/JobDescription.cpp
  src/meta/processors/jobMan/JobDescription.h
  src/meta/processors/jobMan/JobManager.cpp
  src/meta/processors/jobMan/JobManager.h
  src/meta/processors/jobMan/JobStatus.cpp
  src/meta/processors/jobMan/JobStatus.h
  src/meta/processors/jobMan/JobUtils.cpp
  src/meta/processors/jobMan/JobUtils.h
  src/meta/processors/jobMan/TaskDescription.cpp
  src/meta/processors/jobMan/TaskDescription.h
  src/meta/test/CMakeLists.txt
  src/meta/test/JobManagerTest.cpp
  src/parser/MutateSentences.cpp
  src/parser/MutateSentences.h
  src/parser/Sentence.h
  src/parser/parser.yy
  src/parser/scanner.lex
  src/storage/http/StorageHttpAdminHandler.cpp
  src/storage/test/CMakeLists.txt
Labels: ready-for-testing

#1777 fix potential wal bug in ut
  src/kvstore/raftex/RaftPart.cpp
  src/kvstore/raftex/test/RaftexTestBase.cpp
Labels: ready-for-testing

#1776 drop index through compact
  src/common/base/NebulaKeyUtils.h
  src/storage/CompactionFilter.h
  src/storage/StorageServer.cpp
  src/storage/StorageServer.h
  src/storage/test/CMakeLists.txt
  src/storage/test/CompactionTest.cpp
Labels: ready-for-testing

#1779 fix unstable testcase index_scan_test
  src/storage/test/IndexScanTest.cpp
Labels: ready-for-testing

#1737 Make index benchmark work
  src/storage/test/StorageIndexWriteBenchmark.cpp
Labels: ready-for-testing

#1774 Check TTL before creating index
  src/graph/test/IndexTest.cpp
  src/graph/test/SchemaTest.cpp
  src/interface/meta.thrift
  src/meta/MetaServiceUtils.cpp
  src/meta/MetaServiceUtils.h
  src/meta/processors/BaseProcessor.h
  src/meta/processors/BaseProcessor.inl
  src/meta/processors/indexMan/CreateEdgeIndexProcessor.cpp
  src/meta/processors/indexMan/CreateTagIndexProcessor.cpp
  src/meta/processors/schemaMan/AlterEdgeProcessor.cpp
  src/meta/processors/schemaMan/AlterTagProcessor.cpp
  src/meta/test/ProcessorTest.cpp
  src/parser/parser.yy
  src/parser/test/ParserTest.cpp
  src/storage/query/QueryBaseProcessor.inl
Labels: ready-for-testing

#1786 fix some problems during balance
  src/kvstore/raftex/RaftPart.cpp
  src/meta/client/MetaClient.cpp
  src/meta/processors/admin/BalanceProcessor.cpp
  src/meta/processors/admin/Balancer.cpp
  src/meta/processors/admin/Balancer.h
  src/meta/processors/admin/LeaderBalanceProcessor.cpp
  src/meta/processors/partsMan/ListHostsProcessor.cpp
  src/meta/test/BalancerTest.cpp
  src/storage/StorageServiceHandler.cpp
  src/storage/admin/AdminProcessor.h
Labels: ready-for-testing

#1705 Lookup sentence
  src/common/base/test/NebulaKeyUtilsTest.cpp
  src/graph/CMakeLists.txt
  src/graph/Executor.cpp
  src/graph/FindExecutor.cpp
  src/graph/FindExecutor.h
  src/graph/LookupExecutor.cpp
  src/graph/LookupExecutor.h
  src/graph/TraverseExecutor.cpp
  src/graph/test/CMakeLists.txt
  src/graph/test/DataTest.cpp
  src/graph/test/LookupTest.cpp
  src/graph/test/LookupTestBase.h
  src/parser/Sentence.h
  src/parser/TraverseSentences.cpp
  src/parser/TraverseSentences.h
  src/parser/parser.yy
  src/parser/scanner.lex
  src/parser/test/ParserTest.cpp
  src/parser/test/ScannerTest.cpp
  src/storage/index/IndexPolicyMaker.cpp
Labels: ready-for-testing

#1772 Fix the double configuration value not set. And remove some useless c…
  src/meta/GflagsManager.cpp
Labels: ready-for-testing

#1784 [doc] example data for query statements in nGQL added
  docs/manual-CN/2.query-language/0.README.md
  docs/manual-CN/2.query-language/example_data.zip
  docs/manual-EN/2.query-language/0.README.md
  docs/manual-EN/2.query-language/example_data.zip
Labels: ready-for-testing

#1771 [doc] Specify working directory for documents of building by docker
  docs/manual-CN/3.build-develop-and-administration/1.build/2.build-by-docker.md
  docs/manual-EN/3.build-develop-and-administration/1.build/2.build-by-docker.md
Labels: ready-for-testing

#1761 [doc]support TTL storage
  docs/manual-CN/2.query-language/4.statement-syntax/1.data-definition-statements/create-tag-edge-syntax.md
  docs/manual-EN/2.query-language/4.statement-syntax/1.data-definition-statements/create-tag-edge-syntax.md
Labels: ready-for-testing

#1594 [doc]Job manager
  docs/manual-CN/3.build-develop-and-administration/3.deploy-and-administrations/server-administration/storage-service-administration/job-manager.md
  docs/manual-CN/README.md
  docs/manual-EN/3.build-develop-and-administration/3.deploy-and-administrations/server-administration/storage-service-administration/job-manager.md
  docs/manual-EN/README.md
Labels: nGQL, ready-for-testing

#1745 [doc]comparison functions and operators updated
  docs/manual-CN/2.query-language/2.functions-and-operators/comparison-functions-and-operators.md
  docs/manual-EN/2.query-language/2.functions-and-operators/comparison-functions-and-operators.md
Labels: ready-for-testing

#1597 Merge ingest test into rocksdb engine test
  src/kvstore/test/CMakeLists.txt
  src/kvstore/test/LoadTest.cpp
  src/kvstore/test/LogEncoderTest.cpp
  src/kvstore/test/RocksEngineTest.cpp
Labels: ready-for-testing

#1781 Enable query configuration even if the graph started with `--local_co…
  src/meta/client/MetaClient.cpp
  src/meta/test/MetaClientTest.cpp
Labels: ready-for-testing

#1794 Return leader changed when meta has multiple replica
  src/meta/common/MetaCommon.h
  src/meta/processors/BaseProcessor.h
  src/meta/processors/BaseProcessor.inl
  src/meta/processors/admin/BalancePlan.cpp
  src/meta/processors/admin/BalancePlan.h
  src/meta/processors/admin/BalanceProcessor.cpp
  src/meta/processors/admin/BalanceTask.cpp
  src/meta/processors/admin/Balancer.cpp
  src/meta/processors/admin/Balancer.h
  src/meta/processors/admin/CreateSnapshotProcessor.cpp
  src/meta/processors/admin/DropSnapshotProcessor.cpp
  src/meta/processors/admin/HBProcessor.cpp
  src/meta/processors/admin/LeaderBalanceProcessor.cpp
  src/meta/processors/admin/ListSnapshotsProcessor.cpp
  src/meta/processors/configMan/GetConfigProcessor.cpp
  src/meta/processors/configMan/ListConfigsProcessor.cpp
  src/meta/processors/configMan/RegConfigProcessor.cpp
  src/meta/processors/configMan/SetConfigProcessor.cpp
  src/meta/processors/customKV/GetProcessor.cpp
  src/meta/processors/customKV/MultiGetProcessor.cpp
  src/meta/processors/customKV/ScanProcessor.cpp
  src/meta/processors/indexMan/CreateEdgeIndexProcessor.cpp
  src/meta/processors/indexMan/CreateTagIndexProcessor.cpp
  src/meta/processors/indexMan/DropEdgeIndexProcessor.cpp
  src/meta/processors/indexMan/DropTagIndexProcessor.cpp
  src/meta/processors/indexMan/GetEdgeIndexProcessor.cpp
  src/meta/processors/indexMan/GetTagIndexProcessor.cpp
  src/meta/processors/indexMan/ListEdgeIndexesProcessor.cpp
  src/meta/processors/indexMan/ListTagIndexesProcessor.cpp
  src/meta/processors/jobMan/AdminJobProcessor.cpp
  src/meta/processors/partsMan/CreateSpaceProcessor.cpp
  src/meta/processors/partsMan/DropSpaceProcessor.cpp
  src/meta/processors/partsMan/GetPartsAllocProcessor.cpp
  src/meta/processors/partsMan/GetSpaceProcessor.cpp
  src/meta/processors/partsMan/ListHostsProcessor.cpp
  src/meta/processors/partsMan/ListPartsProcessor.cpp
  src/meta/processors/partsMan/ListSpacesProcessor.cpp
  src/meta/processors/schemaMan/AlterEdgeProcessor.cpp
  src/meta/processors/schemaMan/AlterTagProcessor.cpp
  src/meta/processors/schemaMan/CreateEdgeProcessor.cpp
  src/meta/processors/schemaMan/CreateTagProcessor.cpp
  src/meta/processors/schemaMan/DropEdgeProcessor.cpp
  src/meta/processors/schemaMan/DropTagProcessor.cpp
  src/meta/processors/schemaMan/GetEdgeProcessor.cpp
  src/meta/processors/schemaMan/GetTagProcessor.cpp
  src/meta/processors/schemaMan/ListEdgesProcessor.cpp
  src/meta/processors/schemaMan/ListTagsProcessor.cpp
  src/meta/processors/usersMan/AuthenticationProcessor.cpp
Labels: ready-for-testing

#1728 Add length check inside NebulaKeyUtils
  src/common/base/NebulaKeyUtils.h
  src/common/base/test/NebulaKeyUtilsTest.cpp
Labels: ready-for-testing

#1793 Update checkstyle
  .linters/java/nebula_java_style_checks.xml
  src/jni/java/pom.xml
  src/jni/java/src/main/java/com/vesoft/nebula/NebulaCodec.java
  src/jni/java/src/main/java/com/vesoft/nebula/NebulaCodecResourceLoader.java
  src/jni/java/src/test/java/com/vesoft/nebula/NebulaCodecTest.java
  src/tools/native-client/pom.xml
  src/tools/native-client/src/main/java/com/vesoft/client/NativeClient.java
  src/tools/native-client/src/main/java/com/vesoft/client/NativeClientResourceLoader.java
  src/tools/native-client/src/test/java/com/vesoft/client/NativeClientTest.java
Labels: ready-for-testing

#1769 Fix potential raft bug
  src/kvstore/SnapshotManagerImpl.cpp
  src/kvstore/raftex/RaftPart.cpp
  src/kvstore/raftex/SnapshotManager.cpp
  src/kvstore/raftex/SnapshotManager.h
  src/kvstore/raftex/test/TestShard.h
Labels: ready-for-testing

#1796 Fixed the bug
  src/graph/ShowExecutor.cpp
  src/graph/test/SchemaTest.cpp
Labels: ready-for-testing

#1667 enhance number boundary
  src/common/filter/Expressions.cpp
  src/graph/test/YieldTest.cpp
Labels: ready-for-testing

#1790 [doc]Invalid config
  docs/manual-CN/1.overview/2.quick-start/2.FAQ.md
  docs/manual-CN/3.build-develop-and-administration/3.deploy-and-administrations/server-administration/configuration-statements/configs-syntax.md
  docs/manual-EN/1.overview/2.quick-start/2.FAQ.md
  docs/manual-EN/3.build-develop-and-administration/3.deploy-and-administrations/server-administration/configuration-statements/configs-syntax.md
Labels: ready-for-testing

#1719 [doc]change Pict to Fig
  docs/manual-EN/1.overview/3.design-and-architecture/2.storage-design.md
Labels: ready-for-testing

#1806 fix output error for drop index and desc index
  src/graph/DescribeEdgeIndexExecutor.cpp
  src/graph/DescribeTagIndexExecutor.cpp
  src/graph/DropEdgeIndexExecutor.cpp
  src/graph/DropTagIndexExecutor.cpp
Labels: ready-for-testing

#1807 Test partition scan performance
  src/kvstore/test/CMakeLists.txt
  src/kvstore/test/PartPerformanceTest.cpp
Labels: ready-for-testing

#1811 fix issue #1810 old data may cause storaged crash in compact
  src/storage/CompactionFilter.h
Labels: ready-for-testing

#1739 Correct/negative default value
  src/graph/CreateEdgeExecutor.cpp
  src/graph/CreateEdgeExecutor.h
  src/graph/CreateTagExecutor.cpp
  src/graph/CreateTagExecutor.h
  src/graph/SchemaHelper.cpp
  src/graph/test/SchemaTest.cpp
  src/parser/MaintainSentences.h
  src/parser/parser.yy
Labels: bug-fix, ready-for-testing

#1814 Job Manager judged some tasks failed. However they can run success manually by curl.
  src/meta/processors/jobMan/JobManager.cpp
Labels: ready-for-testing

#1818 fix makedir failed when dir is SYM_LINK
  src/common/fs/FileUtils.cpp
  src/common/fs/test/FileUtilsTest.cpp
  src/kvstore/RocksEngine.cpp
  src/kvstore/wal/FileBasedWal.cpp
Labels: ready-for-testing

#1826 Fix meta would crash when balance in multiple relica
  src/kvstore/RocksEngine.cpp
  src/meta/processors/admin/Balancer.cpp
  src/meta/processors/admin/Balancer.h
  src/storage/admin/AdminProcessor.h
Labels: ready-for-testing

#1709 support charset in schema
  etc/nebula-graphd.conf.default
  src/common/CMakeLists.txt
  src/common/charset/CMakeLists.txt
  src/common/charset/Charset.cpp
  src/common/charset/Charset.h
  src/common/charset/test/CMakeLists.txt
  src/common/charset/test/CharsetTest.cpp
  src/daemons/CMakeLists.txt
  src/graph/CreateSpaceExecutor.cpp
  src/graph/CreateSpaceExecutor.h
  src/graph/DescribeSpaceExecutor.cpp
  src/graph/ExecutionContext.h
  src/graph/ExecutionEngine.cpp
  src/graph/ExecutionEngine.h
  src/graph/GraphFlags.cpp
  src/graph/GraphFlags.h
  src/graph/ShowExecutor.cpp
  src/graph/ShowExecutor.h
  src/graph/test/CMakeLists.txt
  src/graph/test/CharsetCollateTest.cpp
  src/graph/test/SchemaTest.cpp
  src/interface/meta.thrift
  src/meta/client/MetaClient.cpp
  src/meta/client/MetaClient.h
  src/meta/processors/BaseProcessor.h
  src/meta/processors/partsMan/CreateSpaceProcessor.cpp
  src/meta/test/BalanceIntegrationTest.cpp
  src/meta/test/CMakeLists.txt
  src/meta/test/ConfigManTest.cpp
  src/meta/test/MetaClientTest.cpp
  src/meta/test/ProcessorTest.cpp
  src/parser/AdminSentences.cpp
  src/parser/AdminSentences.h
  src/parser/parser.yy
  src/parser/scanner.lex
  src/parser/test/ParserTest.cpp
  src/parser/test/ScannerTest.cpp
  src/storage/test/CMakeLists.txt
  src/storage/test/StorageClientTest.cpp
  src/tools/storage-perf/StorageIntegrityTool.cpp
Labels: ready-for-testing

#1738 Lookup benchmark
  src/storage/test/CMakeLists.txt
  src/storage/test/StorageLookupBenchmark.cpp
Labels: ready-for-testing

#1815 [doc]update readme link
  README-CN.md
  README.md
Labels: ready-for-testing

#1809 [doc] update index and job manger
  docs/manual-CN/2.query-language/4.statement-syntax/1.data-definition-statements/index.md
  docs/manual-CN/3.build-develop-and-administration/3.deploy-and-administrations/server-administration/storage-service-administration/job-manager.md
  docs/manual-EN/2.query-language/4.statement-syntax/1.data-definition-statements/index.md
  docs/manual-EN/3.build-develop-and-administration/3.deploy-and-administrations/server-administration/storage-service-administration/job-manager.md
Labels: ready-for-testing

#1808 [doc] prerequisite added in quick start
  docs/manual-CN/1.overview/2.quick-start/1.get-started.md
  docs/manual-EN/1.overview/2.quick-start/1.get-started.md
Labels: ready-for-testing

#1797 [doc]fix metrics-exposer comments and comment out
  docs/manual-CN/3.build-develop-and-administration/3.deploy-and-administrations/deployment/.metrics-exposer.md
  docs/manual-EN/3.build-develop-and-administration/3.deploy-and-administrations/deployment/.metrics-exposer.md
Labels: ready-for-testing

#1791 [doc]configure TTL
  docs/manual-CN/2.query-language/4.statement-syntax/1.data-definition-statements/TTL.md
  docs/manual-CN/README.md
  docs/manual-EN/2.query-language/4.statement-syntax/1.data-definition-statements/TTL.md
  docs/manual-EN/README.md
Labels: ready-for-testing

#1778 [doc]add lookup and update toc
  docs/manual-CN/2.query-language/3.language-structure/.patterns.md
  docs/manual-CN/2.query-language/4.statement-syntax/2.data-query-and-manipulation-statements/go-syntax.md
  docs/manual-CN/2.query-language/4.statement-syntax/2.data-query-and-manipulation-statements/lookup-syntax.md
  docs/manual-CN/README.md
  docs/manual-EN/2.query-language/3.language-structure/.patterns.md
  docs/manual-EN/2.query-language/4.statement-syntax/2.data-query-and-manipulation-statements/go-syntax.md
  docs/manual-EN/2.query-language/4.statement-syntax/2.data-query-and-manipulation-statements/lookup-syntax.md
  docs/manual-EN/README.md
Labels: nGQL, ready-for-testing

#1819 Added sanitizer option for compile scripts.
  package/make_srpm.sh
  package/nebula.spec
  package/package.sh
Labels: ready-for-testing

#1835 [doc] Group By statement updated
  docs/manual-CN/2.query-language/2.functions-and-operators/group-by-function.md
  docs/manual-EN/2.query-language/2.functions-and-operators/group-by-function.md
Labels: ready-for-testing

#1740 Bidirectional traverse.
  src/common/filter/Expressions.h
  src/dataman/RowReader.h
  src/graph/GoExecutor.cpp
  src/graph/GoExecutor.h
  src/graph/test/GoTest.cpp
  src/parser/Clauses.cpp
  src/parser/Clauses.h
  src/parser/parser.yy
  src/parser/scanner.lex
  src/storage/query/QueryBaseProcessor.inl
  src/storage/test/QueryBoundTest.cpp
Labels: ready-for-testing

#1750 [doc]add charset
  docs/manual-CN/2.query-language/4.statement-syntax/1.data-definition-statements/create-space-syntax.md
  docs/manual-CN/2.query-language/4.statement-syntax/3.utility-statements/show-syntax.md
  docs/manual-EN/2.query-language/4.statement-syntax/1.data-definition-statements/create-space-syntax.md
  docs/manual-EN/2.query-language/4.statement-syntax/3.utility-statements/show-syntax.md
Labels: nGQL, ready-for-testing

#1829 [doc]modify block cache
  docs/manual-CN/1.overview/2.quick-start/2.FAQ.md
  docs/manual-EN/1.overview/2.quick-start/2.FAQ.md
Labels: ready-for-testing

#1838 [doc]default value supports expression
  docs/manual-CN/2.query-language/4.statement-syntax/1.data-definition-statements/create-tag-edge-syntax.md
  docs/manual-EN/2.query-language/4.statement-syntax/1.data-definition-statements/create-tag-edge-syntax.md
Labels: ready-for-testing
