Repository vesoft-inc/nebula, pull requests merged in 2021-09, with the labels that each got.

#2771 Reduce unnecessary reading and Typo
  src/meta/processors/BaseProcessor-inl.h
  src/storage/StorageServer.cpp
  src/storage/StorageServer.h
Labels: ready-for-testing

#2773 fix all path bug
  src/graph/executor/algo/ConjunctPathExecutor.cpp
  tests/tck/features/path/AllPath.IntVid.feature
  tests/tck/features/path/AllPath.feature
Labels: ready-for-testing, bug

#2768 Update README.md
  README.md
Labels: ready-for-testing

#2776 fix unstable job related ut
  src/kvstore/raftex/test/LeaderTransferTest.cpp
  src/storage/admin/AdminTaskManager.cpp
  src/storage/admin/AdminTaskManager.h
  src/storage/test/IndexWithTTLTest.cpp
  src/storage/test/RebuildIndexTest.cpp
  src/storage/test/StatsTaskTest.cpp
Labels: ready-for-testing

#2534 Storage slow query
  src/clients/meta/MetaClient.cpp
  src/clients/meta/MetaClient.h
  src/clients/storage/GraphStorageClient.cpp
  src/clients/storage/GraphStorageClient.h
  src/common/base/Status.cpp
  src/common/base/Status.h
  src/graph/executor/mutate/DeleteExecutor.cpp
  src/graph/executor/mutate/InsertExecutor.cpp
  src/graph/executor/mutate/UpdateExecutor.cpp
  src/graph/executor/query/GetEdgesExecutor.cpp
  src/graph/executor/query/GetNeighborsExecutor.cpp
  src/graph/executor/query/GetVerticesExecutor.cpp
  src/graph/executor/query/IndexScanExecutor.cpp
  src/graph/service/QueryInstance.cpp
  src/interface/common.thrift
  src/interface/storage.thrift
  src/mock/MockCluster.cpp
  src/mock/MockCluster.h
  src/storage/CommonUtils.h
  src/storage/exec/GetNeighborsNode.h
  src/storage/exec/HashJoinNode.h
  src/storage/exec/IndexEdgeNode.h
  src/storage/exec/IndexFilterNode.h
  src/storage/exec/IndexOutputNode.h
  src/storage/exec/IndexScanNode.h
  src/storage/exec/IndexVertexNode.h
  src/storage/index/LookupBaseProcessor-inl.h
  src/storage/mutate/UpdateEdgeProcessor.cpp
  src/storage/mutate/UpdateVertexProcessor.cpp
  src/storage/query/GetNeighborsProcessor.cpp
  src/storage/query/GetPropProcessor.cpp
  src/storage/test/CMakeLists.txt
  src/storage/test/KillQueryTest.cpp
  src/storage/test/TossEnvironment.h
  src/tools/storage-perf/StorageIntegrityTool.cpp
  src/tools/storage-perf/StoragePerfTool.cpp
Labels: ready-for-testing

#2568 Cancel uploading the packages to the release assets
  .github/actions/tagname-action/README.md
  .github/actions/tagname-action/action.yml
  .github/workflows/release.yml
Labels: ready-for-testing

#2795 skip the wait in rate limiter in CI
  src/kvstore/CMakeLists.txt
  src/kvstore/NebulaSnapshotManager.cpp
  src/kvstore/NebulaSnapshotManager.h
  src/kvstore/RateLimiter.cpp
  src/kvstore/RateLimiter.h
  src/kvstore/test/RateLimiterTest.cpp
  src/storage/admin/RebuildEdgeIndexTask.cpp
  src/storage/admin/RebuildEdgeIndexTask.h
  src/storage/admin/RebuildIndexTask.cpp
  src/storage/admin/RebuildIndexTask.h
  src/storage/admin/RebuildTagIndexTask.cpp
  src/storage/admin/RebuildTagIndexTask.h
  tests/common/nebula_service.py
Labels: ready-for-testing

#2797 tck testcases strengthening
  .github/workflows/pull_request.yml
  tests/common/utils.py
  tests/tck/conftest.py
Labels: ready-for-testing

#2804 Update GitHub action workflow
  .github/workflows/nightly.yml
  .github/workflows/pull_request.yml
  .github/workflows/release.yml
  tests/common/utils.py
Labels: ready-for-testing

#2774 fixed unstable case get_neighbors_test when ASAN turn on.
  src/mock/MockData.cpp
Labels: ready-for-testing

#2822 Update wait time according to number of current running or queue jobs
  .github/workflows/pull_request.yml
  .github/workflows/release.yml
  tests/tck/conftest.py
Labels: ready-for-testing

#2825 enhancement in rebuild
  src/storage/admin/AdminTaskManager.cpp
  src/storage/admin/RebuildEdgeIndexTask.cpp
  src/storage/admin/RebuildTagIndexTask.cpp
Labels: ready-for-testing

#2820 fix time() infinite loop
  src/graph/visitor/DeduceTypeVisitor.cpp
  tests/tck/features/expression/FunctionCall.feature
Labels: ready-for-testing

#2787 Fix nightly pkg name.
  CMakeLists.txt
Labels: ready-for-testing

#2813 add max allowed query size
  conf/nebula-graphd.conf.default
  conf/nebula-graphd.conf.production
  src/graph/service/GraphFlags.cpp
  src/graph/validator/test/QueryValidatorTest.cpp
  src/parser/GQLParser.h
Labels: ready-for-testing, doc affected

#2819 fix case expression
  src/common/expression/CaseExpression.cpp
  tests/tck/features/aggregate/Agg.feature
  tests/tck/features/expression/Case.feature
Labels: ready-for-testing

#2762 fixed fixed_string expression eval for go
  src/storage/context/StorageExpressionContext.cpp
  src/storage/exec/QueryUtils.h
  tests/tck/features/expression/FixedString.feature
Labels: ready-for-testing, bug

#2850 Revert "Ignore some path don't impact workflow."
  .github/workflows/pull_request.yml
Labels: ready-for-testing

#2848 Fix HomePage Link to "官网"
  README-CN.md
Labels: ready-for-testing

#2855 Fix ply.yacc read parsetab.py error and lookup tests optimization
  src/clients/meta/MetaClient.cpp
  src/kvstore/NebulaStore.cpp
  tests/common/utils.py
  tests/requirements.txt
  tests/tck/features/lookup/ByIndex.feature
  tests/tck/features/lookup/ByIndex.intVid.feature
  tests/tck/features/lookup/TagIndexFullScan.feature
  tests/tck/utils/nbv.py
Labels: ready-for-testing

#2808 Update issue templates
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: ready-for-testing

#2832 fix running jobs in dropped space block others
  src/meta/processors/job/JobManager.cpp
Labels: ready-for-testing

#2856 Fix version display in docker
  docker/Dockerfile
  docker/Dockerfile.graphd
  docker/Dockerfile.metad
  docker/Dockerfile.storaged
  docker/Dockerfile.tools
  package/package.sh
Labels: ready-for-testing

#2863 if space dropped before task finish report, the job status should be …
  src/meta/processors/job/JobManager.cpp
Labels: ready-for-testing

#2754 profiling storage detail
  src/graph/executor/StorageAccessExecutor.h
  src/graph/executor/query/GetNeighborsExecutor.cpp
  src/graph/executor/query/IndexScanExecutor.cpp
  src/storage/BaseProcessor.h
  src/storage/StorageFlags.cpp
  src/storage/StorageFlags.h
  src/storage/exec/AggregateNode.h
  src/storage/exec/DeDupNode.h
  src/storage/exec/EdgeNode.h
  src/storage/exec/FilterNode.h
  src/storage/exec/GetNeighborsNode.h
  src/storage/exec/GetPropNode.h
  src/storage/exec/HashJoinNode.h
  src/storage/exec/IndexEdgeNode.h
  src/storage/exec/IndexFilterNode.h
  src/storage/exec/IndexOutputNode.h
  src/storage/exec/IndexScanNode.h
  src/storage/exec/IndexVertexNode.h
  src/storage/exec/RelNode.h
  src/storage/exec/StoragePlan.h
  src/storage/exec/TagNode.h
  src/storage/exec/UpdateNode.h
  src/storage/exec/UpdateResultNode.h
  src/storage/index/LookupBaseProcessor-inl.h
  src/storage/index/LookupBaseProcessor.h
  src/storage/index/LookupProcessor.cpp
  src/storage/mutate/UpdateEdgeProcessor.cpp
  src/storage/mutate/UpdateEdgeProcessor.h
  src/storage/mutate/UpdateVertexProcessor.cpp
  src/storage/mutate/UpdateVertexProcessor.h
  src/storage/query/GetNeighborsProcessor.cpp
  src/storage/query/GetNeighborsProcessor.h
Labels: ready-for-testing

#2796 Lookup limit push down
  src/clients/storage/GraphStorageClient.cpp
  src/interface/storage.thrift
  src/storage/exec/IndexEdgeNode.h
  src/storage/exec/IndexScanNode.h
  src/storage/exec/IndexVertexNode.h
  src/storage/index/LookupBaseProcessor-inl.h
  src/storage/index/LookupBaseProcessor.h
  src/storage/test/CMakeLists.txt
  src/storage/test/DeleteTagsTest.cpp
  src/storage/test/IndexScanLimitTest.cpp
  src/storage/test/IndexWithTTLTest.cpp
  src/storage/test/KillQueryTest.cpp
  src/storage/test/LookupIndexTest.cpp
Labels: ready-for-testing

#2555 Format subgraph
  .gitignore
  .linters/cpp/checkKeyword.py
  src/graph/context/Iterator.cpp
  src/graph/context/ast/QueryAstContext.h
  src/graph/executor/query/DataCollectExecutor.cpp
  src/graph/planner/ngql/SubgraphPlanner.cpp
  src/graph/validator/GetSubgraphValidator.cpp
  src/graph/validator/GetSubgraphValidator.h
  src/graph/validator/test/GetSubgraphValidatorTest.cpp
  src/parser/TraverseSentences.cpp
  src/parser/TraverseSentences.h
  src/parser/parser.yy
  src/parser/scanner.lex
  tests/tck/features/bugfix/SubgraphBeforePipe.feature
  tests/tck/features/subgraph/subgraph.IntVid.feature
  tests/tck/features/subgraph/subgraph.feature
Labels: ready-for-testing, doc affected

#2829 Just used to test the stability of TCK
  tests/common/utils.py
  tests/tck/conftest.py
  tests/tck/features/index/Index.IntVid.feature
  tests/tck/features/index/Index.feature
  tests/tck/features/index/TagEdgeIndex.feature
  tests/tck/features/lookup/EdgeIndexFullScan.feature
  tests/tck/features/match/SeekById.intVid.feature
Labels: ready-for-testing

#2876 remove redundant code
  src/daemons/CMakeLists.txt
Labels: ready-for-testing

#2784 Fix job finish time and migrate job test to tck.
  src/graph/executor/admin/SubmitJobExecutor.cpp
  src/graph/executor/admin/SubmitJobExecutor.h
  src/graph/executor/test/CMakeLists.txt
  src/graph/executor/test/JobTest.cpp
  tests/Makefile
  tests/common/comparator.py
  tests/job/test_jobs.py
  tests/tck/conftest.py
  tests/tck/features/job/SpaceRequire.feature
  tests/tck/job/Job.feature
  tests/tck/steps/test_jobs.py
Labels: ready-for-testing

#2882 Limit compiling jobs to 10 in ci/ubuntu2004.
  .github/workflows/pull_request.yml
Labels: ready-for-testing, wip

#2888 Fix job test.
  tests/tck/job/Job.feature
Labels: ready-for-testing

#2833 Do not update session when use space.
  src/graph/validator/UseValidator.cpp
  src/graph/validator/test/AdminValidatorTest.cpp
  tests/job/test_session.py
Labels: ready-for-testing

#2890 Cleanup static variables in header files
  .github/workflows/pull_request.yml
  src/clients/meta/MetaClient.cpp
  src/meta/http/MetaHttpDownloadHandler.cpp
  src/meta/http/MetaHttpIngestHandler.cpp
  src/webservice/CMakeLists.txt
  src/webservice/Common.cpp
  src/webservice/Common.h
  src/webservice/test/CMakeLists.txt
Labels: ready-for-testing

#2757 Avoid the extra expression encode decode.
  src/clients/storage/GraphStorageClient.cpp
  src/clients/storage/GraphStorageClient.h
  src/graph/optimizer/OptimizerUtils.cpp
  src/graph/optimizer/rule/PushFilterDownGetNbrsRule.cpp
  src/graph/planner/plan/Query.cpp
  src/graph/planner/plan/Query.h
  src/graph/planner/plan/Scan.h
  src/graph/validator/FetchEdgesValidator.cpp
  src/graph/validator/FetchEdgesValidator.h
  src/graph/validator/FetchVerticesValidator.cpp
  src/graph/validator/FetchVerticesValidator.h
Labels: ready-for-testing

#2896 remove obsolete file
  src/storage/test/StorageServiceHandlerTest.cpp
Labels: ready-for-testing

#2559 Add benchmark for xlog.
  src/common/base/test/LoggingBenchmark.cpp
Labels: ready-for-testing

#2824 Support return query result as a Json string
  src/common/datatypes/DataSet.h
  src/common/datatypes/Date.h
  src/common/datatypes/Edge.cpp
  src/common/datatypes/Edge.h
  src/common/datatypes/List.cpp
  src/common/datatypes/List.h
  src/common/datatypes/Map.cpp
  src/common/datatypes/Map.h
  src/common/datatypes/Path.h
  src/common/datatypes/Set.cpp
  src/common/datatypes/Set.h
  src/common/datatypes/Value.cpp
  src/common/datatypes/Value.h
  src/common/datatypes/Vertex.cpp
  src/common/datatypes/Vertex.h
  src/common/datatypes/test/CMakeLists.txt
  src/common/datatypes/test/ValueToJsonTest.cpp
  src/common/graph/Response.cpp
  src/common/graph/Response.h
  src/common/graph/tests/ResponseEncodeDecodeTest.cpp
  src/graph/service/GraphService.cpp
  src/graph/service/GraphService.h
Labels: new feature, ready-for-testing

#2904 fix crash in sample
  src/common/algorithm/ReservoirSampling.h
  src/common/algorithm/test/ReservoirSamplingTest.cpp
  src/storage/exec/GetNeighborsNode.h
Labels: ready-for-testing

#2862 fix insert edge
  src/graph/validator/MutateValidator.cpp
  src/graph/validator/MutateValidator.h
  src/graph/validator/test/MutateValidatorTest.cpp
  tests/tck/features/insert/InsertEdgeOnDiffParts.feature
  tests/tck/features/schema/Schema.feature
Labels: ready-for-testing, bug

#2884 add code coverage
  .github/workflows/pull_request.yml
  cmake/nebula/GeneralCompilerConfig.cmake
  tests/requirements.txt
Labels: ready-for-testing

#2778 Fix the error the not attached user list all roles of space.
  src/graph/executor/admin/ListRolesExecutor.cpp
  src/graph/session/ClientSession.cpp
  src/graph/session/ClientSession.h
  tests/admin/test_permission.py
Labels: ready-for-testing

#2905 fixed bug limit push down of index scan.
  src/storage/exec/IndexEdgeNode.h
  src/storage/exec/IndexFilterNode.h
  src/storage/exec/IndexScanNode.h
  src/storage/exec/IndexVertexNode.h
  src/storage/index/LookupBaseProcessor-inl.h
  src/storage/index/LookupProcessor.cpp
  src/storage/test/IndexScanLimitTest.cpp
Labels: ready-for-testing, bug

#2877 fix drop host from a zone
  src/meta/processors/zone/UpdateZoneProcessor.cpp
  src/meta/test/GroupZoneTest.cpp
Labels: ready-for-testing

#2572 format fetchvertices
  src/graph/context/ast/QueryAstContext.h
  src/graph/planner/CMakeLists.txt
  src/graph/planner/PlannersRegister.cpp
  src/graph/planner/ngql/FetchVerticesPlanner.cpp
  src/graph/planner/ngql/FetchVerticesPlanner.h
  src/graph/planner/ngql/GoPlanner.cpp
  src/graph/planner/ngql/GoPlanner.h
  src/graph/planner/ngql/PathPlanner.cpp
  src/graph/planner/ngql/SubgraphPlanner.cpp
  src/graph/util/CMakeLists.txt
  src/graph/util/PlannerUtil.cpp
  src/graph/util/PlannerUtil.h
  src/graph/util/ValidateUtil.cpp
  src/graph/util/ValidateUtil.h
  src/graph/validator/CMakeLists.txt
  src/graph/validator/FetchEdgesValidator.cpp
  src/graph/validator/FetchVerticesValidator.cpp
  src/graph/validator/FetchVerticesValidator.h
  src/graph/validator/FindPathValidator.cpp
  src/graph/validator/FindPathValidator.h
  src/graph/validator/GetSubgraphValidator.cpp
  src/graph/validator/GetSubgraphValidator.h
  src/graph/validator/GoValidator.cpp
  src/graph/validator/GoValidator.h
  src/graph/validator/MatchValidator.cpp
  src/graph/validator/MatchValidator.h
  src/graph/validator/TraversalValidator.cpp
  src/graph/validator/TraversalValidator.h
  src/graph/validator/Validator.cpp
  src/graph/validator/Validator.h
  src/graph/validator/YieldValidator.cpp
  src/graph/validator/test/FetchVerticesTest.cpp
  src/graph/validator/test/MatchValidatorTest.cpp
  src/graph/validator/test/QueryValidatorTest.cpp
  src/parser/TraverseSentences.h
  src/parser/parser.yy
  tests/tck/features/fetch/FetchEmpty.feature
  tests/tck/features/fetch/FetchVertices.intVid.feature
  tests/tck/features/fetch/FetchVertices.strVid.feature
  tests/tck/features/go/Orderby.feature
Labels: ready-for-testing

#2781 Add millisecond field for time map initialize.
  src/common/function/test/FunctionManagerTest.cpp
  src/common/time/TimeUtils.cpp
  tests/tck/features/mutate/InsertWithTimeType.feature
Labels: ready-for-testing

#2917 toGraphSpaceName and toGraphSpaceID should be consistent
  src/mock/AdHocSchemaManager.cpp
Labels: ready-for-testing

#2872 Enhancement: "show jobs" only show space related
  src/clients/meta/MetaClient.cpp
  src/graph/validator/AdminJobValidator.cpp
  src/graph/validator/AdminJobValidator.h
  src/interface/common.thrift
  src/meta/processors/job/AdminJobProcessor.cpp
  src/meta/processors/job/JobDescription.h
  src/meta/processors/job/JobManager.cpp
  src/meta/processors/job/JobManager.h
  src/meta/test/JobManagerTest.cpp
  tests/tck/job/Job.feature
Labels: ready-for-testing

#2584 Feature/ssl
  .github/workflows/pull_request.yml
  src/clients/meta/MetaClient.cpp
  src/clients/meta/test/CMakeLists.txt
  src/clients/storage/StorageClientBase-inl.h
  src/codec/test/CMakeLists.txt
  src/common/CMakeLists.txt
  src/common/ssl/CMakeLists.txt
  src/common/ssl/SSLConfig.cpp
  src/common/ssl/SSLConfig.h
  src/common/thrift/ThriftClientManager-inl.h
  src/common/thrift/ThriftClientManager.h
  src/daemons/CMakeLists.txt
  src/daemons/GraphDaemon.cpp
  src/daemons/MetaDaemon.cpp
  src/daemons/StorageDaemon.cpp
  src/graph/context/test/CMakeLists.txt
  src/graph/executor/test/CMakeLists.txt
  src/graph/optimizer/test/CMakeLists.txt
  src/graph/util/test/CMakeLists.txt
  src/graph/validator/test/CMakeLists.txt
  src/graph/visitor/test/CMakeLists.txt
  src/kvstore/NebulaStore.h
  src/kvstore/raftex/RaftexService.cpp
  src/kvstore/raftex/test/CMakeLists.txt
  src/kvstore/raftex/test/TestShard.cpp
  src/kvstore/test/CMakeLists.txt
  src/meta/CMakeLists.txt
  src/meta/processors/admin/AdminClient.h
  src/parser/test/CMakeLists.txt
  src/storage/StorageServer.cpp
  src/storage/test/CMakeLists.txt
  src/tools/db-dump/CMakeLists.txt
  src/tools/db-upgrade/CMakeLists.txt
  src/tools/meta-dump/CMakeLists.txt
  src/tools/storage-perf/CMakeLists.txt
  tests/Makefile
  tests/cert/test.ca.key
  tests/cert/test.ca.pem
  tests/cert/test.ca.srl
  tests/cert/test.derive.crt
  tests/cert/test.derive.csr
  tests/cert/test.derive.key
  tests/common/nebula_service.py
  tests/nebula-test-run.py
Labels: ready-for-testing

#2920 Fix forward compatibility issue when compiling with master rocksdb
  src/kvstore/EventListener.h
Labels: ready-for-testing

#2860 Enable prefix bloom filter by default
  conf/nebula-storaged.conf.default
  conf/nebula-storaged.conf.production
  src/kvstore/KVEngine.h
  src/kvstore/KVStore.h
  src/kvstore/NebulaSnapshotManager.cpp
  src/kvstore/NebulaStore.cpp
  src/kvstore/NebulaStore.h
  src/kvstore/RateLimiter.h
  src/kvstore/RocksEngine.cpp
  src/kvstore/RocksEngine.h
  src/kvstore/RocksEngineConfig.cpp
  src/kvstore/RocksEngineConfig.h
  src/kvstore/raftex/SnapshotManager.cpp
  src/kvstore/test/NebulaStoreTest.cpp
  src/kvstore/test/RateLimiterTest.cpp
  src/kvstore/test/RocksEngineTest.cpp
  src/storage/CMakeLists.txt
  src/storage/StorageServer.cpp
  src/storage/admin/RebuildIndexTask.cpp
  src/storage/http/StorageHttpPropertyHandler.cpp
  src/storage/http/StorageHttpPropertyHandler.h
  src/storage/test/CMakeLists.txt
  src/storage/test/StorageHttpPropertyHandlerTest.cpp
Labels: ready-for-testing, doc affected

#2921 Add docker major version tag when releasing
  .github/actions/tagname-action/action.yml
  .github/workflows/nightly.yml
  .github/workflows/release.yml
  README-CN.md
  README.md
  tests/tck/conftest.py
Labels: ready-for-testing

#2927 fix show zone without host
  src/meta/processors/zone/ListZonesProcessor.cpp
  src/meta/test/GroupZoneTest.cpp
Labels: ready-for-testing

#2843 store admintasks' status and send the status to metad when starting
  .gitignore
  src/common/utils/NebulaKeyUtils.cpp
  src/common/utils/NebulaKeyUtils.h
  src/kvstore/KVEngine.h
  src/kvstore/RocksEngine.cpp
  src/kvstore/RocksEngine.h
  src/storage/CommonUtils.h
  src/storage/StorageServer.cpp
  src/storage/StorageServer.h
  src/storage/admin/AdminTask.h
  src/storage/admin/AdminTaskManager.cpp
  src/storage/admin/AdminTaskManager.h
  src/storage/admin/AdminTaskProcessor.cpp
Labels: ready-for-testing

#2763 support create space as
  src/clients/meta/MetaClient.cpp
  src/clients/meta/MetaClient.h
  src/graph/executor/Executor.cpp
  src/graph/executor/admin/SpaceExecutor.cpp
  src/graph/executor/admin/SpaceExecutor.h
  src/graph/planner/plan/Admin.cpp
  src/graph/planner/plan/Admin.h
  src/graph/planner/plan/PlanNode.cpp
  src/graph/planner/plan/PlanNode.h
  src/graph/service/PermissionCheck.cpp
  src/graph/validator/AdminValidator.cpp
  src/graph/validator/AdminValidator.h
  src/graph/validator/Validator.cpp
  src/interface/meta.thrift
  src/meta/CMakeLists.txt
  src/meta/MetaServiceHandler.cpp
  src/meta/MetaServiceHandler.h
  src/meta/processors/parts/CreateSpaceAsProcessor.cpp
  src/meta/processors/parts/CreateSpaceAsProcessor.h
  src/parser/AdminSentences.cpp
  src/parser/AdminSentences.h
  src/parser/Sentence.h
  src/parser/parser.yy
  tests/common/types.py
  tests/tck/conftest.py
  tests/tck/features/schema/CreateSpaceAs.feature
Labels: ready-for-testing, doc affected

#2895 format lookup
  src/graph/context/ast/QueryAstContext.h
  src/graph/planner/ngql/LookupPlanner.cpp
  src/graph/planner/ngql/LookupPlanner.h
  src/graph/validator/LookupValidator.cpp
  src/graph/validator/LookupValidator.h
  src/graph/validator/test/LookupValidatorTest.cpp
  tests/tck/features/lookup/WithYield.feature
  tests/tck/features/lookup/WithYield.intVid.feature
Labels: ready-for-testing, doc affected

#2928 Grant job permission for all roles except GUEST
  src/graph/service/PermissionCheck.cpp
  src/graph/validator/Validator.cpp
  src/parser/AdminSentences.h
  src/parser/Sentence.h
Labels: ready-for-testing, doc affected

#2937 Fix the var-tracking-assignments warning.
  src/common/function/test/FunctionManagerTest.cpp
Labels: ready-for-testing

#2929 generate master branch coverage
  .github/workflows/nightly.yml
Labels: ready-for-testing

#2532 add a script to do metad folder scp
  scripts/CMakeLists.txt
  scripts/meta-transfer-tools.sh
Labels: ready-for-testing

#2936 Enhance show zones without hosts
  src/meta/processors/zone/ListZonesProcessor.cpp
Labels: ready-for-testing

#2926 Change error code in JSON to Int
  src/common/graph/Response.h
Labels: ready-for-testing

#2942 Add more check about drop zone with created space
  src/graph/planner/ngql/LookupPlanner.cpp
  src/meta/processors/zone/UpdateGroupProcessor.cpp
Labels: ready-for-testing

#2924 Add the case that access property from invalid type.
  tests/tck/features/expression/Attribute.feature
Labels: ready-for-testing

#2779 format fetchedges
  src/graph/context/ast/QueryAstContext.h
  src/graph/planner/CMakeLists.txt
  src/graph/planner/PlannersRegister.cpp
  src/graph/planner/ngql/FetchEdgesPlanner.cpp
  src/graph/planner/ngql/FetchEdgesPlanner.h
  src/graph/validator/FetchEdgesValidator.cpp
  src/graph/validator/FetchEdgesValidator.h
  src/graph/validator/Validator.cpp
  src/graph/validator/Validator.h
  src/graph/validator/test/FetchEdgesTest.cpp
  src/parser/TraverseSentences.h
  tests/tck/features/fetch/FetchEdges.intVid.feature
  tests/tck/features/fetch/FetchEdges.strVid.feature
Labels: ready-for-testing, doc affected

#2529 fix get target host
  src/meta/processors/job/MetaJobExecutor.cpp
Labels: ready-for-testing

#2964 If an edge prepareLocal(), it should not go into resume process.
  src/storage/transaction/ChainAddEdgesProcessorLocal.cpp
  src/storage/transaction/ChainAddEdgesProcessorLocal.h
  src/storage/transaction/ChainResumeProcessor.cpp
Labels: ready-for-testing

#2569 Fix zone balance
  src/meta/processors/admin/BalanceTask.h
  src/meta/processors/admin/Balancer.cpp
  src/meta/processors/admin/Balancer.h
  src/meta/test/BalancerTest.cpp
  src/parser/parser.yy
  src/storage/mutate/UpdateEdgeProcessor.h
Labels: ready-for-testing

#2967 fix create space on empty hosts
  src/meta/processors/parts/CreateSpaceProcessor.cpp
  src/meta/test/ProcessorTest.cpp
Labels: ready-for-testing

#2968 [tck] wait for storage schema
  tests/tck/features/schema/CreateSpaceAs.feature
Labels: ready-for-testing

#2970 improve storage profiling
  src/clients/storage/GraphStorageClient.cpp
  src/clients/storage/GraphStorageClient.h
  src/graph/executor/query/GetNeighborsExecutor.cpp
  src/graph/executor/query/IndexScanExecutor.cpp
  src/graph/planner/plan/ExecutionPlan.h
  src/interface/storage.thrift
  src/storage/BaseProcessor.h
  src/storage/StorageFlags.cpp
  src/storage/StorageFlags.h
  src/storage/index/LookupProcessor.cpp
  src/storage/mutate/UpdateEdgeProcessor.cpp
  src/storage/query/GetNeighborsProcessor.cpp
  src/tools/storage-perf/StoragePerfTool.cpp
Labels: ready-for-testing

#2966 Feature/index scan limit multiple rules
  src/clients/storage/GraphStorageClient.cpp
  src/clients/storage/GraphStorageClient.h
  src/graph/context/ast/QueryAstContext.h
  src/graph/executor/query/IndexScanExecutor.cpp
  src/graph/optimizer/CMakeLists.txt
  src/graph/optimizer/rule/PushLimitDownEdgeIndexFullScanRule.cpp
  src/graph/optimizer/rule/PushLimitDownEdgeIndexFullScanRule.h
  src/graph/optimizer/rule/PushLimitDownEdgeIndexPrefixScanRule.cpp
  src/graph/optimizer/rule/PushLimitDownEdgeIndexPrefixScanRule.h
  src/graph/optimizer/rule/PushLimitDownEdgeIndexRangeScanRule.cpp
  src/graph/optimizer/rule/PushLimitDownEdgeIndexRangeScanRule.h
  src/graph/optimizer/rule/PushLimitDownGetNeighborsRule.cpp
  src/graph/optimizer/rule/PushLimitDownGetNeighborsRule.h
  src/graph/optimizer/rule/PushLimitDownIndexScanRule.cpp
  src/graph/optimizer/rule/PushLimitDownIndexScanRule.h
  src/graph/optimizer/rule/PushLimitDownTagIndexFullScanRule.cpp
  src/graph/optimizer/rule/PushLimitDownTagIndexFullScanRule.h
  src/graph/optimizer/rule/PushLimitDownTagIndexPrefixScanRule.cpp
  src/graph/optimizer/rule/PushLimitDownTagIndexPrefixScanRule.h
  src/graph/optimizer/rule/PushLimitDownTagIndexRangeScanRule.cpp
  src/graph/optimizer/rule/PushLimitDownTagIndexRangeScanRule.h
  src/graph/planner/ngql/LookupPlanner.cpp
  src/graph/planner/plan/Scan.h
  src/graph/validator/LookupValidator.cpp
  src/graph/validator/LookupValidator.h
  src/parser/Clauses.h
  src/parser/TraverseSentences.cpp
  src/parser/TraverseSentences.h
  src/parser/parser.yy
  src/parser/test/ParserTest.cpp
  tests/tck/features/lookup/LookUpLimit.feature
  tests/tck/features/optimizer/PushLimitDownGetNeighborsRule.feature
Labels: ready-for-testing, doc affected

#2536 Breakpad.
  .github/actions/tagname-action/action.yml
  .github/workflows/release.yml
  cmake/FindBreakpad.cmake
  cmake/nebula/GeneralCompilerConfig.cmake
  cmake/nebula/NebulaCMakeMacros.cmake
  cmake/nebula/ThirdPartyConfig.cmake
  docker/Dockerfile.graphd
  docker/Dockerfile.metad
  docker/Dockerfile.storaged
  docker/Dockerfile.tools
  package/package.sh
  src/daemons/CMakeLists.txt
  src/daemons/GraphDaemon.cpp
  src/daemons/MetaDaemon.cpp
  src/daemons/SetupBreakpad.cpp
  src/daemons/StorageDaemon.cpp
Labels: ready-for-testing

#2914 Support cloud user and nebula native user can be mixed
  src/graph/service/GraphService.cpp
  src/graph/service/PermissionCheck.cpp
  src/graph/service/PermissionCheck.h
Labels: ready-for-testing

#2991 fix the bug of can't find auto generated header file
  CMakeLists.txt
Labels: ready-for-testing

#2906 Support lookup indexScan using IN expression as filter
  src/graph/optimizer/OptimizerUtils.cpp
  src/graph/optimizer/OptimizerUtils.h
  src/graph/optimizer/rule/OptimizeTagIndexScanByFilterRule.cpp
  src/graph/optimizer/rule/UnionAllIndexScanBaseRule.cpp
  src/graph/util/ExpressionUtils.cpp
  src/graph/util/ExpressionUtils.h
  src/graph/util/test/ExpressionUtilsTest.cpp
  src/graph/validator/LookupValidator.cpp
  src/graph/validator/LookupValidator.h
  src/graph/visitor/FindVisitor.cpp
  src/graph/visitor/FindVisitor.h
  src/graph/visitor/FoldConstantExprVisitor.cpp
  src/graph/visitor/VidExtractVisitor.cpp
  src/graph/visitor/test/FoldConstantExprVisitorTest.cpp
  tests/tck/features/lookup/EdgeIndexFullScan.feature
  tests/tck/features/lookup/LookupEdge2.feature
  tests/tck/features/lookup/LookupTag2.feature
  tests/tck/features/lookup/TagIndexFullScan.feature
  tests/tck/features/match/SeekById.feature
  tests/tck/features/match/SeekById.intVid.feature
Labels: ready-for-testing, doc affected

#2944 format go yield
  src/common/context/ExpressionContext.h
  src/common/expression/VertexExpression.cpp
  src/common/expression/VertexExpression.h
  src/common/expression/test/ExpressionContextMock.h
  src/common/utils/DefaultValueContext.h
  src/graph/context/Iterator.cpp
  src/graph/context/Iterator.h
  src/graph/context/QueryExpressionContext.cpp
  src/graph/context/QueryExpressionContext.h
  src/graph/validator/GoValidator.cpp
  src/graph/validator/GoValidator.h
  src/graph/validator/test/GetSubgraphValidatorTest.cpp
  src/graph/validator/test/GroupByValidatorTest.cpp
  src/graph/validator/test/LookupValidatorTest.cpp
  src/graph/validator/test/QueryValidatorTest.cpp
  src/parser/parser.yy
  src/storage/context/StorageExpressionContext.h
  tests/tck/features/aggregate/Agg.feature
  tests/tck/features/fetch/FetchVertices.intVid.feature
  tests/tck/features/fetch/FetchVertices.strVid.feature
  tests/tck/features/go/GO.feature
  tests/tck/features/go/GoYieldVertexEdge.feature
  tests/tck/features/subgraph/subgraph.IntVid.feature
  tests/tck/features/subgraph/subgraph.feature
Labels: ready-for-testing, doc affected

#2965 Verify the client version.
  src/clients/meta/MetaClient.cpp
  src/clients/meta/MetaClient.h
  src/common/graph/Response.h
  src/graph/context/test/CMakeLists.txt
  src/graph/executor/test/CMakeLists.txt
  src/graph/optimizer/test/CMakeLists.txt
  src/graph/planner/test/CMakeLists.txt
  src/graph/service/GraphFlags.cpp
  src/graph/service/GraphFlags.h
  src/graph/service/GraphService.cpp
  src/graph/service/GraphService.h
  src/graph/util/test/CMakeLists.txt
  src/interface/common.thrift
  src/interface/graph.thrift
  src/interface/meta.thrift
  src/meta/CMakeLists.txt
  src/meta/MetaServiceHandler.cpp
  src/meta/MetaServiceHandler.h
  src/meta/processors/admin/VerifyClientVersionProcessor.cpp
  src/meta/processors/admin/VerifyClientVersionProcessor.h
  src/meta/test/MetaClientTest.cpp
  src/parser/test/CMakeLists.txt
  src/version/Version.cpp.in
  src/version/Version.h
  tests/conftest.py
  tests/tck/conftest.py
  tests/tck/features/verify_client_version/VerifyClientVersion.feature
Labels: ready-for-testing

#2988 Feature/package tar artifacts
  .github/workflows/nightly.yml
  .github/workflows/release.yml
  CMakeLists.txt
  cmake/CPackage.cmake
  package/package.sh
Labels: ready-for-testing

#2996 Fix match start from edge.
  src/graph/context/ast/CypherAstContext.h
  src/graph/planner/match/LabelIndexSeek.cpp
  src/graph/planner/match/PropIndexSeek.cpp
  src/graph/validator/MatchValidator.cpp
  tests/tck/features/match/SeekByEdge.feature
Labels: ready-for-testing, bug

#2994 Fix the pytest parameter error. Add the password in self signed mode.
  src/common/ssl/SSLConfig.cpp
  tests/cert/test.ca.password
  tests/common/nebula_service.py
  tests/nebula-test-run.py
Labels: ready-for-testing, bug
