Repository vesoft-inc/nebula, pull requests merged in 2021-12, with the labels that each got.

#3357 Modify default session timeout
  conf/nebula-graphd.conf.default
  conf/nebula-graphd.conf.production
  src/graph/executor/admin/ConfigExecutor.cpp
  src/graph/service/GraphFlags.cpp
  src/graph/session/GraphSessionManager.cpp
  tests/admin/test_configs.py
  tests/job/test_session.py
Labels: ready-for-testing, incompatible, doc affected

#3384 add step fail hook
  tests/conftest.py
Labels: ready-for-testing

#3369 Upload diskPaths for meta
  src/clients/meta/MetaClient.cpp
  src/clients/meta/MetaClient.h
  src/common/utils/MetaKeyUtils.cpp
  src/common/utils/MetaKeyUtils.h
  src/interface/meta.thrift
  src/kvstore/DiskManager.cpp
  src/kvstore/DiskManager.h
  src/kvstore/NebulaStore.cpp
  src/kvstore/NebulaStore.h
  src/kvstore/PartManager.cpp
  src/kvstore/PartManager.h
  src/meta/processors/admin/HBProcessor.cpp
  src/meta/test/MetaClientTest.cpp
Labels: ready-for-testing

#3385 Create question template
  .github/ISSUE_TEMPLATE/question.md
Labels: ready-for-testing

#3086 Enable the skip go sample test cases.
  tests/tck/features/go/GO.IntVid.feature
  tests/tck/features/go/GO.feature
Labels: ready-for-testing

#3395 Update nebula-python installation in the test (#3290)
  tests/Makefile
Labels: ready-for-testing

#3401 Increase the number of jobs at compile time
  .github/workflows/nightly.yml
  .github/workflows/pull_request.yml
Labels: ready-for-testing

#3400 Cherry pick：Update nebula-python installation in the test (#3290)
  tests/Makefile
Labels: ready-for-testing

#3405 support specify partId mode
  src/tools/db-upgrade/DbUpgrader.cpp
  src/tools/db-upgrade/DbUpgrader.h
  src/tools/db-upgrade/DbUpgraderTool.cpp
  src/tools/db-upgrade/NebulaKeyUtilsV1.cpp
  src/tools/db-upgrade/NebulaKeyUtilsV1.h
Labels: ready-for-testing

#3389 small fix for EvaluableExprVisitor
  src/graph/visitor/EvaluableExprVisitor.h
Labels: ready-for-testing

#3398 small optimization to avoid recompilation
  src/graph/optimizer/rule/CollapseProjectRule.cpp
  src/graph/optimizer/rule/OptimizeEdgeIndexScanByFilterRule.cpp
  src/graph/optimizer/rule/OptimizeTagIndexScanByFilterRule.cpp
  src/graph/optimizer/rule/PushLimitDownGetNeighborsRule.cpp
  src/graph/optimizer/rule/PushStepLimitDownGetNeighborsRule.cpp
  src/graph/optimizer/rule/PushStepSampleDownGetNeighborsRule.cpp
  src/graph/planner/plan/Query.cpp
  src/graph/planner/plan/Query.h
  src/graph/util/FTIndexUtils.cpp
  src/graph/util/FTIndexUtils.h
  src/graph/validator/FindPathValidator.cpp
  src/graph/validator/MutateValidator.cpp
  src/graph/visitor/VidExtractVisitor.cpp
  src/mock/MockCluster.h
  src/parser/Clauses.cpp
  src/parser/Clauses.h
Labels: ready-for-testing

#3410 enhancement issue template
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/enhancement.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/question.md
Labels: ready-for-testing

#3378 Move version info outside of HB
  src/clients/meta/MetaClient.cpp
  src/common/utils/MetaKeyUtils.cpp
  src/common/utils/MetaKeyUtils.h
  src/interface/meta.thrift
  src/meta/ActiveHostsMan.h
  src/meta/processors/admin/HBProcessor.cpp
  src/meta/processors/admin/VerifyClientVersionProcessor.cpp
  src/meta/processors/parts/ListHostsProcessor.cpp
  src/meta/test/CMakeLists.txt
  src/meta/test/VerifyClientVersionTest.cpp
Labels: ready-for-testing, incompatible

#3380 feat - schema support chinese
  src/parser/parser.yy
  src/parser/scanner.lex
  tests/tck/features/schema/Schema.feature
Labels: ready-for-testing, doc affected

#3413 checkTypeBeforeDropIndex
  src/meta/processors/index/DropEdgeIndexProcessor.cpp
  src/meta/processors/index/DropTagIndexProcessor.cpp
  tests/tck/features/index/TagEdgeIndex.feature
Labels: ready-for-testing

#3316 Support delete vertex without edge
  src/graph/validator/MutateValidator.cpp
  src/graph/validator/MutateValidator.h
  src/graph/validator/test/MutateValidatorTest.cpp
  src/parser/MutateSentences.h
  src/parser/parser.yy
  tests/bench/delete.py
  tests/query/bugs/fixed_delete_vertex_1996.py
  tests/tck/features/delete/DeleteVertex.IntVid.feature
  tests/tck/features/delete/DeleteVertex.feature
  tests/tck/features/delete/DeleteVertexWithoutEdge.feature
  tests/tck/features/geo/GeoBase.feature
  tests/tck/features/mutate/InsertWithTimeType.feature
Labels: ready-for-testing, incompatible, doc affected

#3419 Condition memory checks on cgroup version.
  src/common/memory/MemoryUtils.cpp
Labels: ready-for-testing

#3328 add verteKey
  src/common/utils/NebulaKeyUtils.cpp
  src/common/utils/NebulaKeyUtils.h
  src/common/utils/Types.h
  src/storage/CompactionFilter.h
  src/storage/exec/GetPropNode.h
  src/storage/exec/UpdateNode.h
  src/storage/mutate/AddVerticesProcessor.cpp
  src/storage/mutate/DeleteVerticesProcessor.cpp
  tests/tck/features/delete/DeleteTag.IntVid.feature
  tests/tck/features/delete/DeleteTag.feature
  tests/tck/features/ttl/TTL.feature
Labels: ready-for-testing, incompatible, doc affected

#3416 parse diskPartsKey and add unit test
  src/common/utils/MetaKeyUtils.cpp
  src/common/utils/MetaKeyUtils.h
  src/common/utils/test/MetaKeyUtilsTest.cpp
  src/kvstore/test/DiskManagerTest.cpp
Labels: ready-for-testing

#3436 Update README.md
  README-CN.md
  README.md
Labels: ready-for-testing

#3430 fix inconsistent variable in yield and from clause
  src/graph/validator/GoValidator.cpp
  tests/tck/features/go/GO.feature
Labels: ready-for-testing, type/bug

#3438 Fix the latency type in the executionResponse
  src/common/graph/ExecutionResponseOps-inl.h
  src/common/graph/Response.h
  src/interface/storage.thrift
Labels: ready-for-testing, severity/blocker

#3415 [Raft] fix some remaining problems after pre-vote merged
  src/kvstore/raftex/RaftPart.cpp
  src/kvstore/raftex/test/RaftCase.cpp
Labels: ready-for-testing

#3320 Feature/view vertices edges
  src/clients/storage/StorageClient.cpp
  src/clients/storage/StorageClient.h
  src/common/meta/SchemaManager.cpp
  src/common/meta/SchemaManager.h
  src/graph/context/ast/CypherAstContext.h
  src/graph/executor/CMakeLists.txt
  src/graph/executor/Executor.cpp
  src/graph/executor/query/GetPropExecutor.h
  src/graph/executor/query/ScanEdgesExecutor.cpp
  src/graph/executor/query/ScanEdgesExecutor.h
  src/graph/executor/query/ScanVerticesExecutor.cpp
  src/graph/executor/query/ScanVerticesExecutor.h
  src/graph/optimizer/CMakeLists.txt
  src/graph/optimizer/rule/GetEdgesTransformRule.cpp
  src/graph/optimizer/rule/GetEdgesTransformRule.h
  src/graph/optimizer/rule/PushFilterDownScanVerticesRule.cpp
  src/graph/optimizer/rule/PushFilterDownScanVerticesRule.h
  src/graph/optimizer/rule/PushLimitDownScanAppendVerticesRule.cpp
  src/graph/optimizer/rule/PushLimitDownScanAppendVerticesRule.h
  src/graph/optimizer/rule/PushLimitDownScanEdgesAppendVerticesRule.cpp
  src/graph/optimizer/rule/PushLimitDownScanEdgesAppendVerticesRule.h
  src/graph/optimizer/rule/PushVFilterDownScanVerticesRule.cpp
  src/graph/optimizer/rule/PushVFilterDownScanVerticesRule.h
  src/graph/planner/CMakeLists.txt
  src/graph/planner/PlannersRegister.cpp
  src/graph/planner/match/ScanSeek.cpp
  src/graph/planner/match/ScanSeek.h
  src/graph/planner/plan/PlanNode.cpp
  src/graph/planner/plan/PlanNode.h
  src/graph/planner/plan/Query.cpp
  src/graph/planner/plan/Query.h
  src/graph/validator/test/MatchValidatorTest.cpp
  src/graph/visitor/ExtractFilterExprVisitor.cpp
  src/graph/visitor/ExtractFilterExprVisitor.h
  src/interface/storage.thrift
  src/storage/GraphStorageServiceHandler.cpp
  src/storage/GraphStorageServiceHandler.h
  src/storage/query/ScanEdgeProcessor.cpp
  src/storage/query/ScanEdgeProcessor.h
  src/storage/query/ScanVertexProcessor.cpp
  src/storage/query/ScanVertexProcessor.h
  src/storage/test/ScanEdgeTest.cpp
  src/storage/test/ScanVertexTest.cpp
  tests/tck/features/match/Base.IntVid.feature
  tests/tck/features/match/Base.feature
  tests/tck/features/match/Scan.feature
  tests/tck/features/match/SeekByEdge.feature
  tests/tck/features/match/SeekById.feature
  tests/tck/features/match/SeekById.intVid.feature
  tests/tck/features/optimizer/PushLimitDownScanEdgesRule.feature
  tests/tck/features/optimizer/PushLimitDownScanVerticesRule.feature
Labels: ready-for-testing, doc affected

#3442 fix unused variable
  src/storage/exec/IndexScanNode.h
Labels: ready-for-testing

#3397 disable agg function in unwind clause
  src/graph/validator/MatchValidator.cpp
  tests/tck/features/match/Unwind.feature
  tests/tck/features/match/With.feature
Labels: ready-for-testing, type/bug

#3437 simplify storage SIGINT signal handler
  src/daemons/StorageDaemon.cpp
  src/storage/StorageServer.cpp
  src/storage/StorageServer.h
  src/storage/transaction/TransactionManager.cpp
Labels: ready-for-testing

#3424 LABEL in could be any string
  src/parser/scanner.lex
  src/parser/test/ParserTest.cpp
Labels: ready-for-testing

#3440 Schema support mixed Chinese and English
  src/parser/parser.yy
  src/parser/scanner.lex
  tests/tck/features/schema/Schema.feature
Labels: ready-for-testing, doc affected

#3179 Feature/bison datetime parser
  CMakeLists.txt
  src/codec/test/CMakeLists.txt
  src/common/datatypes/Date.cpp
  src/common/datatypes/Date.h
  src/common/datatypes/test/CMakeLists.txt
  src/common/datatypes/test/ValueToJsonTest.cpp
  src/common/expression/test/CMakeLists.txt
  src/common/function/test/CMakeLists.txt
  src/common/function/test/FunctionManagerTest.cpp
  src/common/geo/test/CMakeLists.txt
  src/common/time/CMakeLists.txt
  src/common/time/TimeUtils.cpp
  src/common/time/TimeUtils.h
  src/common/time/TimezoneInfo.cpp
  src/common/time/parser/CMakeLists.txt
  src/common/time/parser/DatetimeReader.cpp
  src/common/time/parser/DatetimeReader.h
  src/common/time/parser/DatetimeScanner.h
  src/common/time/parser/datetime_parser.yy
  src/common/time/parser/datetime_scanner.lex
  src/common/time/parser/test/CMakeLists.txt
  src/common/time/parser/test/DateTimeParserTest.cpp
  src/common/time/test/CMakeLists.txt
  src/daemons/CMakeLists.txt
  src/daemons/GraphDaemon.cpp
  src/daemons/MetaDaemon.cpp
  src/daemons/StorageDaemon.cpp
  src/graph/context/test/CMakeLists.txt
  src/graph/executor/test/CMakeLists.txt
  src/graph/optimizer/test/CMakeLists.txt
  src/graph/util/test/CMakeLists.txt
  src/graph/validator/test/CMakeLists.txt
  src/graph/visitor/test/CMakeLists.txt
  src/kvstore/test/CMakeLists.txt
  src/meta/CMakeLists.txt
  src/parser/test/CMakeLists.txt
  src/storage/test/CMakeLists.txt
  src/tools/db-dump/CMakeLists.txt
  src/tools/db-upgrade/CMakeLists.txt
  src/tools/meta-dump/CMakeLists.txt
  src/tools/simple-kv-verify/CMakeLists.txt
  src/tools/storage-perf/CMakeLists.txt
  tests/common/nebula_service.py
  tests/tck/features/mutate/InsertWithTimeType.feature
Labels: ready-for-testing, doc affected

#3455 fix unused varaible
  src/graph/validator/GoValidator.cpp
Labels: ready-for-testing

#3390 add cmake git hooks options
  CMakeLists.txt
  cmake/nebula/GitHooksConfig.cmake
  cmake/nebula/IncludeWhatYouUse.cmake
Labels: ready-for-testing, doc affected

#3461 Cover the \n in flex.
  src/common/time/parser/datetime_scanner.lex
  src/common/time/parser/test/DateTimeParserTest.cpp
Labels: ready-for-testing

#3339 Some changes to avoid confusion
  src/common/utils/MetaKeyUtils.cpp
  src/storage/exec/RelNode.h
  src/storage/exec/StoragePlan.h
  src/storage/test/StorageDAGBenchmark.cpp
Labels: ready-for-testing

#3457 Fix/match index selecting
  src/graph/optimizer/rule/IndexScanRule.cpp
  src/graph/planner/match/PropIndexSeek.cpp
  tests/tck/features/bugfix/TruncatedStringIndex.feature
  tests/tck/features/delete/DeleteVertexWithoutEdge.feature
  tests/tck/features/lookup/LookUp.feature
  tests/tck/features/match/IndexSelecting.feature
Labels: ready-for-testing

#3352 fix geo index bound
  src/common/geo/GeoIndex.cpp
Labels: ready-for-testing

#3406 issue_3170: drop space after stop all AdminTaskJobs
  src/kvstore/NebulaStore.cpp
  src/kvstore/NebulaStore.h
  src/storage/admin/AdminTask.h
  src/storage/admin/AdminTaskManager.cpp
  src/storage/admin/AdminTaskManager.h
  src/storage/admin/RebuildEdgeIndexTask.cpp
  src/storage/admin/RebuildIndexTask.cpp
  src/storage/admin/RebuildIndexTask.h
  src/storage/admin/RebuildTagIndexTask.cpp
  src/storage/admin/StatsTask.cpp
  src/storage/admin/StatsTask.h
Labels: ready-for-testing

#3427 Remove extra field.
  src/clients/storage/StorageClientBase-inl.h
  src/interface/storage.thrift
  src/storage/exec/ScanNode.h
  src/storage/query/ScanEdgeProcessor.cpp
  src/storage/query/ScanVertexProcessor.cpp
  src/storage/test/ScanEdgeTest.cpp
  src/storage/test/ScanVertexTest.cpp
Labels: ready-for-testing

#3478 Update pull_request_template.md
  .github/pull_request_template.md
Labels: ready-for-testing

#3392 ignore existed index
  src/clients/storage/StorageClient.cpp
  src/clients/storage/StorageClient.h
  src/clients/storage/StorageClientBase-inl.h
  src/graph/executor/mutate/InsertExecutor.cpp
  src/graph/planner/plan/Mutate.h
  src/graph/validator/MutateValidator.cpp
  src/graph/validator/MutateValidator.h
  src/interface/storage.thrift
  src/parser/MutateSentences.h
  src/parser/parser.yy
  src/parser/scanner.lex
  src/parser/test/ParserTest.cpp
  src/storage/mutate/AddEdgesProcessor.cpp
  src/storage/mutate/AddEdgesProcessor.h
  src/storage/mutate/AddVerticesProcessor.cpp
  src/storage/mutate/AddVerticesProcessor.h
  src/tools/storage-perf/StoragePerfTool.cpp
  tests/tck/features/insert/Insert.IntVid.feature
  tests/tck/features/insert/Insert.feature
Labels: ready-for-testing, doc affected

#3483 save client version
  src/clients/meta/MetaClient.cpp
  src/interface/meta.thrift
  src/meta/processors/admin/VerifyClientVersionProcessor.cpp
  src/meta/test/VerifyClientVersionTest.cpp
Labels: ready-for-testing

#3496 must use the latest nebula-python
  tests/Makefile
Labels: ready-for-testing

#3498 Send HB to meta leader
  src/clients/meta/MetaClient.cpp
Labels: ready-for-testing

#3338 Add duration.
  src/codec/RowReaderV2.cpp
  src/codec/RowWriterV2.cpp
  src/codec/RowWriterV2.h
  src/codec/test/RowWriterV2Test.cpp
  src/codec/test/SchemaWriter.cpp
  src/common/datatypes/CMakeLists.txt
  src/common/datatypes/CommonCpp2Ops.h
  src/common/datatypes/Date.cpp
  src/common/datatypes/Date.h
  src/common/datatypes/Duration.cpp
  src/common/datatypes/Duration.h
  src/common/datatypes/DurationOps-inl.h
  src/common/datatypes/Value.cpp
  src/common/datatypes/Value.h
  src/common/datatypes/ValueOps-inl.h
  src/common/datatypes/test/ValueTest.cpp
  src/common/function/FunctionManager.cpp
  src/common/meta/NebulaSchemaProvider.cpp
  src/common/time/Constants.h
  src/common/time/TimeConversion.h
  src/common/time/TimeUtils.cpp
  src/common/time/TimeUtils.h
  src/common/utils/IndexKeyUtils.h
  src/graph/util/SchemaUtil.cpp
  src/interface/common.thrift
  src/meta/processors/index/CreateEdgeIndexProcessor.cpp
  src/meta/processors/index/CreateTagIndexProcessor.cpp
  src/parser/parser.yy
  src/parser/scanner.lex
  tests/tck/features/expression/TimeComparison.feature
  tests/tck/features/expression/TimeComputation.feature
  tests/tck/features/mutate/InsertDurationType.feature
Labels: ready-for-testing, incompatible, doc affected

#3501 fix add hosts
  src/clients/meta/MetaClient.cpp
Labels: ready-for-testing

#3506 disable mixed usage of cypher & ngql
  src/parser/parser.yy
  tests/tck/features/aggregate/Agg.feature
  tests/tck/features/bugfix/MatchUsedInPipe.feature
  tests/tck/features/expression/ListComprehension.feature
  tests/tck/features/expression/Predicate.feature
  tests/tck/features/expression/Reduce.feature
  tests/tck/features/match/MatchById.IntVid.feature
  tests/tck/features/match/MatchById.feature
  tests/tck/features/match/MatchGroupBy.feature
  tests/tck/features/match/PipeAndVariable.feature
  tests/tck/features/match/StartFromAnyNode.IntVid.feature
  tests/tck/features/match/StartFromAnyNode.feature
  tests/tck/features/match/Unwind.feature
  tests/tck/features/match/VariableLengthPattern.feature
  tests/tck/features/match/VariableLengthPattern.intVid.feature
Labels: ready-for-testing, type/bug, incompatible, doc affected

#3379 support cypher parameter(variable)
  src/common/expression/VariableExpression.cpp
  src/graph/context/QueryContext.cpp
  src/graph/context/QueryContext.h
  src/graph/context/QueryExpressionContext.h
  src/graph/executor/query/AppendVerticesExecutor.cpp
  src/graph/executor/query/GetEdgesExecutor.cpp
  src/graph/executor/query/GetVerticesExecutor.cpp
  src/graph/executor/query/IndexScanExecutor.cpp
  src/graph/executor/query/TraverseExecutor.cpp
  src/graph/optimizer/OptimizerUtils.cpp
  src/graph/optimizer/OptimizerUtils.h
  src/graph/optimizer/rule/GeoPredicateIndexScanBaseRule.cpp
  src/graph/optimizer/rule/IndexFullScanBaseRule.cpp
  src/graph/optimizer/rule/IndexScanRule.cpp
  src/graph/optimizer/rule/IndexScanRule.h
  src/graph/optimizer/rule/OptimizeEdgeIndexScanByFilterRule.cpp
  src/graph/optimizer/rule/OptimizeTagIndexScanByFilterRule.cpp
  src/graph/optimizer/rule/PushLimitDownEdgeIndexFullScanRule.cpp
  src/graph/optimizer/rule/PushLimitDownEdgeIndexPrefixScanRule.cpp
  src/graph/optimizer/rule/PushLimitDownEdgeIndexRangeScanRule.cpp
  src/graph/optimizer/rule/PushLimitDownGetNeighborsRule.cpp
  src/graph/optimizer/rule/PushLimitDownIndexScanRule.cpp
  src/graph/optimizer/rule/PushLimitDownTagIndexFullScanRule.cpp
  src/graph/optimizer/rule/PushLimitDownTagIndexPrefixScanRule.cpp
  src/graph/optimizer/rule/PushLimitDownTagIndexRangeScanRule.cpp
  src/graph/optimizer/rule/PushStepLimitDownGetNeighborsRule.cpp
  src/graph/optimizer/rule/PushStepSampleDownGetNeighborsRule.cpp
  src/graph/optimizer/rule/TopNRule.cpp
  src/graph/optimizer/rule/UnionAllIndexScanBaseRule.cpp
  src/graph/optimizer/test/IndexScanRuleTest.cpp
  src/graph/planner/plan/Query.cpp
  src/graph/planner/plan/Query.h
  src/graph/service/GraphService.cpp
  src/graph/service/GraphService.h
  src/graph/service/RequestContext.h
  src/graph/util/ExpressionUtils.cpp
  src/graph/util/ExpressionUtils.h
  src/graph/validator/FetchEdgesValidator.cpp
  src/graph/validator/GroupByValidator.cpp
  src/graph/validator/LookupValidator.cpp
  src/graph/validator/MatchValidator.cpp
  src/graph/validator/MutateValidator.cpp
  src/graph/validator/Validator.cpp
  src/graph/visitor/CMakeLists.txt
  src/graph/visitor/DeduceTypeVisitor.cpp
  src/graph/visitor/EvaluableExprVisitor.cpp
  src/graph/visitor/EvaluableExprVisitor.h
  src/interface/graph.thrift
  src/parser/parser.yy
  tests/Makefile
  tests/common/utils.py
  tests/tck/conftest.py
  tests/tck/features/go/GO.IntVid.feature
  tests/tck/features/go/GO.feature
  tests/tck/features/go/GoYieldVertexEdge.feature
  tests/tck/features/yield/parameter.feature
Labels: new feature, ready-for-testing, doc affected

#3460 Allow users to choose linker like lld to make build faster.
  cmake/nebula/LinkerConfig.cmake
Labels: ready-for-testing, doc affected

#3482 [fix] meta daemon may stuck
  src/daemons/MetaDaemon.cpp
Labels: ready-for-testing

#3525 Fix crush caused by OptimizeTagIndexScanByFilterRule
  src/graph/optimizer/rule/OptimizeTagIndexScanByFilterRule.cpp
  tests/tck/features/lookup/TagIndexFullScan.feature
Labels: ready-for-testing, type/bug

#3396 support s2 index params
  src/clients/meta/MetaClient.cpp
  src/clients/meta/MetaClient.h
  src/common/datatypes/Geography.h
  src/common/geo/GeoIndex.cpp
  src/common/geo/GeoIndex.h
  src/common/geo/test/GeoIndexTest.cpp
  src/common/utils/IndexKeyUtils.cpp
  src/common/utils/IndexKeyUtils.h
  src/common/utils/test/IndexKeyUtilsTest.cpp
  src/graph/executor/maintain/EdgeIndexExecutor.cpp
  src/graph/executor/maintain/TagIndexExecutor.cpp
  src/graph/optimizer/rule/GeoPredicateIndexScanBaseRule.cpp
  src/graph/planner/plan/Maintain.cpp
  src/graph/planner/plan/Maintain.h
  src/graph/util/IndexUtil.cpp
  src/graph/util/IndexUtil.h
  src/graph/util/SchemaUtil.cpp
  src/graph/util/ToJson.cpp
  src/graph/util/ToJson.h
  src/graph/validator/MaintainValidator.cpp
  src/graph/validator/MaintainValidator.h
  src/interface/meta.thrift
  src/meta/processors/index/CreateEdgeIndexProcessor.cpp
  src/meta/processors/index/CreateTagIndexProcessor.cpp
  src/parser/MaintainSentences.cpp
  src/parser/MaintainSentences.h
  src/parser/parser.yy
  src/parser/scanner.lex
  src/storage/admin/RebuildEdgeIndexTask.cpp
  src/storage/admin/RebuildTagIndexTask.cpp
  src/storage/exec/UpdateNode.h
  src/storage/mutate/AddEdgesProcessor.cpp
  src/storage/mutate/AddVerticesProcessor.cpp
  src/storage/mutate/DeleteEdgesProcessor.cpp
  src/storage/mutate/DeleteTagsProcessor.cpp
  src/storage/mutate/DeleteVerticesProcessor.cpp
  src/storage/test/IndexScanLimitTest.cpp
  src/storage/test/IndexTest.cpp
  src/storage/test/IndexTestUtil.h
  src/storage/test/IndexWriteTest.cpp
  src/tools/db-upgrade/DbUpgrader.cpp
  tests/tck/features/geo/GeoBase.feature
  tests/tck/features/schema/Comment.feature
Labels: ready-for-testing, incompatible, doc affected

#3486 add tck test cases for session
  tests/common/utils.py
  tests/tck/conftest.py
  tests/tck/features/admin/Sessions.feature
Labels: ready-for-testing

#3538 Use ninja to build project
  .github/workflows/pull_request.yml
Labels: ready-for-testing, LGTM2

#3443 Support properties in where clause
  src/graph/validator/FetchEdgesValidator.cpp
  src/graph/validator/FetchEdgesValidator.h
  src/graph/validator/FetchVerticesValidator.cpp
  src/graph/validator/FetchVerticesValidator.h
  src/graph/validator/GoValidator.cpp
  src/graph/validator/GoValidator.h
  src/graph/validator/LookupValidator.cpp
  src/graph/validator/LookupValidator.h
  src/graph/validator/Validator.cpp
  src/graph/validator/Validator.h
  src/graph/visitor/DeducePropsVisitor.cpp
  src/graph/visitor/DeducePropsVisitor.h
  src/graph/visitor/ExtractPropExprVisitor.cpp
  src/graph/visitor/ExtractPropExprVisitor.h
  tests/tck/features/go/GoYieldVertexEdge.feature
Labels: ready-for-testing, doc affected, LGTM2

#3469 Spw/refactor br
  src/clients/meta/MetaClient.cpp
  src/clients/meta/MetaClient.h
  src/common/graph/Response.h
  src/common/utils/MetaKeyUtils.cpp
  src/common/utils/MetaKeyUtils.h
  src/daemons/MetaDaemon.cpp
  src/daemons/StorageDaemon.cpp
  src/graph/service/GraphService.cpp
  src/interface/common.thrift
  src/interface/meta.thrift
  src/interface/storage.thrift
  src/kvstore/DiskManager.cpp
  src/kvstore/KVEngine.h
  src/kvstore/NebulaStore.cpp
  src/kvstore/RocksEngine.cpp
  src/kvstore/RocksEngine.h
  src/meta/ActiveHostsMan.cpp
  src/meta/ActiveHostsMan.h
  src/meta/CMakeLists.txt
  src/meta/MetaServiceHandler.cpp
  src/meta/MetaServiceHandler.h
  src/meta/MetaServiceUtils.cpp
  src/meta/MetaServiceUtils.h
  src/meta/processors/BaseProcessor-inl.h
  src/meta/processors/BaseProcessor.h
  src/meta/processors/admin/AdminClient.cpp
  src/meta/processors/admin/AdminClient.h
  src/meta/processors/admin/AgentHBProcessor.cpp
  src/meta/processors/admin/AgentHBProcessor.h
  src/meta/processors/admin/CreateBackupProcessor.cpp
  src/meta/processors/admin/DropSnapshotProcessor.cpp
  src/meta/processors/admin/GetMetaDirInfoProcessor.cpp
  src/meta/processors/admin/HBProcessor.cpp
  src/meta/processors/admin/ListClusterInfoProcessor.cpp
  src/meta/processors/admin/ListClusterInfoProcessor.h
  src/meta/processors/admin/SnapShot.cpp
  src/meta/processors/admin/SnapShot.h
  src/meta/test/AdminClientTest.cpp
  src/meta/test/AgentHBProcessorTest.cpp
  src/meta/test/CMakeLists.txt
  src/meta/test/CreateBackupProcessorTest.cpp
  src/meta/test/HBProcessorTest.cpp
  src/meta/test/ListClusterInfoTest.cpp
  src/meta/test/MockAdminClient.h
  src/meta/test/RestoreProcessorTest.cpp
  src/storage/CMakeLists.txt
  src/storage/StorageAdminServiceHandler.cpp
  src/storage/StorageAdminServiceHandler.h
  src/storage/StorageServer.cpp
  src/storage/admin/CreateCheckpointProcessor.cpp
  src/storage/admin/DropCheckpointProcessor.cpp
  src/storage/admin/ListClusterInfoProcessor.cpp
  src/storage/admin/ListClusterInfoProcessor.h
  src/storage/admin/SendBlockSignProcessor.cpp
  src/storage/test/CMakeLists.txt
  src/storage/test/CheckpointTest.cpp
  src/storage/test/ListClusterInfoTest.cpp
Labels: ready-for-testing, LGTM2

#3560 fix ci crash
  src/common/expression/AggregateExpression.cpp
  src/common/expression/ArithmeticExpression.cpp
  src/common/expression/AttributeExpression.cpp
  src/common/expression/CaseExpression.cpp
  src/common/expression/ContainerExpression.cpp
  src/common/expression/FunctionCallExpression.cpp
  src/common/expression/LabelAttributeExpression.cpp
  src/common/expression/ListComprehensionExpression.cpp
  src/common/expression/LogicalExpression.cpp
  src/common/expression/PredicateExpression.cpp
  src/common/expression/ReduceExpression.cpp
  src/common/expression/RelationalExpression.cpp
  src/common/expression/SubscriptExpression.cpp
  src/common/expression/TextSearchExpression.cpp
  src/common/expression/TypeCastingExpression.cpp
  src/common/expression/UnaryExpression.cpp
  src/common/expression/VariableExpression.cpp
  src/common/stats/StatsManager.cpp
  src/kvstore/raftex/RaftPart.h
  src/meta/stats/MetaStats.cpp
  src/parser/SequentialSentences.h
  tests/tck/features/admin/Sessions.feature
  third-party/install-gcc.sh
Labels: ready-for-testing

#3552 change ci nebula-python url
  src/graph/service/GraphService.cpp
  tests/Makefile
  tests/tck/conftest.py
  tests/tck/features/yield/parameter.feature
Labels: ready-for-testing, LGTM2

#3544 Fix some memory error.
  src/graph/optimizer/rule/PushFilterDownScanVerticesRule.cpp
  src/graph/planner/match/ScanSeek.cpp
  src/graph/session/ClientSession.h
  src/parser/parser.yy
Labels: ready-for-testing, type/bug, LGTM2

#3528 Fix deprecated function usage
  src/common/utils/test/MetaKeyUtilsTest.cpp
  src/graph/service/CloudAuthenticator.cpp
  src/kvstore/NebulaSnapshotManager.cpp
  src/kvstore/test/NebulaListenerTest.cpp
  src/kvstore/test/RocksEngineTest.cpp
  src/meta/MetaVersionMan.cpp
  src/meta/http/MetaHttpReplaceHostHandler.cpp
  src/meta/processors/admin/CreateBackupProcessor.cpp
  src/meta/processors/admin/CreateSnapshotProcessor.cpp
  src/meta/test/RestoreProcessorTest.cpp
  src/storage/BaseProcessor-inl.h
  src/storage/mutate/AddEdgesProcessor.cpp
  src/storage/mutate/AddVerticesProcessor.cpp
  src/storage/mutate/DeleteEdgesProcessor.cpp
  src/storage/mutate/DeleteTagsProcessor.cpp
  src/storage/mutate/DeleteVerticesProcessor.cpp
  src/storage/test/LookupIndexTest.cpp
  src/storage/test/ScanEdgePropBenchmark.cpp
Labels: ready-for-testing, ready for review

#3546 Fix lack of duration in thrift Value definition.
  src/interface/common.thrift
Labels: ready-for-testing

#2840 Add the shorthand for test all cases.
  tests/Makefile
Labels: ready-for-testing

#3521 Fix duration type deduce.
  src/common/datatypes/Value.cpp
  src/common/datatypes/Value.h
  src/graph/visitor/DeduceTypeVisitor.cpp
  tests/tck/features/expression/TimeComputation.feature
Labels: ready-for-testing, type/bug, ready for review

#3488 Add show local sessions command
  src/graph/executor/admin/SessionExecutor.cpp
  src/graph/executor/admin/SessionExecutor.h
  src/graph/planner/plan/Admin.h
  src/graph/session/GraphSessionManager.cpp
  src/graph/session/GraphSessionManager.h
  src/graph/validator/AdminValidator.cpp
  src/parser/AdminSentences.cpp
  src/parser/AdminSentences.h
  src/parser/parser.yy
  src/parser/scanner.lex
  src/parser/test/ParserTest.cpp
  tests/conftest.py
  tests/job/test_session.py
  tests/tck/conftest.py
  tests/tck/features/admin/Sessions.feature
  tests/tck/slowquery/KillSlowQueryViaDiffrentService.feature
  tests/tck/slowquery/KillSlowQueryViaSameService.feature
Labels: type/enhancement, ready-for-testing, incompatible, doc affected, ready for review

#3534 Memavailable
  .gitignore
  src/common/memory/MemoryUtils.cpp
Labels: ready-for-testing, ready for review

#3462 ExtractFilterExprVisitor
  src/common/expression/LogicalExpression.h
  src/graph/visitor/ExtractFilterExprVisitor.cpp
  src/graph/visitor/ExtractFilterExprVisitor.h
  src/graph/visitor/test/ExtractFilterExprVisitorTest.cpp
Labels: ready-for-testing, ready for review

#2869 Disable the invalid size method of GetNeighbors Iterator.
  .linters/cpp/checkKeyword.py
  src/graph/context/Iterator.cpp
  src/graph/context/Iterator.h
  src/graph/executor/Executor.cpp
  src/graph/executor/StorageAccessExecutor.cpp
  src/graph/executor/algo/ProduceAllPathsExecutor.cpp
  src/graph/executor/algo/SubgraphExecutor.cpp
  src/graph/executor/query/FilterExecutor.cpp
  src/graph/executor/query/ProjectExecutor.cpp
Labels: ready-for-testing, type/bug, ready for review

#3507 Disable the bidirection edges.
  src/graph/optimizer/rule/GetEdgesTransformRule.cpp
  tests/tck/features/match/Scan.feature
Labels: ready-for-testing, type/bug, ready for review

#3569 fix format
  src/graph/visitor/ExtractFilterExprVisitor.cpp
Labels: ready-for-testing, ready for review

#3335 Insert vertex only
  src/graph/planner/ngql/FetchVerticesPlanner.cpp
  src/parser/parser.yy
  tests/tck/features/insert/insertVertexOnly.feature
Labels: ready-for-testing, doc affected, ready for review

#3435 [Raft] refactor processAppendLogRequest
  src/interface/common.thrift
  src/interface/raftex.thrift
  src/kvstore/Listener.cpp
  src/kvstore/Listener.h
  src/kvstore/Part.cpp
  src/kvstore/Part.h
  src/kvstore/raftex/CMakeLists.txt
  src/kvstore/raftex/Host.cpp
  src/kvstore/raftex/Host.h
  src/kvstore/raftex/RaftLogIterator.cpp
  src/kvstore/raftex/RaftLogIterator.h
  src/kvstore/raftex/RaftPart.cpp
  src/kvstore/raftex/RaftPart.h
  src/kvstore/raftex/test/TestShard.cpp
  src/kvstore/raftex/test/TestShard.h
  src/kvstore/test/NebulaListenerTest.cpp
  src/kvstore/wal/AtomicLogBuffer.h
  src/kvstore/wal/WalFileIterator.cpp
  src/kvstore/wal/WalFileIterator.h
Labels: ready-for-testing, ready for review

#3310 Add standalone version for nebula
  CMakeLists.txt
  cmake/nebula/GeneralCMakeOptions.cmake
  conf/CMakeLists.txt
  conf/nebula-standalone.conf.default
  scripts/CMakeLists.txt
  scripts/nebula-standalone.service
  scripts/nebula.service
  src/clients/storage/GeneralStorageClient.h
  src/clients/storage/InternalStorageClient.h
  src/clients/storage/StorageClient.cpp
  src/clients/storage/StorageClient.h
  src/clients/storage/StorageClientBase-inl.h
  src/clients/storage/StorageClientBase.h
  src/common/thrift/ThriftClientManager-inl.h
  src/common/thrift/ThriftLocalClientManager.h
  src/daemons/CMakeLists.txt
  src/daemons/MetaDaemon.cpp
  src/daemons/MetaDaemonInit.cpp
  src/daemons/MetaDaemonInit.h
  src/daemons/StandAloneDaemon.cpp
  src/graph/service/GraphFlags.cpp
  src/kvstore/Listener.cpp
  src/kvstore/plugins/elasticsearch/ESListener.cpp
  src/storage/CMakeLists.txt
  src/storage/GraphStorageLocalServer.cpp
  src/storage/GraphStorageLocalServer.h
  src/storage/StorageServer.cpp
  src/storage/StorageServer.h
  src/tools/CMakeLists.txt
  src/webservice/WebService.cpp
  src/webservice/WebService.h
Labels: ready-for-testing, doc affected, type/feature req, ready for review

#3536 Fix the issue that the query results will still contain the expired e…
  src/storage/query/QueryBaseProcessor-inl.h
  src/storage/test/GetNeighborsTest.cpp
Labels: ready-for-testing, ready for review

#3572 round the float/double when insert it to integer column
  src/codec/RowWriterV2.cpp
  src/graph/executor/admin/SpaceExecutor.cpp
  src/graph/service/GraphService.cpp
  src/graph/service/QueryInstance.cpp
  tests/tck/features/bugfix/RoundFloat.feature
Labels: ready-for-testing, type/bug, incompatible, doc affected

#3541 logrotate
  conf/nebula-graphd.conf.default
  conf/nebula-graphd.conf.production
  conf/nebula-metad.conf.default
  conf/nebula-metad.conf.production
  conf/nebula-storaged-listener.conf.production
  conf/nebula-storaged.conf.default
  conf/nebula-storaged.conf.production
  src/daemons/GraphDaemon.cpp
  src/daemons/MetaDaemon.cpp
  src/daemons/SetupLogging.cpp
  src/daemons/SetupLogging.h
  src/daemons/StorageDaemon.cpp
Labels: ready-for-testing, ready for review

#3549 Make scan limit error more friendly.
  src/graph/executor/query/ScanEdgesExecutor.cpp
  src/graph/executor/query/ScanVerticesExecutor.cpp
  tests/tck/features/match/Base.IntVid.feature
  tests/tck/features/match/Base.feature
  tests/tck/features/match/Scan.feature
  tests/tck/features/match/SeekByEdge.feature
  tests/tck/features/match/SeekById.feature
  tests/tck/features/match/SeekById.intVid.feature
Labels: ready-for-testing, ready for review

#3417 add db-upgrade V3
  src/common/utils/NebulaKeyUtils.cpp
  src/common/utils/NebulaKeyUtils.h
  src/tools/db-upgrade/CMakeLists.txt
  src/tools/db-upgrade/DbUpgrader.cpp
  src/tools/db-upgrade/DbUpgrader.h
  src/tools/db-upgrade/DbUpgraderTool.cpp
  src/tools/db-upgrade/NebulaKeyUtilsV3.cpp
  src/tools/db-upgrade/NebulaKeyUtilsV3.h
Labels: ready-for-testing, ready for review

#3574 Fix cmake statobj for standalone version
  src/daemons/CMakeLists.txt
  src/daemons/StandAloneDaemon.cpp
Labels: ready-for-testing, ready for review

#3575 fix parser memeory leak
  src/kvstore/raftex/Host.cpp
  src/kvstore/raftex/Host.h
  src/parser/parser.yy
  src/parser/test/ParserTest.cpp
Labels: ready-for-testing, ready for review

#3570 Fix/fix
  src/common/ssl/SSLConfig.cpp
  tests/common/nebula_service.py
  tests/common/utils.py
  tests/conftest.py
  tests/job/test_session.py
  tests/nebula-test-run.py
  tests/tck/conftest.py
Labels: ready-for-testing, type/bug

#3332 rebuild index for new prop
  src/common/utils/IndexKeyUtils.cpp
  src/common/utils/IndexKeyUtils.h
  src/storage/admin/RebuildEdgeIndexTask.cpp
  src/storage/admin/RebuildTagIndexTask.cpp
  src/storage/exec/UpdateNode.h
  src/storage/mutate/AddEdgesProcessor.cpp
  src/storage/mutate/AddEdgesProcessor.h
  src/storage/mutate/AddVerticesProcessor.cpp
  src/storage/mutate/AddVerticesProcessor.h
  src/storage/mutate/DeleteEdgesProcessor.cpp
  src/storage/mutate/DeleteVerticesProcessor.cpp
  src/tools/db-upgrade/DbUpgrader.cpp
  src/tools/db-upgrade/DbUpgrader.h
  tests/tck/features/index/Index.feature
Labels: ready-for-testing, community, ready for review

#3548 Support auto registe when storage start up
  src/meta/processors/admin/HBProcessor.cpp
  src/meta/processors/admin/HBProcessor.h
  src/meta/test/HBProcessorTest.cpp
  src/meta/test/ProcessorTest.cpp
Labels: ready-for-testing, ready for review

#3394 Balance
  .linters/cpp/checkKeyword.py
  src/clients/meta/MetaClient.cpp
  src/clients/meta/MetaClient.h
  src/graph/executor/Executor.cpp
  src/graph/executor/admin/SpaceExecutor.cpp
  src/graph/executor/admin/SpaceExecutor.h
  src/graph/executor/admin/SubmitJobExecutor.cpp
  src/graph/planner/plan/Admin.h
  src/graph/planner/plan/PlanNode.cpp
  src/graph/planner/plan/PlanNode.h
  src/graph/service/PermissionCheck.cpp
  src/graph/validator/AdminJobValidator.h
  src/graph/validator/AdminValidator.cpp
  src/graph/validator/AdminValidator.h
  src/graph/validator/Validator.cpp
  src/interface/meta.thrift
  src/meta/CMakeLists.txt
  src/meta/MetaServiceHandler.cpp
  src/meta/MetaServiceHandler.h
  src/meta/processors/job/BalanceJobExecutor.cpp
  src/meta/processors/job/BalanceJobExecutor.h
  src/meta/processors/job/BalancePlan.cpp
  src/meta/processors/job/BalancePlan.h
  src/meta/processors/job/BalanceTask.cpp
  src/meta/processors/job/BalanceTask.h
  src/meta/processors/job/DataBalanceJobExecutor.cpp
  src/meta/processors/job/DataBalanceJobExecutor.h
  src/meta/processors/job/JobExecutor.cpp
  src/meta/processors/job/JobExecutor.h
  src/meta/processors/job/JobManager.cpp
  src/meta/processors/job/JobManager.h
  src/meta/processors/job/LeaderBalanceJobExecutor.cpp
  src/meta/processors/job/LeaderBalanceJobExecutor.h
  src/meta/processors/job/MetaJobExecutor.cpp
  src/meta/processors/job/MetaJobExecutor.h
  src/meta/processors/job/RebuildJobExecutor.h
  src/meta/processors/job/SimpleConcurrentJobExecutor.cpp
  src/meta/processors/job/SimpleConcurrentJobExecutor.h
  src/meta/processors/job/StatsJobExecutor.h
  src/meta/processors/job/StorageJobExecutor.cpp
  src/meta/processors/job/StorageJobExecutor.h
  src/meta/processors/job/ZoneBalanceJobExecutor.cpp
  src/meta/processors/job/ZoneBalanceJobExecutor.h
  src/meta/processors/parts/AlterSpaceProcessor.cpp
  src/meta/processors/parts/AlterSpaceProcessor.h
  src/meta/test/BalancerTest.cpp
  src/meta/test/GetStatsTest.cpp
  src/meta/test/JobManagerTest.cpp
  src/meta/test/ProcessorTest.cpp
  src/meta/test/TestUtils.h
  src/parser/AdminSentences.cpp
  src/parser/AdminSentences.h
  src/parser/Sentence.h
  src/parser/parser.yy
  src/parser/scanner.lex
  src/parser/test/ParserTest.cpp
Labels: ready-for-testing, incompatible, doc affected, ready for review

#3586 Fix stats init order
  src/daemons/GraphDaemon.cpp
  src/daemons/StandAloneDaemon.cpp
Labels: ready-for-testing

#3374 To support delete in toss.
  src/clients/storage/InternalStorageClient.cpp
  src/clients/storage/InternalStorageClient.h
  src/clients/storage/StorageClient.cpp
  src/common/utils/Types.h
  src/graph/executor/mutate/DeleteExecutor.cpp
  src/interface/storage.thrift
  src/kvstore/Part.cpp
  src/kvstore/raftex/RaftPart.cpp
  src/mock/MockData.cpp
  src/mock/MockData.h
  src/storage/CMakeLists.txt
  src/storage/GraphStorageServiceHandler.cpp
  src/storage/GraphStorageServiceHandler.h
  src/storage/InternalStorageServiceHandler.cpp
  src/storage/InternalStorageServiceHandler.h
  src/storage/mutate/AddEdgesProcessor.h
  src/storage/mutate/DeleteEdgesProcessor.cpp
  src/storage/mutate/DeleteEdgesProcessor.h
  src/storage/test/CMakeLists.txt
  src/storage/test/ChainAddEdgesTest.cpp
  src/storage/test/ChainDeleteEdgesTest.cpp
  src/storage/test/ChainResumeEdgeTest.cpp
  src/storage/test/ChainTestUtils.h
  src/storage/test/ChainUpdateEdgeTest.cpp
  src/storage/transaction/ChainAddEdgesGroupProcessor.cpp
  src/storage/transaction/ChainAddEdgesLocalProcessor.cpp
  src/storage/transaction/ChainAddEdgesLocalProcessor.h
  src/storage/transaction/ChainAddEdgesRemoteProcessor.cpp
  src/storage/transaction/ChainAddEdgesRemoteProcessor.h
  src/storage/transaction/ChainDeleteEdgesGroupProcessor.cpp
  src/storage/transaction/ChainDeleteEdgesGroupProcessor.h
  src/storage/transaction/ChainDeleteEdgesLocalProcessor.cpp
  src/storage/transaction/ChainDeleteEdgesLocalProcessor.h
  src/storage/transaction/ChainDeleteEdgesRemoteProcessor.cpp
  src/storage/transaction/ChainDeleteEdgesRemoteProcessor.h
  src/storage/transaction/ChainDeleteEdgesResumeProcessor.cpp
  src/storage/transaction/ChainDeleteEdgesResumeProcessor.h
  src/storage/transaction/ChainDeleteEdgesResumeRemoteProcessor.cpp
  src/storage/transaction/ChainDeleteEdgesResumeRemoteProcessor.h
  src/storage/transaction/ChainProcessorFactory.cpp
  src/storage/transaction/ChainResumeProcessor.cpp
  src/storage/transaction/ChainResumeProcessor.h
  src/storage/transaction/ChainUpdateEdgeLocalProcessor.cpp
  src/storage/transaction/ChainUpdateEdgeLocalProcessor.h
  src/storage/transaction/ChainUpdateEdgeProcessorRemote.cpp
  src/storage/transaction/ChainUpdateEdgeRemoteProcessor.cpp
  src/storage/transaction/ChainUpdateEdgeRemoteProcessor.h
  src/storage/transaction/ConsistTypes.h
  src/storage/transaction/ConsistUtil.cpp
  src/storage/transaction/ConsistUtil.h
  src/storage/transaction/ResumeAddEdgeProcessor.cpp
  src/storage/transaction/ResumeAddEdgeRemoteProcessor.cpp
  src/storage/transaction/ResumeAddEdgeRemoteProcessor.h
  src/storage/transaction/ResumeUpdateProcessor.cpp
  src/storage/transaction/ResumeUpdateProcessor.h
  src/storage/transaction/ResumeUpdateRemoteProcessor.cpp
  src/storage/transaction/ResumeUpdateRemoteProcessor.h
  src/storage/transaction/TransactionManager.cpp
  src/storage/transaction/TransactionManager.h
Labels: ready-for-testing, ready for review

#3588 Synchronize the enterprise version to reduce conflicts
  src/clients/meta/MetaClient.cpp
  src/clients/meta/MetaClient.h
  src/common/meta/SchemaManager.h
  src/common/meta/ServerBasedSchemaManager.cpp
  src/common/meta/ServerBasedSchemaManager.h
  src/common/utils/MetaKeyUtils.cpp
  src/common/utils/MetaKeyUtils.h
  src/graph/executor/CMakeLists.txt
  src/graph/executor/Executor.cpp
  src/graph/executor/admin/ShowServiceClientsExecutor.cpp
  src/graph/executor/admin/ShowServiceClientsExecutor.h
  src/graph/executor/admin/ShowTSClientsExecutor.cpp
  src/graph/executor/admin/ShowTSClientsExecutor.h
  src/graph/executor/admin/SignInServiceExecutor.cpp
  src/graph/executor/admin/SignInServiceExecutor.h
  src/graph/executor/admin/SignInTSServiceExecutor.h
  src/graph/executor/admin/SignOutServiceExecutor.cpp
  src/graph/executor/admin/SignOutServiceExecutor.h
  src/graph/planner/plan/Admin.h
  src/graph/planner/plan/PlanNode.cpp
  src/graph/planner/plan/PlanNode.h
  src/graph/service/PermissionCheck.cpp
  src/graph/util/FTIndexUtils.cpp
  src/graph/validator/AdminValidator.cpp
  src/graph/validator/AdminValidator.h
  src/graph/validator/Validator.cpp
  src/graph/validator/test/MockSchemaManager.cpp
  src/graph/validator/test/MockSchemaManager.h
  src/interface/common.thrift
  src/interface/meta.thrift
  src/kvstore/plugins/elasticsearch/ESListener.cpp
  src/meta/CMakeLists.txt
  src/meta/MetaServiceHandler.cpp
  src/meta/MetaServiceHandler.h
  src/meta/processors/Common.h
  src/meta/processors/index/FTServiceProcessor.cpp
  src/meta/processors/index/FTServiceProcessor.h
  src/meta/processors/service/ServiceProcessor.cpp
  src/meta/processors/service/ServiceProcessor.h
  src/meta/test/MetaClientTest.cpp
  src/mock/AdHocSchemaManager.cpp
  src/mock/AdHocSchemaManager.h
  src/mock/MockCluster.cpp
  src/mock/MockCluster.h
  src/parser/AdminSentences.cpp
  src/parser/AdminSentences.h
  src/parser/Sentence.h
  src/parser/parser.yy
  src/storage/test/ElasticSearchBulkInsertTest.cpp
Labels: ready-for-testing, ready for review

#3592 Revert "Support auto registe when storage start up"
  src/meta/processors/admin/HBProcessor.cpp
  src/meta/processors/admin/HBProcessor.h
  src/meta/test/HBProcessorTest.cpp
  src/meta/test/ProcessorTest.cpp
Labels: ready-for-testing

#3590 Add more space level metrics
  src/graph/executor/Executor.cpp
  src/graph/optimizer/rule/IndexScanRule.cpp
  src/graph/service/GraphService.cpp
  src/graph/service/QueryInstance.cpp
  src/graph/session/ClientSession.cpp
  src/graph/stats/GraphStats.cpp
  src/graph/stats/GraphStats.h
Labels: ready-for-testing, ready for review

#3458 Adjust get neighbor plan
  src/storage/CommonUtils.h
  src/storage/exec/FilterNode.h
  src/storage/exec/GetNeighborsNode.h
  src/storage/exec/MultiTagNode.h
  src/storage/query/GetNeighborsProcessor.cpp
  src/storage/test/GetNeighborsTest.cpp
Labels: ready-for-testing, ready for review

#3596 Fix mistake modification.
  tests/cert/test.ca.password
Labels: ready-for-testing

#3542 simplify graph signal handler
  src/daemons/GraphDaemon.cpp
  src/graph/service/CMakeLists.txt
  src/graph/service/GraphServer.cpp
  src/graph/service/GraphServer.h
Labels: ready-for-testing, ready for review

#3580 enhance tck setup
  tests/common/nebula_service.py
Labels: ready-for-testing

#3605 Adjust the name format of space level metrics
  src/common/stats/StatsManager.cpp
  src/common/stats/test/StatsManagerTest.cpp
  src/storage/test/CMakeLists.txt
Labels: ready-for-testing

#3598 Fix scheduler broken promise error
  src/graph/context/Iterator.h
  src/graph/scheduler/AsyncMsgNotifyBasedScheduler.cpp
  src/graph/scheduler/AsyncMsgNotifyBasedScheduler.h
Labels: ready-for-testing, type/bug

#3499 topN push down for lookup
  src/clients/storage/StorageClient.cpp
  src/clients/storage/StorageClient.h
  src/graph/executor/query/IndexScanExecutor.cpp
  src/graph/optimizer/CMakeLists.txt
  src/graph/optimizer/OptimizerUtils.cpp
  src/graph/optimizer/rule/PushTopNDownEdgeIndexFullScanRule.cpp
  src/graph/optimizer/rule/PushTopNDownEdgeIndexFullScanRule.h
  src/graph/optimizer/rule/PushTopNDownEdgeIndexPrefixScanRule.cpp
  src/graph/optimizer/rule/PushTopNDownEdgeIndexPrefixScanRule.h
  src/graph/optimizer/rule/PushTopNDownEdgeIndexRangeScanRule.cpp
  src/graph/optimizer/rule/PushTopNDownEdgeIndexRangeScanRule.h
  src/graph/optimizer/rule/PushTopNDownIndexScanRule.cpp
  src/graph/optimizer/rule/PushTopNDownIndexScanRule.h
  src/graph/optimizer/rule/PushTopNDownTagIndexFullScanRule.cpp
  src/graph/optimizer/rule/PushTopNDownTagIndexFullScanRule.h
  src/graph/optimizer/rule/PushTopNDownTagIndexPrefixScanRule.cpp
  src/graph/optimizer/rule/PushTopNDownTagIndexPrefixScanRule.h
  src/graph/optimizer/rule/PushTopNDownTagIndexRangeScanRule.cpp
  src/graph/optimizer/rule/PushTopNDownTagIndexRangeScanRule.h
  src/graph/planner/ngql/LookupPlanner.cpp
  src/graph/planner/plan/Query.cpp
  src/graph/planner/plan/Query.h
  src/interface/storage.thrift
  src/storage/CMakeLists.txt
  src/storage/exec/IndexLimitNode.h
  src/storage/exec/IndexTopNNode.cpp
  src/storage/exec/IndexTopNNode.h
  src/storage/index/LookupProcessor.cpp
  src/storage/test/CMakeLists.txt
  src/storage/test/IndexScanTopNTest.cpp
  tests/tck/features/lookup/LookUpTopN.feature
Labels: ready-for-testing

#3500 Add snowflake id
  src/clients/meta/MetaClient.cpp
  src/clients/meta/MetaClient.h
  src/common/CMakeLists.txt
  src/common/expression/UUIDExpression.cpp
  src/common/expression/UUIDExpression.h
  src/common/expression/test/EncodeDecodeTest.cpp
  src/common/expression/test/ExpressionTest.cpp
  src/common/id/CMakeLists.txt
  src/common/id/Snowflake.cpp
  src/common/id/Snowflake.h
  src/common/id/test/CMakeLists.txt
  src/common/id/test/SnowflakeBenchmark.cpp
  src/common/id/test/SnowflakeTest.cpp
  src/daemons/CMakeLists.txt
  src/graph/service/GraphServer.cpp
  src/graph/service/GraphService.h
  src/interface/common.thrift
  src/interface/meta.thrift
  src/meta/CMakeLists.txt
  src/meta/MetaServiceHandler.cpp
  src/meta/MetaServiceHandler.h
  src/meta/processors/Common.h
  src/meta/processors/id/GetWorkerIdProcessor.cpp
  src/meta/processors/id/GetWorkerIdProcessor.h
  src/parser/parser.yy
  src/parser/test/ParserTest.cpp
Labels: ready-for-testing, ready for review

#3573 Add constraints on invalid password attempts
  src/clients/meta/MetaClient.cpp
  src/clients/meta/MetaClient.h
  src/common/graph/Response.h
  src/graph/service/Authenticator.h
  src/graph/service/CloudAuthenticator.cpp
  src/graph/service/CloudAuthenticator.h
  src/graph/service/GraphFlags.h
  src/graph/service/GraphService.cpp
  src/graph/service/GraphService.h
  src/graph/service/PasswordAuthenticator.cpp
  src/graph/service/PasswordAuthenticator.h
  tests/Makefile
  tests/common/nebula_service.py
  tests/nebula-test-run.py
  tests/tck/conftest.py
  tests/tck/features/admin/Authentication.feature
Labels: ready-for-testing, doc affected

#3604 fix br bugs in cluster mode
  conf/nebula-metad.conf.default
  conf/nebula-metad.conf.production
  resources/gflags.json
  src/clients/meta/MetaClient.cpp
  src/common/graph/Response.h
  src/common/meta/GflagsManager.cpp
  src/common/utils/MetaKeyUtils.cpp
  src/graph/planner/plan/Admin.h
  src/interface/common.thrift
  src/interface/meta.thrift
  src/meta/ActiveHostsMan.cpp
  src/meta/processors/BaseProcessor-inl.h
  src/meta/processors/BaseProcessor.h
  src/meta/processors/admin/ListClusterInfoProcessor.cpp
  src/meta/processors/admin/RestoreProcessor.cpp
  src/meta/processors/parts/ListHostsProcessor.cpp
  src/parser/parser.yy
  src/parser/scanner.lex
  src/parser/test/ScannerTest.cpp
Labels: ready-for-testing

#3608 Fix duration to string.
  src/common/datatypes/Duration.h
  src/common/datatypes/test/ValueTest.cpp
  src/storage/test/GetNeighborsTest.cpp
Labels: ready-for-testing

#3597 disable agg function in ngql's yield clause & where clause
  src/graph/validator/FetchEdgesValidator.cpp
  src/graph/validator/FetchVerticesValidator.cpp
  src/graph/validator/FindPathValidator.cpp
  src/graph/validator/GoValidator.cpp
  src/graph/validator/LookupValidator.cpp
  src/graph/validator/test/GroupByValidatorTest.cpp
  src/graph/validator/test/LookupValidatorTest.cpp
  src/graph/validator/test/QueryValidatorTest.cpp
  src/parser/parser.yy
  src/parser/test/ParserTest.cpp
  tests/tck/features/aggregate/Agg.feature
  tests/tck/features/go/GroupbyLimit.IntVid.feature
  tests/tck/features/go/GroupbyLimit.feature
  tests/tck/features/yield/yield.IntVid.feature
  tests/tck/features/yield/yield.feature
Labels: ready-for-testing, type/bug, ready for review

#3589 Update pull_request_template.md
  .github/pull_request_template.md
Labels: ready-for-testing, ready for review
