Repository vesoft-inc/nebula, pull requests merged in 2021-11, with the labels that each got.

#3240 Build ARM platform docker images
  .github/workflows/nightly.yml
  .github/workflows/release.yml
  third-party/install-cmake.sh
  third-party/install-gcc.sh
  third-party/install-third-party.sh
Labels: ready-for-testing, doc affected

#3245 disable lookup yield agg function
  src/graph/validator/LookupValidator.cpp
  src/graph/validator/test/LookupValidatorTest.cpp
  tests/tck/features/lookup/WithYield.feature
  tests/tck/features/lookup/WithYield.intVid.feature
Labels: ready-for-testing, bug

#3251 Use self-hosted runner to speed up nightly and releasing packaging
  .github/workflows/nightly.yml
  .github/workflows/release.yml
Labels: ready-for-testing

#3250 Cherry pick from master to v2.6.1
  .github/workflows/nightly.yml
  .github/workflows/release.yml
  src/graph/validator/LookupValidator.cpp
  src/graph/validator/test/LookupValidatorTest.cpp
  tests/tck/features/lookup/WithYield.feature
  tests/tck/features/lookup/WithYield.intVid.feature
  third-party/install-cmake.sh
  third-party/install-gcc.sh
  third-party/install-third-party.sh
Labels: ready-for-testing

#3261 disable lookup yield agg function (#3245)
  src/graph/validator/LookupValidator.cpp
  src/graph/validator/test/LookupValidatorTest.cpp
  tests/tck/features/lookup/WithYield.feature
  tests/tck/features/lookup/WithYield.intVid.feature
Labels: ready-for-testing

#3234 [Minor] Fix typos in the template
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/pull_request_template.md
Labels: ready-for-testing

#3178 Specify the floating point accuracy of the round() function
  src/common/function/FunctionManager.cpp
  src/common/function/test/FunctionManagerTest.cpp
  tests/tck/features/expression/FunctionCall.feature
Labels: ready-for-testing

#3268 Add license check
  .github/workflows/pull_request.yml
  .github/workflows/release.yml
  .licenserc.yaml
  scripts/meta-transfer-tools.sh
  scripts/utils.sh
  src/common/datatypes/EdgeOps-inl.h
  src/common/datatypes/HostAddrOps-inl.h
  src/common/datatypes/PathOps-inl.h
  src/common/datatypes/ValueOps-inl.h
  src/common/geo/GeoIndex.cpp
Labels: ready-for-testing

#3276 Remove duplicate license files
  .dockerignore
  LICENSES/Apache-2.0.txt
Labels: ready-for-testing

#3277 Limit workflow job concurrency
  .github/workflows/nightly.yml
  .github/workflows/pull_request.yml
  .github/workflows/release.yml
Labels: ready-for-testing

#3196 Refactor storage index
  src/common/utils/IndexKeyUtils.h
  src/common/utils/test/CMakeLists.txt
  src/daemons/CMakeLists.txt
  src/graph/optimizer/OptimizerUtils.cpp
  src/interface/storage.thrift
  src/kvstore/test/CMakeLists.txt
  src/storage/CMakeLists.txt
  src/storage/CommonUtils.h
  src/storage/ExprVisitorBase.cpp
  src/storage/ExprVisitorBase.h
  src/storage/exec/IndexDedupNode.cpp
  src/storage/exec/IndexDedupNode.h
  src/storage/exec/IndexEdgeNode.h
  src/storage/exec/IndexEdgeScanNode.cpp
  src/storage/exec/IndexEdgeScanNode.h
  src/storage/exec/IndexFilterNode.h
  src/storage/exec/IndexLimitNode.cpp
  src/storage/exec/IndexLimitNode.h
  src/storage/exec/IndexNode.cpp
  src/storage/exec/IndexNode.h
  src/storage/exec/IndexOutputNode.h
  src/storage/exec/IndexProjectionNode.cpp
  src/storage/exec/IndexProjectionNode.h
  src/storage/exec/IndexScanNode.cpp
  src/storage/exec/IndexScanNode.h
  src/storage/exec/IndexSelectionNode.cpp
  src/storage/exec/IndexSelectionNode.h
  src/storage/exec/IndexVertexNode.h
  src/storage/exec/IndexVertexScanNode.cpp
  src/storage/exec/IndexVertexScanNode.h
  src/storage/exec/StorageIterator.h
  src/storage/index/LookupBaseProcessor-inl.h
  src/storage/index/LookupBaseProcessor.h
  src/storage/index/LookupProcessor.cpp
  src/storage/index/LookupProcessor.h
  src/storage/test/CMakeLists.txt
  src/storage/test/IndexScanTest.cpp
  src/storage/test/IndexTest.cpp
  src/storage/test/IndexTestUtil.h
  src/storage/test/LookupIndexTest.cpp
  src/tools/db-dump/CMakeLists.txt
  src/tools/meta-dump/CMakeLists.txt
  tests/tck/features/lookup/LookUp.feature
Labels: ready-for-testing

#3290 Update nebula-python installation in the test
  tests/Makefile
Labels: ready-for-testing

#3291 rm outdated test
  src/storage/test/IndexScanTest.cpp
Labels: ready-for-testing

#3292 Update the runner associated with the workflow
  .github/workflows/nightly.yml
  .github/workflows/pull_request.yml
  .github/workflows/release.yml
Labels: ready-for-testing

#3241 Delete .github/PULL_REQUEST_TEMPLATE directory
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Labels: ready-for-testing

#3262 Feature/scan multiple parts
  src/clients/storage/GraphStorageClient.cpp
  src/clients/storage/GraphStorageClient.h
  src/clients/storage/StorageClientBase-inl.h
  src/clients/storage/StorageClientBase.h
  src/interface/storage.thrift
  src/storage/exec/EdgeNode.h
  src/storage/exec/RelNode.h
  src/storage/exec/ScanNode.h
  src/storage/exec/TagNode.h
  src/storage/query/ScanEdgeProcessor.cpp
  src/storage/query/ScanEdgeProcessor.h
  src/storage/query/ScanVertexProcessor.cpp
  src/storage/query/ScanVertexProcessor.h
  src/storage/test/ScanEdgeTest.cpp
  src/storage/test/ScanVertexTest.cpp
Labels: ready-for-testing

#3226 Delete the useless target `install-all`
  CMakeLists.txt
Labels: ready-for-testing, doc affected

#3306 fix a bug may stuck
  src/storage/transaction/ChainAddEdgesProcessorLocal.cpp
Labels: ready-for-testing

#3256 remove read lock in meta client
  src/clients/meta/MetaClient.cpp
  src/clients/meta/MetaClient.h
  src/graph/service/CloudAuthenticator.cpp
  src/graph/service/CloudAuthenticator.h
  src/graph/service/PasswordAuthenticator.cpp
  src/graph/service/PasswordAuthenticator.h
  src/graph/service/QueryEngine.h
Labels: ready-for-testing

#3303 fix typo error of KW_VALUE
  src/parser/parser.yy
  src/parser/scanner.lex
  src/parser/test/ScannerTest.cpp
  tests/tck/features/bugfix/TypoError.feature
Labels: ready-for-testing, bug, incompatible

#3301 Merge all expression tests to save disk consumption
  src/common/expression/test/AggregateExpressionTest.cpp
  src/common/expression/test/ArithmeticExpressionTest.cpp
  src/common/expression/test/AttributeExpressionTest.cpp
  src/common/expression/test/CMakeLists.txt
  src/common/expression/test/CaseExpressionTest.cpp
  src/common/expression/test/ColumnExpressionTest.cpp
  src/common/expression/test/ConstantExpressionTest.cpp
  src/common/expression/test/ContainerExpressionTest.cpp
  src/common/expression/test/EncodeDecodeTest.cpp
  src/common/expression/test/FunctionCallExpressionTest.cpp
  src/common/expression/test/LabelExpressionTest.cpp
  src/common/expression/test/ListComprehensionExpressionTest.cpp
  src/common/expression/test/LogicalExpressionTest.cpp
  src/common/expression/test/PathBuildExpressionTest.cpp
  src/common/expression/test/PredicateExpressionTest.cpp
  src/common/expression/test/PropertyExpressionTest.cpp
  src/common/expression/test/ReduceExpressionTest.cpp
  src/common/expression/test/RelationalExpressionTest.cpp
  src/common/expression/test/SubscriptExpressionTest.cpp
  src/common/expression/test/TestBase.cpp
  src/common/expression/test/TestBase.h
  src/common/expression/test/TypeCastingExpressionTest.cpp
  src/common/expression/test/UnaryExpressionTest.cpp
  src/common/expression/test/VersionedVariableExpressionTest.cpp
Labels: ready-for-testing

#3289 Cancel memory check when the ratio greater than 1.0
  conf/nebula-graphd.conf.default
  conf/nebula-graphd.conf.production
  src/common/memory/MemoryUtils.cpp
Labels: ready-for-testing

#3307 [Minor] Edit cmakelist to void conflict with nebula ent
  src/daemons/CMakeLists.txt
Labels: ready-for-testing

#3285 Modify index bound value
  src/common/utils/IndexKeyUtils.h
  src/graph/optimizer/OptimizerUtils.cpp
  src/graph/optimizer/OptimizerUtils.h
  src/graph/optimizer/rule/IndexScanRule.cpp
  src/graph/optimizer/rule/IndexScanRule.h
  src/graph/optimizer/test/CMakeLists.txt
  src/graph/optimizer/test/IndexBoundValueTest.cpp
  src/graph/optimizer/test/IndexScanRuleTest.cpp
  src/graph/util/ToJson.cpp
  src/storage/exec/IndexScanNode.cpp
  tests/tck/features/bugfix/TruncatedStringIndex.feature
  tests/tck/features/optimizer/IndexScanRule.feature
Labels: ready-for-testing

#3031 separate thenValue/thenError when rpc fail to handle timeout
  src/clients/storage/StorageClientBase-inl.h
  src/clients/storage/StorageClientBase.h
  src/kvstore/raftex/Host.cpp
Labels: ready-for-testing

#3308 Traverse.
  src/common/datatypes/Edge.cpp
  src/common/datatypes/Edge.h
  src/common/expression/PathBuildExpression.cpp
  src/common/expression/PathBuildExpression.h
  src/common/expression/test/ExpressionContextMock.cpp
  src/common/function/FunctionManager.cpp
  src/graph/context/Iterator.cpp
  src/graph/context/Iterator.h
  src/graph/executor/CMakeLists.txt
  src/graph/executor/Executor.cpp
  src/graph/executor/query/AppendVerticesExecutor.cpp
  src/graph/executor/query/AppendVerticesExecutor.h
  src/graph/executor/query/TraverseExecutor.cpp
  src/graph/executor/query/TraverseExecutor.h
  src/graph/planner/CMakeLists.txt
  src/graph/planner/match/Expand.cpp
  src/graph/planner/match/Expand.h
  src/graph/planner/match/LabelIndexSeek.cpp
  src/graph/planner/match/MatchClausePlanner.cpp
  src/graph/planner/match/MatchClausePlanner.h
  src/graph/planner/match/MatchSolver.cpp
  src/graph/planner/match/PropIndexSeek.cpp
  src/graph/planner/match/VertexIdSeek.cpp
  src/graph/planner/match/VertexIdSeek.h
  src/graph/planner/ngql/PathPlanner.cpp
  src/graph/planner/ngql/SubgraphPlanner.cpp
  src/graph/planner/plan/PlanNode.cpp
  src/graph/planner/plan/PlanNode.h
  src/graph/planner/plan/Query.cpp
  src/graph/planner/plan/Query.h
  src/graph/util/SchemaUtil.cpp
  src/graph/util/SchemaUtil.h
  src/graph/validator/MatchValidator.cpp
  src/graph/validator/MatchValidator.h
  src/graph/validator/test/MatchValidatorTest.cpp
  src/graph/validator/test/QueryValidatorTest.cpp
  src/parser/MatchSentence.cpp
  src/parser/MatchSentence.h
  src/parser/parser.yy
  tests/tck/features/expression/RelationalExpr.feature
  tests/tck/features/expression/UnaryExpr.feature
  tests/tck/features/match/With.feature
  tests/tck/features/optimizer/CollapseProjectRule.feature
  tests/tck/features/optimizer/CombineFilterRule.feature
  tests/tck/features/optimizer/IndexScanRule.feature
  tests/tck/features/optimizer/MergeGetNbrsDedupProjectRule.feature
  tests/tck/features/optimizer/MergeGetVerticesDedupProjectRule.feature
  tests/tck/features/optimizer/PushLimitDownProjectRule.feature
  tests/tck/features/optimizer/RemoveUselessProjectRule.feature
Labels: ready-for-testing

#3286 replace kVertex with kTag
  src/common/utils/IndexKeyUtils.h
  src/common/utils/NebulaKeyUtils.cpp
  src/common/utils/NebulaKeyUtils.h
  src/common/utils/Types.h
  src/common/utils/test/NebulaKeyUtilsTest.cpp
  src/kvstore/Part.cpp
  src/kvstore/plugins/elasticsearch/ESListener.cpp
  src/kvstore/plugins/hbase/HBaseStore.cpp
  src/kvstore/plugins/hbase/test/HBaseStoreTest.cpp
  src/kvstore/test/NebulaListenerTest.cpp
  src/kvstore/test/NebulaStoreTest.cpp
  src/kvstore/test/PartTest.cpp
  src/kvstore/test/RocksEngineTest.cpp
  src/storage/CompactionFilter.h
  src/storage/admin/RebuildTagIndexTask.cpp
  src/storage/admin/StatsTask.cpp
  src/storage/exec/IndexVertexScanNode.cpp
  src/storage/exec/ScanNode.h
  src/storage/exec/TagNode.h
  src/storage/exec/UpdateNode.h
  src/storage/mutate/AddVerticesProcessor.cpp
  src/storage/mutate/DeleteTagsProcessor.cpp
  src/storage/mutate/DeleteVerticesProcessor.cpp
  src/storage/test/AddAndUpdateVertexAndEdgeBenchmark.cpp
  src/storage/test/CompactionTest.cpp
  src/storage/test/GetNeighborsBenchmark.cpp
  src/storage/test/GetPropTest.cpp
  src/storage/test/IndexScanLimitTest.cpp
  src/storage/test/IndexTest.cpp
  src/storage/test/IndexWithTTLTest.cpp
  src/storage/test/IndexWriteTest.cpp
  src/storage/test/LookupIndexTest.cpp
  src/storage/test/MemoryLockBenchmark.cpp
  src/storage/test/PrefixBloomFilterBenchmark.cpp
  src/storage/test/QueryStatsTest.cpp
  src/storage/test/QueryTestUtils.h
  src/storage/test/RebuildIndexTest.cpp
  src/storage/test/StatsTaskTest.cpp
  src/storage/test/StorageIndexWriteBenchmark.cpp
  src/storage/test/TestUtils.h
  src/storage/test/UpdateVertexTest.cpp
  src/tools/db-dump/DbDumper.cpp
  src/tools/db-upgrade/DbUpgrader.cpp
  src/tools/db-upgrade/NebulaKeyUtilsV2.cpp
  src/tools/db-upgrade/NebulaKeyUtilsV2.h
Labels: ready-for-testing

#3172 [Raft] make me crazy
  conf/nebula-storaged.conf.production
  src/common/base/SlowOpTracker.cpp
  src/interface/raftex.thrift
  src/kvstore/NebulaSnapshotManager.cpp
  src/kvstore/raftex/Host.cpp
  src/kvstore/raftex/Host.h
  src/kvstore/raftex/RaftPart.cpp
  src/kvstore/raftex/RaftPart.h
  src/kvstore/raftex/SnapshotManager.cpp
  src/kvstore/raftex/SnapshotManager.h
  src/kvstore/raftex/test/CMakeLists.txt
  src/kvstore/raftex/test/SnapshotTest.cpp
  src/kvstore/wal/FileBasedWal.cpp
  src/kvstore/wal/FileBasedWal.h
  src/kvstore/wal/Wal.h
  src/kvstore/wal/WalFileIterator.cpp
  src/kvstore/wal/test/FileBasedWalTest.cpp
  tests/admin/test_configs.py
Labels: ready-for-testing

#3293 Add more geo tests
  .clang-tidy
  src/codec/RowWriterV2.cpp
  src/codec/test/RowWriterV2Test.cpp
  src/common/geo/test/CMakeLists.txt
  src/common/geo/test/GeoIndexTest.cpp
Labels: ready-for-testing

#3326 DSS part10 unify LogStrListIterator for raft and drainer
  src/common/utils/CMakeLists.txt
  src/common/utils/LogStrListIterator.cpp
  src/common/utils/LogStrListIterator.h
  src/daemons/CMakeLists.txt
  src/interface/common.thrift
  src/interface/raftex.thrift
  src/kvstore/raftex/CMakeLists.txt
  src/kvstore/raftex/Host.cpp
  src/kvstore/raftex/RaftPart.cpp
  src/kvstore/raftex/test/CMakeLists.txt
  src/kvstore/test/CMakeLists.txt
  src/meta/CMakeLists.txt
  src/storage/test/CMakeLists.txt
  src/tools/db-dump/CMakeLists.txt
  src/tools/db-upgrade/CMakeLists.txt
  src/tools/meta-dump/CMakeLists.txt
  src/tools/simple-kv-verify/CMakeLists.txt
  src/tools/storage-perf/CMakeLists.txt
Labels: ready-for-testing

#3283 Trigger packaging action when pushing release branch
  .github/workflows/nightly.yml
  .github/workflows/rc.yml
  .github/workflows/release.yml
Labels: ready-for-testing

#2858 Using int64 to present graph execution latency.
  src/interface/graph.thrift
Labels: ready-for-testing, incompatible

#3325 fix issue 3317
  src/storage/exec/IndexEdgeScanNode.cpp
  src/storage/exec/IndexVertexScanNode.cpp
Labels: ready-for-testing

#3334 Filter the label by tag property for more friendly to push down.
  src/graph/planner/match/MatchClausePlanner.cpp
  src/graph/validator/MatchValidator.cpp
Labels: ready-for-testing

#3298 CI improvements
  .github/workflows/pull_request.yml
  .linters/cpp/hooks/pre-commit.sh
  tests/Makefile
Labels: enhancement, ready-for-testing, community

#3272 enhance match attribute filter
  src/graph/validator/MatchValidator.cpp
  src/graph/validator/MatchValidator.h
  src/graph/visitor/FoldConstantExprVisitor.cpp
  src/graph/visitor/test/FilterTransformTest.cpp
  src/parser/MatchSentence.h
  src/storage/exec/IndexScanNode.cpp
  tests/tck/features/expression/EndsWith.feature
  tests/tck/features/expression/Null.feature
  tests/tck/features/expression/StartsWith.feature
  tests/tck/features/expression/function/Mathematical.feature
  tests/tck/features/expression/function/TypeConversion.feature
  tests/tck/features/go/GO.feature
  tests/tck/features/lookup/ByIndex.feature
  tests/tck/features/lookup/ByIndex.intVid.feature
  tests/tck/features/match/Base.IntVid.feature
  tests/tck/features/match/Base.feature
  tests/tck/features/schema/Schema.feature
  tests/tck/features/yield/yield.IntVid.feature
  tests/tck/features/yield/yield.feature
Labels: enhancement, ready-for-testing

#3318 Multi paths.
  src/common/expression/test/CMakeLists.txt
  src/common/geo/io/wkb/test/CMakeLists.txt
  src/common/geo/io/wkt/test/CMakeLists.txt
  src/daemons/CMakeLists.txt
  src/graph/context/test/CMakeLists.txt
  src/graph/executor/test/CMakeLists.txt
  src/graph/optimizer/test/CMakeLists.txt
  src/graph/planner/CMakeLists.txt
  src/graph/planner/Planner.h
  src/graph/planner/plan/ExecutionPlan.h
  src/graph/planner/test/CMakeLists.txt
  src/graph/util/PlannerUtil.cpp
  src/graph/util/ValidateUtil.cpp
  src/graph/util/test/CMakeLists.txt
  src/graph/validator/MatchValidator.cpp
  src/graph/validator/test/CMakeLists.txt
  src/graph/visitor/test/CMakeLists.txt
  src/parser/MatchSentence.cpp
  src/parser/MatchSentence.h
  src/parser/parser.yy
  src/parser/test/CMakeLists.txt
  src/parser/test/ParserTest.cpp
Labels: ready-for-testing

#3342 small fix for previous merge conflict
  src/graph/executor/admin/BalanceLeadersExecutor.h
  src/meta/processors/admin/Balancer.cpp
  src/meta/processors/admin/Balancer.h
Labels: ready-for-testing

#3150 Support https for es client
  src/common/plugin/fulltext/FTUtils.h
  src/common/plugin/fulltext/test/FulltextPluginTest.cpp
  src/graph/executor/admin/ShowTSClientsExecutor.cpp
  src/graph/util/FTIndexUtils.cpp
  src/interface/meta.thrift
  src/kvstore/plugins/elasticsearch/ESListener.cpp
  src/parser/AdminSentences.cpp
  src/parser/parser.yy
  src/parser/scanner.lex
  src/parser/test/ParserTest.cpp
Labels: ready-for-testing, v2.6.0

#3341 remove some useless code
  src/meta/processors/job/BalanceJobExecutor.cpp
  src/meta/processors/job/BalanceJobExecutor.h
Labels: ready-for-testing

#3281 Add key value separation feature to Nebula storage engine
  conf/nebula-storaged.conf.default
  conf/nebula-storaged.conf.production
  src/kvstore/RocksEngineConfig.cpp
  src/kvstore/RocksEngineConfig.h
  src/kvstore/test/RocksEngineConfigTest.cpp
Labels: ready-for-testing

#3315 fix index existence check
  src/meta/processors/BaseProcessor-inl.h
  src/meta/test/IndexProcessorTest.cpp
  tests/tck/features/index/Index.feature
Labels: ready-for-testing

#3311 fix index degeneration
  src/graph/optimizer/rule/IndexScanRule.cpp
  tests/tck/features/match/IndexSelecting.feature
Labels: ready-for-testing

#3139 Lookup subgraph format yield
  src/graph/validator/GetSubgraphValidator.cpp
  src/graph/validator/LookupValidator.cpp
  src/graph/validator/test/GetSubgraphValidatorTest.cpp
  src/graph/validator/test/LookupValidatorTest.cpp
  tests/tck/features/bugfix/TruncatedStringIndex.feature
  tests/tck/features/delete/DeleteTag.IntVid.feature
  tests/tck/features/delete/DeleteTag.feature
  tests/tck/features/geo/GeoBase.feature
  tests/tck/features/index/Index.IntVid.feature
  tests/tck/features/index/Index.feature
  tests/tck/features/index/TagEdgeIndex.feature
  tests/tck/features/insert/Insert.feature
  tests/tck/features/lookup/ByIndex.feature
  tests/tck/features/lookup/ByIndex.intVid.feature
  tests/tck/features/lookup/EdgeIndexFullScan.feature
  tests/tck/features/lookup/LookUp.IntVid.feature
  tests/tck/features/lookup/LookUp.feature
  tests/tck/features/lookup/LookUpLimit.feature
  tests/tck/features/lookup/LookupEdge.feature
  tests/tck/features/lookup/LookupEdge2.feature
  tests/tck/features/lookup/LookupTag.feature
  tests/tck/features/lookup/LookupTag2.feature
  tests/tck/features/lookup/Output.feature
  tests/tck/features/lookup/Output.intVid.feature
  tests/tck/features/lookup/TagIndexFullScan.feature
  tests/tck/features/lookup/WithYield.feature
  tests/tck/features/lookup/WithYield.intVid.feature
  tests/tck/features/optimizer/CollapseProjectRule.feature
  tests/tck/features/optimizer/PushFilterDownLeftJoinRule.feature
  tests/tck/features/schema/CreateSpaceAs.feature
  tests/tck/features/subgraph/subgraph.IntVid.feature
  tests/tck/features/subgraph/subgraph.feature
Labels: ready-for-testing, incompatible, doc affected

#3053 optimize rewrite visitor
  src/graph/validator/GroupByValidator.cpp
  src/graph/validator/MatchValidator.cpp
  src/graph/visitor/RewriteVisitor.cpp
Labels: ready-for-testing

#3347 fix meta follower read remaining jobs
  src/meta/processors/job/JobManager.cpp
Labels: ready-for-testing

#3330 Remove group relevant component
  src/clients/meta/MetaClient.cpp
  src/clients/meta/MetaClient.h
  src/graph/executor/CMakeLists.txt
  src/graph/executor/Executor.cpp
  src/graph/executor/admin/GroupExecutor.cpp
  src/graph/executor/admin/GroupExecutor.h
  src/graph/planner/plan/Admin.h
  src/graph/planner/plan/PlanNode.cpp
  src/graph/planner/plan/PlanNode.h
  src/graph/service/PermissionCheck.cpp
  src/graph/validator/MaintainValidator.cpp
  src/graph/validator/MaintainValidator.h
  src/graph/validator/Validator.cpp
  src/interface/meta.thrift
  src/meta/CMakeLists.txt
  src/meta/MetaServiceHandler.cpp
  src/meta/MetaServiceHandler.h
  src/meta/processors/zone/AddGroupProcessor.cpp
  src/meta/processors/zone/AddGroupProcessor.h
  src/meta/processors/zone/DropGroupProcessor.cpp
  src/meta/processors/zone/DropGroupProcessor.h
  src/meta/processors/zone/GetGroupProcessor.cpp
  src/meta/processors/zone/GetGroupProcessor.h
  src/meta/processors/zone/ListGroupsProcessor.cpp
  src/meta/processors/zone/ListGroupsProcessor.h
  src/meta/processors/zone/UpdateGroupProcessor.cpp
  src/meta/processors/zone/UpdateGroupProcessor.h
  src/meta/test/GroupZoneTest.cpp
  src/meta/test/MetaClientTest.cpp
  src/meta/test/ProcessorTest.cpp
  src/parser/MaintainSentences.cpp
  src/parser/MaintainSentences.h
  src/parser/Sentence.h
  src/parser/parser.yy
  src/parser/test/ParserTest.cpp
  tests/maintain/test_zone.py
Labels: ready-for-testing, incompatible, doc affected

#3271 disable yield var
  src/graph/optimizer/rule/TopNRule.cpp
  src/graph/util/ExpressionUtils.cpp
  src/graph/util/ExpressionUtils.h
  src/parser/parser.yy
  tests/tck/features/bugfix/VariableExpression.feature
  tests/tck/features/go/GroupbyLimit.IntVid.feature
  tests/tck/features/go/GroupbyLimit.feature
Labels: ready-for-testing, incompatible, doc affected

#3329 Support filter in scan.
  src/storage/context/StorageExpressionContext.h
  src/storage/exec/ScanNode.h
  src/storage/query/GetNeighborsProcessor.cpp
  src/storage/query/QueryBaseProcessor-inl.h
  src/storage/query/QueryBaseProcessor.h
  src/storage/query/ScanEdgeProcessor.cpp
  src/storage/query/ScanEdgeProcessor.h
  src/storage/query/ScanVertexProcessor.cpp
  src/storage/query/ScanVertexProcessor.h
  src/storage/test/ScanEdgeTest.cpp
  src/storage/test/ScanVertexTest.cpp
  src/storage/test/UpdateEdgeTest.cpp
Labels: ready-for-testing

#3322 [Raft] Add prevote to make it better
  src/interface/raftex.thrift
  src/kvstore/Listener.cpp
  src/kvstore/raftex/RaftPart.cpp
  src/kvstore/raftex/RaftPart.h
Labels: ready-for-testing

#3300 describe the user
  src/graph/executor/CMakeLists.txt
  src/graph/executor/Executor.cpp
  src/graph/executor/admin/DescribeUserExecutor.cpp
  src/graph/executor/admin/DescribeUserExecutor.h
  src/graph/planner/plan/Admin.cpp
  src/graph/planner/plan/Admin.h
  src/graph/planner/plan/PlanNode.cpp
  src/graph/planner/plan/PlanNode.h
  src/graph/service/PermissionCheck.cpp
  src/graph/service/PermissionManager.cpp
  src/graph/service/PermissionManager.h
  src/graph/validator/ACLValidator.cpp
  src/graph/validator/ACLValidator.h
  src/graph/validator/Validator.cpp
  src/parser/AdminSentences.cpp
  src/parser/AdminSentences.h
  src/parser/Sentence.h
  src/parser/parser.yy
  tests/tck/conftest.py
  tests/tck/features/user/User.feature
Labels: ready-for-testing, doc affected

#3351 [fix] can't show edge after clone space
  src/meta/processors/parts/CreateSpaceAsProcessor.cpp
  tests/tck/features/schema/CreateSpaceAs.feature
Labels: ready-for-testing

#3282 enable kv interface in 2.0
  src/clients/storage/CMakeLists.txt
  src/clients/storage/GeneralStorageClient.cpp
  src/clients/storage/GeneralStorageClient.h
  src/clients/storage/StorageClient.cpp
  src/clients/storage/StorageClient.h
  src/daemons/CMakeLists.txt
  src/graph/context/QueryContext.cpp
  src/graph/context/QueryContext.h
  src/graph/executor/mutate/DeleteExecutor.cpp
  src/graph/executor/mutate/InsertExecutor.cpp
  src/graph/executor/mutate/UpdateExecutor.cpp
  src/graph/executor/query/AppendVerticesExecutor.cpp
  src/graph/executor/query/GetEdgesExecutor.cpp
  src/graph/executor/query/GetNeighborsExecutor.cpp
  src/graph/executor/query/GetVerticesExecutor.cpp
  src/graph/executor/query/IndexScanExecutor.cpp
  src/graph/executor/query/IndexScanExecutor.h
  src/graph/executor/query/TraverseExecutor.cpp
  src/graph/executor/query/TraverseExecutor.h
  src/graph/executor/test/CMakeLists.txt
  src/graph/planner/test/CMakeLists.txt
  src/graph/service/GraphService.cpp
  src/graph/service/QueryEngine.cpp
  src/graph/service/QueryEngine.h
  src/interface/CMakeLists.txt
  src/interface/storage.thrift
  src/meta/CMakeLists.txt
  src/mock/MockCluster.cpp
  src/mock/MockCluster.h
  src/storage/CMakeLists.txt
  src/storage/CompactionFilter.h
  src/storage/GeneralStorageServiceHandler.cpp
  src/storage/GeneralStorageServiceHandler.h
  src/storage/GraphStorageServiceHandler.cpp
  src/storage/GraphStorageServiceHandler.h
  src/storage/StorageServer.cpp
  src/storage/test/CMakeLists.txt
  src/storage/test/KVClientTest.cpp
  src/storage/test/KVTest.cpp
  src/storage/test/StorageClientTest.cpp
  src/storage/test/StorageLookupBenchmark.cpp
  src/storage/test/TossTestExecutor.h
  src/storage/test/TossTestUtils.h
  src/tools/CMakeLists.txt
  src/tools/simple-kv-verify/CMakeLists.txt
  src/tools/simple-kv-verify/SimpleKVVerifyTool.cpp
  src/tools/storage-perf/CMakeLists.txt
  src/tools/storage-perf/StorageIntegrityTool.cpp
  src/tools/storage-perf/StoragePerfTool.cpp
Labels: ready-for-testing

#3336 add rpc to query raft status
  src/interface/raftex.thrift
  src/kvstore/raftex/RaftPart.cpp
  src/kvstore/raftex/RaftPart.h
  src/kvstore/raftex/RaftexService.cpp
  src/kvstore/raftex/RaftexService.h
Labels: new feature, ready-for-testing

#3355 report error when use agg in where clause
  src/graph/validator/YieldValidator.cpp
  tests/tck/features/yield/yield.IntVid.feature
  tests/tck/features/yield/yield.feature
Labels: ready-for-testing, bug

#3314 fix - tck contains is invalid
  tests/common/comparator.py
  tests/tck/features/admin/Hosts.feature
  tests/tck/features/index/TagEdgeIndex.feature
Labels: ready-for-testing

#3358 [fix] storage may stuck, if we have kvstore operation while shutdown cluster
  src/kvstore/NebulaStore.cpp
  src/kvstore/raftex/RaftexService.cpp
Labels: ready-for-testing, bug

#3371 Update README.md
  README.md
Labels: ready-for-testing

#3302 support gql list/set/map
  .linters/cpp/checkKeyword.py
  src/common/expression/ContainerExpression.cpp
  src/graph/validator/test/YieldValidatorTest.cpp
  src/parser/parser.yy
  src/parser/scanner.lex
  src/parser/test/ParserTest.cpp
  tests/tck/features/basic/data.feature
  tests/tck/features/expression/ListComprehension.feature
  tests/tck/openCypher/features/expressions/list/List2.feature
  tests/tck/openCypher/features/expressions/map/Map1.feature
Labels: ready-for-testing, incompatible, doc affected

#3266 tck test cluster
  tests/README.md
  tests/common/constants.py
  tests/common/nebula_service.py
  tests/common/utils.py
  tests/conftest.py
  tests/nebula-test-run.py
  tests/tck/cluster/Example.feature
  tests/tck/cluster/terminate.feature
  tests/tck/conftest.py
  tests/tck/features/optimizer/PushSampleDownRule.feature
  tests/tck/steps/test_cluster.py
Labels: ready-for-testing

#3382 [Minor] Check the result of listHosts()
  src/clients/meta/MetaClient.cpp
Labels: ready-for-testing, bug
