Repository vesoft-inc/nebula, pull requests merged in 2021-08, with the labels that each got.

#2487 Fix lint error
  .github/workflows/pull_request.yml
  src/daemons/CMakeLists.txt
  src/daemons/GraphDaemon.cpp
  src/graph/service/GraphFlags.cpp
Labels: ready-for-testing

#2491 fix script nebula.service
  scripts/nebula.service
Labels: ready-for-testing

#2489 Fix links in README
  .github/workflows/nightly.yml
  README-CN.md
  README.md
Labels: ready-for-testing

#2502 Fix package script
  README.md
  cmake/ThriftGenerate.cmake
  package/CMakeLists.txt
  package/package.sh
Labels: ready-for-testing

#2504 Rename inline headers
  .linters/cpp/hooks/pre-commit.sh
  src/clients/storage/StorageClientBase-inl.h
  src/clients/storage/StorageClientBase.h
  src/codec/test/RowWriterV1-inl.h
  src/codec/test/RowWriterV1.h
  src/common/base/CollectNSucceeded-inl.h
  src/common/base/CollectNSucceeded.h
  src/common/datatypes/DataSetOps-inl.h
  src/common/datatypes/DateOps-inl.h
  src/common/datatypes/EdgeOps-inl.h
  src/common/datatypes/HostAddrOps-inl.h
  src/common/datatypes/KeyValueOps-inl.h
  src/common/datatypes/ListOps-inl.h
  src/common/datatypes/MapOps-inl.h
  src/common/datatypes/PathOps-inl.h
  src/common/datatypes/SetOps-inl.h
  src/common/datatypes/ValueOps-inl.h
  src/common/datatypes/VertexOps-inl.h
  src/common/expression/Expression.cpp
  src/common/graph/AuthResponseOps-inl.h
  src/common/graph/ExecutionResponseOps-inl.h
  src/common/graph/PairOps-inl.h
  src/common/graph/PlanDescriptionOps-inl.h
  src/common/graph/PlanNodeBranchInfoOps-inl.h
  src/common/graph/PlanNodeDescriptionOps-inl.h
  src/common/graph/ProfilingStatsOps-inl.h
  src/common/stats/StatsManager-inl.h
  src/common/stats/StatsManager.h
  src/common/thrift/ThriftClientManager-inl.h
  src/common/thrift/ThriftClientManager.h
  src/interface/common.thrift
  src/interface/graph.thrift
  src/kvstore/LogEncoder.cpp
  src/meta/processors/BaseProcessor-inl.h
  src/meta/processors/BaseProcessor.h
  src/storage/BaseProcessor-inl.h
  src/storage/BaseProcessor.h
  src/storage/index/LookupBaseProcessor-inl.h
  src/storage/index/LookupBaseProcessor.h
  src/storage/query/QueryBaseProcessor-inl.h
  src/storage/query/QueryBaseProcessor.h
Labels: ready-for-testing

#2490 Move the rfcs to folder from issues.
  docs/rfcs/0000-template.md
Labels: ready-for-testing

#2510 Delete AliasPropertyExpression introduced in merging repos
  src/common/expression/AliasPropertyExpression.cpp
  src/common/expression/AliasPropertyExpression.h
Labels: ready-for-testing

#2516 Fix Dockerfiles for building docker images
  .github/workflows/pull_request.yml
  docker/Dockerfile
  docker/Dockerfile.metad
  docker/Dockerfile.storaged
  docker/Dockerfile.tools
Labels: ready-for-testing

#2486 Delete useless README files
  docker/README.md
  src/README.md
  src/clients/graph/README.md
  src/codec/README.md
  src/common/utils/README.md
  src/daemons/README.md
  src/interface/README.md
  src/kvstore/README.md
  src/kvstore/raftex/README.md
  src/meta/README.md
  src/parser/README.md
  src/parser/test/fuzzing/README.md
Labels: ready-for-testing

#2517 Upgrade clang from 9.0.0 to 10.0.0
  .clang-format
  .github/workflows/pull_request.yml
  CMakeLists.txt
  src/common/datatypes/DataSetOps-inl.h
  src/common/datatypes/DateOps-inl.h
  src/common/datatypes/EdgeOps-inl.h
  src/common/datatypes/HostAddrOps-inl.h
  src/common/datatypes/KeyValueOps-inl.h
  src/common/datatypes/ListOps-inl.h
  src/common/datatypes/MapOps-inl.h
  src/common/datatypes/PathOps-inl.h
  src/common/datatypes/SetOps-inl.h
  src/common/datatypes/VertexOps-inl.h
  src/common/graph/AuthResponseOps-inl.h
  src/common/graph/ExecutionResponseOps-inl.h
  src/common/graph/PairOps-inl.h
  src/common/graph/PlanDescriptionOps-inl.h
  src/common/graph/PlanNodeBranchInfoOps-inl.h
  src/common/graph/PlanNodeDescriptionOps-inl.h
  src/common/graph/ProfilingStatsOps-inl.h
Labels: ready-for-testing

#2521 Fix clang format check
  .github/workflows/pull_request.yml
Labels: ready-for-testing

#2492 Rename graph context object target
  src/daemons/CMakeLists.txt
  src/graph/context/CMakeLists.txt
  src/graph/context/test/CMakeLists.txt
  src/graph/executor/test/CMakeLists.txt
  src/graph/optimizer/test/CMakeLists.txt
  src/graph/planner/test/CMakeLists.txt
  src/graph/util/test/CMakeLists.txt
  src/graph/validator/test/CMakeLists.txt
  src/graph/visitor/test/CMakeLists.txt
  src/parser/test/CMakeLists.txt
Labels: ready-for-testing

#2500 Remove useless common and storage cmake configuration
  cmake/ConfigNebulaStorage.cmake
  cmake/nebula/ConfigNebulaCommon.cmake
Labels: ready-for-testing

#2488 Small improvement to daemons compilation.
  src/daemons/CMakeLists.txt
Labels: ready-for-testing

#2524 Install metad configure files
  conf/CMakeLists.txt
  scripts/CMakeLists.txt
  src/graph/context/ExecutionContext.h
Labels: ready-for-testing

#2520 delete tag
  src/graph/executor/Executor.cpp
  src/graph/executor/mutate/DeleteExecutor.cpp
  src/graph/executor/mutate/DeleteExecutor.h
  src/graph/planner/plan/Mutate.cpp
  src/graph/planner/plan/Mutate.h
  src/graph/planner/plan/PlanNode.cpp
  src/graph/planner/plan/PlanNode.h
  src/graph/service/PermissionCheck.cpp
  src/graph/validator/MutateValidator.cpp
  src/graph/validator/MutateValidator.h
  src/graph/validator/Validator.cpp
  src/parser/MutateSentences.cpp
  src/parser/MutateSentences.h
  src/parser/Sentence.h
  src/parser/parser.yy
  src/parser/test/ParserTest.cpp
  tests/tck/features/delete/DeleteTag.IntVid.feature
  tests/tck/features/delete/DeleteTag.feature
Labels: ready-for-testing, doc affected

#2527 Fix the error which insert mismatched datetime type.
  src/codec/RowWriterV2.cpp
  tests/tck/features/bugfix/InsertMismatchedTypeDateTime.feature
  tests/tck/features/bugfix/TimeDefaultValue.feature
Labels: ready-for-testing, bug

#2522 [raft] clean part rocksdb data when raftpart::reset
  src/common/utils/NebulaKeyUtils.cpp
  src/common/utils/NebulaKeyUtils.h
  src/kvstore/NebulaStore.cpp
  src/kvstore/Part.cpp
  src/kvstore/Part.h
  src/kvstore/test/PartTest.cpp
Labels: ready-for-testing

#2523 Check the code format before commit.
  .linters/cpp/hooks/pre-commit.sh
Labels: ready-for-testing

#2528 Cleanup package workflow
  .linters/cpp/hooks/pre-commit.sh
  CMakeLists.txt
  package/CMakeLists.txt
  package/package.sh
  resources/CMakeLists.txt
  src/daemons/CMakeLists.txt
  src/graph/optimizer/OptimizerUtils.h
  src/tools/db-dump/CMakeLists.txt
  src/tools/db-upgrade/CMakeLists.txt
  src/tools/meta-dump/CMakeLists.txt
Labels: ready-for-testing

#2485 add a callback register interface of Part
  src/kvstore/Part.cpp
  src/kvstore/Part.h
Labels: ready-for-testing

#2540 add concat & concat_ws
  src/common/function/FunctionManager.cpp
  src/common/function/FunctionManager.h
  src/common/function/test/FunctionManagerTest.cpp
  tests/tck/features/expression/FunctionCall.feature
Labels: ready-for-testing, doc affected

#2538 Fix codec namespace
  src/codec/NebulaCodecImpl.cpp
  src/codec/NebulaCodecImpl.h
  src/codec/include/NebulaCodec.h
  src/codec/test/NebulaCodecTest.cpp
  src/kvstore/plugins/hbase/HBaseStore.cpp
  src/kvstore/plugins/hbase/test/CMakeLists.txt
  src/meta/test/CMakeLists.txt
Labels: ready-for-testing

#2549 Fix parsing scientific notation string and add UTs
  src/common/datatypes/Value.cpp
  src/common/datatypes/test/ValueTest.cpp
  tests/tck/features/expression/function/TypeConversion.feature
Labels: ready-for-testing

#2543 Test Dep PyYAML update
  tests/requirements.txt
Labels: ready-for-testing

#2552 add failed piped fetch clause test case
  tests/tck/features/fetch/FetchVertices.intVid.feature
  tests/tck/features/fetch/FetchVertices.strVid.feature
Labels: ready-for-testing

#2550 use local id in the space range for tag edge index
  src/meta/MetaServiceUtils.cpp
  src/meta/MetaServiceUtils.h
  src/meta/processors/BaseProcessor-inl.h
  src/meta/processors/BaseProcessor.h
  src/meta/processors/Common.h
  src/meta/processors/index/CreateEdgeIndexProcessor.cpp
  src/meta/processors/index/CreateTagIndexProcessor.cpp
  src/meta/processors/parts/DropSpaceProcessor.cpp
  src/meta/processors/schema/CreateEdgeProcessor.cpp
  src/meta/processors/schema/CreateTagProcessor.cpp
  src/meta/test/IndexProcessorTest.cpp
  src/meta/test/ProcessorTest.cpp
  src/meta/test/TestUtils.h
Labels: ready-for-testing

#2570 [migrate #1314]fix the wrong usage of limit sentence
  src/graph/validator/OrderByValidator.cpp
  src/graph/validator/OrderByValidator.h
  src/graph/validator/SequentialValidator.cpp
  src/parser/parser.yy
  tests/tck/features/fetch/FetchVertices.intVid.feature
  tests/tck/features/fetch/FetchVertices.strVid.feature
  tests/tck/features/go/GroupbyLimit.feature
  tests/tck/features/go/Orderby.feature
  tests/tck/features/lookup/ByIndex.feature
  tests/tck/features/lookup/ByIndex.intVid.feature
  tests/tck/features/optimizer/TopNRule.feature
Labels: ready-for-testing

#2513 Ignore some path don't impact workflow.
  .github/workflows/pull_request.yml
Labels: ready-for-testing

#2567 used input host as clientMap key, instead of the resloved host
  src/common/thrift/ThriftClientManager-inl.h
Labels: ready-for-testing

#2577 improve show stats display when stats info is empty
  src/clients/meta/MetaClient.cpp
  src/interface/common.thrift
  src/meta/processors/job/GetStatsProcessor.cpp
Labels: ready-for-testing

#2581 Cherry-pick PR from v2.5.0
  .github/workflows/pull_request.yml
  src/clients/meta/MetaClient.cpp
  src/clients/meta/MetaClient.h
  src/interface/meta.thrift
  src/meta/CMakeLists.txt
  src/meta/MetaServiceUtils.cpp
  src/meta/processors/admin/HBProcessor.cpp
  src/meta/processors/admin/HBProcessor.h
  src/meta/test/HBProcessorTest.cpp
  src/meta/test/RestoreProcessorTest.cpp
  src/storage/admin/RebuildEdgeIndexTask.cpp
  src/storage/admin/RebuildTagIndexTask.cpp
  src/storage/test/CMakeLists.txt
  src/tools/db-dump/CMakeLists.txt
  src/tools/db-upgrade/CMakeLists.txt
  src/tools/meta-dump/CMakeLists.txt
  src/tools/simple-kv-verify/CMakeLists.txt
  src/tools/storage-perf/CMakeLists.txt
Labels: ready-for-testing
