Repository vesoft-inc/nebula, pull requests merged in 2022-10, with the labels that each got.

#4357 subgraph filter
  src/graph/context/ExecutionContext.cpp
  src/graph/context/ExecutionContext.h
  src/graph/context/Iterator.cpp
  src/graph/context/Iterator.h
  src/graph/context/ast/QueryAstContext.h
  src/graph/executor/algo/SubgraphExecutor.cpp
  src/graph/executor/algo/SubgraphExecutor.h
  src/graph/executor/query/DataCollectExecutor.cpp
  src/graph/planner/ngql/SubgraphPlanner.cpp
  src/graph/planner/ngql/SubgraphPlanner.h
  src/graph/planner/plan/Algo.cpp
  src/graph/planner/plan/Algo.h
  src/graph/validator/GetSubgraphValidator.cpp
  src/graph/validator/GetSubgraphValidator.h
  src/graph/validator/test/GetSubgraphValidatorTest.cpp
  src/graph/visitor/ExtractFilterExprVisitor.cpp
  src/graph/visitor/ExtractFilterExprVisitor.h
  src/interface/storage.thrift
  src/parser/TraverseSentences.cpp
  src/parser/TraverseSentences.h
  src/parser/parser.yy
  src/storage/exec/GetNeighborsNode.h
  tests/tck/features/subgraph/subgraphWithFilter.feature
Labels: ready-for-testing, doc affected, ready for review

#4683 change time point calculate in ttl
  src/mock/MockData.cpp
  src/storage/CommonUtils.cpp
  src/storage/test/IndexWithTTLTest.cpp
  src/storage/test/QueryTestUtils.h
Labels: ready-for-testing

#4698 fix subgraph crash
  src/graph/context/Iterator.cpp
  src/graph/context/test/IteratorTest.cpp
Labels: ready-for-testing, ready for review, cherry-pick-v3.3

#4701 fix_ambiguous_case
  tests/tck/features/optimizer/PrunePropertiesRule.feature
Labels: ready-for-testing, ready for review

#4707 fix map hash method
  src/common/datatypes/Map.cpp
  src/common/datatypes/test/ValueTest.cpp
  tests/tck/features/go/GO.feature
Labels: ready-for-testing

#4695 Cherry pick 3.3.0 (1008-1011）
  src/common/datatypes/Map.cpp
  src/common/datatypes/test/ValueTest.cpp
  src/graph/context/Iterator.cpp
  src/graph/context/ast/QueryAstContext.h
  src/graph/context/test/IteratorTest.cpp
  src/graph/executor/query/GetDstBySrcExecutor.h
  src/graph/planner/ngql/GoPlanner.cpp
  src/graph/planner/ngql/GoPlanner.h
  src/graph/visitor/DeducePropsVisitor.h
  src/mock/MockData.cpp
  src/storage/CommonUtils.cpp
  src/storage/test/IndexWithTTLTest.cpp
  src/storage/test/QueryTestUtils.h
  tests/tck/features/go/GO.feature
  tests/tck/features/go/SimpleCase.feature
  tests/tck/features/optimizer/PrunePropertiesRule.feature
Labels: ready-for-testing

#4716 Use vertex key only when use_vertex_key is on
  docker/README.md
  src/common/utils/NebulaKeyUtils.cpp
  src/graph/service/GraphFlags.cpp
  src/graph/service/GraphFlags.h
  src/graph/validator/MutateValidator.cpp
  src/storage/exec/GetPropNode.h
  src/storage/exec/UpdateNode.h
  src/storage/mutate/AddVerticesProcessor.cpp
  src/tools/CMakeLists.txt
  src/tools/db-upgrade/CMakeLists.txt
  src/tools/db-upgrade/DbUpgrader.cpp
  src/tools/db-upgrade/DbUpgrader.h
  src/tools/db-upgrade/DbUpgraderTool.cpp
  src/tools/db-upgrade/NebulaKeyUtilsV1.cpp
  src/tools/db-upgrade/NebulaKeyUtilsV1.h
  src/tools/db-upgrade/NebulaKeyUtilsV2.cpp
  src/tools/db-upgrade/NebulaKeyUtilsV2.h
  src/tools/db-upgrade/NebulaKeyUtilsV3.cpp
  src/tools/db-upgrade/NebulaKeyUtilsV3.h
  tests/tck/features/delete/DeleteTag.IntVid.feature
  tests/tck/features/delete/DeleteTag.feature
  tests/tck/features/go/GO.IntVid.feature
  tests/tck/features/go/GO.feature
  tests/tck/features/go/GoYieldVertexEdge.feature
  tests/tck/features/insert/insertVertexOnly.feature
  tests/tck/features/match/MatchById.IntVid.feature
  tests/tck/features/match/SeekByEdge.feature
  tests/tck/features/match/With.feature
  tests/tck/features/ttl/TTL.feature
Labels: ready-for-testing

#4717 fix job status when all finished
  src/graph/executor/admin/SubmitJobExecutor.cpp
Labels: ready-for-testing

#4705 Fix if-not-exists behavior of create index statements
  src/meta/processors/index/CreateEdgeIndexProcessor.cpp
  src/meta/processors/index/CreateTagIndexProcessor.cpp
  tests/tck/features/index/Index.feature
Labels: ready-for-testing, ready for review

#4720 Cherry pick 3.3.0 (10.13)
  docker/README.md
  src/common/utils/NebulaKeyUtils.cpp
  src/graph/executor/admin/SubmitJobExecutor.cpp
  src/graph/service/GraphFlags.cpp
  src/graph/service/GraphFlags.h
  src/graph/validator/MutateValidator.cpp
  src/meta/processors/index/CreateEdgeIndexProcessor.cpp
  src/meta/processors/index/CreateTagIndexProcessor.cpp
  src/storage/exec/GetPropNode.h
  src/storage/exec/UpdateNode.h
  src/storage/mutate/AddVerticesProcessor.cpp
  src/tools/CMakeLists.txt
  src/tools/db-upgrade/CMakeLists.txt
  src/tools/db-upgrade/DbUpgrader.cpp
  src/tools/db-upgrade/DbUpgrader.h
  src/tools/db-upgrade/DbUpgraderTool.cpp
  src/tools/db-upgrade/NebulaKeyUtilsV1.cpp
  src/tools/db-upgrade/NebulaKeyUtilsV1.h
  src/tools/db-upgrade/NebulaKeyUtilsV2.cpp
  src/tools/db-upgrade/NebulaKeyUtilsV2.h
  src/tools/db-upgrade/NebulaKeyUtilsV3.cpp
  src/tools/db-upgrade/NebulaKeyUtilsV3.h
  tests/tck/features/delete/DeleteTag.IntVid.feature
  tests/tck/features/delete/DeleteTag.feature
  tests/tck/features/go/GO.IntVid.feature
  tests/tck/features/go/GO.feature
  tests/tck/features/go/GoYieldVertexEdge.feature
  tests/tck/features/index/Index.feature
  tests/tck/features/insert/insertVertexOnly.feature
  tests/tck/features/match/MatchById.IntVid.feature
  tests/tck/features/match/SeekByEdge.feature
  tests/tck/features/match/With.feature
  tests/tck/features/ttl/TTL.feature
Labels: ready-for-testing

#4706 Fix aggregate expression type deduce
  src/graph/validator/test/YieldValidatorTest.cpp
  src/graph/visitor/DeduceTypeVisitor.cpp
  tests/tck/features/go/GO.feature
Labels: ready-for-testing, ready for review

#4723 fix hdfs download command will always return succeeded sometimes
  src/common/hdfs/HdfsCommandHelper.cpp
Labels: ready-for-testing, cherry-pick-v3.3

#4722 remove rebuild index guard when job finished
  src/storage/admin/RebuildIndexTask.cpp
  src/storage/admin/RebuildIndexTask.h
Labels: ready-for-testing, cherry-pick-v3.3

#4728 split experimental_feature flag
  conf/nebula-graphd.conf.default
  conf/nebula-graphd.conf.production
  conf/nebula-standalone.conf.default
  src/graph/executor/mutate/DeleteExecutor.cpp
  src/graph/executor/mutate/InsertExecutor.cpp
  src/graph/executor/mutate/UpdateExecutor.cpp
  src/graph/service/GraphFlags.cpp
  src/graph/service/GraphFlags.h
  src/graph/validator/AdminJobValidator.cpp
  src/graph/validator/MutateValidator.cpp
Labels: ready-for-testing

#4727 forbid insert vertex when vertex_key flag is off
  src/graph/service/GraphFlags.cpp
  src/graph/service/GraphFlags.h
  src/graph/validator/MutateValidator.cpp
  src/storage/exec/GetPropNode.h
  src/storage/query/GetPropProcessor.cpp
  tests/tck/features/delete/DeleteTag.IntVid.feature
  tests/tck/features/insert/insertVertexOnly.feature
  tests/tck/features/match/Base.feature
  tests/tck/features/ttl/TTL.feature
Labels: ready-for-testing, cherry-pick-v3.3

#4735 Cherry pick 3.3 (1013-1017)
  conf/nebula-graphd.conf.default
  conf/nebula-graphd.conf.production
  conf/nebula-standalone.conf.default
  src/common/hdfs/HdfsCommandHelper.cpp
  src/graph/executor/mutate/DeleteExecutor.cpp
  src/graph/executor/mutate/InsertExecutor.cpp
  src/graph/executor/mutate/UpdateExecutor.cpp
  src/graph/service/GraphFlags.cpp
  src/graph/service/GraphFlags.h
  src/graph/validator/AdminJobValidator.cpp
  src/graph/validator/MutateValidator.cpp
  src/graph/validator/test/YieldValidatorTest.cpp
  src/graph/visitor/DeduceTypeVisitor.cpp
  src/storage/admin/RebuildIndexTask.cpp
  src/storage/admin/RebuildIndexTask.h
  src/storage/exec/GetPropNode.h
  src/storage/query/GetPropProcessor.cpp
  tests/tck/features/delete/DeleteTag.IntVid.feature
  tests/tck/features/go/GO.feature
  tests/tck/features/insert/insertVertexOnly.feature
  tests/tck/features/match/Base.feature
  tests/tck/features/ttl/TTL.feature
Labels: ready-for-testing

#4736 fix dep of loop in go planner
  src/graph/planner/ngql/GoPlanner.cpp
  tests/tck/features/go/SimpleCase.feature
Labels: ready-for-testing, cherry-pick-v3.3

#4737 fix inappropriate error code from raft
  src/kvstore/raftex/RaftPart.cpp
Labels: ready-for-testing, ready for review, cherry-pick-v3.3

#4724 Fix variable types collected and graph crash
  src/graph/planner/match/MatchPlanner.cpp
  tests/tck/features/match/MultiLineMultiQueryParts.feature
  tests/tck/ldbc/business_intelligence_workload/Read.feature
Labels: ready-for-testing, doc affected, ready for review, cherry-pick-v3.3

#4738 stats handle the flag use_vertex_key, and JobManager Related fix
  src/storage/admin/StatsTask.cpp
Labels: ready-for-testing, ready for review, cherry-pick-v3.3

#4742 JobManager related fix
  src/clients/meta/MetaClient.cpp
  src/interface/common.thrift
  src/meta/processors/job/JobManager.cpp
  src/meta/processors/job/StorageJobExecutor.cpp
  src/meta/test/GetStatsTest.cpp
  src/meta/test/JobManagerTest.cpp
Labels: ready-for-testing, ready for review, cherry-pick-v3.3

#4754 download job related fix
  src/common/hdfs/HdfsCommandHelper.cpp
  src/kvstore/RocksEngine.cpp
  src/kvstore/test/RocksEngineTest.cpp
  src/storage/admin/DownloadTask.cpp
Labels: ready-for-testing, ready for review, cherry-pick-v3.3

#4744 fixed case-when error
  src/graph/visitor/PropertyTrackerVisitor.cpp
  tests/tck/features/expression/Case.feature
Labels: ready-for-testing

#4750 Refine go planner
  src/graph/context/ast/QueryAstContext.h
  src/graph/planner/ngql/GoPlanner.cpp
  src/graph/planner/ngql/GoPlanner.h
  src/graph/validator/GoValidator.cpp
  src/graph/validator/GoValidator.h
  tests/tck/conftest.py
  tests/tck/features/go/SimpleCase.feature
Labels: ready-for-testing, ready for review

#4761 Cherry pick 3.3 （1017-1020）
  src/clients/meta/MetaClient.cpp
  src/common/hdfs/HdfsCommandHelper.cpp
  src/graph/context/ast/QueryAstContext.h
  src/graph/planner/match/MatchPlanner.cpp
  src/graph/planner/ngql/GoPlanner.cpp
  src/graph/planner/ngql/GoPlanner.h
  src/graph/validator/GoValidator.cpp
  src/graph/validator/GoValidator.h
  src/graph/visitor/PropertyTrackerVisitor.cpp
  src/interface/common.thrift
  src/kvstore/RocksEngine.cpp
  src/kvstore/raftex/RaftPart.cpp
  src/kvstore/test/RocksEngineTest.cpp
  src/meta/processors/job/JobManager.cpp
  src/meta/processors/job/StorageJobExecutor.cpp
  src/meta/test/GetStatsTest.cpp
  src/meta/test/JobManagerTest.cpp
  src/storage/admin/DownloadTask.cpp
  src/storage/admin/StatsTask.cpp
  tests/tck/conftest.py
  tests/tck/features/expression/Case.feature
  tests/tck/features/go/SimpleCase.feature
  tests/tck/features/match/MultiLineMultiQueryParts.feature
  tests/tck/ldbc/business_intelligence_workload/Read.feature
Labels: ready-for-testing

#4759 logging error if any error in step
  tests/conftest.py
  tests/tck/conftest.py
Labels: ready-for-testing

#4762 fix storage job
  src/meta/processors/job/StorageJobExecutor.h
Labels: ready-for-testing

#4726 chore: polishing readme
  README-CN.md
  README.md
Labels: ready-for-testing

#4748 Avoid full scan of match when there is an Relational In predicate
  src/common/expression/ContainerExpression.h
  src/graph/util/ExpressionUtils.cpp
  src/graph/util/ExpressionUtils.h
  src/graph/validator/MatchValidator.cpp
  tests/tck/features/match/IndexSelecting.feature
Labels: ready-for-testing, ready for review

#4772 Cherry pick 3.3 (1020-1021)
  src/common/expression/ContainerExpression.h
  src/graph/planner/ngql/GoPlanner.cpp
  src/graph/util/ExpressionUtils.cpp
  src/graph/util/ExpressionUtils.h
  src/graph/validator/GoValidator.cpp
  src/graph/validator/MatchValidator.cpp
  src/meta/processors/job/StorageJobExecutor.h
  tests/conftest.py
  tests/tck/conftest.py
  tests/tck/features/go/SimpleCase.feature
  tests/tck/features/match/IndexSelecting.feature
Labels: ready-for-testing

#4771 Fix/find start error
  src/graph/planner/match/ArgumentFinder.h
  src/graph/planner/match/LabelIndexSeek.cpp
  src/graph/planner/match/LabelIndexSeek.h
  src/graph/planner/match/PropIndexSeek.h
  src/graph/planner/match/ScanSeek.h
  src/graph/planner/match/StartVidFinder.h
  src/graph/planner/match/VertexIdSeek.h
  tests/tck/features/bugfix/FindStartError.feature
Labels: ready-for-testing, cherry-pick-v3.3

#4743 Introduce JSON_EXTRACT function
  src/common/datatypes/Map.cpp
  src/common/datatypes/Map.h
  src/common/function/FunctionManager.cpp
  src/common/function/test/FunctionManagerTest.cpp
  tests/tck/features/function/coalesce.feature
  tests/tck/features/function/json_extract.feature
Labels: ready-for-testing, doc affected, ready for review, cherry-pick-v3.3

#4740 Fix bug #1337 from ent
  src/graph/validator/MatchValidator.cpp
  tests/tck/features/match/Base.IntVid.feature
  tests/tck/features/match/Base.feature
  tests/tck/features/match/MatchById.IntVid.feature
  tests/tck/features/match/MatchById.feature
  tests/tck/features/match/PathExpr.feature
  tests/tck/features/match/Scan.feature
  tests/tck/features/match/VariableLengthPattern.feature
  tests/tck/features/match/VariableLengthPattern.intVid.feature
  tests/tck/features/yield/parameter.feature
Labels: ready-for-testing, doc affected, ready for review, cherry-pick-v3.3

#4780 Fix mutil-match crash
  src/graph/planner/plan/PlanNode.cpp
  src/graph/planner/plan/Query.cpp
  tests/tck/features/match/MatchById.feature
Labels: ready-for-testing, ready for review

#4776 fix subgraph step
  src/graph/executor/algo/SubgraphExecutor.cpp
  src/graph/planner/ngql/SubgraphPlanner.cpp
  tests/tck/features/subgraph/subgraph.IntVid.feature
  tests/tck/features/subgraph/subgraph.feature
  tests/tck/features/subgraph/subgraphWithFilter.feature
Labels: ready-for-testing, type/bug, ready for review

#4779 Cherry pick 3.3 (1022-1025)
  src/common/datatypes/Map.cpp
  src/common/datatypes/Map.h
  src/common/function/FunctionManager.cpp
  src/common/function/test/FunctionManagerTest.cpp
  src/graph/executor/algo/SubgraphExecutor.cpp
  src/graph/executor/query/RollUpApplyExecutor.cpp
  src/graph/planner/match/ArgumentFinder.h
  src/graph/planner/match/LabelIndexSeek.cpp
  src/graph/planner/match/LabelIndexSeek.h
  src/graph/planner/match/PropIndexSeek.h
  src/graph/planner/match/ScanSeek.h
  src/graph/planner/match/StartVidFinder.h
  src/graph/planner/match/VertexIdSeek.h
  src/graph/planner/ngql/SubgraphPlanner.cpp
  src/graph/planner/plan/PlanNode.cpp
  src/graph/planner/plan/Query.cpp
  src/graph/validator/MatchValidator.cpp
  tests/tck/features/bugfix/FindStartError.feature
  tests/tck/features/function/coalesce.feature
  tests/tck/features/function/json_extract.feature
  tests/tck/features/match/Base.IntVid.feature
  tests/tck/features/match/Base.feature
  tests/tck/features/match/MatchById.IntVid.feature
  tests/tck/features/match/MatchById.feature
  tests/tck/features/match/PathExpr.feature
  tests/tck/features/match/Scan.feature
  tests/tck/features/match/VariableLengthPattern.feature
  tests/tck/features/match/VariableLengthPattern.intVid.feature
  tests/tck/features/subgraph/subgraph.IntVid.feature
  tests/tck/features/subgraph/subgraph.feature
  tests/tck/features/subgraph/subgraphWithFilter.feature
  tests/tck/features/yield/parameter.feature
Labels: ready-for-testing

#4788 Fix wrong output when using pattern expression as the filter in MATCH
  src/common/expression/UnaryExpression.h
  src/graph/executor/query/RollUpApplyExecutor.cpp
  tests/tck/features/match/PathExpr.feature
Labels: ready-for-testing, ready for review, cherry-pick-v3.3

#4791 add log for failed plan
  src/meta/processors/job/DataBalanceJobExecutor.cpp
  src/meta/processors/job/LeaderBalanceJobExecutor.cpp
  src/meta/processors/job/ZoneBalanceJobExecutor.cpp
Labels: ready-for-testing

#4799 Solve the problem of ES writing error caused by truncation of UTF8 ch…
  src/common/plugin/fulltext/FTUtils.h
  src/storage/query/ScanEdgeProcessor.h
  src/storage/query/ScanVertexProcessor.h
Labels: ready-for-testing
