Repository vesoft-inc/nebula, pull requests merged in 2022-09, with the labels that each got.

#4566 Minor optimize for go n steps
  src/graph/planner/ngql/GoPlanner.cpp
  src/graph/validator/test/QueryValidatorTest.cpp
  tests/tck/features/go/SimpleCase.feature
Labels: ready-for-testing

#4585 Nebula Graph to NebulaGraph
  CONTRIBUTING.md
  conf/tuned/README.md
  conf/tuned/nebula/tuned.conf
  docker/README.md
  package/package.sh
  resources/README.md
  scripts/README.md
  src/daemons/MetaDaemonInit.cpp
  src/daemons/StorageDaemon.cpp
  src/graph/service/GraphFlags.cpp
  src/parser/test/fuzzing/README.md
  tests/README.md
  tests/conftest.py
  tests/nebula-test-run.py
Labels: ready-for-testing

#4609 Some minor fix
  src/storage/exec/GetPropNode.h
  src/storage/exec/QueryUtils.h
  src/storage/exec/ScanNode.h
  src/storage/query/GetNeighborsProcessor.cpp
  src/storage/query/GetPropProcessor.cpp
  src/storage/query/ScanEdgeProcessor.cpp
  src/storage/query/ScanVertexProcessor.cpp
Labels: ready-for-testing, ready for review

#4607 Fix 1212
  src/graph/visitor/FoldConstantExprVisitor.cpp
  tests/tck/features/expression/NotIn.feature
Labels: ready-for-testing, ready for review, cherry-pick-v3.2, affects-v3.2

#4618 Avoid fatal when expression illegal.
  src/common/expression/LabelAttributeExpression.h
Labels: type/enhancement, ready-for-testing

#4604 extract attribute from properties function
  src/graph/executor/query/ScanEdgesExecutor.cpp
  src/graph/optimizer/rule/GetEdgesTransformUtils.h
  src/graph/planner/plan/PlanNodeVisitor.h
  src/graph/planner/plan/Query.cpp
  src/graph/planner/plan/Query.h
  src/graph/visitor/PropertyTrackerVisitor.cpp
  src/graph/visitor/PropertyTrackerVisitor.h
  src/graph/visitor/PrunePropertiesVisitor.cpp
  src/graph/visitor/PrunePropertiesVisitor.h
  tests/tck/features/optimizer/PrunePropertiesRule.feature
Labels: ready-for-testing, type/bug, ready for review, cherry-pick-v3.2, affects-v3.2

#4612 Add tck execution with retry
  tests/tck/conftest.py
  tests/tck/features/delete/DeleteVertexWithoutEdge.feature
  tests/tck/features/geo/GeoBase.feature
  tests/tck/features/index/Index.feature
  tests/tck/features/insert/insertVertexOnly.feature
  tests/tck/features/lookup/LookUp.feature
  tests/tck/features/lookup/LookupTag2.feature
Labels: ready-for-testing

#4623 fix startup service failed when log directory not exists and enable_breakpad
  src/daemons/MetaDaemon.cpp
  src/daemons/StorageDaemon.cpp
Labels: ready-for-testing, ready for review

#4622 fix exit code in script
  scripts/nebula.service
Labels: ready-for-testing

#4616 fix list tag/edge/tagindex/edgeindex
  src/common/utils/MetaKeyUtils.cpp
  src/common/utils/MetaKeyUtils.h
  src/meta/processors/index/ListEdgeIndexesProcessor.cpp
  src/meta/processors/index/ListTagIndexesProcessor.cpp
  src/meta/processors/schema/ListEdgesProcessor.cpp
  src/meta/processors/schema/ListTagsProcessor.cpp
  src/meta/test/IndexProcessorTest.cpp
  src/meta/test/MetaClientTest.cpp
Labels: ready-for-testing, ready for review

#4601 Better error msg for validity check of geography
  src/common/datatypes/Geography.cpp
  src/common/datatypes/Geography.h
  src/common/function/FunctionManager.cpp
  src/common/geo/io/wkb/test/WKBTest.cpp
  src/common/geo/test/GeoFunctionTest.cpp
Labels: ready-for-testing

#4610 Add meta offline detect
  src/kvstore/raftex/Host.h
  src/kvstore/raftex/RaftPart.cpp
  src/kvstore/raftex/RaftPart.h
  src/meta/processors/parts/ListHostsProcessor.cpp
Labels: ready-for-testing

#4619 update thirdparty v3.3
  cmake/nebula/ThirdPartyConfig.cmake
Labels: ready-for-testing

#4633 Always set rebuildIndexGuard to finish(succeed or failed)
  src/storage/admin/RebuildIndexTask.cpp
Labels: ready-for-testing

#4627 fix issue 4274
  src/kvstore/Part.cpp
  src/kvstore/raftex/RaftPart.cpp
  src/kvstore/raftex/RaftPart.h
  src/storage/admin/AdminProcessor.h
Labels: ready-for-testing

#4628 abandon uppercase letters in fulltext index name
  src/graph/validator/MaintainValidator.cpp
Labels: ready-for-testing, ready for review

#4651 lookup with dedup
  src/graph/planner/ngql/LookupPlanner.cpp
  tests/tck/features/lookup/LookUp.feature
Labels: ready-for-testing

#4652 fix tagless
  src/graph/visitor/PrunePropertiesVisitor.cpp
  tests/tck/features/optimizer/PrunePropertiesRule.feature
Labels: ready-for-testing, ready for review

#4656 fix some typos
  src/clients/meta/MetaClient.h
  src/common/conf/test/ConfigurationTest.cpp
  src/kvstore/raftex/RaftPart.cpp
  src/storage/exec/HashJoinNode.h
  src/storage/test/IndexWriteTest.cpp
Labels: ready-for-testing

#4629 Rollback vertex key
  docker/README.md
  src/common/utils/NebulaKeyUtils.cpp
  src/common/utils/NebulaKeyUtils.h
  src/graph/service/GraphFlags.cpp
  src/graph/service/GraphFlags.h
  src/graph/validator/MutateValidator.cpp
  src/storage/CompactionFilter.h
  src/storage/StorageFlags.cpp
  src/storage/StorageFlags.h
  src/storage/admin/StatsTask.cpp
  src/storage/exec/GetPropNode.h
  src/storage/exec/UpdateNode.h
  src/storage/mutate/AddVerticesProcessor.cpp
  src/tools/CMakeLists.txt
  src/tools/db-upgrade/CMakeLists.txt
  src/tools/db-upgrade/DbUpgrader.cpp
  src/tools/db-upgrade/DbUpgrader.h
  src/tools/db-upgrade/DbUpgraderTool.cpp
  src/tools/db-upgrade/NebulaKeyUtilsV1.cpp
  src/tools/db-upgrade/NebulaKeyUtilsV1.h
  src/tools/db-upgrade/NebulaKeyUtilsV2.cpp
  src/tools/db-upgrade/NebulaKeyUtilsV2.h
  src/tools/db-upgrade/NebulaKeyUtilsV3.cpp
  src/tools/db-upgrade/NebulaKeyUtilsV3.h
  tests/tck/features/delete/DeleteTag.IntVid.feature
  tests/tck/features/delete/DeleteTag.feature
  tests/tck/features/go/GO.IntVid.feature
  tests/tck/features/go/GO.feature
  tests/tck/features/go/GoYieldVertexEdge.feature
  tests/tck/features/insert/insertVertexOnly.feature
  tests/tck/features/match/MatchById.IntVid.feature
  tests/tck/features/match/SeekByEdge.feature
  tests/tck/features/match/With.feature
  tests/tck/features/ttl/TTL.feature
Labels: ready-for-testing, doc affected, ready for review

#4664 fix parameter expression in lookup statement
  src/graph/validator/LookupValidator.cpp
  tests/tck/features/yield/parameter.feature
Labels: ready-for-testing, ready for review

#4648 ENABLE_CCACHE option didn't work
  cmake/nebula/CompilerLauncher.cmake
Labels: ready-for-testing

#4643 add retry for god user check when leader changed
  src/daemons/MetaDaemon.cpp
  src/daemons/MetaDaemonInit.cpp
  src/daemons/MetaDaemonInit.h
  src/daemons/StandAloneDaemon.cpp
  src/meta/RootUserMan.h
Labels: ready-for-testing

#4674 allow check god user read from follower
  src/daemons/MetaDaemonInit.cpp
  src/meta/RootUserMan.h
Labels: ready-for-testing

#4670 Fix incorrect result of optional match statement
  src/graph/planner/match/MatchPlanner.cpp
  tests/tck/features/match/MultiLineMultiQueryParts.feature
Labels: ready-for-testing, ready for review

#4676 add bash -c for folly::subprocess
  src/common/hdfs/HdfsCommandHelper.cpp
Labels: ready-for-testing

#4675 fix bug of tagless
  src/storage/admin/StatsTask.cpp
  src/storage/mutate/AddVerticesProcessor.cpp
Labels: ready-for-testing

#4654 job use future
  src/meta/processors/job/BalanceJobExecutor.cpp
  src/meta/processors/job/BalanceJobExecutor.h
  src/meta/processors/job/BalancePlan.cpp
  src/meta/processors/job/BalancePlan.h
  src/meta/processors/job/DataBalanceJobExecutor.cpp
  src/meta/processors/job/DataBalanceJobExecutor.h
  src/meta/processors/job/JobDescription.h
  src/meta/processors/job/JobExecutor.cpp
  src/meta/processors/job/JobExecutor.h
  src/meta/processors/job/JobManager.cpp
  src/meta/processors/job/JobManager.h
  src/meta/processors/job/LeaderBalanceJobExecutor.cpp
  src/meta/processors/job/LeaderBalanceJobExecutor.h
  src/meta/processors/job/MetaJobExecutor.cpp
  src/meta/processors/job/MetaJobExecutor.h
  src/meta/processors/job/StorageJobExecutor.cpp
  src/meta/processors/job/StorageJobExecutor.h
  src/meta/processors/job/ZoneBalanceJobExecutor.cpp
  src/meta/processors/job/ZoneBalanceJobExecutor.h
  src/meta/test/BalancerTest.cpp
  src/meta/test/GetStatsTest.cpp
  src/meta/test/JobManagerTest.cpp
Labels: ready-for-testing, ready for review

#4671 add vertex filter for GetNeighbors
  src/clients/storage/StorageClient.cpp
  src/clients/storage/StorageClient.h
  src/graph/executor/algo/BatchShortestPath.cpp
  src/graph/executor/algo/SingleShortestPath.cpp
  src/graph/executor/query/GetNeighborsExecutor.cpp
  src/graph/executor/query/TraverseExecutor.cpp
  src/interface/storage.thrift
  src/storage/CommonUtils.h
  src/storage/exec/FilterNode.h
  src/storage/exec/GetNeighborsNode.h
  src/storage/query/GetNeighborsProcessor.cpp
  src/storage/query/GetPropProcessor.cpp
  src/storage/query/QueryBaseProcessor-inl.h
  src/storage/query/QueryBaseProcessor.h
  src/storage/query/ScanEdgeProcessor.cpp
  src/storage/query/ScanVertexProcessor.cpp
  src/storage/test/GetNeighborsTest.cpp
Labels: ready-for-testing, ready for review

#4679 add copyright header for cmaketxt
  src/codec/CMakeLists.txt
  src/codec/test/CMakeLists.txt
  src/common/utils/CMakeLists.txt
  src/common/utils/test/CMakeLists.txt
  src/console/CMakeLists.txt
  src/graph/context/CMakeLists.txt
  src/graph/gc/CMakeLists.txt
  src/graph/util/test/CMakeLists.txt
  src/kvstore/CMakeLists.txt
  src/kvstore/plugins/CMakeLists.txt
  src/kvstore/raftex/CMakeLists.txt
  src/kvstore/raftex/test/CMakeLists.txt
  src/kvstore/test/CMakeLists.txt
  src/kvstore/wal/CMakeLists.txt
  src/kvstore/wal/test/CMakeLists.txt
  src/mock/CMakeLists.txt
  src/storage/CMakeLists.txt
  src/storage/test/CMakeLists.txt
  src/tools/CMakeLists.txt
  src/tools/db-dump/CMakeLists.txt
  src/tools/meta-dump/CMakeLists.txt
  src/tools/simple-kv-verify/CMakeLists.txt
  src/tools/storage-perf/CMakeLists.txt
Labels: ready-for-testing

#4680 only write vertex key when flag is set or explictly insert vertex
  src/storage/mutate/AddVerticesProcessor.cpp
Labels: ready-for-testing, ready for review

#4678 fix job manager ut in asan
  src/meta/test/JobManagerTest.cpp
Labels: ready-for-testing, ready for review

#4673 fixed `show hosts`
  src/graph/executor/admin/ShowHostsExecutor.cpp
Labels: ready-for-testing, doc affected

#4685 insert vertex key when only vertex and flag is set
  src/storage/mutate/AddVerticesProcessor.cpp
Labels: ready-for-testing, ready for review

#4672 Early leave findshortestpath loop optimization
  src/graph/executor/algo/BFSShortestPathExecutor.cpp
  src/graph/executor/algo/BFSShortestPathExecutor.h
  src/graph/planner/ngql/PathPlanner.cpp
  src/graph/planner/ngql/PathPlanner.h
  src/graph/planner/plan/Algo.h
Labels: ready-for-testing

#4663 set job default status as submitted until get some result
  src/common/graph/Response.h
  src/graph/executor/admin/SubmitJobExecutor.cpp
  src/interface/common.thrift
  src/meta/processors/job/JobDescription.h
  src/meta/processors/job/TaskDescription.h
Labels: ready-for-testing
