Repository vesoft-inc/nebula, pull requests merged in 2022-12, with the labels that each got.

#4961 fix ttl not work when ttl column has default value
  src/clients/meta/MetaClient.h
  src/storage/CommonUtils.cpp
  src/storage/CommonUtils.h
  src/storage/exec/QueryUtils.h
  tests/tck/features/ttl/TTL.feature
Labels: ready-for-testing, ready for review

#4959 Extend white space in unicode.
  src/parser/scanner.lex
  src/parser/test/ScannerTest.cpp
Labels: ready-for-testing, type/bug

#4922 Add some case to IndexTest
  src/storage/test/IndexTest.cpp
  src/storage/test/IndexTestUtil.h
Labels: ready-for-testing, ready for review

#4963 update-readme-cn&en
  README-CN.md
  README.md
Labels: ready-for-testing

#4966 Http client ut
  src/common/http/test/CMakeLists.txt
  src/common/http/test/HttpClientTest.cpp
  src/mock/CMakeLists.txt
  src/mock/FakeHttpServer.cpp
  src/mock/FakeHttpServer.h
Labels: ready-for-testing

#4965 fix duplicate output column names of join
  src/graph/executor/query/InnerJoinExecutor.cpp
  src/graph/executor/query/InnerJoinExecutor.h
  src/graph/executor/query/JoinExecutor.cpp
  src/graph/executor/query/JoinExecutor.h
  src/graph/executor/test/JoinTest.cpp
  src/graph/planner/plan/Query.cpp
  tests/tck/features/match/MultiQueryParts.feature
Labels: ready-for-testing, ready for review

#4940 Fix dup alias in MATCH
  src/graph/planner/match/MatchPathPlanner.cpp
  src/graph/validator/test/MatchValidatorTest.cpp
  tests/tck/features/bugfix/DupAliasInMatch.feature
Labels: ready-for-testing

#4970 add new es client
  src/common/http/HttpClient.cpp
  src/common/http/HttpClient.h
  src/common/http/test/HttpClientTest.cpp
  src/common/plugin/fulltext/CMakeLists.txt
  src/common/plugin/fulltext/elasticsearch/ESAdapter.cpp
  src/common/plugin/fulltext/elasticsearch/ESAdapter.h
  src/common/plugin/fulltext/elasticsearch/ESClient.cpp
  src/common/plugin/fulltext/elasticsearch/ESClient.h
  src/common/plugin/fulltext/test/CMakeLists.txt
  src/common/plugin/fulltext/test/ESQueryResultExample.h
  src/common/plugin/fulltext/test/ElasticsearchTest.cpp
  src/graph/service/CloudAuthenticator.cpp
  src/storage/test/StorageHttpAdminHandlerTest.cpp
  src/storage/test/StorageHttpPropertyHandlerTest.cpp
  src/storage/test/StorageHttpStatsHandlerTest.cpp
  src/webservice/test/StatusHandlerTest.cpp
  src/webservice/test/TestUtils.h
Labels: ready-for-testing, ready for review

#4978 Cleanup match planner
  src/graph/context/ast/CypherAstContext.h
  src/graph/planner/match/MatchClausePlanner.cpp
  src/graph/planner/match/MatchPathPlanner.cpp
  src/graph/planner/match/MatchPathPlanner.h
  src/graph/planner/match/MatchPlanner.cpp
  src/graph/planner/match/MatchSolver.cpp
  src/graph/planner/match/MatchSolver.h
  src/graph/planner/match/SegmentsConnector.cpp
  src/graph/planner/match/SegmentsConnector.h
  src/graph/planner/match/ShortestPathPlanner.cpp
  src/graph/planner/match/ShortestPathPlanner.h
  src/graph/planner/match/UnwindClausePlanner.cpp
  src/graph/planner/match/WhereClausePlanner.cpp
  src/graph/planner/match/YieldClausePlanner.cpp
  src/graph/planner/plan/ExecutionPlan.cpp
  src/graph/planner/plan/ExecutionPlan.h
Labels: ready-for-testing

#4977 Rename bijoin plan node
  src/graph/executor/Executor.cpp
  src/graph/executor/algo/CartesianProductExecutor.cpp
  src/graph/executor/algo/CartesianProductExecutor.h
  src/graph/executor/query/InnerJoinExecutor.cpp
  src/graph/executor/query/InnerJoinExecutor.h
  src/graph/executor/query/JoinExecutor.cpp
  src/graph/executor/query/LeftJoinExecutor.cpp
  src/graph/executor/query/LeftJoinExecutor.h
  src/graph/executor/test/JoinTest.cpp
  src/graph/optimizer/rule/RemoveNoopProjectRule.cpp
  src/graph/planner/match/MatchPlanner.cpp
  src/graph/planner/match/SegmentsConnector.cpp
  src/graph/planner/match/ShortestPathPlanner.cpp
  src/graph/planner/plan/Algo.cpp
  src/graph/planner/plan/Algo.h
  src/graph/planner/plan/PlanNode.cpp
  src/graph/planner/plan/PlanNode.h
  src/graph/planner/plan/PlanNodeVisitor.h
  src/graph/planner/plan/Query.cpp
  src/graph/planner/plan/Query.h
  src/graph/visitor/PrunePropertiesVisitor.cpp
  src/graph/visitor/PrunePropertiesVisitor.h
  tests/tck/features/bugfix/ArgumentPlanNodeDep.feature
  tests/tck/features/match/MultiQueryParts.feature
  tests/tck/features/optimizer/PrunePropertiesRule.feature
Labels: ready-for-testing

#4976 disable LeaderTransferTest unittest
  src/kvstore/raftex/test/LeaderTransferTest.cpp
Labels: ready-for-testing, ready for review

#4985 added a deprecated marker in common.thrift
  src/interface/common.thrift
Labels: ready-for-testing, ready for review

#4984 sync from ent repo for supportting show hosts storage listener
  src/clients/meta/MetaClient.cpp
  src/interface/meta.thrift
  src/meta/processors/admin/HBProcessor.cpp
  src/meta/processors/job/StorageJobExecutor.cpp
  src/meta/processors/listener/ListenerProcessor.cpp
  src/meta/processors/parts/ListHostsProcessor.cpp
  src/meta/test/JobManagerTest.cpp
  src/meta/test/MetaClientTest.cpp
  src/parser/parser.yy
  src/parser/test/ParserTest.cpp
  src/storage/StorageServer.cpp
Labels: ready-for-testing, ready for review

#4943 Skip redudant self-reflective edges in GetNeighborsNode
  src/graph/executor/query/TraverseExecutor.h
  src/storage/exec/GetNeighborsNode.h
  tests/tck/features/match/SelfReflectiveEdges.feature
Labels: ready-for-testing, ready for review

#4815 Fix rewrite edge node filter.
  src/common/function/FunctionManager.cpp
  src/common/function/test/FunctionManagerTest.cpp
  src/graph/optimizer/rule/PushEFilterDownRule.cpp
  src/graph/scheduler/AsyncMsgNotifyBasedScheduler.h
  tests/tck/features/bugfix/RewriteEdgeFilter.feature
Labels: ready-for-testing, type/bug, ready for review

#4956 Push filter down HashInnerJoin rule
  src/graph/context/Symbols.cpp
  src/graph/context/Symbols.h
  src/graph/optimizer/CMakeLists.txt
  src/graph/optimizer/OptGroup.cpp
  src/graph/optimizer/OptGroup.h
  src/graph/optimizer/OptRule.cpp
  src/graph/optimizer/OptRule.h
  src/graph/optimizer/Optimizer.cpp
  src/graph/optimizer/Optimizer.h
  src/graph/optimizer/rule/PushFilterDownAggregateRule.cpp
  src/graph/optimizer/rule/PushFilterDownHashInnerJoinRule.cpp
  src/graph/optimizer/rule/PushFilterDownHashInnerJoinRule.h
  src/graph/optimizer/rule/PushFilterDownInnerJoinRule.cpp
  src/graph/optimizer/rule/PushFilterDownLeftJoinRule.cpp
  src/graph/optimizer/rule/PushFilterDownProjectRule.cpp
  src/graph/optimizer/rule/PushFilterDownProjectRule.h
  src/graph/optimizer/rule/RemoveNoopProjectRule.cpp
  src/graph/optimizer/rule/RemoveNoopProjectRule.h
  src/graph/planner/match/ArgumentFinder.cpp
  src/graph/planner/match/MatchPlanner.cpp
  src/graph/planner/plan/PlanNode.cpp
  src/graph/planner/plan/PlanNode.h
  src/graph/planner/plan/Query.cpp
  src/graph/service/QueryInstance.cpp
  src/graph/util/ExpressionUtils.cpp
  src/graph/util/ExpressionUtils.h
  tests/tck/features/match/AllShortestPaths.feature
  tests/tck/features/match/MultiLineMultiQueryParts.feature
  tests/tck/features/optimizer/PushFilterDownHashInnerJoinRule.feature
Labels: ready-for-testing

#4990 Remove the pruning of Expression::Kind::kVarProperty in agg.
  src/graph/visitor/PropertyTrackerVisitor.cpp
  tests/tck/features/optimizer/PrunePropertiesRule.feature
Labels: ready-for-testing

#4987 push filter down traverse rule
  src/common/expression/PredicateExpression.cpp
  src/graph/optimizer/CMakeLists.txt
  src/graph/optimizer/OptGroup.cpp
  src/graph/optimizer/rule/PushFilterDownTraverseRule.cpp
  src/graph/optimizer/rule/PushFilterDownTraverseRule.h
  src/graph/planner/plan/Query.h
  src/graph/util/ExpressionUtils.cpp
  src/graph/util/ExpressionUtils.h
  src/storage/query/QueryBaseProcessor-inl.h
  tests/tck/features/optimizer/PushFilterDownHashInnerJoinRule.feature
  tests/tck/features/optimizer/PushFilterDownTraverseRule.feature
Labels: ready-for-testing

#5007 [LDBC] Fix argument when the input is `NULL`
  src/graph/executor/logic/ArgumentExecutor.cpp
  tests/tck/features/match/MultiLineMultiQueryParts.feature
Labels: ready-for-testing, ready for review

#4980 optimize left join predicate & Eliminate useless appendVertices
  src/common/function/FunctionManager.cpp
  src/graph/optimizer/CMakeLists.txt
  src/graph/optimizer/rule/OptimizeLeftJoinPredicateRule.cpp
  src/graph/optimizer/rule/OptimizeLeftJoinPredicateRule.h
  tests/tck/features/match/MultiQueryParts.feature
  tests/tck/features/optimizer/OptimizeLeftJoinPredicateRule.feature
  tests/tck/features/optimizer/PushFilterDownTraverseRule.feature
Labels: ready-for-testing, ready for review

#4916 Enhancement/pattern expression
  src/graph/context/ast/CypherAstContext.h
  src/graph/executor/CMakeLists.txt
  src/graph/executor/Executor.cpp
  src/graph/executor/query/PatternApplyExecutor.cpp
  src/graph/executor/query/PatternApplyExecutor.h
  src/graph/optimizer/rule/RemoveNoopProjectRule.cpp
  src/graph/planner/match/MatchPathPlanner.cpp
  src/graph/planner/match/SegmentsConnector.cpp
  src/graph/planner/match/SegmentsConnector.h
  src/graph/planner/match/WhereClausePlanner.cpp
  src/graph/planner/plan/PlanNode.cpp
  src/graph/planner/plan/PlanNode.h
  src/graph/planner/plan/Query.cpp
  src/graph/planner/plan/Query.h
  src/graph/util/ExpressionUtils.cpp
  src/graph/util/ExpressionUtils.h
  src/graph/validator/MatchValidator.cpp
  src/graph/validator/MatchValidator.h
  src/parser/MatchPath.h
Labels: ready-for-testing, ready for review

#5014 Port: remove useless appendVertices below innner/left join
  src/common/expression/PredicateExpression.cpp
  src/graph/optimizer/CMakeLists.txt
  src/graph/optimizer/rule/RemoveAppendVerticesBelowJoinRule.cpp
  src/graph/optimizer/rule/RemoveAppendVerticesBelowJoinRule.h
  tests/tck/features/match/MultiQueryParts.feature
  tests/tck/features/optimizer/PrunePropertiesRule.feature
  tests/tck/features/optimizer/RemoveAppendVerticesBelowJoinRule.feature
Labels: ready-for-testing, ready for review

#4973 refine AliasType deducing when planning
  src/graph/context/ast/CypherAstContext.h
  src/graph/planner/match/MatchPlanner.cpp
  src/graph/planner/match/MatchPlanner.h
  src/graph/validator/MatchValidator.cpp
  src/graph/visitor/CMakeLists.txt
  src/graph/visitor/DeduceAliasTypeVisitor.cpp
  src/graph/visitor/DeduceAliasTypeVisitor.h
  src/graph/visitor/test/CMakeLists.txt
  src/graph/visitor/test/DeduceAliasTypeVisitorTest.cpp
  tests/tck/features/bugfix/AliasTypeDeduce.feature
  tests/tck/features/match/PathExpr.feature
Labels: ready-for-testing, ready for review

#5017 Fix wrong invoke of toEdgeName
  src/graph/optimizer/rule/PushEFilterDownRule.cpp
  src/graph/optimizer/rule/PushEFilterDownRule.h
  tests/tck/features/optimizer/PushEFilterDownRule.feature
  tests/tck/features/optimizer/PushFilterDownHashInnerJoinRule.feature
Labels: ready-for-testing

#5000 Share memory for vertex and edge value (#1565)
  src/common/datatypes/Edge.h
  src/common/datatypes/Path.h
  src/common/datatypes/Value.cpp
  src/common/datatypes/Value.h
  src/common/datatypes/ValueOps-inl.h
  src/common/datatypes/Vertex.h
  src/graph/context/Iterator.cpp
  src/graph/context/Iterator.h
Labels: ready-for-testing, ready for review

#5018 Enhance the AppendVertices operator to avoid unnecessary rpc overhead
  src/graph/executor/query/AppendVerticesExecutor.cpp
  src/graph/planner/plan/Query.h
Labels: ready-for-testing, ready for review

#5021 Allow usage of aliases defined in previous matches.
  src/graph/validator/MatchValidator.cpp
  src/parser/Clauses.h
  tests/tck/features/match/With.feature
Labels: ready-for-testing, ready for review

#5019 push filter down index scan
  src/graph/optimizer/rule/PushLimitDownScanAppendVerticesRule.cpp
  src/graph/optimizer/rule/PushLimitDownScanAppendVerticesRule.h
  tests/tck/features/match/Base.feature
Labels: ready-for-testing

#5029 Fix a tck.
  tests/tck/features/match/SelfReflectiveEdges.feature
Labels: ready-for-testing, ready for review

#5045 Pass aliases from unwind to project.
  src/graph/validator/MatchValidator.cpp
  tests/tck/features/match/With.feature
Labels: ready-for-testing, ready for review

#5048 remove sa ci
  .github/workflows/pull_request.yml
Labels: ready-for-testing

#4995 Feature/test data
  tests/common/types.py
  tests/common/utils.py
  tests/data/test/Label_0.csv
  tests/data/test/Label_1.csv
  tests/data/test/Label_10.csv
  tests/data/test/Label_11.csv
  tests/data/test/Label_2.csv
  tests/data/test/Label_3.csv
  tests/data/test/Label_4.csv
  tests/data/test/Label_5.csv
  tests/data/test/Label_6.csv
  tests/data/test/Label_7.csv
  tests/data/test/Label_8.csv
  tests/data/test/Label_9.csv
  tests/data/test/Rel_0.csv
  tests/data/test/Rel_1.csv
  tests/data/test/Rel_2.csv
  tests/data/test/Rel_3.csv
  tests/data/test/Rel_4.csv
  tests/data/test/Rel_5.csv
  tests/data/test/Rel_6.csv
  tests/data/test/config.yaml
  tests/data/test/gen_graph.sh
  tests/tck/features/optimizer/PrunePropertiesRule.feature
Labels: ready-for-testing

#5050 Restrict the max depth of plan tree in optimizer
  src/graph/optimizer/Optimizer.cpp
  src/graph/optimizer/Optimizer.h
Labels: ready-for-testing

#5002 build path base on BFS through adjancency list (#1669)
  src/graph/executor/query/ProjectExecutor.cpp
  src/graph/executor/query/TraverseExecutor.cpp
  src/graph/executor/query/TraverseExecutor.h
  tests/tck/features/optimizer/PrunePropertiesRule.feature
Labels: ready-for-testing, ready for review

#5008 Fix label tag expression toString function
  src/common/expression/PropertyExpression.cpp
  src/graph/service/QueryInstance.cpp
  tests/tck/features/bugfix/AliasTypeDeduce.feature
  tests/tck/features/bugfix/PushFilterDownProject.feature
  tests/tck/features/optimizer/PushFilterDownHashInnerJoinRule.feature
  tests/tck/features/optimizer/PushFilterDownTraverseRule.feature
Labels: ready-for-testing

#5053 Enhance test data set.
  tests/common/types.py
  tests/data/test/Edge_label_limits.csv
  tests/data/test/Edge_ttl_0.csv
  tests/data/test/Label_0.csv
  tests/data/test/Label_1.csv
  tests/data/test/Label_10.csv
  tests/data/test/Label_11.csv
  tests/data/test/Label_2.csv
  tests/data/test/Label_3.csv
  tests/data/test/Label_4.csv
  tests/data/test/Label_5.csv
  tests/data/test/Label_6.csv
  tests/data/test/Label_7.csv
  tests/data/test/Label_8.csv
  tests/data/test/Label_9.csv
  tests/data/test/Label_same_prop_0.csv
  tests/data/test/Label_same_prop_1.csv
  tests/data/test/Label_ttl_0.csv
  tests/data/test/Rel_0.csv
  tests/data/test/Rel_1.csv
  tests/data/test/Rel_2.csv
  tests/data/test/Rel_3.csv
  tests/data/test/Rel_4.csv
  tests/data/test/Rel_5.csv
  tests/data/test/Rel_6.csv
  tests/data/test/config.yaml
Labels: ready-for-testing

#5056 Remove HTTP port in `SHOW HOSTS`
  src/graph/executor/admin/ShowHostsExecutor.cpp
  tests/admin/test_configs.py
  tests/admin/test_show_hosts.py
  tests/tck/features/admin/Hosts.feature
  tests/tck/features/parser/Example.feature
Labels: ready-for-testing, ready for review

#5057 Add note about test data.
  tests/data/test/README.md
Labels: ready-for-testing

#5064 Minor enhancement about error message
  src/clients/meta/MetaClient.cpp
  src/clients/storage/StorageClientBase-inl.h
  src/graph/executor/StorageAccessExecutor.h
  src/interface/common.thrift
  src/meta/processors/BaseProcessor-inl.h
  src/meta/processors/BaseProcessor.h
  src/meta/processors/index/CreateEdgeIndexProcessor.cpp
  src/meta/processors/index/CreateTagIndexProcessor.cpp
  src/meta/processors/schema/CreateTagProcessor.cpp
  src/meta/test/IndexProcessorTest.cpp
  src/meta/test/ProcessorTest.cpp
  src/tools/db-dump/CMakeLists.txt
Labels: ready-for-testing, ready for review

#5074 Upgrade third party version to 3.3
  third-party/install-third-party.sh
Labels: ready-for-testing

#5006 support add listener in tck
  .github/workflows/nightly.yml
  .github/workflows/pull_request.yml
  tests/Makefile
  tests/common/nebula_service.py
  tests/tck/conftest.py
  tests/tck/features/fulltext_index/FulltextIndex.feature
Labels: ready-for-testing, ready for review

#5054 Fix expressions that shall be rewritten to LabelTagProperty
  src/common/expression/AttributeExpression.cpp
  src/common/expression/test/AttributeExpressionTest.cpp
  src/common/expression/test/ExpressionContextMock.h
  src/common/expression/test/ListComprehensionExpressionTest.cpp
  src/common/expression/test/PredicateExpressionTest.cpp
  src/graph/validator/MatchValidator.cpp
  tests/tck/features/expression/ListComprehension.feature
  tests/tck/features/expression/Predicate.feature
  tests/tck/features/expression/Reduce.feature
  tests/tck/features/match/Unwind.feature
Labels: ready-for-testing, ready for review

#5058 Test/permission
  tests/admin/test_permission.py
Labels: ready-for-testing

#5088 change-nebulagraph-logo
  README-CN.md
  README.md
Labels: ready-for-testing

#4991 Modify the constraint of fulltext index name
  src/graph/validator/MaintainValidator.cpp
  src/graph/validator/MaintainValidator.h
  src/parser/MaintainSentences.h
Labels: ready-for-testing, ready for review

#5086 More unwind tests from community
  tests/tck/features/match/Unwind.feature
Labels: ready-for-testing

#5085 add some truncated fixed string case
  src/codec/Common.h
  src/codec/RowWriterV2.cpp
  tests/tck/features/fetch/FetchEmpty.feature
  tests/tck/features/index/Index.feature
Labels: ready-for-testing, ready for review

#5024 could not add a host that is not a storage
  src/clients/meta/MetaClient.cpp
  src/interface/common.thrift
  src/meta/processors/zone/AddHostsProcessor.cpp
  src/meta/test/ProcessorTest.cpp
Labels: ready-for-testing, ready for review

#5038 allow multi fulltext index on a tag/edge
  src/clients/meta/MetaClient.cpp
  src/clients/meta/MetaClient.h
  src/common/meta/SchemaManager.h
  src/common/meta/ServerBasedSchemaManager.cpp
  src/common/meta/ServerBasedSchemaManager.h
  src/graph/validator/LookupValidator.cpp
  src/graph/validator/test/MockSchemaManager.h
  src/kvstore/listener/elasticsearch/ESListener.cpp
  src/meta/processors/BaseProcessor-inl.h
  src/meta/processors/BaseProcessor.h
  src/meta/processors/schema/AlterEdgeProcessor.cpp
  src/meta/processors/schema/AlterTagProcessor.cpp
  src/meta/processors/schema/DropEdgeProcessor.cpp
  src/meta/processors/schema/DropTagProcessor.cpp
  src/mock/AdHocSchemaManager.h
Labels: ready-for-testing

#5104 support loading the test space in tck.
  tests/conftest.py
  tests/tck/conftest.py
Labels: ready-for-testing, ready for review

#5077 Refactor fulltext index plan
  .github/workflows/pull_request.yml
  src/common/http/HttpClient.cpp
  src/common/plugin/fulltext/elasticsearch/ESAdapter.cpp
  src/common/plugin/fulltext/elasticsearch/ESAdapter.h
  src/common/plugin/fulltext/elasticsearch/ESClient.cpp
  src/common/plugin/fulltext/elasticsearch/ESClient.h
  src/common/plugin/fulltext/test/ElasticsearchTest.cpp
  src/graph/context/ast/QueryAstContext.h
  src/graph/executor/CMakeLists.txt
  src/graph/executor/Executor.cpp
  src/graph/executor/query/FulltextIndexScanExecutor.cpp
  src/graph/executor/query/FulltextIndexScanExecutor.h
  src/graph/executor/query/IndexScanExecutor.cpp
  src/graph/optimizer/OptimizerUtils.cpp
  src/graph/optimizer/rule/IndexScanRule.cpp
  src/graph/optimizer/rule/IndexScanRule.h
  src/graph/planner/ngql/LookupPlanner.cpp
  src/graph/planner/plan/PlanNode.cpp
  src/graph/planner/plan/PlanNode.h
  src/graph/planner/plan/Query.cpp
  src/graph/planner/plan/Query.h
  src/graph/planner/plan/Scan.h
  src/graph/util/FTIndexUtils.cpp
  src/graph/validator/LookupValidator.cpp
  src/kvstore/listener/elasticsearch/ESListener.cpp
  src/kvstore/listener/elasticsearch/ESListener.h
  src/meta/processors/index/FTIndexProcessor.cpp
  src/meta/test/IndexProcessorTest.cpp
  tests/Makefile
  tests/common/nebula_service.py
  tests/tck/features/fulltext_index/FulltextIndex.feature
  tests/tck/features/fulltext_index/FulltextIndexQuery1.feature
  tests/tck/features/fulltext_index/FulltextIndexQuery2.feature
Labels: ready-for-testing

#5100 Fix the crash caused by a nullptr variable
  src/clients/storage/StorageClientBase-inl.h
Labels: ready-for-testing, priority/hi-pri, ready for review

#5062 fix wrong vid finder for logic or expr
  src/graph/util/ExpressionUtils.cpp
  src/graph/util/ExpressionUtils.h
  src/graph/util/test/ExpressionUtilsTest.cpp
  src/graph/visitor/VidExtractVisitor.cpp
  tests/tck/features/match/SeekById.feature
Labels: ready-for-testing, priority/hi-pri

#5096 do not check term for leader info by default para
  src/meta/ActiveHostsMan.cpp
Labels: ready-for-testing

#5102 revise error messages.
  src/graph/executor/query/FilterExecutor.cpp
  tests/tck/features/match/Base.feature
Labels: ready-for-testing, priority/hi-pri, ready for review

#5105 fix the bug when alter column that doesn't have a default value to no…
  src/graph/validator/MaintainValidator.cpp
  tests/tck/features/schema/Comment.feature
  tests/tck/features/schema/Schema.feature
Labels: ready-for-testing, doc affected, priority/hi-pri

#5099 add job permission check for data balance
  src/graph/service/PermissionCheck.cpp
  src/parser/AdminSentences.cpp
  src/parser/AdminSentences.h
Labels: ready-for-testing, priority/hi-pri

#5093 set adminClient for job manager at the beginning
  src/daemons/MetaDaemon.cpp
  src/meta/MetaServiceHandler.cpp
  src/meta/MetaServiceHandler.h
  src/meta/processors/job/AdminJobProcessor.cpp
  src/meta/processors/job/JobManager.cpp
  src/meta/processors/job/JobManager.h
  src/meta/test/CreateBackupProcessorTest.cpp
  src/meta/test/GetStatsTest.cpp
  src/meta/test/JobManagerTest.cpp
Labels: ready-for-testing, priority/hi-pri

#5083 Add index test cases
  src/storage/BaseProcessor.h
  src/storage/exec/IndexScanNode.cpp
  src/storage/test/IndexTest.cpp
  src/storage/test/IndexTestUtil.h
  tests/tck/features/index/Index.feature
Labels: ready-for-testing, ready for review

#5106 fix issue1527(pruning properties)
  src/graph/visitor/PropertyTrackerVisitor.cpp
  src/graph/visitor/PrunePropertiesVisitor.cpp
  tests/common/plan_differ.py
  tests/tck/conftest.py
  tests/tck/features/optimizer/PrunePropertiesRule.feature
Labels: ready-for-testing, priority/hi-pri

#5076 Fix checking update filter expression.
  src/graph/validator/MutateValidator.cpp
  src/graph/visitor/CMakeLists.txt
  src/graph/visitor/RewriteSymExprVisitor.cpp
  src/graph/visitor/RewriteSymExprVisitor.h
  tests/tck/features/bugfix/CompareDate.feature
Labels: ready-for-testing, type/bug

#5013 Check running job before create backup
  src/clients/meta/MetaClient.cpp
  src/common/graph/Response.h
  src/interface/common.thrift
  src/meta/processors/admin/CreateBackupProcessor.cpp
  src/meta/processors/job/AdminJobProcessor.cpp
  src/meta/processors/job/JobManager.cpp
  src/meta/processors/job/JobManager.h
  src/meta/test/CreateBackupProcessorTest.cpp
Labels: ready-for-testing, priority/hi-pri

#5095 feat: tck for fixed length pattern match
  tests/tck/features/match/Base.feature
Labels: ready-for-testing

#5103 fetch-prop tck
  tests/tck/features/fetch/FetchEdges.intVid.feature
  tests/tck/features/fetch/FetchEdges.strVid.feature
  tests/tck/features/fetch/FetchVertices.intVid.feature
  tests/tck/features/fetch/FetchVertices.strVid.feature
Labels: ready-for-testing, ready for review

#5121 Fix a crash bug. Deduce props in yield.
  src/graph/validator/GroupByValidator.cpp
  tests/tck/features/yield/parameter.feature
Labels: ready-for-testing, priority/hi-pri, ready for review

#5122 Add more fulltext index tck case
  src/interface/common.thrift
  src/kvstore/listener/elasticsearch/ESListener.cpp
  src/kvstore/listener/elasticsearch/ESListener.h
  src/meta/processors/index/FTIndexProcessor.cpp
  tests/tck/features/fulltext_index/FultextIndexDDL.feature
Labels: ready-for-testing

#5126 forbid string index length <= 0
  src/meta/processors/index/CreateEdgeIndexProcessor.cpp
  src/meta/processors/index/CreateTagIndexProcessor.cpp
  tests/tck/features/index/Index.feature
Labels: ready-for-testing, ready for review

#5082 Memory Tracker
  cmake/nebula/ThirdPartyConfig.cmake
  src/common/memory/CMakeLists.txt
  src/common/memory/Memory.h
  src/common/memory/MemoryTracker.cpp
  src/common/memory/MemoryTracker.h
  src/common/memory/MemoryUtils.cpp
  src/common/memory/MemoryUtils.h
  src/common/memory/NewDelete.cpp
  src/common/memory/test/CMakeLists.txt
  src/graph/executor/Executor.h
  src/graph/executor/StorageAccessExecutor.h
  src/graph/executor/algo/BFSShortestPathExecutor.cpp
  src/graph/executor/algo/BatchShortestPath.cpp
  src/graph/executor/algo/MultiShortestPathExecutor.cpp
  src/graph/executor/algo/ProduceAllPathsExecutor.cpp
  src/graph/executor/algo/ShortestPathBase.cpp
  src/graph/executor/algo/ShortestPathBase.h
  src/graph/executor/algo/SingleShortestPath.cpp
  src/graph/executor/algo/SubgraphExecutor.cpp
  src/graph/executor/maintain/EdgeExecutor.cpp
  src/graph/executor/maintain/EdgeIndexExecutor.cpp
  src/graph/executor/maintain/FTIndexExecutor.cpp
  src/graph/executor/maintain/TagExecutor.cpp
  src/graph/executor/maintain/TagIndexExecutor.cpp
  src/graph/executor/mutate/DeleteExecutor.cpp
  src/graph/executor/mutate/InsertExecutor.cpp
  src/graph/executor/mutate/UpdateExecutor.cpp
  src/graph/executor/query/AppendVerticesExecutor.cpp
  src/graph/executor/query/GetDstBySrcExecutor.cpp
  src/graph/executor/query/GetEdgesExecutor.cpp
  src/graph/executor/query/GetNeighborsExecutor.cpp
  src/graph/executor/query/GetVerticesExecutor.cpp
  src/graph/executor/query/IndexScanExecutor.cpp
  src/graph/executor/query/ScanEdgesExecutor.cpp
  src/graph/executor/query/ScanVerticesExecutor.cpp
  src/graph/executor/query/TraverseExecutor.cpp
  src/graph/scheduler/AsyncMsgNotifyBasedScheduler.cpp
  src/interface/common.thrift
  src/storage/BaseProcessor.h
  src/storage/StorageServer.cpp
  src/storage/StorageServer.h
  src/storage/index/LookupProcessor.cpp
  src/storage/query/GetDstBySrcProcessor.cpp
  src/storage/query/GetNeighborsProcessor.cpp
  src/storage/query/GetPropProcessor.cpp
  src/storage/query/ScanEdgeProcessor.cpp
  src/storage/query/ScanVertexProcessor.cpp
Labels: ready-for-testing, priority/hi-pri, ready for review

#5098 Restrict schema type conversion
  src/meta/MetaServiceUtils.cpp
  src/meta/test/ProcessorTest.cpp
  tests/query/stateless/test_schema.py
  tests/tck/features/schema/Schema.feature
  tests/tck/features/ttl/TTL.feature
Labels: ready-for-testing, priority/hi-pri, ready for review

#5124 Fix join on edge list
  src/common/datatypes/Edge.cpp
  src/common/function/FunctionManager.cpp
  src/graph/planner/match/MatchPlanner.cpp
  src/graph/planner/match/SegmentsConnector.cpp
  tests/tck/features/bugfix/MatchJoinOnEdge.feature
Labels: ready-for-testing, ready for review

#5079 parameter tck
  tests/tck/features/yield/parameter.feature
Labels: ready-for-testing

#5119 Close toss, and some other minor enhancement
  conf/nebula-graphd.conf.default
  conf/nebula-graphd.conf.production
  conf/nebula-standalone.conf.default
  conf/nebula-storaged-listener.conf.production
  conf/nebula-storaged.conf.default
  conf/nebula-storaged.conf.production
  src/graph/executor/admin/SpaceExecutor.cpp
  src/graph/service/GraphFlags.cpp
  src/parser/parser.yy
  src/parser/test/ParserTest.cpp
  src/storage/StorageServer.cpp
  src/storage/StorageServer.h
  src/storage/test/StorageHttpPropertyHandlerTest.cpp
  src/storage/transaction/ChainAddEdgesGroupProcessor.cpp
  src/storage/transaction/ChainDeleteEdgesGroupProcessor.cpp
  src/storage/transaction/ChainUpdateEdgeLocalProcessor.cpp
  src/tools/simple-kv-verify/CMakeLists.txt
  src/tools/storage-perf/CMakeLists.txt
  tests/admin/test_space.py
  tests/tck/features/match/With.feature
Labels: ready-for-testing, ready for review

#5117 delete unused keyword step
  src/parser/scanner.lex
  src/parser/test/ScannerTest.cpp
  tests/tck/features/delete/DeleteVertexWithoutEdge.feature
  tests/tck/features/go/SimpleCase.feature
  tests/tck/features/insert/insertVertexOnly.feature
Labels: ready-for-testing, doc affected, ready for review

#5129 Fix update time when session is created
  src/meta/processors/session/SessionManagerProcessor.cpp
Labels: ready-for-testing, type/bug, ready for review

#5061 Add tests for intersect/union, limit, group by, order by, variable, list exprs
  src/common/expression/PredicateExpression.cpp
  src/graph/context/Symbols.cpp
  src/graph/context/Symbols.h
  src/graph/validator/AssignmentValidator.cpp
  tests/tck/features/aggregate/Agg.feature
  tests/tck/features/expression/Predicate.feature
  tests/tck/features/go/GroupbyLimit.feature
  tests/tck/features/go/Orderby.feature
  tests/tck/features/match/PipeAndVariable.feature
  tests/tck/features/set/Set.feature
Labels: ready-for-testing, priority/hi-pri

#5133 update error msg of optimizer
  src/graph/service/QueryInstance.cpp
Labels: ready-for-testing

#5132 fix wrong untracked_reserved_memory_mb
  src/common/memory/MemoryUtils.cpp
Labels: ready-for-testing, ready for review

#5136 forbid zero fixed string
  src/parser/parser.yy
  tests/tck/features/index/Index.feature
  tests/tck/features/schema/Schema.feature
Labels: ready-for-testing

#5140 Enhance MemoryStats to avoid the false sharing effect on the CPU cache
  src/common/memory/MemoryTracker.h
Labels: ready-for-testing, ready for review

#5137 add tagFilter for traverse
  src/graph/executor/query/TraverseExecutor.cpp
  src/graph/planner/match/MatchPathPlanner.cpp
  src/graph/planner/plan/Query.cpp
  src/graph/planner/plan/Query.h
  tests/tck/features/match/Base.IntVid.feature
  tests/tck/features/match/Base.feature
Labels: ready-for-testing, type/bug, ready for review

#5135 fix push down of rank(e)
  src/graph/optimizer/rule/PushFilterDownTraverseRule.cpp
  src/graph/util/ExpressionUtils.cpp
  src/graph/util/ExpressionUtils.h
  src/graph/validator/MatchValidator.cpp
  src/graph/visitor/FindVisitor.cpp
  src/graph/visitor/FindVisitor.h
  tests/tck/features/match/Base.feature
Labels: ready-for-testing, ready for review

#5116 support intersect/minus for cypher
  src/common/datatypes/Edge.cpp
  src/common/datatypes/Vertex.h
  src/common/expression/test/TestBase.h
  src/graph/context/ast/CypherAstContext.h
  src/graph/validator/MatchValidator.cpp
  src/graph/validator/MatchValidator.h
  src/parser/parser.yy
  tests/tck/features/bugfix/ListSlicingWithNull.feature
  tests/tck/features/expression/Case.feature
  tests/tck/features/expression/function/Mathematical.feature
  tests/tck/features/function/coalesce.feature
  tests/tck/features/set/Set.feature
  tests/tck/features/yield/return.feature
Labels: ready-for-testing, doc affected, ready for review

#5152 fix listener may crash when remove
  conf/nebula-storaged-listener.conf.default
  conf/nebula-storaged-listener.conf.production
  src/graph/executor/admin/SpaceExecutor.cpp
  src/kvstore/listener/Listener.cpp
  src/kvstore/listener/Listener.h
Labels: ready-for-testing, ready for review

#5150 fix error msg trancated
  src/graph/service/QueryInstance.cpp
Labels: ready-for-testing, ready for review

#5148 Fix PushFilterDownHashInnerJoinRule
  src/graph/optimizer/rule/PushFilterDownHashInnerJoinRule.cpp
  tests/tck/features/optimizer/PushFilterDownHashInnerJoinRule.feature
Labels: ready-for-testing, priority/hi-pri, ready for review

#5149 Revert "Remove all UNKNOWN_PROP as a type of null. (#4907)"
  src/codec/RowReaderV1.cpp
  src/codec/RowReaderV2.cpp
  src/common/datatypes/Map.h
  src/common/datatypes/Value.cpp
  src/common/datatypes/Value.h
  src/common/datatypes/test/ValueTest.cpp
  src/common/datatypes/test/ValueToJsonTest.cpp
  src/common/expression/AttributeExpression.cpp
  src/common/expression/test/AttributeExpressionTest.cpp
  src/common/expression/test/SubscriptExpressionTest.cpp
  src/common/time/TimeUtils.h
  src/common/utils/IndexKeyUtils.cpp
  src/interface/common.thrift
  src/storage/exec/IndexEdgeScanNode.cpp
  src/storage/exec/IndexVertexScanNode.cpp
  src/storage/exec/QueryUtils.h
  src/tools/db-upgrade/DbUpgrader.cpp
  tests/common/nebula_test_suite.py
  tests/tck/features/expression/Attribute.feature
  tests/tck/features/match/Base.feature
  tests/tck/features/match/MultiQueryParts.feature
  tests/tck/features/match/With.feature
  tests/tck/features/optimizer/PrunePropertiesRule.feature
  tests/tck/features/parser/nebula.feature
  tests/tck/utils/nbv.py
Labels: ready-for-testing, priority/hi-pri, ready for review

#5130 Forbid adding schema properties if they existed before
  src/common/utils/MetaKeyUtils.cpp
  src/common/utils/MetaKeyUtils.h
  src/meta/MetaServiceUtils.cpp
  src/meta/MetaServiceUtils.h
  src/meta/processors/schema/AlterEdgeProcessor.cpp
  src/meta/processors/schema/AlterTagProcessor.cpp
  src/meta/processors/schema/GetEdgeProcessor.cpp
  src/meta/processors/schema/GetTagProcessor.cpp
  src/meta/test/ProcessorTest.cpp
  tests/query/stateless/test_schema.py
  tests/tck/features/fulltext_index/FultextIndexDDL.feature
  tests/tck/features/schema/Schema.feature
Labels: ready-for-testing, type/bug, ready for review

#5155 refine MemTracker log & adjust flag & fix build with gcc
  src/common/memory/MemoryTracker.h
  src/common/memory/MemoryUtils.cpp
  src/common/memory/MemoryUtils.h
  src/common/memory/NewDelete.cpp
  src/common/memory/test/MemoryUtilsTest.cpp
  src/graph/context/Iterator.cpp
  src/graph/executor/Executor.cpp
  src/graph/service/QueryEngine.cpp
  src/storage/StorageServer.cpp
Labels: ready-for-testing

#5144 improve snapshots and add some tests
  src/clients/meta/MetaClient.cpp
  src/common/datatypes/Value.cpp
  src/common/graph/Response.h
  src/common/thrift/ThriftClientManager-inl.h
  src/interface/common.thrift
  src/meta/ActiveHostsMan.cpp
  src/meta/ActiveHostsMan.h
  src/meta/processors/BaseProcessor-inl.h
  src/meta/processors/BaseProcessor.h
  src/meta/processors/admin/CreateSnapshotProcessor.cpp
  src/meta/processors/admin/CreateSnapshotProcessor.h
  src/meta/processors/admin/DropSnapshotProcessor.cpp
  src/meta/processors/admin/DropSnapshotProcessor.h
  src/meta/processors/admin/HBProcessor.cpp
  src/meta/processors/admin/SnapShot.cpp
  src/meta/processors/job/JobManager.h
  src/meta/test/CMakeLists.txt
  src/meta/test/SnapshotProcessorsTest.cpp
  src/meta/test/TestUtils.h
  src/mock/RpcServer.h
Labels: ready-for-testing, ready for review

#5159 fix node label filter
  src/graph/executor/query/TraverseExecutor.cpp
  tests/tck/features/bugfix/MatchNodeLabelFilter.feature
Labels: ready-for-testing, ready for review

#5164 Revert "delete unused keyword step"
  src/parser/scanner.lex
  src/parser/test/ScannerTest.cpp
  tests/tck/features/delete/DeleteVertexWithoutEdge.feature
  tests/tck/features/go/SimpleCase.feature
  tests/tck/features/insert/insertVertexOnly.feature
Labels: ready-for-testing, ready for review

#5160 Add match tck, covering fixed bugs
  tests/tck/conftest.py
  tests/tck/features/match/Path.feature
  tests/tck/features/optimizer/CasesUsingTestSpace.feature
  tests/tck/features/optimizer/PushFilterDownHashInnerJoinRule.feature
Labels: ready-for-testing, priority/hi-pri, ready for review

#5146 [Feature] Kill sessions
  src/clients/meta/MetaClient.cpp
  src/clients/meta/MetaClient.h
  src/graph/executor/Executor.cpp
  src/graph/executor/admin/SessionExecutor.cpp
  src/graph/executor/admin/SessionExecutor.h
  src/graph/planner/plan/Admin.h
  src/graph/planner/plan/PlanNode.cpp
  src/graph/planner/plan/PlanNode.h
  src/graph/service/PermissionCheck.cpp
  src/graph/session/GraphSessionManager.cpp
  src/graph/session/GraphSessionManager.h
  src/graph/validator/AdminValidator.cpp
  src/graph/validator/AdminValidator.h
  src/graph/validator/Validator.cpp
  src/interface/meta.thrift
  src/meta/MetaServiceHandler.cpp
  src/meta/MetaServiceHandler.h
  src/meta/processors/BaseProcessor-inl.h
  src/meta/processors/BaseProcessor.h
  src/meta/processors/session/SessionManagerProcessor.cpp
  src/meta/processors/session/SessionManagerProcessor.h
  src/meta/test/ProcessorTest.cpp
  src/parser/AdminSentences.cpp
  src/parser/AdminSentences.h
  src/parser/Sentence.h
  src/parser/parser.yy
  src/parser/test/ParserTest.cpp
  src/storage/admin/AdminProcessor.h
  tests/common/nebula_test_suite.py
  tests/job/test_session.py
Labels: ready-for-testing, doc affected, type/feature req, ready for review

#5165 fix match node label
  src/graph/executor/query/TraverseExecutor.cpp
  tests/tck/features/bugfix/MatchNodeLabelFilter.feature
Labels: ready-for-testing, ready for review

#5171 Fix scan efilter.
  src/graph/optimizer/rule/GetEdgesTransformAppendVerticesLimitRule.cpp
  src/graph/optimizer/rule/GetEdgesTransformRule.cpp
  tests/tck/features/bugfix/LackFilterGetEdges.feature
Labels: ready-for-testing, type/bug

#5169 drop space not exist
  src/clients/meta/MetaClient.cpp
  src/common/graph/Response.h
  src/common/thrift/ThriftClientManager-inl.h
  src/interface/common.thrift
  src/meta/processors/admin/DropSnapshotProcessor.cpp
  src/meta/test/SnapshotProcessorsTest.cpp
Labels: ready-for-testing

#5168 add more ttl tck case
  tests/tck/features/ttl/TTL2.feature
Labels: ready-for-testing

#5167 [memtracker] improve throw bad_alloc logic
  src/clients/storage/StorageClientBase-inl.h
  src/common/memory/MemoryTracker.h
  src/graph/executor/Executor.h
  src/graph/executor/algo/BFSShortestPathExecutor.cpp
  src/graph/executor/algo/BatchShortestPath.cpp
  src/graph/executor/algo/MultiShortestPathExecutor.cpp
  src/graph/executor/algo/ProduceAllPathsExecutor.cpp
  src/graph/executor/algo/ShortestPathBase.cpp
  src/graph/executor/algo/SingleShortestPath.cpp
  src/graph/executor/algo/SubgraphExecutor.cpp
  src/graph/executor/maintain/EdgeExecutor.cpp
  src/graph/executor/maintain/EdgeIndexExecutor.cpp
  src/graph/executor/maintain/FTIndexExecutor.cpp
  src/graph/executor/maintain/TagExecutor.cpp
  src/graph/executor/maintain/TagIndexExecutor.cpp
  src/graph/executor/mutate/DeleteExecutor.cpp
  src/graph/executor/mutate/InsertExecutor.cpp
  src/graph/executor/mutate/UpdateExecutor.cpp
  src/graph/executor/query/AppendVerticesExecutor.cpp
  src/graph/executor/query/FilterExecutor.cpp
  src/graph/executor/query/GetDstBySrcExecutor.cpp
  src/graph/executor/query/GetEdgesExecutor.cpp
  src/graph/executor/query/GetNeighborsExecutor.cpp
  src/graph/executor/query/GetVerticesExecutor.cpp
  src/graph/executor/query/IndexScanExecutor.cpp
  src/graph/executor/query/InnerJoinExecutor.cpp
  src/graph/executor/query/LeftJoinExecutor.cpp
  src/graph/executor/query/ProjectExecutor.cpp
  src/graph/executor/query/ScanEdgesExecutor.cpp
  src/graph/executor/query/ScanVerticesExecutor.cpp
  src/graph/executor/query/TraverseExecutor.cpp
  src/graph/scheduler/AsyncMsgNotifyBasedScheduler.cpp
  src/graph/service/GraphService.cpp
  src/graph/service/QueryEngine.cpp
  src/graph/service/QueryInstance.cpp
  src/meta/CMakeLists.txt
  src/storage/GraphStorageServiceHandler.cpp
  src/storage/index/LookupProcessor.cpp
  src/storage/kv/GetProcessor.cpp
  src/storage/kv/PutProcessor.cpp
  src/storage/kv/RemoveProcessor.cpp
  src/storage/mutate/AddEdgesProcessor.cpp
  src/storage/mutate/AddVerticesProcessor.cpp
  src/storage/mutate/DeleteEdgesProcessor.cpp
  src/storage/mutate/DeleteTagsProcessor.cpp
  src/storage/mutate/DeleteVerticesProcessor.cpp
  src/storage/mutate/UpdateEdgeProcessor.cpp
  src/storage/mutate/UpdateVertexProcessor.cpp
  src/storage/query/GetDstBySrcProcessor.cpp
  src/storage/query/GetNeighborsProcessor.cpp
  src/storage/query/GetPropProcessor.cpp
  src/storage/query/ScanEdgeProcessor.cpp
  src/storage/query/ScanVertexProcessor.cpp
  src/storage/test/CMakeLists.txt
  src/tools/CMakeLists.txt
Labels: ready-for-testing

#5151 Fix the bad type evaluated from AttributeExpression on vertices
  src/common/expression/AttributeExpression.cpp
  tests/tck/features/expression/Attribute1.feature
Labels: ready-for-testing, priority/hi-pri, ready for review

#5172 Fix clang compilation
  .github/workflows/pull_request.yml
  src/common/memory/MemoryUtils.cpp
  src/common/memory/NewDelete.cpp
  src/graph/validator/AdminValidator.h
Labels: ready-for-testing, type/bug, ready for review
