Repository vesoft-inc/nebula, pull requests merged in 2022-06, with the labels that each got.

#4292 fix learner's wal is not empty in rare cases
  src/kvstore/raftex/RaftPart.cpp
  src/kvstore/wal/FileBasedWal.cpp
Labels: ready-for-testing, ready for review

#4270 Push eFilter down.
  src/graph/executor/query/TraverseExecutor.cpp
  src/graph/executor/query/TraverseExecutor.h
  src/graph/optimizer/CMakeLists.txt
  src/graph/optimizer/rule/PushEFilterDownRule.cpp
  src/graph/optimizer/rule/PushEFilterDownRule.h
  src/graph/planner/plan/Query.h
  src/graph/visitor/RewriteVisitor.cpp
  src/graph/visitor/RewriteVisitor.h
  src/storage/query/QueryBaseProcessor-inl.h
  src/storage/query/QueryBaseProcessor.h
  tests/tck/features/optimizer/PushEFilterDownRule.feature
Labels: type/enhancement, ready-for-testing

#4260 Push vFilter down.
  src/graph/executor/query/TraverseExecutor.cpp
  src/graph/executor/query/TraverseExecutor.h
  src/graph/optimizer/CMakeLists.txt
  src/graph/optimizer/rule/PushFilterDownNodeRule.cpp
  src/graph/optimizer/rule/PushFilterDownNodeRule.h
  src/graph/optimizer/rule/PushVFilterDownScanVerticesRule.cpp
  src/graph/planner/match/MatchSolver.cpp
  src/graph/planner/plan/Query.cpp
  src/graph/planner/plan/Query.h
  src/graph/visitor/ExtractFilterExprVisitor.cpp
  tests/tck/features/optimizer/PrunePropertiesRule.feature
  tests/tck/features/optimizer/PushFilterDownNodeRule.feature
Labels: type/enhancement, ready-for-testing

#4071 Shortest path
  src/graph/context/Iterator.h
  src/graph/context/ast/CypherAstContext.h
  src/graph/executor/CMakeLists.txt
  src/graph/executor/Executor.cpp
  src/graph/executor/algo/BatchShortestPath.cpp
  src/graph/executor/algo/BatchShortestPath.h
  src/graph/executor/algo/ShortestPathBase.cpp
  src/graph/executor/algo/ShortestPathBase.h
  src/graph/executor/algo/ShortestPathExecutor.cpp
  src/graph/executor/algo/ShortestPathExecutor.h
  src/graph/executor/algo/SingleShortestPath.cpp
  src/graph/executor/algo/SingleShortestPath.h
  src/graph/executor/query/TraverseExecutor.cpp
  src/graph/planner/CMakeLists.txt
  src/graph/planner/match/MatchClausePlanner.cpp
  src/graph/planner/match/MatchClausePlanner.h
  src/graph/planner/match/MatchPathPlanner.cpp
  src/graph/planner/match/MatchPathPlanner.h
  src/graph/planner/match/MatchSolver.cpp
  src/graph/planner/match/MatchSolver.h
  src/graph/planner/match/ShortestPathPlanner.cpp
  src/graph/planner/match/ShortestPathPlanner.h
  src/graph/planner/plan/Algo.cpp
  src/graph/planner/plan/Algo.h
  src/graph/planner/plan/PlanNode.cpp
  src/graph/planner/plan/PlanNode.h
  src/graph/planner/plan/Query.cpp
  src/graph/util/PlannerUtil.cpp
  src/graph/util/SchemaUtil.cpp
  src/graph/util/SchemaUtil.h
  src/graph/validator/MatchValidator.cpp
  src/parser/MatchPath.h
  src/parser/parser.yy
  src/parser/scanner.lex
  tests/tck/features/match/AllShortestPaths.feature
  tests/tck/features/match/SingleShorestPath.feature
Labels: ready-for-testing, type/feature req, ready for review

#4293 Update CODEOWNERS
  .github/CODEOWNERS
Labels: ready-for-testing

#4259 Create auto_cherry_pick.yml
  .github/workflows/auto_cherry_pick.yml
Labels: ready-for-testing

#4305 fix storage crash
  src/storage/mutate/AddEdgesProcessor.cpp
  src/storage/mutate/AddEdgesProcessor.h
  tests/tck/features/insert/Insert.feature
Labels: ready-for-testing, type/bug, priority/hi-pri, ready for review

#4306 Fix the license header.
  src/common/base/Arena.cpp
  src/common/base/Arena.h
  src/common/base/test/ArenaBenchmark.cpp
  src/common/base/test/ArenaTest.cpp
  src/common/id/CMakeLists.txt
  tests/tck/features/bugfix/VariableExpression.feature
Labels: ready-for-testing

#4304 More readable error msg for operator and/or.
  src/graph/visitor/DeduceTypeVisitor.cpp
  tests/tck/features/yield/yield.feature
Labels: ready-for-testing

#4312 Fix cloud auth
  src/graph/service/GraphService.cpp
Labels: ready-for-testing, type/bug, ready for review

#4311 fix when restoring, the machine key is lost
  src/meta/processors/admin/RestoreProcessor.cpp
Labels: ready-for-testing, ready for review

#4283 Move probe rows of Join.
  src/graph/executor/Executor.h
  src/graph/executor/query/InnerJoinExecutor.cpp
  src/graph/executor/query/InnerJoinExecutor.h
  src/graph/executor/query/JoinExecutor.cpp
  src/graph/executor/query/JoinExecutor.h
  src/graph/executor/query/LeftJoinExecutor.cpp
  src/graph/executor/query/LeftJoinExecutor.h
  src/graph/executor/query/RollUpApplyExecutor.cpp
  src/graph/executor/query/RollUpApplyExecutor.h
Labels: type/enhancement, ready-for-testing, ready for review

#4310 add some config
  conf/nebula-graphd.conf.default
  conf/nebula-graphd.conf.production
  conf/nebula-storaged.conf.default
  conf/nebula-storaged.conf.production
Labels: ready-for-testing, ready for review

#4242 Optimize input/var property expression to get property from tuple by
  src/common/base/ObjectPool.h
  src/common/context/ExpressionContext.h
  src/common/expression/PropertyExpression.cpp
  src/common/expression/PropertyExpression.h
  src/common/expression/test/ColumnExpressionTest.cpp
  src/common/expression/test/ExpressionContextMock.cpp
  src/common/expression/test/ExpressionContextMock.h
  src/common/expression/test/PathBuildExpressionTest.cpp
  src/common/utils/DefaultValueContext.h
  src/graph/context/Iterator.cpp
  src/graph/context/Iterator.h
  src/graph/context/QueryExpressionContext.cpp
  src/graph/context/QueryExpressionContext.h
  src/graph/context/test/CMakeLists.txt
  src/graph/context/test/InputVarPropBenchmark.cpp
  src/storage/context/StorageExpressionContext.h
  src/storage/exec/IndexExprContext.h
Labels: type/enhancement, ready-for-testing, ready for review

#4157 Enhancement remove useless project.
  src/graph/executor/algo/ProduceAllPathsExecutor.cpp
  src/graph/optimizer/OptGroup.cpp
  src/graph/optimizer/OptRule.h
  src/graph/optimizer/rule/RemoveNoopProjectRule.cpp
  src/graph/optimizer/rule/RemoveNoopProjectRule.h
  src/graph/planner/plan/Algo.cpp
  src/graph/planner/plan/Algo.h
  src/graph/planner/plan/PlanNode.cpp
  src/graph/planner/plan/PlanNode.h
  tests/tck/features/optimizer/RemoveUselessProjectRule.feature
Labels: ready-for-testing, ready for review

#4319 fix zone lost in backup
  src/meta/processors/BaseProcessor-inl.h
  src/meta/processors/BaseProcessor.h
  src/meta/processors/admin/RestoreProcessor.cpp
  src/meta/processors/zone/AddHostsProcessor.cpp
  src/meta/test/RestoreProcessorTest.cpp
Labels: ready-for-testing, ready for review

#4324 enhance docker and rc
  .github/workflows/nightly.yml
  .github/workflows/rc.yml
  tests/admin/test_show_hosts.py
Labels: ready-for-testing

#4327 fix docker rc version
  .github/workflows/rc.yml
  docker/Dockerfile
Labels: ready-for-testing

#4331 force cache the docker layer
  .github/workflows/nightly.yml
  .github/workflows/rc.yml
Labels: ready-for-testing

#4330 check god role exist when meta init
  src/daemons/MetaDaemon.cpp
  src/daemons/StandAloneDaemon.cpp
  src/meta/RootUserMan.h
Labels: ready-for-testing, ready for review, cherry-pick-v3.2

#4332 Fix object pool mtsafe.
  src/common/base/ObjectPool.h
Labels: ready-for-testing, cherry-pick-v3.2

#4328 Fix get edges transform rule.
  src/graph/optimizer/rule/CollapseProjectRule.cpp
  src/graph/optimizer/rule/GetEdgesTransformAppendVerticesLimitRule.cpp
  src/graph/optimizer/rule/GetEdgesTransformRule.cpp
  src/graph/optimizer/rule/GetEdgesTransformUtils.h
Labels: ready-for-testing, cherry-pick-v3.2

#4336 fix rc docker
  .github/workflows/rc.yml
Labels: ready-for-testing, cherry-pick-v3.2

#4342 fix token of cherry pick
  .github/workflows/auto_cherry_pick.yml
Labels: ready-for-testing

#4352 fix_shortest_path_crash
  src/graph/executor/algo/BatchShortestPath.cpp
  src/graph/executor/algo/ShortestPathBase.cpp
  src/graph/executor/algo/ShortestPathBase.h
  src/graph/executor/algo/SingleShortestPath.cpp
Labels: ready-for-testing, type/bug, ready for review, cherry-pick-v3.2

#4344 fix map concurrency issue
  src/meta/processors/job/JobManager.cpp
  src/meta/processors/job/JobManager.h
  src/meta/test/GetStatsTest.cpp
  src/meta/test/JobManagerTest.cpp
Labels: ready-for-testing, ready for review, cherry-pick-v3.2

#4353 add stats under index condition
  src/storage/mutate/AddEdgesProcessor.cpp
  src/storage/mutate/AddVerticesProcessor.cpp
Labels: ready-for-testing, ready for review, cherry-pick-v3.2

#4354 Cherry pick v3.2.0 (0616-0627)
  .github/workflows/nightly.yml
  .github/workflows/rc.yml
  src/common/base/ObjectPool.h
  src/daemons/MetaDaemon.cpp
  src/daemons/StandAloneDaemon.cpp
  src/graph/executor/algo/BatchShortestPath.cpp
  src/graph/executor/algo/ShortestPathBase.cpp
  src/graph/executor/algo/ShortestPathBase.h
  src/graph/executor/algo/SingleShortestPath.cpp
  src/graph/optimizer/rule/CollapseProjectRule.cpp
  src/graph/optimizer/rule/GetEdgesTransformAppendVerticesLimitRule.cpp
  src/graph/optimizer/rule/GetEdgesTransformRule.cpp
  src/graph/optimizer/rule/GetEdgesTransformUtils.h
  src/meta/RootUserMan.h
  src/meta/processors/job/JobManager.cpp
  src/meta/processors/job/JobManager.h
  src/meta/test/GetStatsTest.cpp
  src/meta/test/JobManagerTest.cpp
  src/storage/mutate/AddEdgesProcessor.cpp
  src/storage/mutate/AddVerticesProcessor.cpp
  src/webservice/GetFlagsHandler.cpp
  src/webservice/GetStatsHandler.cpp
  src/webservice/Router.cpp
  src/webservice/SetFlagsHandler.cpp
  src/webservice/StatusHandler.cpp
Labels: ready-for-testing

#4355 enhance nightly tck test job
  .github/workflows/nightly.yml
  .github/workflows/rc.yml
  tests/Makefile
  tests/common/nebula_service.py
  tests/nebula-test-run.py
Labels: ready-for-testing

#4360 fix_multithread_bug
  src/graph/executor/algo/ShortestPathBase.cpp
Labels: ready-for-testing, type/bug, ready for review, cherry-pick-v3.2

#4356 Enable codeql analysis
  .github/workflows/codeql-analysis.yml
Labels: ready-for-testing, ready for review

#4361 Implement inner parallel procesing by using Scatter/Gather model.
  .github/workflows/nightly.yml
  src/graph/context/Iterator.cpp
  src/graph/context/Iterator.h
  src/graph/executor/Executor.cpp
  src/graph/executor/Executor.h
  src/graph/executor/query/AppendVerticesExecutor.cpp
  src/graph/executor/query/AppendVerticesExecutor.h
  src/graph/executor/query/FilterExecutor.cpp
  src/graph/executor/query/FilterExecutor.h
  src/graph/executor/query/InnerJoinExecutor.cpp
  src/graph/executor/query/InnerJoinExecutor.h
  src/graph/executor/query/JoinExecutor.cpp
  src/graph/executor/query/JoinExecutor.h
  src/graph/executor/query/LeftJoinExecutor.cpp
  src/graph/executor/query/LeftJoinExecutor.h
  src/graph/executor/query/ProjectExecutor.cpp
  src/graph/executor/query/ProjectExecutor.h
  src/graph/executor/query/TraverseExecutor.cpp
  src/graph/executor/query/TraverseExecutor.h
  src/graph/service/GraphFlags.cpp
  src/graph/service/GraphFlags.h
  tests/Makefile
  tests/common/nebula_service.py
  tests/nebula-test-run.py
  tests/tck/features/optimizer/PrunePropertiesRule.feature
Labels: ready-for-testing, cherry-pick-v3.2

#4362 Async gc.
  .github/workflows/nightly.yml
  src/common/expression/test/CMakeLists.txt
  src/common/thread/GenericThreadPool.h
  src/daemons/CMakeLists.txt
  src/graph/CMakeLists.txt
  src/graph/context/CMakeLists.txt
  src/graph/context/ExecutionContext.cpp
  src/graph/context/test/CMakeLists.txt
  src/graph/executor/test/CMakeLists.txt
  src/graph/gc/CMakeLists.txt
  src/graph/gc/GC.cpp
  src/graph/gc/GC.h
  src/graph/optimizer/test/CMakeLists.txt
  src/graph/planner/test/CMakeLists.txt
  src/graph/service/GraphFlags.cpp
  src/graph/service/GraphFlags.h
  src/graph/util/test/CMakeLists.txt
  src/graph/validator/test/CMakeLists.txt
  src/graph/visitor/test/CMakeLists.txt
  src/parser/test/CMakeLists.txt
Labels: ready-for-testing, cherry-pick-v3.2
