Repository vesoft-inc/nebula, pull requests merged in 2022-11, with the labels that each got.

#4813 [BUG] Fix wrong output when returning a pattern
  src/graph/planner/match/WhereClausePlanner.cpp
  tests/tck/features/match/PathExpr.feature
Labels: ready-for-testing, type/bug, ready for review

#4814 [enhancement] Add indents to storage details when profiling a query
  src/graph/executor/StorageAccessExecutor.cpp
Labels: type/enhancement, ready-for-testing, ready for review

#4825 Filter should keep column names.
  src/graph/optimizer/rule/PushFilterDownProjectRule.cpp
Labels: ready-for-testing, type/bug, cherry-pick-v3.3

#4798 Fix match index selection related to parameter in expression
  src/graph/util/ExpressionUtils.cpp
  src/graph/validator/MatchValidator.cpp
  src/graph/visitor/VidExtractVisitor.cpp
  tests/tck/features/yield/parameter.feature
Labels: ready-for-testing, ready for review

#4832 Modify edge behavior of rpc interface `getProps`
  src/storage/query/GetPropProcessor.cpp
  src/storage/test/GetPropTest.cpp
Labels: ready-for-testing, ready for review

#4841 Fix some filter don't push down project.
  src/graph/util/ExpressionUtils.cpp
  tests/tck/features/bugfix/PredicationPushDownInGo.feature
Labels: ready-for-testing, type/bug

#4850 Fix/inner variable race condition
  src/graph/planner/match/MatchSolver.cpp
  src/graph/util/ParserUtil.cpp
  src/graph/validator/MatchValidator.cpp
  src/parser/MatchPath.h
  tests/tck/features/bugfix/InnerVar.feature
  tests/tck/features/optimizer/PushFilterDownGetNbrsRule.feature
Labels: ready-for-testing, type/bug

#4855 Add implicit bool checking in expr predication.
  src/common/expression/ListComprehensionExpression.cpp
  src/common/expression/PredicateExpression.cpp
  tests/tck/features/bugfix/BoolCheckingInExpr.feature
Labels: ready-for-testing, type/bug

#4863 Fix filter push down project.
  src/graph/optimizer/rule/PushFilterDownProjectRule.cpp
  tests/tck/features/bugfix/PushFilterDownProject.feature
Labels: ready-for-testing, type/bug

#4861 catch up ent
  src/kvstore/Listener.cpp
  src/kvstore/Listener.h
  src/kvstore/Part.cpp
  src/kvstore/Part.h
  src/kvstore/raftex/RaftPart.cpp
  src/kvstore/raftex/RaftPart.h
  src/kvstore/raftex/test/TestShard.h
  src/kvstore/test/DiskManagerTest.cpp
  src/kvstore/wal/AtomicLogBuffer.h
  src/kvstore/wal/FileBasedWal.cpp
  src/kvstore/wal/FileBasedWal.h
  src/kvstore/wal/test/FileBasedWalTest.cpp
  src/kvstore/wal/test/WalFileIterTest.cpp
Labels: ready-for-testing

#4872 unify time format in show job
  src/graph/executor/admin/SubmitJobExecutor.cpp
Labels: ready-for-testing

#4883 correct covarage
  .github/workflows/nightly.yml
  .github/workflows/pull_request.yml
Labels: ready-for-testing

#4878 add jobs info to meta dump tool
  src/tools/meta-dump/MetaDumpTool.cpp
Labels: ready-for-testing

#4840 [bugfix] security: fix check grant god when FLAGS_enable_authorize is…
  src/graph/service/PermissionManager.cpp
  tests/tck/cluster/Example.feature
Labels: ready-for-testing

#4858 modify outdated gmock interface
  src/meta/test/MockAdminClient.h
  src/storage/exec/UpdateNode.h
Labels: ready-for-testing

#4846 fix wrong expr evaluation on bool-type property in with
  src/common/expression/AttributeExpression.cpp
  tests/tck/features/expression/Attribute.feature
  tests/tck/features/match/With.feature
  tests/tck/features/optimizer/PrunePropertiesRule.feature
Labels: ready-for-testing, ready for review

#4887 Profile storage GetDstBySrcProcessor
  src/storage/context/StorageExpressionContext.h
  src/storage/exec/GetDstBySrcNode.h
  src/storage/exec/StoragePlan.h
  src/storage/mutate/UpdateEdgeProcessor.h
  src/storage/mutate/UpdateVertexProcessor.h
  src/storage/query/GetDstBySrcProcessor.cpp
  src/storage/query/GetDstBySrcProcessor.h
  src/storage/query/GetNeighborsProcessor.cpp
  src/storage/query/GetNeighborsProcessor.h
  src/storage/query/QueryBaseProcessor-inl.h
  src/storage/query/QueryBaseProcessor.h
Labels: type/enhancement, ready-for-testing

#4893 fix Nan & Infinity comparison And Value's operator/ & operator%
  src/common/datatypes/Value.cpp
  src/common/datatypes/Value.h
  src/common/datatypes/test/ValueTest.cpp
  src/common/expression/RelationalExpression.cpp
  src/common/expression/test/ArithmeticExpressionTest.cpp
  src/common/expression/test/TestBase.h
  src/common/function/FunctionManager.cpp
  src/common/function/test/FunctionManagerTest.cpp
  tests/common/comparator.py
  tests/tck/features/bugfix/NaNInfinityFloat.feature
  tests/tck/features/parser/nebula.feature
  tests/tck/utils/nbv.py
Labels: ready-for-testing, ready for review

#4899 fix nightly coverage oom
  .github/workflows/nightly.yml
  .github/workflows/pull_request.yml
Labels: ready-for-testing, ready for review

#4895 Fix graph profiling data format
  src/common/datatypes/HostAddr.h
  src/graph/executor/StorageAccessExecutor.cpp
  src/graph/executor/StorageAccessExecutor.h
  src/graph/executor/algo/ShortestPathBase.cpp
  src/graph/executor/algo/ShortestPathBase.h
  src/graph/executor/algo/SubgraphExecutor.cpp
  src/graph/executor/query/GetDstBySrcExecutor.cpp
  src/graph/executor/query/GetNeighborsExecutor.cpp
  src/graph/executor/query/TraverseExecutor.cpp
  src/graph/util/CMakeLists.txt
  src/graph/util/Utils.cpp
  src/graph/util/Utils.h
  src/storage/query/GetDstBySrcProcessor.cpp
  tests/common/plan_differ.py
  tests/tck/conftest.py
  tests/tck/features/explain/ExplainAndProfile.feature
Labels: type/enhancement, ready-for-testing

#4891 use libcurl
  src/codec/test/CMakeLists.txt
  src/common/expression/test/CMakeLists.txt
  src/common/http/HttpClient.cpp
  src/common/http/HttpClient.h
  src/common/http/test/CMakeLists.txt
  src/common/http/test/HttpClientTest.cpp
  src/common/id/test/CMakeLists.txt
  src/common/plugin/fulltext/FTUtils.h
  src/common/plugin/fulltext/elasticsearch/ESGraphAdapter.cpp
  src/common/plugin/fulltext/elasticsearch/ESStorageAdapter.cpp
  src/daemons/CMakeLists.txt
  src/graph/context/test/CMakeLists.txt
  src/graph/executor/test/CMakeLists.txt
  src/graph/optimizer/test/CMakeLists.txt
  src/graph/service/CloudAuthenticator.cpp
  src/graph/util/test/CMakeLists.txt
  src/graph/validator/test/CMakeLists.txt
  src/graph/visitor/test/CMakeLists.txt
  src/kvstore/test/CMakeLists.txt
  src/meta/CMakeLists.txt
  src/meta/http/MetaHttpReplaceHostHandler.cpp
  src/meta/processors/job/JobManager.cpp
  src/parser/test/CMakeLists.txt
  src/storage/test/CMakeLists.txt
  src/storage/test/StorageHttpAdminHandlerTest.cpp
  src/storage/test/StorageHttpPropertyHandlerTest.cpp
  src/storage/test/StorageHttpStatsHandlerTest.cpp
  src/tools/CMakeLists.txt
  src/tools/db-dump/CMakeLists.txt
  src/tools/db-upgrade/CMakeLists.txt
  src/tools/meta-dump/CMakeLists.txt
  src/tools/storage-perf/CMakeLists.txt
  src/webservice/test/CMakeLists.txt
  src/webservice/test/StatusHandlerTest.cpp
  src/webservice/test/TestUtils.h
Labels: ready-for-testing, ready for review

#4896 fix validateHostOrIp fail when one device has more than one ip
  src/common/network/NetworkUtils.cpp
  src/common/network/NetworkUtils.h
  src/common/network/test/NetworkUtilsTest.cpp
Labels: ready-for-testing, ready for review

#4888 remove job entries when drop space && check space exist when check jo…
  src/meta/processors/job/JobManager.cpp
  src/meta/processors/job/JobManager.h
  src/meta/processors/job/ReportTaskProcessor.cpp
  src/meta/processors/parts/DropSpaceProcessor.cpp
Labels: ready-for-testing

#4884 Fix wrong properties prune in `length` function.
  src/graph/visitor/PropertyTrackerVisitor.cpp
  tests/tck/features/bugfix/NullInputOfLength.feature
  tests/tck/features/optimizer/PrunePropertiesRule.feature
Labels: ready-for-testing, type/bug

#4902 remove redundant logic in GetDstBySrc
  src/storage/exec/EdgeNode.h
  src/storage/exec/GetDstBySrcNode.h
  src/storage/exec/StorageIterator.h
  src/storage/query/GetDstBySrcProcessor.cpp
Labels: ready-for-testing, ready for review

#4885 Avoid drop root user.
  src/graph/validator/ACLValidator.cpp
  src/graph/validator/ACLValidator.h
  tests/tck/features/bugfix/DropRootUser.feature
Labels: ready-for-testing, type/bug

#4823 Fix extract filter.
  src/graph/visitor/ExtractFilterExprVisitor.cpp
  tests/tck/features/bugfix/ExtractFilter.feature
Labels: ready-for-testing, type/bug

#4849 fix restart if the process is stopped
  scripts/nebula.service
Labels: ready-for-testing

#4901 Fold constant for List/Set expression
  src/graph/optimizer/OptimizerUtils.cpp
  src/graph/optimizer/rule/OptimizeEdgeIndexScanByFilterRule.cpp
  src/graph/optimizer/rule/OptimizeTagIndexScanByFilterRule.cpp
  src/graph/optimizer/rule/UnionAllIndexScanBaseRule.cpp
  src/graph/util/ExpressionUtils.cpp
  src/graph/validator/LookupValidator.cpp
  src/graph/visitor/FoldConstantExprVisitor.cpp
  src/graph/visitor/test/FoldConstantExprVisitorTest.cpp
Labels: ready-for-testing, ready for review

#4905 reduce link threads to avoid OOM
  .github/workflows/pull_request.yml
Labels: ready-for-testing

#4903 fix typo
  README-CN.md
  README.md
  docs/rfcs/0000-template.md
  src/graph/context/Symbols.cpp
  src/graph/executor/admin/SubmitJobExecutor.cpp
  src/graph/executor/algo/MultiShortestPathExecutor.cpp
  src/graph/optimizer/rule/MergeGetNbrsAndProjectRule.h
  src/graph/planner/Planner.h
  src/graph/planner/match/MatchPathPlanner.cpp
  src/graph/util/ExpressionUtils.cpp
  src/graph/util/FTIndexUtils.h
  src/graph/util/IndexUtil.h
  src/graph/util/ValidateUtil.h
  src/graph/validator/MatchValidator.cpp
  src/graph/validator/MutateValidator.cpp
  src/graph/visitor/PropertyTrackerVisitor.cpp
  src/graph/visitor/test/FilterTransformTest.cpp
  src/interface/common.thrift
  src/meta/processors/admin/AdminClient.cpp
  tests/common/nebula_test_suite.py
  tests/conftest.py
  tests/tck/cluster/terminate.feature
  tests/tck/features/go/SimpleCase.feature
  tests/tck/features/insert/insertVertexOnly.feature
  tests/tck/features/optimizer/MergeGetNbrsDedupProjectRule.feature
  tests/tck/features/optimizer/PrunePropertiesRule.feature
Labels: ready-for-testing

#4864 Fix two crash issues caused by the optimizer's filter push-down rules
  src/graph/optimizer/rule/PushFilterDownAggregateRule.cpp
  src/graph/optimizer/rule/PushFilterDownProjectRule.cpp
  src/graph/planner/plan/PlanNode.cpp
  src/graph/planner/plan/PlanNode.h
  src/graph/planner/plan/Query.cpp
  src/graph/planner/plan/Query.h
  src/graph/visitor/PrunePropertiesVisitor.cpp
  tests/tck/features/bugfix/MatchCrash.feature
  tests/tck/features/optimizer/PushFilterDownAggregateRule.feature
  tests/tck/features/optimizer/PushFilterDownProjectRule.feature
Labels: ready-for-testing, ready for review

#4913 make evaluation of inner var expr thread-safe
  src/common/context/ExpressionContext.h
  src/common/expression/ListComprehensionExpression.cpp
  src/common/expression/PredicateExpression.cpp
  src/common/expression/ReduceExpression.cpp
  src/common/expression/VariableExpression.cpp
  src/common/expression/VariableExpression.h
  src/common/expression/test/ExpressionContextMock.h
  src/common/expression/test/ListComprehensionExpressionTest.cpp
  src/common/expression/test/PredicateExpressionTest.cpp
  src/common/expression/test/ReduceExpressionTest.cpp
  src/common/utils/DefaultValueContext.h
  src/graph/context/QueryExpressionContext.cpp
  src/graph/context/QueryExpressionContext.h
  src/graph/planner/match/MatchSolver.cpp
  src/graph/util/ParserUtil.cpp
  src/graph/visitor/ValidatePatternExpressionVisitor.cpp
  src/graph/visitor/test/VisitorTestBase.h
  src/storage/context/StorageExpressionContext.cpp
  src/storage/context/StorageExpressionContext.h
  src/storage/exec/IndexExprContext.h
Labels: ready-for-testing, ready for review

#4915 fix update config
  src/common/meta/GflagsManager.cpp
  tests/admin/test_configs.py
Labels: ready-for-testing

#4918 Fix prune properties.
  src/graph/visitor/PropertyTrackerVisitor.cpp
  tests/tck/features/bugfix/NullProp.feature
Labels: ready-for-testing, type/bug

#4927 Refactor listener related interface and data structure
  src/clients/meta/MetaClient.cpp
  src/clients/meta/MetaClient.h
  src/common/meta/Common.h
  src/kvstore/Listener.cpp
  src/kvstore/Listener.h
  src/kvstore/ListenerFactory.h
  src/kvstore/NebulaStore.cpp
  src/kvstore/NebulaStore.h
  src/kvstore/PartManager.cpp
  src/kvstore/PartManager.h
  src/kvstore/plugins/elasticsearch/ESListener.h
  src/kvstore/test/NebulaListenerTest.cpp
  src/kvstore/test/NebulaStoreTest.cpp
  src/meta/test/MetaClientTest.cpp
Labels: ready-for-testing, ready for review

#4923 Fix multiple match joined on edge produce wrong result
  src/common/datatypes/Edge.cpp
  src/common/datatypes/Edge.h
  src/common/datatypes/test/EdgeTest.cpp
  src/common/function/FunctionManager.cpp
  src/graph/context/ast/CypherAstContext.h
  src/graph/planner/match/MatchPathPlanner.cpp
  src/graph/planner/match/MatchPlanner.cpp
  src/graph/planner/match/MatchPlanner.h
  src/graph/planner/match/SegmentsConnector.cpp
  src/graph/validator/MatchValidator.cpp
  tests/tck/features/bugfix/MatchJoinOnEdge.feature
Labels: ready-for-testing, ready for review

#4932 fix argument
  src/graph/executor/logic/ArgumentExecutor.cpp
  src/graph/planner/match/MatchPathPlanner.cpp
Labels: ready-for-testing

#4912 Ci listener
  .github/workflows/nightly.yml
  .github/workflows/pull_request.yml
  conf/nebula-storaged-listener.conf.default
  tests/README.md
  tests/common/nebula_service.py
  tests/nebula-test-run.py
  tests/tck/cluster/Example.feature
  tests/tck/cluster/terminate.feature
  tests/tck/conftest.py
  tests/tck/features/admin/Authentication.feature
  tests/tck/features/admin/Sessions.feature
Labels: ready-for-testing

#4931 Minor enhancement about listener
  src/kvstore/Listener.cpp
  src/kvstore/Listener.h
  src/kvstore/NebulaStore.cpp
  src/kvstore/NebulaStore.h
  src/kvstore/plugins/elasticsearch/ESListener.h
  src/kvstore/test/NebulaListenerTest.cpp
Labels: ready-for-testing, ready for review

#4868 allow redefined aliases in with.
  src/graph/validator/MatchValidator.cpp
  tests/tck/features/match/RedefinedNode.feature
Labels: ready-for-testing, ready for review

#4933 fix folly::stringPrintf when ref empty str
  src/storage/exec/UpdateResultNode.h
  src/storage/test/UpdateVertexTest.cpp
  tests/README.md
  tests/tck/features/update/Update.feature
Labels: ready-for-testing

#4939 Fix the dependency of argument plan node
  src/graph/executor/logic/ArgumentExecutor.cpp
  src/graph/planner/match/MatchPathPlanner.cpp
  src/graph/planner/plan/Logic.cpp
  tests/Makefile
  tests/tck/features/bugfix/ArgumentPlanNodeDep.feature
  tests/tck/features/optimizer/PrunePropertiesRule.feature
Labels: ready-for-testing

#4907 Remove all UNKNOWN_PROP as a type of null.
  src/codec/RowReaderV1.cpp
  src/codec/RowReaderV2.cpp
  src/common/datatypes/Map.h
  src/common/datatypes/Value.cpp
  src/common/datatypes/Value.h
  src/common/datatypes/test/ValueTest.cpp
  src/common/datatypes/test/ValueToJsonTest.cpp
  src/common/expression/AttributeExpression.cpp
  src/common/expression/test/AttributeExpressionTest.cpp
  src/common/expression/test/SubscriptExpressionTest.cpp
  src/common/time/TimeUtils.h
  src/common/utils/IndexKeyUtils.cpp
  src/interface/common.thrift
  src/storage/exec/IndexEdgeScanNode.cpp
  src/storage/exec/IndexVertexScanNode.cpp
  src/storage/exec/QueryUtils.h
  src/tools/db-upgrade/DbUpgrader.cpp
  tests/common/nebula_test_suite.py
  tests/tck/features/expression/Attribute.feature
  tests/tck/features/match/With.feature
  tests/tck/features/optimizer/PrunePropertiesRule.feature
  tests/tck/features/parser/nebula.feature
  tests/tck/utils/nbv.py
Labels: ready-for-testing

#4941 fix SubGraph edge type in filter does not exist in tranversed edge type
  src/graph/context/ast/QueryAstContext.h
  src/graph/validator/GetSubgraphValidator.cpp
  tests/tck/features/subgraph/subgraph.feature
Labels: ready-for-testing, ready for review

#4944 add auto label
  .github/workflows/check_label.yml
Labels: ready-for-testing

#4859 fix some rocksdb api will fail in PlainTable
  src/kvstore/NebulaStore.cpp
  src/kvstore/RocksEngine.cpp
  src/kvstore/RocksEngine.h
  src/kvstore/RocksEngineConfig.cpp
  src/kvstore/test/RocksEngineTest.cpp
Labels: ready-for-testing

#4949 Fix property pruner do not parse none exist tag correctly
  src/clients/meta/MetaClient.cpp
  src/graph/validator/test/MockSchemaManager.cpp
  src/graph/visitor/PrunePropertiesVisitor.cpp
  src/meta/test/MetaClientTest.cpp
  tests/tck/features/mutate/ClearSpace.feature
  tests/tck/features/optimizer/PrunePropertiesRule.feature
  tests/tck/features/schema/Schema.feature
  tests/tck/features/yield/NoSpaceChosen.feature
  tests/tck/features/yield/return.feature
  tests/tck/features/yield/yield.IntVid.feature
  tests/tck/features/yield/yield.feature
Labels: ready-for-testing, ready for review

#4953 Reorganize the directory structure of the listener
  src/daemons/CMakeLists.txt
  src/kvstore/CMakeLists.txt
  src/kvstore/NebulaStore.cpp
  src/kvstore/NebulaStore.h
  src/kvstore/listener/CMakeLists.txt
  src/kvstore/listener/Listener.cpp
  src/kvstore/listener/Listener.h
  src/kvstore/listener/elasticsearch/ESListener.cpp
  src/kvstore/listener/elasticsearch/ESListener.h
  src/kvstore/listener/test/CMakeLists.txt
  src/kvstore/listener/test/NebulaListenerTest.cpp
  src/kvstore/plugins/CMakeLists.txt
  src/kvstore/test/CMakeLists.txt
  src/meta/CMakeLists.txt
  src/storage/test/CMakeLists.txt
  src/tools/CMakeLists.txt
Labels: ready-for-testing, ready for review

#4952 Fix graphd's crash due to lack of support of xor.
  src/graph/util/ExpressionUtils.cpp
  src/graph/util/ExpressionUtils.h
  tests/tck/features/expression/LogicalExpression.feature
Labels: ready-for-testing

#4964 fix PrunProperties tck random order
  tests/tck/features/optimizer/PrunePropertiesRule.feature
Labels: ready-for-testing, ready for review
