Repository vesoft-inc/nebula, pull requests merged in 2022-01, with the labels that each got.

#3610 Support duration default value.
  src/meta/processors/schema/SchemaUtil.cpp
  src/meta/processors/schema/SchemaUtil.h
  tests/tck/features/bugfix/CreateDurationAsDefaultValue.feature
Labels: ready-for-testing, type/bug

#3615 [Minor] Fix typos in the PR submit template
  .github/pull_request_template.md
Labels: ready-for-testing

#3613 fix fetch edges tostring
  src/parser/TraverseSentences.cpp
Labels: ready-for-testing, cherry-pick-v3.0, ready for review

#3583 fix create space assign offline host
  src/meta/processors/BaseProcessor-inl.h
  src/meta/processors/BaseProcessor.h
  src/meta/processors/admin/HBProcessor.cpp
  src/meta/processors/parts/CreateSpaceProcessor.cpp
  src/meta/processors/parts/CreateSpaceProcessor.h
  src/meta/processors/parts/ListHostsProcessor.cpp
  src/meta/processors/zone/AddHostsIntoZoneProcessor.cpp
  src/meta/processors/zone/AddHostsProcessor.cpp
  src/meta/processors/zone/DropHostsProcessor.cpp
  src/meta/processors/zone/GetZoneProcessor.cpp
  src/meta/processors/zone/RenameZoneProcessor.cpp
  src/meta/test/AuthProcessorTest.cpp
  src/meta/test/IndexProcessorTest.cpp
  src/meta/test/MetaClientTest.cpp
  src/meta/test/ProcessorTest.cpp
  src/storage/test/KVClientTest.cpp
Labels: ready-for-testing, cherry-pick-v3.0

#3600 disable an unstable test case
  src/storage/test/ChainDeleteEdgesTest.cpp
Labels: ready-for-testing, ready for review

#3618 Disable ARM version docker image since related third party not ready
  .github/workflows/nightly.yml
  .github/workflows/rc.yml
Labels: ready-for-testing, cherry-pick-v3.0

#3620 Unify raft error code
  src/graph/executor/StorageAccessExecutor.h
  src/interface/common.thrift
  src/interface/raftex.thrift
  src/kvstore/Listener.h
  src/kvstore/Part.cpp
  src/kvstore/Part.h
  src/kvstore/raftex/Host.cpp
  src/kvstore/raftex/Host.h
  src/kvstore/raftex/RaftPart.cpp
  src/kvstore/raftex/RaftPart.h
  src/kvstore/raftex/RaftexService.cpp
  src/kvstore/raftex/SnapshotManager.cpp
  src/kvstore/raftex/test/LogAppendTest.cpp
  src/kvstore/raftex/test/LogCASTest.cpp
  src/storage/admin/AdminProcessor.h
Labels: ready-for-testing, cherry-pick-v3.0

#3540 Meta upgrader v3
  src/clients/meta/MetaClient.h
  src/common/function/FunctionManager.cpp
  src/daemons/CMakeLists.txt
  src/daemons/MetaDaemonInit.cpp
  src/graph/executor/query/LeftJoinExecutor.cpp
  src/graph/planner/match/ScanSeek.cpp
  src/kvstore/plugins/hbase/HBaseClient.cpp
  src/meta/CMakeLists.txt
  src/meta/MetaVersionMan.cpp
  src/meta/MetaVersionMan.h
  src/meta/processors/admin/ListClusterInfoProcessor.cpp
  src/meta/processors/job/DataBalanceJobExecutor.cpp
  src/meta/processors/job/ZoneBalanceJobExecutor.cpp
  src/meta/processors/zone/ListZonesProcessor.cpp
  src/meta/processors/zone/MergeZoneProcessor.cpp
  src/meta/test/MetaClientTest.cpp
  src/meta/test/ProcessorTest.cpp
  src/meta/upgrade/CMakeLists.txt
  src/meta/upgrade/MetaDataUpgrade.cpp
  src/meta/upgrade/MetaDataUpgrade.h
  src/meta/upgrade/v2/CMakeLists.txt
  src/meta/upgrade/v2/MetaServiceUtilsV2.cpp
  src/meta/upgrade/v2/MetaServiceUtilsV2.h
  src/meta/upgrade/v2/meta.thrift
  src/storage/http/StorageHttpDownloadHandler.cpp
  src/storage/test/CMakeLists.txt
  src/tools/db-dump/CMakeLists.txt
  src/tools/db-upgrade/CMakeLists.txt
  src/tools/meta-dump/CMakeLists.txt
  src/tools/simple-kv-verify/CMakeLists.txt
  src/tools/storage-perf/CMakeLists.txt
Labels: ready-for-testing, cherry-pick-v3.0

#3628 Add more check about parse host result
  src/meta/processors/parts/CreateSpaceProcessor.cpp
Labels: ready-for-testing, cherry-pick-v3.0

#3634 support bottom level compression
  src/kvstore/RocksEngineConfig.cpp
  src/kvstore/RocksEngineConfig.h
  src/kvstore/test/RocksEngineConfigTest.cpp
Labels: ready-for-testing, ready for review

#3616 fix service crash
  src/daemons/GraphDaemon.cpp
  src/daemons/MetaDaemon.cpp
  src/daemons/StorageDaemon.cpp
Labels: ready-for-testing, cherry-pick-v3.0

#3622 Cleanup branch param in package script
  .github/workflows/rc.yml
  package/package.sh
Labels: ready-for-testing, cherry-pick-v3.0

#3606 fix crash when the expression exceed the depth
  src/graph/util/ExpressionUtils.cpp
  src/graph/util/ExpressionUtils.h
  src/parser/parser.yy
  src/parser/test/ParserBenchmark.cpp
  tests/tck/features/expression/Depth.feature
Labels: ready-for-testing, cherry-pick-v3.0, ready for review

#3641 Remove deprecated function calling.
  src/meta/MetaVersionMan.cpp
Labels: ready-for-testing

#3626 Fix the column index in lexer.
  src/parser/scanner.lex
  src/parser/test/ScannerTest.cpp
  tests/tck/features/match/PipeAndVariable.feature
Labels: ready-for-testing, type/bug

#3629 Enhance login password check
  src/clients/meta/MetaClient.cpp
  src/clients/meta/MetaClient.h
Labels: ready-for-testing, type/bug, cherry-pick-v3.0, ready for review

#3627 fix_batch_insert_problem
  src/storage/mutate/AddEdgesProcessor.cpp
  src/storage/mutate/AddEdgesProcessor.h
  src/storage/mutate/AddVerticesProcessor.cpp
  src/storage/mutate/AddVerticesProcessor.h
  tests/tck/features/insert/InsertIfNotExists.feature
  tests/tck/features/lookup/LookUp.feature
Labels: ready-for-testing, type/bug, cherry-pick-v3.0, ready for review

#3621 add notifyStop() for metaClient
  src/clients/meta/MetaClient.cpp
  src/clients/meta/MetaClient.h
  src/mock/MockCluster.h
  src/storage/StorageServer.cpp
  src/tools/storage-perf/StoragePerfTool.cpp
Labels: ready-for-testing, cherry-pick-v3.0

#3648 Fix retry in tck.
  tests/common/utils.py
Labels: ready-for-testing

#3651 Fix remove session
  src/graph/session/GraphSessionManager.cpp
Labels: ready-for-testing, type/bug, cherry-pick-v3.0

#3553 Issue3373 storage exit crash
  src/clients/meta/MetaClient.cpp
  src/clients/meta/MetaClient.h
  src/storage/test/ChainTestUtils.h
  src/storage/test/KillQueryTest.cpp
Labels: ready-for-testing, cherry-pick-v3.0

#3653 Fix coalesce bug
  src/common/function/FunctionManager.cpp
  src/common/function/test/FunctionManagerTest.cpp
  tests/tck/features/function/coalesce.feature
Labels: ready-for-testing, cherry-pick-v3.0, ready for review

#3647 delete double check agg in where clause
  src/parser/parser.yy
Labels: ready-for-testing, cherry-pick-v3.0, ready for review

#3660 fix meta crash after create space
  src/meta/processors/parts/CreateSpaceProcessor.cpp
Labels: ready-for-testing, type/bug, cherry-pick-v3.0

#3576 add LogMonitor to check log disk freeBytes and change log level when space is almost full
  src/common/CMakeLists.txt
  src/common/log/CMakeLists.txt
  src/common/log/LogMonitor.cpp
  src/common/log/LogMonitor.h
  src/daemons/CMakeLists.txt
  src/storage/StorageServer.cpp
  src/storage/StorageServer.h
Labels: ready-for-testing, cherry-pick-v3.0, ready for review

#3504 Push aggregate in LookupIndex
  src/interface/storage.thrift
  src/meta/processors/BaseProcessor-inl.h
  src/storage/BaseProcessor-inl.h
  src/storage/BaseProcessor.h
  src/storage/CMakeLists.txt
  src/storage/exec/IndexAggregateNode.cpp
  src/storage/exec/IndexAggregateNode.h
  src/storage/exec/IndexExprContext.h
  src/storage/exec/IndexNode.h
  src/storage/exec/IndexProjectionNode.cpp
  src/storage/exec/IndexSelectionNode.cpp
  src/storage/exec/IndexSelectionNode.h
  src/storage/index/LookupProcessor.cpp
  src/storage/index/LookupProcessor.h
  src/storage/query/GetNeighborsProcessor.cpp
  src/storage/query/GetNeighborsProcessor.h
  src/storage/test/LookupIndexTest.cpp
  src/storage/test/QueryTestUtils.h
Labels: ready-for-testing, ready for review

#3537 Ldbc test cases.
  .github/workflows/pull_request.yml
  tests/Makefile
  tests/common/utils.py
  tests/conftest.py
  tests/data/ldbc_v0_3_3/config.yaml
  tests/tck/conftest.py
  tests/tck/ldbc/business_intelligence_workload/Read.feature
  tests/tck/ldbc/interactive_workload/ComplexReads.feature
  tests/tck/ldbc/interactive_workload/ShortReads.feature
  tests/tck/steps/test_ldbc.py
Labels: ready-for-testing, cherry-pick-v3.0

#3678 fix issue 3675
  src/clients/meta/MetaClient.cpp
  src/common/graph/Response.h
  src/interface/common.thrift
  src/meta/processors/parts/CreateSpaceProcessor.cpp
  src/meta/processors/parts/CreateSpaceProcessor.h
  src/meta/test/ProcessorTest.cpp
Labels: ready-for-testing, cherry-pick-v3.0

#3685 fix clang compile failed
  src/storage/index/LookupProcessor.cpp
  src/storage/test/LookupIndexTest.cpp
Labels: ready-for-testing, cherry-pick-v3.0

#3614 Fix expression rewrite
  conf/nebula-graphd.conf.default
  conf/nebula-graphd.conf.production
  src/graph/util/ExpressionUtils.cpp
  src/graph/visitor/DeduceTypeVisitor.cpp
  src/graph/visitor/test/FilterTransformTest.cpp
  src/graph/visitor/test/RewriteRelExprVisitorTest.cpp
  tests/tck/features/match/Base.IntVid.feature
  tests/tck/features/match/Base.feature
  tests/tck/features/match/SeekById.feature
Labels: ready-for-testing, type/bug, cherry-pick-v3.0, ready for review

#3699 fix divide zone should be failed if two zones use the same host
  src/meta/processors/zone/DivideZoneProcessor.cpp
  src/meta/test/MetaClientTest.cpp
  src/meta/test/ProcessorTest.cpp
Labels: ready-for-testing, cherry-pick-v3.0

#3703 Support more check about merge zone arguments
  src/meta/processors/zone/MergeZoneProcessor.cpp
  src/meta/test/MetaClientTest.cpp
  src/meta/test/ProcessorTest.cpp
Labels: ready-for-testing

#3694 fix match index
  src/graph/optimizer/rule/IndexScanRule.cpp
  src/graph/planner/match/LabelIndexSeek.cpp
  src/graph/planner/match/VertexIdSeek.cpp
  src/graph/util/ExpressionUtils.cpp
  src/graph/visitor/VidExtractVisitor.cpp
  src/graph/visitor/test/FilterTransformTest.cpp
  src/storage/exec/IndexScanNode.h
  tests/tck/features/match/SeekById.feature
  tests/tck/features/match/SeekById.intVid.feature
  tests/tck/features/optimizer/IndexScanRule.feature
Labels: ready-for-testing, type/bug, priority/hi-pri, cherry-pick-v3.0, ready for review

#3666 fix issue 3601
  src/clients/meta/MetaClient.cpp
  src/clients/meta/MetaClient.h
  src/codec/RowWriterV2.cpp
  src/codec/test/ResultSchemaProvider.cpp
  src/codec/test/ResultSchemaProvider.h
  src/codec/test/SchemaWriter.cpp
  src/common/meta/NebulaSchemaProvider.cpp
  src/common/meta/NebulaSchemaProvider.h
  src/common/meta/SchemaProviderIf.h
  src/common/utils/IndexKeyUtils.cpp
  src/common/utils/test/CMakeLists.txt
  src/graph/util/SchemaUtil.cpp
  src/graph/util/SchemaUtil.h
  src/graph/validator/MaintainValidator.cpp
  src/graph/validator/MutateValidator.cpp
  src/mock/MockData.cpp
  src/storage/exec/QueryUtils.h
  src/storage/exec/UpdateNode.h
  src/storage/test/IndexWithTTLTest.cpp
  src/storage/transaction/ChainAddEdgesLocalProcessor.cpp
Labels: ready-for-testing, cherry-pick-v3.0

#3734 fix meta upgrade for multi instance
  src/daemons/MetaDaemonInit.cpp
  src/meta/MetaVersionMan.cpp
  src/meta/MetaVersionMan.h
  src/meta/upgrade/MetaDataUpgrade.cpp
  src/meta/upgrade/MetaDataUpgrade.h
Labels: ready-for-testing

#3735 Fix race of create tag and edge
  src/codec/RowReaderV2.h
  src/graph/planner/match/MatchPlanner.h
  src/meta/processors/Common.h
  src/meta/processors/index/FTIndexProcessor.cpp
  src/meta/processors/parts/CreateSpaceAsProcessor.cpp
  src/meta/processors/schema/AlterEdgeProcessor.cpp
  src/meta/processors/schema/AlterTagProcessor.cpp
  src/meta/processors/schema/CreateEdgeProcessor.cpp
  src/meta/processors/schema/CreateTagProcessor.cpp
  src/meta/processors/schema/DropEdgeProcessor.cpp
  src/meta/processors/schema/DropTagProcessor.cpp
  src/meta/processors/schema/GetEdgeProcessor.cpp
  src/meta/processors/schema/GetTagProcessor.cpp
  src/meta/processors/schema/ListEdgesProcessor.cpp
  src/meta/processors/schema/ListTagsProcessor.cpp
Labels: ready-for-testing, type/bug, ready for review

#3702 Add version for `show hosts`
  src/graph/executor/admin/ShowHostsExecutor.cpp
  tests/admin/test_show_hosts.py
  tests/tck/features/admin/Hosts.feature
  tests/tck/features/parser/Example.feature
Labels: ready-for-testing, doc affected, cherry-pick-v3.0, ready for review

#3722 Enhancement/set expression depth by flag
  src/graph/util/ExpressionUtils.cpp
  src/graph/util/ExpressionUtils.h
  src/parser/parser.yy
  tests/common/nebula_service.py
  tests/tck/features/expression/Depth.feature
Labels: ready-for-testing

#3741 Update client version to v3.0.0
  cmake/ThriftGenerate.cmake
  src/graph/service/GraphFlags.cpp
  src/graph/service/test/StandAloneTestGraphFlags.cpp
  src/interface/common.thrift
  src/interface/graph.thrift
  src/interface/meta.thrift
  src/interface/storage.thrift
  src/meta/processors/admin/VerifyClientVersionProcessor.cpp
  tests/admin/test_permission.py
  tests/common/comparator.py
  tests/common/dataset_printer.py
  tests/common/nebula_service.py
  tests/common/nebula_test_suite.py
  tests/common/path_value.py
  tests/common/utils.py
  tests/conftest.py
  tests/job/test_session.py
  tests/query/stateless/test_if_exists.py
  tests/query/stateless/test_keyword.py
  tests/query/stateless/test_range.py
  tests/tck/conftest.py
  tests/tck/steps/conftest.py
  tests/tck/utils/nbv.py
  tests/tck/utils/table.py
Labels: ready-for-testing, incompatible, cherry-pick-v3.0

#3747 Fix create fulltext index failed
  src/kvstore/raftex/RaftPart.cpp
  src/meta/processors/index/FTIndexProcessor.cpp
  src/meta/test/IndexProcessorTest.cpp
  src/meta/test/TestUtils.h
Labels: ready-for-testing, cherry-pick-v3.0, ready for review

#3662 add comments and adjust log level for meta/processors/admin
  src/meta/processors/admin/AdminClient.cpp
  src/meta/processors/admin/AdminClient.h
  src/meta/processors/admin/AgentHBProcessor.cpp
  src/meta/processors/admin/AgentHBProcessor.h
  src/meta/processors/admin/CreateBackupProcessor.cpp
  src/meta/processors/admin/CreateBackupProcessor.h
  src/meta/processors/admin/CreateSnapshotProcessor.cpp
  src/meta/processors/admin/CreateSnapshotProcessor.h
  src/meta/processors/admin/DropSnapshotProcessor.cpp
  src/meta/processors/admin/DropSnapshotProcessor.h
  src/meta/processors/admin/GetMetaDirInfoProcessor.cpp
  src/meta/processors/admin/GetMetaDirInfoProcessor.h
  src/meta/processors/admin/HBProcessor.cpp
  src/meta/processors/admin/HBProcessor.h
  src/meta/processors/admin/ListClusterInfoProcessor.cpp
  src/meta/processors/admin/ListClusterInfoProcessor.h
  src/meta/processors/admin/ListSnapshotsProcessor.cpp
  src/meta/processors/admin/ListSnapshotsProcessor.h
  src/meta/processors/admin/RestoreProcessor.cpp
  src/meta/processors/admin/RestoreProcessor.h
  src/meta/processors/admin/SnapShot.cpp
  src/meta/processors/admin/SnapShot.h
Labels: ready-for-testing

#3746 fix writternBy delete by optimizer
  src/graph/optimizer/OptGroup.cpp
  src/graph/planner/plan/PlanNode.cpp
  src/graph/planner/plan/PlanNode.h
  tests/tck/features/match/MultiQueryParts.feature
Labels: ready-for-testing, cherry-pick-v3.0

#3736 fix with & optimizer rule error
  src/common/expression/PropertyExpression.h
  src/graph/util/ExpressionUtils.cpp
  src/graph/util/ExpressionUtils.h
  src/graph/validator/MatchValidator.cpp
  src/graph/visitor/RewriteVisitor.cpp
  src/graph/visitor/RewriteVisitor.h
  tests/tck/features/match/With.feature
  tests/tck/features/optimizer/CollapseProjectRule.feature
Labels: ready-for-testing, priority/hi-pri, cherry-pick-v3.0

#3772 fix upgrade bug
  src/tools/db-upgrade/NebulaKeyUtilsV3.cpp
Labels: ready-for-testing, cherry-pick-v3.0

#3737 Support divide from itself
  src/meta/MetaVersionMan.cpp
  src/meta/processors/zone/DivideZoneProcessor.cpp
  src/meta/test/MetaClientTest.cpp
  src/meta/test/ProcessorTest.cpp
Labels: ready-for-testing, cherry-pick-v3.0

#3668 Balance fix
  src/kvstore/raftex/RaftPart.cpp
  src/kvstore/raftex/RaftexService.cpp
  src/meta/processors/job/BalanceJobExecutor.cpp
  src/meta/processors/job/BalanceJobExecutor.h
  src/meta/processors/job/BalancePlan.cpp
  src/meta/processors/job/BalancePlan.h
  src/meta/processors/job/BalanceTask.h
  src/meta/processors/job/DataBalanceJobExecutor.cpp
  src/meta/processors/job/JobManager.cpp
  src/meta/processors/job/JobManager.h
  src/meta/processors/job/ZoneBalanceJobExecutor.cpp
  src/meta/processors/job/ZoneBalanceJobExecutor.h
  src/meta/test/BalancerTest.cpp
  src/meta/test/TestUtils.h
Labels: ready-for-testing, cherry-pick-v3.0

#3363 Eliminte the useless row collect.
  src/graph/optimizer/CMakeLists.txt
  src/graph/optimizer/rule/EliminateRowCollectRule.cpp
  src/graph/optimizer/rule/EliminateRowCollectRule.h
  tests/tck/features/optimizer/PushLimitDownGetNeighborsRule.feature
  tests/tck/features/optimizer/PushLimitDownProjectRule.feature
  tests/tck/features/optimizer/PushLimitDownScanEdgesRule.feature
  tests/tck/features/optimizer/PushLimitDownScanVerticesRule.feature
Labels: ready-for-testing

#3717 Add snapshot for prefix iterate.
  src/kvstore/KVEngine.h
  src/kvstore/KVStore.h
  src/kvstore/NebulaSnapshotManager.cpp
  src/kvstore/NebulaSnapshotManager.h
  src/kvstore/NebulaStore.cpp
  src/kvstore/NebulaStore.h
  src/kvstore/PartManager.h
  src/kvstore/RocksEngine.cpp
  src/kvstore/RocksEngine.h
  src/kvstore/plugins/hbase/HBaseStore.cpp
  src/kvstore/plugins/hbase/HBaseStore.h
  src/kvstore/test/NebulaStoreTest.cpp
  src/storage/test/IndexTestUtil.h
  src/tools/db-upgrade/DbUpgrader.cpp
Labels: ready-for-testing, cherry-pick-v3.0

#3693 Read lock zone when create space.
  src/meta/processors/parts/CreateSpaceProcessor.cpp
Labels: ready-for-testing, type/bug

#3705 suppress undesired ASAN error
  src/common/base/SanitizerOptions.cpp
  src/storage/test/StorageHttpPropertyHandlerTest.cpp
  tests/query/stateless/test_admin.py
Labels: ready-for-testing, cherry-pick-v3.0

#3787 fix upgrade
  src/tools/db-upgrade/DbUpgrader.cpp
Labels: ready-for-testing, cherry-pick-v3.0

#3791 cherry pick: fix meta upgrade for multi instance (#3734)
  src/daemons/MetaDaemonInit.cpp
  src/meta/MetaVersionMan.cpp
  src/meta/MetaVersionMan.h
  src/meta/upgrade/MetaDataUpgrade.cpp
  src/meta/upgrade/MetaDataUpgrade.h
Labels: ready-for-testing

#3756 disable data balance
  src/graph/validator/AdminJobValidator.cpp
Labels: ready-for-testing, doc affected, cherry-pick-v3.0

#3785 Fix iterator with snapshot(parameter position)
  src/kvstore/NebulaStore.cpp
  src/tools/db-upgrade/DbUpgrader.cpp
Labels: ready-for-testing, cherry-pick-v3.0

#3796 fix ci
  .github/workflows/pull_request.yml
  tests/Makefile
Labels: ready-for-testing

#3792 cherry pick：Condition memory checks on cgroup version. (#3419)
  src/common/memory/MemoryUtils.cpp
Labels: ready-for-testing

#3793 cherry pick: Fix create fulltext index failed (#3747)
  src/meta/processors/index/FTIndexProcessor.cpp
  src/meta/test/IndexProcessorTest.cpp
  src/meta/test/TestUtils.h
Labels: ready-for-testing, ready for review

#3798 disable meta upgrade from v1 to v3 directly
  src/daemons/CMakeLists.txt
  src/daemons/MetaDaemonInit.cpp
  src/meta/CMakeLists.txt
  src/meta/MetaVersionMan.cpp
  src/meta/MetaVersionMan.h
  src/meta/upgrade/CMakeLists.txt
  src/meta/upgrade/MetaDataUpgrade.cpp
  src/meta/upgrade/MetaDataUpgrade.h
  src/meta/upgrade/v1/CMakeLists.txt
  src/meta/upgrade/v1/MetaServiceUtilsV1.cpp
  src/meta/upgrade/v1/MetaServiceUtilsV1.h
  src/meta/upgrade/v1/meta.thrift
  src/storage/test/CMakeLists.txt
  src/tools/db-dump/CMakeLists.txt
  src/tools/db-upgrade/CMakeLists.txt
  src/tools/meta-dump/CMakeLists.txt
  src/tools/simple-kv-verify/CMakeLists.txt
  src/tools/storage-perf/CMakeLists.txt
Labels: ready-for-testing, cherry-pick-v3.0

#3806 fix memory increase
  src/clients/meta/MetaClient.cpp
  src/clients/meta/MetaClient.h
  src/codec/RowWriterV2.cpp
  src/codec/test/ResultSchemaProvider.cpp
  src/codec/test/ResultSchemaProvider.h
  src/codec/test/SchemaWriter.cpp
  src/common/meta/NebulaSchemaProvider.cpp
  src/common/meta/NebulaSchemaProvider.h
  src/common/meta/SchemaProviderIf.h
  src/graph/util/SchemaUtil.cpp
  src/graph/util/SchemaUtil.h
  src/graph/validator/MaintainValidator.cpp
  src/graph/validator/MutateValidator.cpp
  src/mock/MockData.cpp
  src/storage/exec/QueryUtils.h
  src/storage/exec/UpdateNode.h
  src/storage/test/IndexWithTTLTest.cpp
  src/storage/transaction/ChainAddEdgesProcessorLocal.cpp
Labels: ready-for-testing

#3807 [Minor] Add gflag validator for client_idle_timeout_secs
  src/graph/service/GraphFlags.cpp
Labels: type/enhancement, ready-for-testing, doc affected, cherry-pick-v3.0

#3776 Disable zone commands
  src/common/meta/Common.h
  src/graph/validator/AdminValidator.cpp
  src/graph/validator/MaintainValidator.cpp
  src/graph/validator/MaintainValidator.h
  src/graph/validator/Validator.cpp
  src/parser/AdminSentences.cpp
  src/parser/AdminSentences.h
  src/parser/MaintainSentences.cpp
  src/parser/MaintainSentences.h
  src/parser/parser.yy
  tests/admin/test_space.py
  tests/common/nebula_service.py
  tests/maintain/test_zone.py
  tests/tck/features/admin/Hosts.feature
  tests/tck/features/schema/Comment.feature
Labels: ready-for-testing, cherry-pick-v3.0

#3637 Add ci for standalone compile and ut.
  .github/workflows/pull_request.yml
  src/clients/storage/StorageClientBase-inl.h
  src/daemons/CMakeLists.txt
  src/daemons/StandAloneDaemon.cpp
  src/graph/executor/test/StorageServerStub.cpp
  src/storage/GraphStorageLocalServer.cpp
  src/storage/stats/StorageStats.cpp
  tests/Makefile
  tests/common/nebula_service.py
  tests/nebula-test-run.py
  tests/pytest.ini
  tests/tck/features/admin/Authentication.feature
  tests/tck/features/admin/Sessions.feature
Labels: ready-for-testing, cherry-pick-v3.0

#3814 Fix the promise/future in traverse executor.
  src/graph/executor/query/TraverseExecutor.cpp
  src/graph/executor/query/TraverseExecutor.h
Labels: ready-for-testing, priority/hi-pri, cherry-pick-v3.0

#3827 cherry pick: Disable upgrade meta from v1 to v3
  src/daemons/CMakeLists.txt
  src/daemons/MetaDaemonInit.cpp
  src/meta/CMakeLists.txt
  src/meta/MetaVersionMan.cpp
  src/meta/MetaVersionMan.h
  src/meta/upgrade/CMakeLists.txt
  src/meta/upgrade/MetaDataUpgrade.cpp
  src/meta/upgrade/MetaDataUpgrade.h
  src/meta/upgrade/v1/CMakeLists.txt
  src/meta/upgrade/v1/MetaServiceUtilsV1.cpp
  src/meta/upgrade/v1/MetaServiceUtilsV1.h
  src/meta/upgrade/v1/meta.thrift
  src/storage/test/CMakeLists.txt
  src/tools/db-dump/CMakeLists.txt
  src/tools/db-upgrade/CMakeLists.txt
  src/tools/meta-dump/CMakeLists.txt
  src/tools/simple-kv-verify/CMakeLists.txt
  src/tools/storage-perf/CMakeLists.txt
Labels: ready-for-testing

#3643 add comments & accumulate bug fix for TOSS
  src/clients/storage/InternalStorageClient.cpp
  src/common/utils/MemoryLockWrapper.h
  src/interface/common.thrift
  src/kvstore/NebulaStore.cpp
  src/meta/upgrade/v2/meta.thrift
  src/mock/MockCluster.cpp
  src/storage/CMakeLists.txt
  src/storage/InternalStorageServiceHandler.h
  src/storage/StorageServer.cpp
  src/storage/index/LookupProcessor.h
  src/storage/kv/GetProcessor.h
  src/storage/kv/PutProcessor.h
  src/storage/kv/RemoveProcessor.h
  src/storage/test/CMakeLists.txt
  src/storage/test/ChainAddEdgesTest.cpp
  src/storage/test/ChainDeleteEdgesTest.cpp
  src/storage/test/ChainResumeEdgeTest.cpp
  src/storage/test/ChainTestUtils.h
  src/storage/test/ChainUpdateEdgeTest.cpp
  src/storage/transaction/ChainAddEdgesLocalProcessor.cpp
  src/storage/transaction/ChainAddEdgesLocalProcessor.h
  src/storage/transaction/ChainAddEdgesRemoteProcessor.cpp
  src/storage/transaction/ChainBaseProcessor.h
  src/storage/transaction/ChainDeleteEdgesLocalProcessor.cpp
  src/storage/transaction/ChainDeleteEdgesLocalProcessor.h
  src/storage/transaction/ChainDeleteEdgesResumeProcessor.cpp
  src/storage/transaction/ChainDeleteEdgesResumeRemoteProcessor.cpp
  src/storage/transaction/ChainDeleteEdgesResumeRemoteProcessor.h
  src/storage/transaction/ChainProcessorFactory.cpp
  src/storage/transaction/ChainProcessorFactory.h
  src/storage/transaction/ChainResumeAddDoublePrimeProcessor.cpp
  src/storage/transaction/ChainResumeAddDoublePrimeProcessor.h
  src/storage/transaction/ChainResumeAddPrimeProcessor.cpp
  src/storage/transaction/ChainResumeAddPrimeProcessor.h
  src/storage/transaction/ChainResumeProcessor.cpp
  src/storage/transaction/ChainResumeProcessor.h
  src/storage/transaction/ChainResumeUpdateDoublePrimeProcessor.cpp
  src/storage/transaction/ChainResumeUpdateDoublePrimeProcessor.h
  src/storage/transaction/ChainResumeUpdatePrimeProcessor.cpp
  src/storage/transaction/ChainResumeUpdatePrimeProcessor.h
  src/storage/transaction/ChainUpdateEdgeLocalProcessor.cpp
  src/storage/transaction/ChainUpdateEdgeLocalProcessor.h
  src/storage/transaction/ConsistUtil.cpp
  src/storage/transaction/ConsistUtil.h
  src/storage/transaction/ResumeAddEdgeProcessor.cpp
  src/storage/transaction/ResumeAddEdgeRemoteProcessor.cpp
  src/storage/transaction/ResumeUpdateRemoteProcessor.cpp
  src/storage/transaction/TransactionManager.cpp
  src/storage/transaction/TransactionManager.h
Labels: ready-for-testing, cherry-pick-v3.0

#3829 Cherry pick v3.0.0 0126 1
  src/graph/executor/query/TraverseExecutor.cpp
  src/graph/executor/query/TraverseExecutor.h
  src/graph/service/GraphFlags.cpp
Labels: ready-for-testing

#3825 disable add hosts into zone
  src/graph/validator/MaintainValidator.cpp
Labels: ready-for-testing, cherry-pick-v3.0

#3822 Check active zone before create space
  src/meta/ActiveHostsMan.cpp
  src/meta/processors/parts/CreateSpaceProcessor.cpp
  src/meta/test/ProcessorTest.cpp
Labels: ready-for-testing, cherry-pick-v3.0

#3818 abandon upgrader for old version
  src/tools/db-upgrade/DbUpgraderTool.cpp
Labels: ready-for-testing, cherry-pick-v3.0

#3817 put dataVersionKey on create space for storage
  src/common/utils/NebulaKeyUtils.cpp
  src/common/utils/NebulaKeyUtils.h
  src/kvstore/RocksEngine.cpp
Labels: ready-for-testing, cherry-pick-v3.0

#3828 cherry pick: disable zone
  src/graph/validator/AdminValidator.cpp
  src/graph/validator/MaintainValidator.cpp
  src/graph/validator/MaintainValidator.h
  src/graph/validator/Validator.cpp
  src/parser/AdminSentences.cpp
  src/parser/AdminSentences.h
  src/parser/MaintainSentences.cpp
  src/parser/MaintainSentences.h
  src/parser/parser.yy
  tests/admin/test_space.py
  tests/common/nebula_service.py
  tests/maintain/test_zone.py
  tests/tck/features/admin/Hosts.feature
  tests/tck/features/schema/Comment.feature
Labels: ready-for-testing

#3831 Cherry pick v3.0.0 0126-2
  .github/workflows/pull_request.yml
  src/clients/storage/StorageClientBase-inl.h
  src/common/utils/NebulaKeyUtils.cpp
  src/common/utils/NebulaKeyUtils.h
  src/daemons/CMakeLists.txt
  src/daemons/StandAloneDaemon.cpp
  src/graph/executor/test/StorageServerStub.cpp
  src/graph/validator/MaintainValidator.cpp
  src/kvstore/RocksEngine.cpp
  src/meta/ActiveHostsMan.cpp
  src/meta/processors/parts/CreateSpaceProcessor.cpp
  src/meta/test/ProcessorTest.cpp
  src/storage/GraphStorageLocalServer.cpp
  src/storage/stats/StorageStats.cpp
  src/tools/db-upgrade/DbUpgraderTool.cpp
  tests/Makefile
  tests/common/nebula_service.py
  tests/nebula-test-run.py
  tests/pytest.ini
  tests/tck/features/admin/Authentication.feature
  tests/tck/features/admin/Sessions.feature
Labels: ready-for-testing

#3809 [Minor] Update PR template
  .github/pull_request_template.md
Labels: type/enhancement, ready-for-testing

#3810 fix clang compile
  src/meta/MetaVersionMan.cpp
Labels: ready-for-testing

#3794 fix meta http replace host handler
  src/meta/http/MetaHttpReplaceHostHandler.cpp
  src/meta/http/MetaHttpReplaceHostHandler.h
  src/meta/http/test/CMakeLists.txt
  src/meta/http/test/MetaHttpReplaceHandlerTest.cpp
  src/meta/processors/admin/RestoreProcessor.cpp
  src/meta/test/TestUtils.h
Labels: ready-for-testing

#3833 cherry-pick (#3643)
  src/clients/storage/InternalStorageClient.cpp
  src/common/utils/MemoryLockWrapper.h
  src/interface/common.thrift
  src/kvstore/NebulaStore.cpp
  src/meta/upgrade/v2/meta.thrift
  src/mock/MockCluster.cpp
  src/storage/CMakeLists.txt
  src/storage/InternalStorageServiceHandler.h
  src/storage/StorageServer.cpp
  src/storage/index/LookupProcessor.h
  src/storage/kv/GetProcessor.h
  src/storage/kv/PutProcessor.h
  src/storage/kv/RemoveProcessor.h
  src/storage/test/CMakeLists.txt
  src/storage/test/ChainAddEdgesTest.cpp
  src/storage/test/ChainDeleteEdgesTest.cpp
  src/storage/test/ChainResumeEdgeTest.cpp
  src/storage/test/ChainTestUtils.h
  src/storage/test/ChainUpdateEdgeTest.cpp
  src/storage/transaction/ChainAddEdgesLocalProcessor.cpp
  src/storage/transaction/ChainAddEdgesLocalProcessor.h
  src/storage/transaction/ChainAddEdgesRemoteProcessor.cpp
  src/storage/transaction/ChainBaseProcessor.h
  src/storage/transaction/ChainDeleteEdgesLocalProcessor.cpp
  src/storage/transaction/ChainDeleteEdgesLocalProcessor.h
  src/storage/transaction/ChainDeleteEdgesResumeProcessor.cpp
  src/storage/transaction/ChainDeleteEdgesResumeRemoteProcessor.cpp
  src/storage/transaction/ChainDeleteEdgesResumeRemoteProcessor.h
  src/storage/transaction/ChainProcessorFactory.cpp
  src/storage/transaction/ChainProcessorFactory.h
  src/storage/transaction/ChainResumeAddDoublePrimeProcessor.cpp
  src/storage/transaction/ChainResumeAddDoublePrimeProcessor.h
  src/storage/transaction/ChainResumeAddPrimeProcessor.cpp
  src/storage/transaction/ChainResumeAddPrimeProcessor.h
  src/storage/transaction/ChainResumeProcessor.cpp
  src/storage/transaction/ChainResumeProcessor.h
  src/storage/transaction/ChainResumeUpdateDoublePrimeProcessor.cpp
  src/storage/transaction/ChainResumeUpdateDoublePrimeProcessor.h
  src/storage/transaction/ChainResumeUpdatePrimeProcessor.cpp
  src/storage/transaction/ChainResumeUpdatePrimeProcessor.h
  src/storage/transaction/ChainUpdateEdgeLocalProcessor.cpp
  src/storage/transaction/ChainUpdateEdgeLocalProcessor.h
  src/storage/transaction/ConsistUtil.cpp
  src/storage/transaction/ConsistUtil.h
  src/storage/transaction/ResumeAddEdgeProcessor.cpp
  src/storage/transaction/ResumeAddEdgeRemoteProcessor.cpp
  src/storage/transaction/ResumeUpdateRemoteProcessor.cpp
  src/storage/transaction/TransactionManager.cpp
  src/storage/transaction/TransactionManager.h
Labels: ready-for-testing, cherry-pick-v3.0

#3594 support toSet function
  src/common/datatypes/Value.cpp
  src/common/datatypes/Value.h
  src/common/function/FunctionManager.cpp
  tests/tck/features/expression/function/TypeConversion.feature
Labels: ready-for-testing, doc affected, ready for review

#3797 Enhance date parser
  src/common/time/parser/DatetimeReader.h
  src/common/time/parser/datetime_parser.yy
  src/common/time/parser/datetime_scanner.lex
  src/common/time/parser/test/DateTimeParserTest.cpp
Labels: ready-for-testing, ready for review

#3819 raft fix: fix always loop when no log need to send
  src/kvstore/raftex/Host.cpp
Labels: ready-for-testing, cherry-pick-v3.0

#3781 refactor AdminClient
  src/interface/storage.thrift
  src/meta/ActiveHostsMan.cpp
  src/meta/ActiveHostsMan.h
  src/meta/processors/admin/AdminClient.cpp
  src/meta/processors/admin/AdminClient.h
  src/meta/processors/admin/SnapShot.cpp
  src/meta/processors/job/CompactJobExecutor.cpp
  src/meta/processors/job/FlushJobExecutor.cpp
  src/meta/processors/job/RebuildEdgeJobExecutor.cpp
  src/meta/processors/job/RebuildFTJobExecutor.cpp
  src/meta/processors/job/RebuildJobExecutor.cpp
  src/meta/processors/job/RebuildTagJobExecutor.cpp
  src/meta/processors/job/StatsJobExecutor.cpp
  src/meta/processors/job/StatsJobExecutor.h
  src/meta/processors/job/StorageJobExecutor.cpp
  src/meta/test/AdminClientTest.cpp
  src/meta/test/CreateBackupProcessorTest.cpp
  src/meta/test/GetStatsTest.cpp
  src/meta/test/MockAdminClient.h
  src/storage/CMakeLists.txt
  src/storage/StorageAdminServiceHandler.cpp
  src/storage/StorageAdminServiceHandler.h
  src/storage/admin/AdminProcessor.h
  src/storage/admin/AdminTask.h
  src/storage/admin/AdminTaskProcessor.cpp
  src/storage/admin/AdminTaskProcessor.h
  src/storage/admin/CreateCheckpointProcessor.cpp
  src/storage/admin/CreateCheckpointProcessor.h
  src/storage/admin/DropCheckpointProcessor.cpp
  src/storage/admin/DropCheckpointProcessor.h
  src/storage/admin/GetLeaderProcessor.cpp
  src/storage/admin/GetLeaderProcessor.h
  src/storage/admin/SendBlockSignProcessor.cpp
  src/storage/admin/SendBlockSignProcessor.h
  src/storage/admin/StopAdminTaskProcessor.cpp
  src/storage/admin/StopAdminTaskProcessor.h
  src/storage/test/CheckpointTest.cpp
  src/storage/test/IndexWithTTLTest.cpp
  src/storage/test/RebuildIndexTest.cpp
  src/storage/test/StatsTaskTest.cpp
Labels: type/enhancement, ready-for-testing

#3769 Feature/optimizer trait match
  src/graph/optimizer/CMakeLists.txt
  src/graph/optimizer/OptRule.cpp
  src/graph/optimizer/OptRule.h
  src/graph/optimizer/rule/PushLimitDownEdgeIndexFullScanRule.cpp
  src/graph/optimizer/rule/PushLimitDownEdgeIndexFullScanRule.h
  src/graph/optimizer/rule/PushLimitDownEdgeIndexPrefixScanRule.cpp
  src/graph/optimizer/rule/PushLimitDownEdgeIndexPrefixScanRule.h
  src/graph/optimizer/rule/PushLimitDownEdgeIndexRangeScanRule.cpp
  src/graph/optimizer/rule/PushLimitDownEdgeIndexRangeScanRule.h
  src/graph/optimizer/rule/PushLimitDownIndexScanRule.cpp
  src/graph/optimizer/rule/PushLimitDownIndexScanRule.h
  src/graph/optimizer/rule/PushLimitDownTagIndexFullScanRule.cpp
  src/graph/optimizer/rule/PushLimitDownTagIndexFullScanRule.h
  src/graph/optimizer/rule/PushLimitDownTagIndexPrefixScanRule.cpp
  src/graph/optimizer/rule/PushLimitDownTagIndexPrefixScanRule.h
  src/graph/optimizer/rule/PushLimitDownTagIndexRangeScanRule.cpp
  src/graph/optimizer/rule/PushLimitDownTagIndexRangeScanRule.h
  src/graph/optimizer/rule/PushTopNDownEdgeIndexFullScanRule.cpp
  src/graph/optimizer/rule/PushTopNDownEdgeIndexFullScanRule.h
  src/graph/optimizer/rule/PushTopNDownEdgeIndexPrefixScanRule.cpp
  src/graph/optimizer/rule/PushTopNDownEdgeIndexPrefixScanRule.h
  src/graph/optimizer/rule/PushTopNDownEdgeIndexRangeScanRule.cpp
  src/graph/optimizer/rule/PushTopNDownEdgeIndexRangeScanRule.h
  src/graph/optimizer/rule/PushTopNDownIndexScanRule.cpp
  src/graph/optimizer/rule/PushTopNDownIndexScanRule.h
  src/graph/optimizer/rule/PushTopNDownTagIndexFullScanRule.cpp
  src/graph/optimizer/rule/PushTopNDownTagIndexFullScanRule.h
  src/graph/optimizer/rule/PushTopNDownTagIndexPrefixScanRule.cpp
  src/graph/optimizer/rule/PushTopNDownTagIndexPrefixScanRule.h
  src/graph/optimizer/rule/PushTopNDownTagIndexRangeScanRule.cpp
  src/graph/optimizer/rule/PushTopNDownTagIndexRangeScanRule.h
  src/graph/planner/plan/PlanNode.h
Labels: ready-for-testing

#3712 Simplify datetime tostring.
  src/common/datatypes/Date.cpp
Labels: ready-for-testing

#3842 pragma once not allowd
  .linters/cpp/cpplint.py
Labels: ready-for-testing

#3780 replace STRING to name_label for zone's name
  src/parser/MaintainSentences.cpp
  src/parser/Sentence.h
  src/parser/parser.yy
  src/parser/test/ParserTest.cpp
  tests/tck/features/admin/Hosts.feature
Labels: ready-for-testing, incompatible, ready for review
