Repository vesoft-inc/nebula, pull requests merged in 2022-03, with the labels that each got.

#3911 Merge active host manager write operations into one
  src/common/utils/MetaKeyUtils.cpp
  src/common/utils/MetaKeyUtils.h
  src/meta/ActiveHostsMan.cpp
  src/meta/ActiveHostsMan.h
  src/meta/processors/BaseProcessor-inl.h
  src/meta/processors/BaseProcessor.h
  src/meta/processors/admin/AgentHBProcessor.cpp
  src/meta/processors/admin/CreateSnapshotProcessor.cpp
  src/meta/processors/admin/DropSnapshotProcessor.cpp
  src/meta/processors/admin/GetMetaDirInfoProcessor.cpp
  src/meta/processors/admin/HBProcessor.cpp
  src/meta/processors/admin/ListClusterInfoProcessor.cpp
  src/meta/processors/config/RegConfigProcessor.cpp
  src/meta/processors/config/SetConfigProcessor.cpp
  src/meta/processors/id/GetWorkerIdProcessor.cpp
  src/meta/processors/id/GetWorkerIdProcessor.h
  src/meta/processors/index/CreateEdgeIndexProcessor.cpp
  src/meta/processors/index/CreateTagIndexProcessor.cpp
  src/meta/processors/index/DropEdgeIndexProcessor.cpp
  src/meta/processors/index/DropTagIndexProcessor.cpp
  src/meta/processors/index/FTIndexProcessor.cpp
  src/meta/processors/job/BalanceJobExecutor.cpp
  src/meta/processors/job/BalanceJobExecutor.h
  src/meta/processors/job/DataBalanceJobExecutor.cpp
  src/meta/processors/job/GetStatsProcessor.cpp
  src/meta/processors/job/JobDescription.h
  src/meta/processors/job/JobManager.cpp
  src/meta/processors/job/JobManager.h
  src/meta/processors/job/LeaderBalanceJobExecutor.cpp
  src/meta/processors/job/TaskDescription.h
  src/meta/processors/job/ZoneBalanceJobExecutor.cpp
  src/meta/processors/listener/ListenerProcessor.cpp
  src/meta/processors/parts/CreateSpaceAsProcessor.cpp
  src/meta/processors/parts/CreateSpaceProcessor.cpp
  src/meta/processors/parts/DropSpaceProcessor.cpp
  src/meta/processors/schema/AlterEdgeProcessor.cpp
  src/meta/processors/schema/AlterTagProcessor.cpp
  src/meta/processors/schema/CreateEdgeProcessor.cpp
  src/meta/processors/schema/CreateTagProcessor.cpp
  src/meta/processors/schema/DropEdgeProcessor.cpp
  src/meta/processors/schema/DropTagProcessor.cpp
  src/meta/processors/service/ServiceProcessor.cpp
  src/meta/processors/user/AuthenticationProcessor.cpp
  src/meta/processors/zone/AddHostsIntoZoneProcessor.cpp
  src/meta/processors/zone/AddHostsProcessor.cpp
  src/meta/processors/zone/DropHostsProcessor.cpp
  src/meta/processors/zone/DropZoneProcessor.cpp
  src/meta/test/ActiveHostsManTest.cpp
  src/meta/test/AdminClientTest.cpp
  src/meta/test/CreateBackupProcessorTest.cpp
  src/meta/test/GetStatsTest.cpp
  src/meta/test/JobManagerTest.cpp
  src/meta/test/ProcessorTest.cpp
  src/meta/test/RestoreProcessorTest.cpp
  src/meta/test/TestUtils.h
  src/storage/BaseProcessor-inl.h
  src/storage/BaseProcessor.h
  src/storage/test/IndexTestUtil.h
Labels: ready-for-testing

#3834 time-trace option for clang
  CMakeLists.txt
  cmake/nebula/TimeTrace.cmake
Labels: ready-for-testing, ready for review

#3908 Comments for stats module
  src/common/stats/StatsManager.h
  src/graph/stats/GraphStats.h
  src/kvstore/stats/KVStats.h
  src/storage/http/StorageHttpStatsHandler.cpp
Labels: ready-for-testing, ready for review

#3844 Push filter down GetProps.
  src/storage/exec/GetPropNode.h
  src/storage/exec/HashJoinNode.h
  src/storage/exec/QueryUtils.h
  src/storage/exec/ScanNode.h
  src/storage/query/GetPropProcessor.cpp
  src/storage/test/GetPropTest.cpp
Labels: ready-for-testing, ready for review

#3871 Optimize subgraph
  src/graph/context/Iterator.cpp
  src/graph/context/Iterator.h
  src/graph/context/ast/QueryAstContext.h
  src/graph/executor/algo/SubgraphExecutor.cpp
  src/graph/executor/algo/SubgraphExecutor.h
  src/graph/executor/query/DataCollectExecutor.cpp
  src/graph/executor/test/DataCollectTest.cpp
  src/graph/planner/ngql/SubgraphPlanner.cpp
  src/graph/planner/plan/Algo.h
  src/graph/planner/plan/Query.h
  src/graph/validator/GetSubgraphValidator.cpp
  src/graph/validator/test/GetSubgraphValidatorTest.cpp
  tests/tck/features/subgraph/subgraph.IntVid.feature
  tests/tck/features/subgraph/subgraph.feature
Labels: type/enhancement, ready-for-testing, ready for review

#3954 Reduce useless explicit modification
  src/common/base/StatusOr.h
  src/common/datatypes/Date.h
  src/common/expression/LogicalExpression.h
  src/common/expression/RelationalExpression.h
  src/common/expression/SubscriptExpression.h
  src/common/expression/UnaryExpression.h
  src/graph/service/QueryInstance.h
  src/graph/session/ClientSession.h
  src/meta/processors/admin/AgentHBProcessor.h
  src/parser/AdminSentences.h
  src/parser/Clauses.h
  src/parser/MaintainSentences.h
  src/parser/MatchSentence.h
  src/parser/MutateSentences.h
  src/parser/TraverseSentences.h
  src/storage/exec/DeDupNode.h
  src/storage/exec/IndexAggregateNode.h
  src/storage/exec/IndexNode.h
  src/storage/kv/GetProcessor.h
  src/storage/test/ChainTestUtils.h
Labels: ready-for-testing

#3958 Improve timestamp by get it from syscall.
  src/common/function/FunctionManager.cpp
  src/common/time/TimeUtils.h
Labels: ready-for-testing, type/bug, ready for review

#3967 fix Issue3649
  src/storage/admin/StatsTask.cpp
Labels: ready-for-testing

#3971 fix issue3215
  src/clients/meta/MetaClient.cpp
Labels: ready-for-testing

#3953 Prune properties/no need to collect columns of dedup
  src/graph/planner/plan/PlanNodeVisitor.h
  src/graph/planner/plan/Query.cpp
  src/graph/planner/plan/Query.h
  src/graph/visitor/PrunePropertiesVisitor.cpp
  src/graph/visitor/PrunePropertiesVisitor.h
  tests/tck/features/optimizer/PrunePropertiesRule.feature
Labels: ready-for-testing

#3975 Can't push down LabelTagPropertyExpression.
  src/graph/visitor/ExtractFilterExprVisitor.cpp
  src/graph/visitor/test/ExtractFilterExprVisitorTest.cpp
Labels: ready-for-testing, type/bug

#3905 add nebula-console package action
  .github/workflows/nightly.yml
  .github/workflows/rc.yml
  CMakeLists.txt
  cmake/CPackage.cmake
  package/package.sh
  src/CMakeLists.txt
  src/console/CMakeLists.txt
  src/console/compile-console.sh
Labels: ready-for-testing, doc affected, ready for review

#3884 Add comments to util module
  src/graph/util/AnonColGenerator.h
  src/graph/util/AnonVarGenerator.h
  src/graph/util/AstUtils.h
  src/graph/util/ContainerConv.h
  src/graph/util/ExpressionUtils.cpp
  src/graph/util/ExpressionUtils.h
  src/graph/util/FTIndexUtils.cpp
  src/graph/util/FTIndexUtils.h
  src/graph/util/IdGenerator.cpp
  src/graph/util/IdGenerator.h
  src/graph/util/IndexUtil.cpp
  src/graph/util/IndexUtil.h
  src/graph/util/ParserUtil.cpp
  src/graph/util/ParserUtil.h
  src/graph/util/PlannerUtil.cpp
  src/graph/util/PlannerUtil.h
  src/graph/util/SchemaUtil.cpp
  src/graph/util/SchemaUtil.h
  src/graph/util/ToJson.cpp
  src/graph/util/ToJson.h
  src/graph/util/Utils.h
  src/graph/util/ValidateUtil.cpp
  src/graph/util/ValidateUtil.h
  src/graph/util/ZoneUtil.cpp
  src/graph/util/ZoneUtil.h
  src/graph/util/test/ExpressionUtilsTest.cpp
  src/graph/util/test/IdGeneratorTest.cpp
  src/graph/validator/Validator.cpp
Labels: type/enhancement, ready-for-testing, ready for review

#3870 add more table in meta dump
  src/common/utils/MetaKeyUtils.cpp
  src/common/utils/MetaKeyUtils.h
  src/tools/meta-dump/MetaDumpTool.cpp
Labels: ready-for-testing

#3950 Machine not registed should response leader address
  src/clients/meta/MetaClient.cpp
  src/meta/processors/BaseProcessor.h
  src/meta/processors/admin/HBProcessor.cpp
  src/meta/processors/admin/HBProcessor.h
Labels: ready-for-testing, doc affected

#3987 Disable console building in docker image
  .dockerignore
  docker/Dockerfile
  docker/Dockerfile.graphd
  docker/Dockerfile.metad
  docker/Dockerfile.storaged
  docker/Dockerfile.tools
  package/package.sh
Labels: ready-for-testing, type/bug, ready for review

#3976 refactor job manager part1
  src/graph/validator/AdminJobValidator.h
  src/interface/storage.thrift
  src/meta/processors/admin/AdminClient.cpp
  src/meta/processors/admin/AdminClient.h
  src/meta/processors/job/AdminJobProcessor.cpp
  src/meta/processors/job/AdminJobProcessor.h
  src/meta/processors/job/CompactJobExecutor.cpp
  src/meta/processors/job/FlushJobExecutor.cpp
  src/meta/processors/job/JobManager.cpp
  src/meta/processors/job/JobManager.h
  src/meta/processors/job/MetaJobExecutor.h
  src/meta/processors/job/RebuildEdgeJobExecutor.cpp
  src/meta/processors/job/RebuildFTJobExecutor.cpp
  src/meta/processors/job/RebuildTagJobExecutor.cpp
  src/meta/processors/job/SimpleConcurrentJobExecutor.cpp
  src/meta/processors/job/StatsJobExecutor.cpp
  src/meta/processors/job/StorageJobExecutor.h
  src/meta/test/GetStatsTest.cpp
  src/meta/test/MockAdminClient.h
  src/parser/AdminSentences.cpp
  src/parser/parser.yy
  src/parser/test/ParserTest.cpp
  src/storage/admin/AdminTask.h
  src/storage/admin/AdminTaskManager.cpp
  src/storage/admin/AdminTaskManager.h
Labels: ready-for-testing, ready for review

#3846 Use the same rocksdb snapshot when sending snapshot
  resources/gflags.json
  src/common/base/CMakeLists.txt
  src/common/base/SlowOpTracker.cpp
  src/common/base/SlowOpTracker.h
  src/common/base/test/CMakeLists.txt
  src/common/base/test/SlowOpTrackerTest.cpp
  src/common/meta/GflagsManager.cpp
  src/kvstore/KVEngine.h
  src/kvstore/KVStore.h
  src/kvstore/NebulaSnapshotManager.cpp
  src/kvstore/NebulaSnapshotManager.h
  src/kvstore/NebulaStore.cpp
  src/kvstore/NebulaStore.h
  src/kvstore/Part.cpp
  src/kvstore/RocksEngine.cpp
  src/kvstore/RocksEngine.h
  src/kvstore/raftex/Host.cpp
  src/kvstore/raftex/RaftPart.cpp
  src/kvstore/raftex/SnapshotManager.cpp
  src/kvstore/raftex/SnapshotManager.h
  src/kvstore/raftex/test/TestShard.h
  src/kvstore/stats/KVStats.cpp
  src/kvstore/stats/KVStats.h
  src/storage/test/IndexTestUtil.h
  tests/admin/test_configs.py
Labels: ready-for-testing, ready for review

#3999 Change the name of source code zip
  .github/workflows/rc.yml
Labels: ready-for-testing

#4000 Fix lambda capture bug in GraphStorageLocalServer
  src/storage/GraphStorageLocalServer.cpp
Labels: ready-for-testing, type/bug

#3942 Fix service crash caused by connecting using a pre-v2.6.0 client
  src/clients/meta/MetaClient.cpp
  src/clients/meta/MetaClient.h
  src/graph/service/GraphService.cpp
  src/graph/service/GraphService.h
  src/graph/service/PasswordAuthenticator.h
Labels: ready-for-testing, type/bug, doc affected, cherry-pick-v3.0, ready for review

#3644 Comment
  src/storage/exec/IndexNode.h
  src/storage/exec/IndexProjectionNode.h
  src/storage/exec/IndexScanNode.h
Labels: ready-for-testing, ready for review

#3998 Fix crash when use `executeJson()` with profile
  src/common/graph/Response.h
  src/common/graph/tests/ResponseEncodeDecodeTest.cpp
Labels: ready-for-testing, type/bug

#4007 Cherry pick v3.0.1
  .github/workflows/rc.yml
  src/clients/meta/MetaClient.cpp
  src/clients/meta/MetaClient.h
  src/graph/planner/match/MatchClausePlanner.cpp
  src/graph/service/GraphService.cpp
  src/graph/service/GraphService.h
  src/graph/service/PasswordAuthenticator.h
  src/tools/db-upgrade/DbUpgrader.cpp
  tests/tck/features/bugfix/CrashWhenNullPathExpr.feature
Labels: ready-for-testing

#4020 cherry pick: machine not registed should response leader address (#3950)
  src/clients/meta/MetaClient.cpp
  src/meta/processors/BaseProcessor.h
  src/meta/processors/admin/HBProcessor.cpp
  src/meta/processors/admin/HBProcessor.h
Labels: ready-for-testing

#3989 Clear space
  .linters/cpp/checkKeyword.py
  src/clients/meta/MetaClient.cpp
  src/clients/meta/MetaClient.h
  src/common/plugin/fulltext/FTGraphAdapter.h
  src/common/plugin/fulltext/elasticsearch/ESGraphAdapter.cpp
  src/common/plugin/fulltext/elasticsearch/ESGraphAdapter.h
  src/common/plugin/fulltext/test/FulltextPluginTest.cpp
  src/graph/executor/Executor.cpp
  src/graph/executor/admin/SpaceExecutor.cpp
  src/graph/executor/admin/SpaceExecutor.h
  src/graph/planner/plan/Admin.cpp
  src/graph/planner/plan/Admin.h
  src/graph/planner/plan/PlanNode.cpp
  src/graph/planner/plan/PlanNode.h
  src/graph/service/PermissionCheck.cpp
  src/graph/util/FTIndexUtils.cpp
  src/graph/util/FTIndexUtils.h
  src/graph/validator/AdminValidator.cpp
  src/graph/validator/AdminValidator.h
  src/graph/validator/Validator.cpp
  src/interface/meta.thrift
  src/interface/storage.thrift
  src/kvstore/NebulaStore.cpp
  src/kvstore/NebulaStore.h
  src/kvstore/Part.h
  src/kvstore/PartManager.h
  src/meta/CMakeLists.txt
  src/meta/MetaServiceHandler.cpp
  src/meta/MetaServiceHandler.h
  src/meta/processors/BaseProcessor-inl.h
  src/meta/processors/BaseProcessor.h
  src/meta/processors/admin/AdminClient.cpp
  src/meta/processors/admin/AdminClient.h
  src/meta/processors/admin/ClearSpaceProcessor.cpp
  src/meta/processors/admin/ClearSpaceProcessor.h
  src/meta/processors/parts/ListPartsProcessor.cpp
  src/meta/processors/parts/ListPartsProcessor.h
  src/parser/AdminSentences.cpp
  src/parser/AdminSentences.h
  src/parser/Sentence.h
  src/parser/parser.yy
  src/parser/scanner.lex
  src/storage/CMakeLists.txt
  src/storage/StorageAdminServiceHandler.cpp
  src/storage/StorageAdminServiceHandler.h
  src/storage/admin/ClearSpaceProcessor.cpp
  src/storage/admin/ClearSpaceProcessor.h
  tests/conftest.py
  tests/tck/conftest.py
  tests/tck/features/mutate/ClearSpace.feature
Labels: ready-for-testing, incompatible, doc affected, ready for review

#4013 update time when alter space
  src/meta/processors/parts/AlterSpaceProcessor.cpp
Labels: ready-for-testing

#4022 unify leader change and machine not found
  src/clients/meta/MetaClient.cpp
Labels: ready-for-testing, cherry-pick-v3.0

#4021 Update error message when connect with an out-of-date client
  src/graph/service/GraphService.cpp
Labels: ready-for-testing, cherry-pick-v3.0, ready for review

#4027 Cherry pick v3.0.1
  src/clients/meta/MetaClient.cpp
  src/common/CMakeLists.txt
  src/common/base/StringUnorderedMap.h
  src/common/encryption/Base64.cpp
  src/common/encryption/Base64.h
  src/common/encryption/CMakeLists.txt
  src/common/encryption/MD5Utils.cpp
  src/common/encryption/MD5Utils.h
  src/common/expression/test/CMakeLists.txt
  src/common/plugin/fulltext/FTUtils.h
  src/common/plugin/fulltext/test/CMakeLists.txt
  src/common/plugin/fulltext/test/FulltextPluginTest.cpp
  src/common/utils/test/CMakeLists.txt
  src/daemons/CMakeLists.txt
  src/graph/context/test/CMakeLists.txt
  src/graph/executor/admin/ChangePasswordExecutor.cpp
  src/graph/executor/admin/CreateUserExecutor.cpp
  src/graph/executor/admin/UpdateUserExecutor.cpp
  src/graph/executor/test/CMakeLists.txt
  src/graph/optimizer/test/CMakeLists.txt
  src/graph/service/CloudAuthenticator.cpp
  src/graph/service/GraphService.cpp
  src/graph/util/test/CMakeLists.txt
  src/graph/validator/test/CMakeLists.txt
  src/graph/visitor/test/CMakeLists.txt
  src/kvstore/test/CMakeLists.txt
  src/meta/CMakeLists.txt
  src/meta/RootUserMan.h
  src/parser/test/CMakeLists.txt
  src/storage/test/CMakeLists.txt
  src/tools/db-dump/CMakeLists.txt
  src/tools/db-upgrade/CMakeLists.txt
  src/tools/meta-dump/CMakeLists.txt
  src/tools/simple-kv-verify/CMakeLists.txt
  src/tools/storage-perf/CMakeLists.txt
Labels: ready-for-testing

#4006 Add version for nightly.
  .github/workflows/nightly.yml
Labels: ready-for-testing, doc affected

#4005 Return unique white client version list.
  src/graph/service/GraphService.cpp
Labels: ready-for-testing

#3944 Clean log.
  src/graph/validator/MutateValidator.cpp
  src/graph/validator/UseValidator.cpp
Labels: ready-for-testing

#4028 [Minor] Update error message
  src/graph/service/GraphService.cpp
Labels: ready-for-testing, ready for review

#4031 Fix: exec time calculated twice
  src/graph/executor/query/TraverseExecutor.cpp
Labels: ready-for-testing, type/bug

#3986 Fix lookup in crash when the property has no corresponding filter
  src/graph/optimizer/rule/OptimizeTagIndexScanByFilterRule.cpp
  src/graph/optimizer/rule/UnionAllIndexScanBaseRule.cpp
  src/graph/util/ExpressionUtils.cpp
  src/graph/util/ExpressionUtils.h
  tests/tck/features/bugfix/LookupIn.feature
Labels: ready-for-testing, type/bug, ready for review

#3738 Support more compiler launchers: distcc sccache
  CMakeLists.txt
  cmake/nebula/CcacheConfig.cmake
  cmake/nebula/CompilerLauncher.cmake
Labels: ready-for-testing, ready for review

#3754 add some comments
  src/storage/exec/MultiTagNode.h
  src/storage/exec/QueryUtils.h
  src/storage/exec/RelNode.h
  src/storage/exec/ScanNode.h
  src/storage/exec/StorageIterator.h
  src/storage/exec/StoragePlan.h
  src/storage/exec/TagNode.h
  src/storage/exec/UpdateNode.h
  src/storage/exec/UpdateResultNode.h
Labels: ready-for-testing, ready for review

#3910 add optimizer comments
  src/graph/optimizer/OptContext.h
  src/graph/optimizer/Optimizer.cpp
  src/graph/optimizer/rule/CollapseProjectRule.h
  src/graph/optimizer/rule/CombineFilterRule.h
  src/graph/optimizer/rule/EdgeIndexFullScanRule.h
  src/graph/optimizer/rule/EliminateRowCollectRule.h
  src/graph/optimizer/rule/GeoPredicateEdgeIndexScanRule.h
  src/graph/optimizer/rule/GeoPredicateTagIndexScanRule.h
  src/graph/optimizer/rule/GetEdgesTransformRule.cpp
  src/graph/optimizer/rule/GetEdgesTransformRule.h
  src/graph/optimizer/rule/IndexScanRule.cpp
  src/graph/optimizer/rule/IndexScanRule.h
  src/graph/optimizer/rule/MergeGetNbrsAndDedupRule.h
  src/graph/optimizer/rule/MergeGetNbrsAndProjectRule.h
  src/graph/optimizer/rule/MergeGetVerticesAndDedupRule.h
  src/graph/optimizer/rule/MergeGetVerticesAndProjectRule.h
  src/graph/optimizer/rule/PushFilterDownAggregateRule.h
  src/graph/optimizer/rule/PushFilterDownGetNbrsRule.h
  src/graph/optimizer/rule/PushFilterDownLeftJoinRule.h
  src/graph/optimizer/rule/PushFilterDownProjectRule.cpp
  src/graph/optimizer/rule/PushFilterDownProjectRule.h
  src/graph/optimizer/rule/PushFilterDownScanVerticesRule.h
  src/graph/optimizer/rule/PushLimitDownGetNeighborsRule.h
  src/graph/optimizer/rule/PushLimitDownIndexScanRule.h
  src/graph/optimizer/rule/PushLimitDownProjectRule.h
  src/graph/optimizer/rule/PushLimitDownScanAppendVerticesRule.h
  src/graph/optimizer/rule/PushLimitDownScanEdgesAppendVerticesRule.h
  src/graph/optimizer/rule/PushStepLimitDownGetNeighborsRule.h
  src/graph/optimizer/rule/PushStepSampleDownGetNeighborsRule.h
  src/graph/optimizer/rule/PushTopNDownIndexScanRule.h
  src/graph/optimizer/rule/PushVFilterDownScanVerticesRule.h
  src/graph/optimizer/rule/RemoveNoopProjectRule.h
  src/graph/optimizer/rule/TagIndexFullScanRule.h
  src/graph/optimizer/rule/TopNRule.h
  src/graph/optimizer/rule/UnionAllEdgeIndexScanRule.h
  src/graph/optimizer/rule/UnionAllTagIndexScanRule.h
Labels: ready-for-testing

#3729 Limit number of sessions that are created by same client ip and same user for each graphd
  conf/nebula-graphd.conf.production
  resources/gflags.json
  src/common/session/SessionManager.h
  src/graph/service/GraphFlags.cpp
  src/graph/service/GraphFlags.h
  src/graph/session/GraphSessionManager.cpp
  src/graph/session/GraphSessionManager.h
  tests/admin/test_configs.py
  tests/job/test_session.py
Labels: ready-for-testing, incompatible, doc affected, community, ready for review

#4014 show peers in raft stat
  src/interface/raftex.thrift
  src/kvstore/raftex/RaftPart.cpp
Labels: ready-for-testing

#4030 refactor: use STL facilities instead of 3rd party libraries
  src/clients/meta/MetaClient.cpp
  src/clients/storage/InternalStorageClient.cpp
  src/clients/storage/InternalStorageClient.h
  src/codec/NebulaCodecImpl.cpp
  src/codec/include/NebulaCodec.h
  src/codec/test/NebulaCodecTest.cpp
  src/common/base/Base.h
  src/common/base/ConcurrentLRUCache.h
  src/kvstore/plugins/hbase/HBaseStore.cpp
  src/kvstore/raftex/RaftPart.cpp
  src/kvstore/raftex/RaftPart.h
  src/kvstore/raftex/test/LogCASTest.cpp
  src/kvstore/raftex/test/TestShard.cpp
  src/kvstore/raftex/test/TestShard.h
  src/meta/processors/job/JobDescription.h
  src/meta/processors/job/JobUtils.h
  src/meta/test/ConfigManTest.cpp
  src/parser/AdminSentences.cpp
  src/parser/AdminSentences.h
  src/parser/MaintainSentences.cpp
  src/parser/MaintainSentences.h
  src/storage/exec/EdgeNode.h
  src/storage/exec/QueryUtils.h
  src/storage/exec/StorageIterator.h
  src/storage/exec/TagNode.h
  src/storage/exec/UpdateNode.h
  src/storage/mutate/AddEdgesProcessor.h
  src/storage/mutate/UpdateEdgeProcessor.h
  src/storage/test/AdminTaskManagerTest.cpp
  src/storage/test/ChainDeleteEdgesTest.cpp
  src/storage/test/ChainTestUtils.h
  src/storage/test/StorageLookupBenchmark.cpp
  src/storage/transaction/ChainAddEdgesLocalProcessor.h
  src/storage/transaction/ChainUpdateEdgeLocalProcessor.h
Labels: ready-for-testing

#4016 fix dead lock when stop storage while balancing
  src/kvstore/raftex/RaftexService.cpp
  src/kvstore/raftex/SnapshotManager.cpp
Labels: ready-for-testing

#4025 Fix data flow checking.
  src/graph/optimizer/OptRule.cpp
Labels: ready-for-testing, type/bug, ready for review

#3877 [bug fix] Need to wait for previous recover task finished.
  src/common/utils/MemoryLockCore.h
  src/storage/test/ChainTestUtils.h
  src/storage/transaction/TransactionManager.cpp
  src/storage/transaction/TransactionManager.h
Labels: ready-for-testing, ready for review

#3771 persist learner info
  src/common/datatypes/HostAddr.h
  src/kvstore/Common.h
  src/kvstore/KVEngine.h
  src/kvstore/NebulaStore.cpp
  src/kvstore/NebulaStore.h
  src/kvstore/Part.cpp
  src/kvstore/PartManager.cpp
  src/kvstore/PartManager.h
  src/kvstore/RocksEngine.cpp
  src/kvstore/RocksEngine.h
  src/kvstore/raftex/RaftPart.cpp
  src/kvstore/test/CMakeLists.txt
  src/kvstore/test/CommonTest.cpp
  src/kvstore/test/NebulaStoreTest.cpp
  src/storage/admin/AdminProcessor.h
Labels: ready-for-testing

#4017 Balancefix
  src/meta/processors/job/BalancePlan.cpp
  src/meta/processors/job/BalanceTask.cpp
  src/meta/processors/job/DataBalanceJobExecutor.cpp
  src/meta/processors/job/ZoneBalanceJobExecutor.cpp
  src/meta/test/BalancerTest.cpp
Labels: ready-for-testing

#4023 fix-bug-when-scheam-version-greater-than-256
  src/common/utils/MetaKeyUtils.cpp
  src/common/utils/MetaKeyUtils.h
  src/meta/processors/schema/AlterEdgeProcessor.cpp
  src/meta/processors/schema/AlterTagProcessor.cpp
  src/meta/processors/schema/GetEdgeProcessor.cpp
  src/meta/processors/schema/GetTagProcessor.cpp
  src/meta/test/ProcessorTest.cpp
Labels: ready-for-testing, ready for review

#4045 refactor job manager part3
  src/clients/meta/MetaClient.cpp
  src/clients/meta/MetaClient.h
  src/graph/executor/admin/SubmitJobExecutor.cpp
  src/graph/executor/admin/SubmitJobExecutor.h
  src/graph/executor/test/JobTest.cpp
  src/graph/planner/plan/Admin.cpp
  src/graph/planner/plan/Admin.h
  src/graph/validator/AdminJobValidator.cpp
  src/graph/validator/AdminJobValidator.h
  src/interface/meta.thrift
  src/interface/storage.thrift
  src/meta/processors/admin/AdminClient.cpp
  src/meta/processors/admin/AdminClient.h
  src/meta/processors/job/AdminJobProcessor.cpp
  src/meta/processors/job/CompactJobExecutor.cpp
  src/meta/processors/job/FlushJobExecutor.cpp
  src/meta/processors/job/JobDescription.cpp
  src/meta/processors/job/JobDescription.h
  src/meta/processors/job/JobExecutor.cpp
  src/meta/processors/job/JobManager.cpp
  src/meta/processors/job/JobManager.h
  src/meta/processors/job/ListEdgeIndexStatusProcessor.cpp
  src/meta/processors/job/ListTagIndexStatusProcessor.cpp
  src/meta/processors/job/RebuildEdgeJobExecutor.cpp
  src/meta/processors/job/RebuildFTJobExecutor.cpp
  src/meta/processors/job/RebuildTagJobExecutor.cpp
  src/meta/processors/job/StatsJobExecutor.cpp
  src/meta/test/BalancerTest.cpp
  src/meta/test/GetStatsTest.cpp
  src/meta/test/JobManagerTest.cpp
  src/meta/test/MockAdminClient.h
  src/parser/AdminSentences.cpp
  src/parser/AdminSentences.h
  src/parser/parser.yy
  src/storage/admin/AdminTask.cpp
  src/storage/admin/AdminTask.h
  src/storage/test/IndexWithTTLTest.cpp
  src/storage/test/RebuildIndexTest.cpp
  src/storage/test/StatsTaskTest.cpp
Labels: ready-for-testing, ready for review

#4015 cleanWal by commitLogId
  src/kvstore/Listener.cpp
  src/kvstore/Listener.h
  src/kvstore/NebulaStore.cpp
  src/kvstore/raftex/RaftPart.cpp
  src/kvstore/raftex/RaftPart.h
  src/kvstore/wal/FileBasedWal.cpp
  src/kvstore/wal/test/FileBasedWalTest.cpp
Labels: ready-for-testing

#3909 fix a node can't accept more logs after receiving snapshot
  src/kvstore/raftex/RaftLogIterator.h
  src/kvstore/raftex/RaftPart.cpp
  src/kvstore/wal/FileBasedWal.cpp
  src/kvstore/wal/FileBasedWal.h
Labels: ready-for-testing

#4019 refactor process snapshot
  src/interface/raftex.thrift
  src/kvstore/Listener.cpp
  src/kvstore/Listener.h
  src/kvstore/NebulaStore.cpp
  src/kvstore/Part.cpp
  src/kvstore/Part.h
  src/kvstore/raftex/RaftPart.cpp
  src/kvstore/raftex/RaftPart.h
  src/kvstore/raftex/SnapshotManager.cpp
  src/kvstore/raftex/test/TestShard.cpp
  src/kvstore/raftex/test/TestShard.h
  src/kvstore/test/NebulaListenerTest.cpp
Labels: ready-for-testing

#4044 Improve test framework for session usage
  tests/admin/test_permission.py
  tests/tck/conftest.py
  tests/tck/features/mutate/ClearSpace.feature
Labels: ready-for-testing

#3929 Feature/expand into filter
  src/graph/planner/match/MatchClausePlanner.cpp
  src/graph/planner/match/MatchClausePlanner.h
  src/graph/validator/MatchValidator.cpp
  tests/data/nba_int_vid/config.yaml
  tests/tck/features/match/Base.IntVid.feature
  tests/tck/features/match/MultiLineMultiQueryParts.feature
  tests/tck/features/match/MultiQueryParts.feature
  tests/tck/features/match/RedefinedNode.feature
Labels: ready-for-testing, doc affected, ready for review

#4040 remove learner parts when removing space
  src/kvstore/NebulaStore.cpp
  src/kvstore/NebulaStore.h
  src/kvstore/PartManager.h
Labels: ready-for-testing

#3550 Segment auto-increasing id
  .github/workflows/pull_request.yml
  src/clients/meta/MetaClient.cpp
  src/clients/meta/MetaClient.h
  src/common/id/CMakeLists.txt
  src/common/id/SegmentId.cpp
  src/common/id/SegmentId.h
  src/common/id/test/CMakeLists.txt
  src/common/id/test/MockMetaClient.h
  src/common/id/test/SegmentIdBenchmark.cpp
  src/common/id/test/SegmentIdTest.cpp
  src/common/id/test/SnowflakeBenchmark.cpp
  src/common/id/test/SnowflakeTest.cpp
  src/interface/common.thrift
  src/interface/meta.thrift
  src/meta/CMakeLists.txt
  src/meta/MetaServiceHandler.cpp
  src/meta/MetaServiceHandler.h
  src/meta/processors/Common.h
  src/meta/processors/id/GetSegmentIdProcessor.cpp
  src/meta/processors/id/GetSegmentIdProcessor.h
  src/meta/processors/id/GetWorkerIdProcessor.cpp
  src/meta/test/CMakeLists.txt
  src/meta/test/IdProcessorTest.cpp
Labels: ready-for-testing, ready for review

#4058 remove duplicate flag
  src/graph/service/GraphFlags.h
Labels: ready-for-testing

#4056 treat E_RAFT_UNKNOWN_APPEND_LOG as succeeded
  src/storage/transaction/ChainAddEdgesLocalProcessor.cpp
  src/storage/transaction/ChainDeleteEdgesLocalProcessor.cpp
  src/storage/transaction/ChainUpdateEdgeLocalProcessor.cpp
Labels: ready-for-testing, ready for review

#3977 Refactor RPC client getResponse implementation
  .github/workflows/pull_request.yml
  src/clients/storage/InternalStorageClient.cpp
  src/clients/storage/StorageClient.cpp
  src/clients/storage/StorageClientBase-inl.h
  src/clients/storage/StorageClientBase.h
  src/common/base/StatusOr.h
  tests/Makefile
  tests/tck/conftest.py
  tests/tck/features/bugfix/LookupIn.feature
  third-party/install-gcc.sh
Labels: ready-for-testing, ready for review

#4068 enhance docker build, using cache
  .github/workflows/nightly.yml
  .github/workflows/rc.yml
  docker/Dockerfile
  docker/Dockerfile.graphd
  docker/Dockerfile.metad
  docker/Dockerfile.storaged
  docker/Dockerfile.tools
  docker/README.md
Labels: ready-for-testing

#3533 Disable breakpad in no-release version
  .github/workflows/rc.yml
  CMakeLists.txt
  cmake/nebula/BreakPadConfig.cmake
  cmake/nebula/GeneralCMakeOptions.cmake
  cmake/nebula/ThirdPartyConfig.cmake
  docker/Dockerfile
  package/package.sh
  src/daemons/GraphDaemon.cpp
  src/daemons/MetaDaemon.cpp
  src/daemons/SetupBreakpad.cpp
  src/daemons/StandAloneDaemon.cpp
  src/daemons/StorageDaemon.cpp
Labels: ready-for-testing, ready for review

#4061 fix bug stop job before it start
  src/meta/processors/job/JobDescription.cpp
  src/meta/processors/job/JobManager.cpp
  src/meta/processors/job/JobManager.h
Labels: ready-for-testing

#4064 add parser notes
  src/parser/parser.yy
  src/parser/scanner.lex
Labels: ready-for-testing

#4067 Refactor job manager part4
  src/common/utils/MetaKeyUtils.cpp
  src/common/utils/MetaKeyUtils.h
  src/graph/executor/admin/SubmitJobExecutor.cpp
  src/interface/meta.thrift
  src/meta/processors/job/JobDescription.cpp
  src/meta/processors/job/JobDescription.h
  src/meta/processors/job/JobManager.cpp
  src/meta/processors/job/RebuildJobExecutor.cpp
  src/meta/processors/job/StorageJobExecutor.cpp
  src/meta/processors/job/TaskDescription.cpp
  src/meta/processors/job/TaskDescription.h
  src/meta/test/BalancerTest.cpp
  src/meta/test/GetStatsTest.cpp
  src/meta/test/JobManagerTest.cpp
  tests/tck/job/Job.feature
Labels: ready-for-testing, ready for review

#3980 Fix some bugs in some cases
  src/common/thread/test/GenericWorkerTest.cpp
  src/kvstore/KVStore.h
  src/kvstore/NebulaStore.cpp
  src/kvstore/NebulaStore.h
  src/kvstore/RocksEngine.cpp
  src/kvstore/RocksEngine.h
  src/meta/ActiveHostsMan.cpp
  src/meta/processors/admin/AgentHBProcessor.cpp
  src/meta/processors/admin/CreateBackupProcessor.cpp
  src/meta/processors/admin/ListClusterInfoProcessor.cpp
  src/meta/processors/admin/ListClusterInfoProcessor.h
  src/meta/processors/admin/RestoreProcessor.cpp
  src/meta/processors/admin/RestoreProcessor.h
  src/meta/test/RestoreProcessorTest.cpp
  src/storage/test/IndexTestUtil.h
Labels: ready-for-testing, ready for review

#4075 Revert https://github.com/vesoft-inc/nebula/pull/3942
  src/clients/meta/MetaClient.cpp
  src/clients/meta/MetaClient.h
  src/graph/service/GraphService.cpp
  src/graph/service/GraphService.h
Labels: ready-for-testing, type/bug, cherry-pick-v3.0

#4080 fix version in docker image and Revert https://github.com/vesoft-inc/nebula/pull/4068
  .github/workflows/nightly.yml
  .github/workflows/rc.yml
  docker/Dockerfile
  docker/Dockerfile.graphd
  docker/Dockerfile.metad
  docker/Dockerfile.storaged
  docker/Dockerfile.tools
  docker/README.md
Labels: ready-for-testing, cherry-pick-v3.0

#4082 cherry pick: 3.0.2
  .github/workflows/nightly.yml
  .github/workflows/rc.yml
  docker/Dockerfile
  docker/Dockerfile.graphd
  docker/Dockerfile.metad
  docker/Dockerfile.storaged
  docker/Dockerfile.tools
  src/clients/meta/MetaClient.cpp
  src/clients/meta/MetaClient.h
  src/graph/service/GraphService.cpp
  src/graph/service/GraphService.h
Labels: ready-for-testing

#4087 fix docker image version （typo）
  .github/workflows/rc.yml
  docker/Dockerfile
  docker/Dockerfile.graphd
  docker/Dockerfile.metad
  docker/Dockerfile.storaged
  docker/Dockerfile.tools
Labels: ready-for-testing, cherry-pick-v3.0

#4090 cherry pick: fix docker image version(typo) (#4087)
  .github/workflows/rc.yml
  docker/Dockerfile
  docker/Dockerfile.graphd
  docker/Dockerfile.metad
  docker/Dockerfile.storaged
  docker/Dockerfile.tools
Labels: ready-for-testing

#4086 Fix breakpad config.
  CMakeLists.txt
  cmake/nebula/BreakPadConfig.cmake
  cmake/nebula/ThirdPartyConfig.cmake
Labels: ready-for-testing, type/bug

#4094 change some log to dlog
  src/storage/transaction/TransactionManager.cpp
Labels: ready-for-testing, ready for review

#4085 balace job show total information
  src/graph/executor/admin/SubmitJobExecutor.cpp
  src/meta/processors/job/BalanceJobExecutor.cpp
Labels: ready-for-testing, ready for review

#4091 Fix build path.
  src/common/expression/PathBuildExpression.cpp
  tests/tck/features/bugfix/BuildPathMistake.feature
Labels: ready-for-testing, type/bug

#4034 Refactor StorageServer stop
  src/common/thread/test/GenericThreadPoolTest.cpp
  src/common/thread/test/GenericWorkerTest.cpp
  src/graph/executor/test/StorageServerStub.cpp
  src/kvstore/NebulaStore.cpp
  src/kvstore/NebulaStore.h
  src/kvstore/raftex/RaftPart.cpp
  src/kvstore/raftex/RaftexService.cpp
  src/kvstore/raftex/RaftexService.h
  src/kvstore/raftex/test/RaftexTestBase.cpp
  src/mock/LocalServer.h
  src/mock/MockCluster.h
  src/storage/GraphStorageLocalServer.cpp
  src/storage/GraphStorageLocalServer.h
  src/storage/StorageServer.cpp
  src/storage/StorageServer.h
Labels: ready-for-testing

#4088 fix crash when try lock raftLock, enable balance by experimental
  src/graph/validator/AdminJobValidator.cpp
  src/kvstore/Listener.cpp
  src/kvstore/Listener.h
  src/kvstore/NebulaStore.cpp
  src/kvstore/Part.cpp
  src/kvstore/Part.h
  src/kvstore/raftex/RaftPart.cpp
  src/kvstore/raftex/RaftPart.h
  src/kvstore/raftex/test/TestShard.cpp
  src/kvstore/raftex/test/TestShard.h
Labels: ready-for-testing

#4100 Add notice for nebula status
  scripts/nebula.service
Labels: ready-for-testing

#4105 Trigger release workflow manually
  .github/actions/tagname-action/action.yml
  .github/workflows/nightly.yml
  .github/workflows/pull_request.yml
  .github/workflows/rc.yml
  .github/workflows/release.yml
  .gitignore
Labels: ready-for-testing
