Repository vesoft-inc/nebula, pull requests merged in 2022-07, with the labels that each got.

#4384 Fixed crash on dropping fulltext index
  src/graph/executor/admin/SpaceExecutor.cpp
Labels: ready-for-testing, cherry-pick-v3.2

#4390 Fix lint build error
  .github/workflows/pull_request.yml
Labels: ready-for-testing, cherry-pick-v3.2

#4386 enhance atomic log buffer memory usage
  src/kvstore/wal/AtomicLogBuffer.cpp
Labels: ready-for-testing, ready for review, cherry-pick-v3.2

#4389 Cherry pick v3.2.0 (0701-0708)
  .github/workflows/pull_request.yml
  src/graph/executor/admin/SpaceExecutor.cpp
  src/kvstore/raftex/RaftPart.cpp
  src/kvstore/wal/AtomicLogBuffer.cpp
Labels: ready-for-testing

#4391 A cluster global timezone configuration.
  resources/gflags.json
  src/clients/meta/MetaClient.cpp
  src/common/meta/GflagsManager.cpp
  src/common/meta/GflagsManager.h
  src/common/time/TimezoneInfo.h
  src/daemons/GraphDaemon.cpp
  src/graph/service/GraphService.cpp
  src/storage/StorageServer.cpp
  tests/admin/test_configs.py
Labels: ready-for-testing, cherry-pick-v3.2

#4393 Cherry pick v3.2.0 (0709-0711)
  resources/gflags.json
  src/clients/meta/MetaClient.cpp
  src/common/meta/GflagsManager.cpp
  src/common/meta/GflagsManager.h
  src/common/time/TimezoneInfo.h
  src/daemons/GraphDaemon.cpp
  src/graph/service/GraphService.cpp
  src/storage/StorageServer.cpp
  tests/admin/test_configs.py
Labels: ready-for-testing

#4400 Release with separate debug info in ELF format
  package/package.sh
Labels: ready-for-testing

#4402 enhance night tck testing
  .github/workflows/nightly.yml
Labels: ready-for-testing

#4395 Replace obsolete RocksDB API
  src/kvstore/RocksEngine.cpp
  src/kvstore/RocksEngine.h
Labels: ready-for-testing

#4405 Fix web service crash(issue:#4398)
  src/webservice/SetFlagsHandler.cpp
Labels: ready-for-testing, cherry-pick-v3.2

#4406 Fix delete vertex or edge, the storage crashed.(issue: #4397)
  src/storage/mutate/DeleteEdgesProcessor.cpp
  src/storage/mutate/DeleteVerticesProcessor.cpp
Labels: ready-for-testing, cherry-pick-v3.2

#4408 Cherry pick 3.2.0 (0712-0713)
  package/package.sh
  src/storage/mutate/DeleteEdgesProcessor.cpp
  src/storage/mutate/DeleteVerticesProcessor.cpp
  src/webservice/SetFlagsHandler.cpp
Labels: ready-for-testing

#4416 fix deadlock
  src/meta/processors/job/LeaderBalanceJobExecutor.cpp
Labels: ready-for-testing, ready for review

#4420 Cherry pick 3.2.0 (0714)
  src/meta/processors/job/LeaderBalanceJobExecutor.cpp
Labels: ready-for-testing

#4421 Add simple vid overlength tck
  tests/tck/features/bugfix/VidInvalidLength.feature
Labels: ready-for-testing, ready for review

#4431 modify the test case of shortestspaths3 to make its results determini…
  tests/tck/features/match/SingleShorestPath.feature
Labels: ready-for-testing, ready for review

#4413 Fix ColumnExpression encode and decode are not matched
  src/common/expression/ColumnExpression.cpp
  src/common/expression/test/ColumnExpressionTest.cpp
Labels: ready-for-testing, ready for review

#4440 add commit in package
  package/package.sh
Labels: ready-for-testing

#4409 Fix/fix log file
  src/daemons/SetupLogging.cpp
Labels: ready-for-testing, type/bug

#4433 [Enhancement] Add opt rule to push down `STARTS WITH` expr
  src/graph/optimizer/rule/OptimizeTagIndexScanByFilterRule.cpp
  src/graph/util/ExpressionUtils.cpp
  src/graph/util/ExpressionUtils.h
  tests/tck/features/lookup/TagIndexFullScan.feature
Labels: type/enhancement, ready-for-testing, ready for review

#4442 fix download always return succeeded
  src/common/hdfs/CMakeLists.txt
  src/common/hdfs/HdfsCommandHelper.cpp
  src/common/hdfs/HdfsCommandHelper.h
  src/common/hdfs/HdfsHelper.h
  src/common/hdfs/test/CMakeLists.txt
  src/common/hdfs/test/HdfsHelperTest.cpp
  src/meta/test/MockHdfsHelper.h
  src/storage/test/MockHdfsHelper.h
Labels: ready-for-testing, ready for review

#4444 Could report error even if there is no task
  src/meta/processors/job/BalanceJobExecutor.cpp
  src/meta/processors/job/BalanceJobExecutor.h
  src/meta/processors/job/DownloadJobExecutor.cpp
  src/meta/processors/job/DownloadJobExecutor.h
  src/meta/processors/job/IngestJobExecutor.cpp
  src/meta/processors/job/IngestJobExecutor.h
  src/meta/processors/job/JobExecutor.h
  src/meta/processors/job/JobManager.cpp
  src/meta/processors/job/JobManager.h
  src/meta/processors/job/MetaJobExecutor.cpp
  src/meta/processors/job/MetaJobExecutor.h
  src/meta/processors/job/SimpleConcurrentJobExecutor.cpp
  src/meta/processors/job/SimpleConcurrentJobExecutor.h
  src/meta/processors/job/StatsJobExecutor.cpp
  src/meta/processors/job/StatsJobExecutor.h
  src/meta/processors/job/StorageJobExecutor.h
  src/meta/test/GetStatsTest.cpp
  src/meta/test/JobManagerTest.cpp
Labels: ready-for-testing, ready for review

#4443 Avoid folly::init overwirte log configuration.
  src/daemons/MetaDaemon.cpp
  src/daemons/StorageDaemon.cpp
Labels: ready-for-testing, type/bug

#4441 ignore order while comparing nested json objects.
  tests/common/plan_differ.py
Labels: ready-for-testing, ready for review

#4414 Fix #4407, building failures with tests on
  src/common/base/ICord.h
  src/common/datatypes/test/ValueTest.cpp
  src/common/graph/tests/ResponseEncodeDecodeTest.cpp
Labels: ready-for-testing, ready for review

#4446 Job manager related fix
  src/clients/meta/MetaClient.cpp
  src/graph/executor/admin/SubmitJobExecutor.cpp
  src/graph/executor/test/JobTest.cpp
  src/interface/common.thrift
  src/meta/processors/job/DataBalanceJobExecutor.cpp
  src/meta/processors/job/DataBalanceJobExecutor.h
  src/meta/processors/job/JobManager.cpp
  src/meta/processors/job/LeaderBalanceJobExecutor.cpp
  src/meta/processors/job/LeaderBalanceJobExecutor.h
  src/meta/processors/job/MetaJobExecutor.cpp
  src/meta/processors/job/MetaJobExecutor.h
  src/meta/processors/job/ZoneBalanceJobExecutor.cpp
  src/meta/processors/job/ZoneBalanceJobExecutor.h
  src/meta/test/BalancerTest.cpp
  tests/tck/job/Job.feature
Labels: ready-for-testing, ready for review

#4468 Update CODE_OF_CONDUCT.md
  Coding_Style_Guide.md
Labels: ready-for-testing
