Repository vesoft-inc/nebula, pull requests merged in 2022-04, with the labels that each got.

#4103 fix memory leak
  src/meta/test/JobManagerTest.cpp
  src/parser/parser.yy
Labels: ready-for-testing

#4024 Param MATCH vid seek fix
  src/graph/planner/match/VertexIdSeek.cpp
  src/graph/visitor/VidExtractVisitor.cpp
  src/graph/visitor/VidExtractVisitor.h
  tests/tck/features/yield/parameter.feature
Labels: ready-for-testing, ready for review, cherry-pick-v3.1

#4110 disable console pkg
  package/package.sh
Labels: ready-for-testing, ready for review, cherry-pick-v3.1

#4112 disable console pkg
  package/package.sh
Labels: ready-for-testing, ready for review, cherry-pick-v3.1

#4111 Fix service crash caused by using function call as a part of the filter in `LOOKUP`
  src/common/function/FunctionManager.cpp
  src/common/function/FunctionManager.h
  src/common/function/test/FunctionManagerTest.cpp
  src/graph/optimizer/OptimizerUtils.cpp
  tests/tck/features/bugfix/LookupIn.feature
Labels: ready-for-testing, cherry-pick-v3.1

#4114 Fix cmake command error in nightly workflow
  .github/workflows/nightly.yml
Labels: ready-for-testing, cherry-pick-v3.1

#4115 Cherry pick v3.1.0 (0401-0402)
  .github/workflows/nightly.yml
  package/package.sh
  src/common/function/FunctionManager.cpp
  src/common/function/FunctionManager.h
  src/common/function/test/FunctionManagerTest.cpp
  src/graph/optimizer/OptimizerUtils.cpp
  src/graph/planner/match/VertexIdSeek.cpp
  src/graph/visitor/VidExtractVisitor.cpp
  src/graph/visitor/VidExtractVisitor.h
  src/meta/test/JobManagerTest.cpp
  src/parser/parser.yy
  tests/tck/features/bugfix/LookupIn.feature
  tests/tck/features/yield/parameter.feature
Labels: ready-for-testing

#4107 fix apply outdate membership change
  src/kvstore/LogEncoder.cpp
  src/kvstore/Part.cpp
  src/meta/processors/admin/AdminClient.cpp
Labels: ready-for-testing, cherry-pick-v3.1

#4101 add code for part peers backward compatible
  src/common/utils/NebulaKeyUtils.cpp
  src/common/utils/NebulaKeyUtils.h
  src/common/utils/Types.h
  src/kvstore/Common.h
  src/kvstore/KVEngine.h
  src/kvstore/NebulaStore.cpp
  src/kvstore/RocksEngine.cpp
  src/kvstore/RocksEngine.h
  src/kvstore/test/NebulaStoreTest.cpp
Labels: ready-for-testing, cherry-pick-v3.1

#4116 fixed_bug_3853
  src/meta/processors/admin/VerifyClientVersionProcessor.cpp
Labels: ready-for-testing, ready for review, cherry-pick-v3.1

#4118 move KW_CLEAR to unresolved keyword
  .linters/cpp/checkKeyword.py
  scripts/nebula.service
  src/parser/parser.yy
  src/parser/scanner.lex
Labels: ready-for-testing, ready for review, cherry-pick-v3.1

#4104 Limits for add and recover balance data or zone balance jobs
  src/clients/meta/MetaClient.cpp
  src/common/graph/Response.h
  src/graph/executor/StorageAccessExecutor.cpp
  src/graph/executor/admin/ChangePasswordExecutor.cpp
  src/graph/executor/admin/ConfigExecutor.cpp
  src/graph/executor/admin/CreateUserExecutor.cpp
  src/graph/executor/admin/DescribeUserExecutor.cpp
  src/graph/executor/admin/DropUserExecutor.cpp
  src/graph/executor/admin/KillQueryExecutor.cpp
  src/graph/executor/admin/ListRolesExecutor.cpp
  src/graph/executor/admin/ListUserRolesExecutor.cpp
  src/graph/executor/admin/PartExecutor.cpp
  src/graph/executor/admin/RevokeRoleExecutor.cpp
  src/graph/executor/admin/ShowHostsExecutor.cpp
  src/graph/executor/admin/ShowMetaLeaderExecutor.cpp
  src/graph/executor/admin/ShowServiceClientsExecutor.cpp
  src/graph/executor/admin/ShowStatsExecutor.cpp
  src/graph/executor/admin/SignInServiceExecutor.cpp
  src/graph/executor/admin/SnapshotExecutor.cpp
  src/graph/executor/logic/ArgumentExecutor.cpp
  src/graph/executor/logic/LoopExecutor.cpp
  src/graph/executor/logic/SelectExecutor.cpp
  src/graph/executor/maintain/EdgeExecutor.cpp
  src/graph/executor/maintain/FTIndexExecutor.cpp
  src/graph/executor/maintain/TagExecutor.cpp
  src/graph/executor/mutate/DeleteExecutor.cpp
  src/graph/executor/mutate/InsertExecutor.cpp
  src/graph/executor/query/AggregateExecutor.cpp
  src/graph/executor/query/AssignExecutor.cpp
  src/graph/executor/query/DataCollectExecutor.cpp
  src/graph/executor/query/FilterExecutor.cpp
  src/graph/executor/query/GetEdgesExecutor.cpp
  src/graph/executor/query/GetNeighborsExecutor.cpp
  src/graph/executor/query/IndexScanExecutor.cpp
  src/graph/executor/query/InnerJoinExecutor.cpp
  src/graph/executor/query/IntersectExecutor.cpp
  src/graph/executor/query/JoinExecutor.cpp
  src/graph/executor/query/LeftJoinExecutor.cpp
  src/graph/executor/query/LimitExecutor.cpp
  src/graph/executor/query/MinusExecutor.cpp
  src/graph/executor/query/ProjectExecutor.cpp
  src/graph/executor/query/SampleExecutor.cpp
  src/graph/executor/query/ScanEdgesExecutor.cpp
  src/graph/executor/query/SetExecutor.cpp
  src/graph/executor/query/SortExecutor.cpp
  src/graph/executor/query/TopNExecutor.cpp
  src/graph/executor/query/TraverseExecutor.cpp
  src/graph/executor/query/UnionAllVersionVarExecutor.cpp
  src/graph/executor/query/UnionExecutor.cpp
  src/graph/executor/query/UnwindExecutor.cpp
  src/interface/common.thrift
  src/meta/processors/job/AdminJobProcessor.cpp
  src/meta/processors/job/JobDescription.h
  src/meta/processors/job/JobManager.cpp
  src/meta/processors/job/JobManager.h
  src/meta/test/JobManagerTest.cpp
Labels: ready-for-testing, ready for review, cherry-pick-v3.1

#4128 Fix group by outputs.
  src/graph/validator/GroupByValidator.cpp
  tests/tck/features/aggregate/Agg.feature
Labels: ready-for-testing, cherry-pick-v3.1

#4119 remove the conception of zone in all place
  src/clients/meta/MetaClient.cpp
  src/graph/executor/admin/SpaceExecutor.cpp
  src/meta/processors/job/ZoneBalanceJobExecutor.cpp
  src/meta/processors/zone/AddHostsProcessor.cpp
  src/meta/processors/zone/DropHostsProcessor.cpp
  src/meta/test/BalancerTest.cpp
  src/parser/parser.yy
  src/parser/test/ParserTest.cpp
  tests/tck/features/schema/Comment.feature
Labels: ready-for-testing, doc affected, cherry-pick-v3.1

#4130 Cherry pick v3.1.0 (0408-0411)
  src/clients/meta/MetaClient.cpp
  src/graph/executor/admin/SpaceExecutor.cpp
  src/graph/validator/GroupByValidator.cpp
  src/meta/processors/job/ZoneBalanceJobExecutor.cpp
  src/meta/processors/zone/AddHostsProcessor.cpp
  src/meta/processors/zone/DropHostsProcessor.cpp
  src/meta/test/BalancerTest.cpp
  src/parser/parser.yy
  src/parser/test/ParserTest.cpp
  src/storage/StorageServer.cpp
  tests/common/nebula_service.py
  tests/tck/features/aggregate/Agg.feature
  tests/tck/features/schema/Comment.feature
Labels: ready-for-testing

#4124 change default variables in release
  .github/workflows/nightly.yml
  .github/workflows/rc.yml
  docker/Dockerfile
  docker/Dockerfile.graphd
  docker/Dockerfile.metad
  docker/Dockerfile.storaged
  docker/Dockerfile.tools
  package/package.sh
Labels: ready-for-testing

#4098 add extract
  src/common/function/FunctionManager.cpp
  src/common/function/test/FunctionManagerTest.cpp
  tests/tck/features/expression/FunctionCall.feature
Labels: ready-for-testing

#4139 fix updatePart
  src/kvstore/KVEngine.h
  src/kvstore/Part.cpp
  src/kvstore/RocksEngine.cpp
  src/kvstore/RocksEngine.h
Labels: ready-for-testing, cherry-pick-v3.1

#4138 show DATA_BALANCE in job list
  src/graph/executor/admin/SubmitJobExecutor.cpp
Labels: ready-for-testing, cherry-pick-v3.1

#4131 fix disk fault recovery
  src/kvstore/DiskManager.cpp
  src/kvstore/NebulaStore.cpp
  src/kvstore/NebulaStore.h
  src/kvstore/PartManager.h
  src/kvstore/test/NebulaStoreTest.cpp
Labels: ready-for-testing, ready for review, cherry-pick-v3.1

#4142 Just report error of property prune in debug
  src/graph/optimizer/Optimizer.cpp
Labels: ready-for-testing, cherry-pick-v3.1

#4127 remove Atomic Edge
  src/graph/executor/admin/SpaceExecutor.cpp
  tests/tck/features/schema/Comment.feature
Labels: ready-for-testing, doc affected, ready for review, cherry-pick-v3.1

#4148 fix show tag/edge index status
  src/meta/processors/job/ListEdgeIndexStatusProcessor.cpp
  src/meta/processors/job/ListTagIndexStatusProcessor.cpp
  src/meta/test/IndexProcessorTest.cpp
Labels: ready-for-testing, ready for review, cherry-pick-v3.1

#4143 fix multiple match
  src/graph/planner/match/MatchClausePlanner.cpp
  src/graph/planner/match/MatchPlanner.cpp
  src/graph/planner/match/MatchPlanner.h
  src/graph/planner/plan/Logic.cpp
  src/graph/planner/plan/Logic.h
  tests/tck/features/match/MultiLineMultiQueryParts.feature
Labels: ready-for-testing, ready for review, cherry-pick-v3.1

#4146 Refactor the process of symbols in optimizer.
  src/graph/context/Symbols.cpp
  src/graph/optimizer/OptGroup.cpp
  src/graph/optimizer/OptGroup.h
  src/graph/optimizer/OptRule.cpp
  src/graph/optimizer/OptRule.h
  src/graph/optimizer/rule/CollapseProjectRule.cpp
  src/graph/optimizer/rule/GetEdgesTransformRule.cpp
  src/graph/optimizer/rule/IndexScanRule.cpp
  src/graph/optimizer/rule/MergeGetNbrsAndDedupRule.cpp
  src/graph/optimizer/rule/MergeGetNbrsAndProjectRule.cpp
  src/graph/optimizer/rule/MergeGetVerticesAndDedupRule.cpp
  src/graph/optimizer/rule/MergeGetVerticesAndProjectRule.cpp
  src/graph/optimizer/rule/PushFilterDownGetNbrsRule.cpp
  src/graph/optimizer/rule/PushFilterDownProjectRule.cpp
  src/graph/optimizer/rule/PushFilterDownScanVerticesRule.cpp
  src/graph/optimizer/rule/PushLimitDownGetNeighborsRule.cpp
  src/graph/optimizer/rule/PushLimitDownIndexScanRule.cpp
  src/graph/optimizer/rule/PushLimitDownProjectRule.cpp
  src/graph/optimizer/rule/PushLimitDownScanAppendVerticesRule.cpp
  src/graph/optimizer/rule/PushLimitDownScanEdgesAppendVerticesRule.cpp
  src/graph/optimizer/rule/PushStepLimitDownGetNeighborsRule.cpp
  src/graph/optimizer/rule/PushStepSampleDownGetNeighborsRule.cpp
  src/graph/optimizer/rule/PushTopNDownIndexScanRule.cpp
  src/graph/optimizer/rule/PushVFilterDownScanVerticesRule.cpp
  src/graph/planner/plan/PlanNode.cpp
  src/graph/planner/plan/PlanNode.h
  src/graph/scheduler/AsyncMsgNotifyBasedScheduler.cpp
  src/graph/scheduler/AsyncMsgNotifyBasedScheduler.h
Labels: ready-for-testing, type/bug, cherry-pick-v3.1

#4158 fix issue 4152
  src/graph/service/GraphService.cpp
  src/graph/session/GraphSessionManager.cpp
Labels: ready-for-testing, cherry-pick-v3.1

#4159 Fix optional of multi-match
  src/graph/planner/match/MatchPlanner.cpp
  tests/tck/features/match/MultiLineMultiQueryParts.feature
Labels: ready-for-testing, ready for review, cherry-pick-v3.1

#4165 Fix incompatibility imported by https://github.com/vesoft-inc/nebula/pull/4116
  src/clients/meta/MetaClient.cpp
  src/clients/meta/MetaClient.h
  src/interface/meta.thrift
  src/meta/CMakeLists.txt
  src/meta/MetaServiceHandler.cpp
  src/meta/MetaServiceHandler.h
  src/meta/processors/admin/SaveGraphVersionProcessor.cpp
  src/meta/processors/admin/SaveGraphVersionProcessor.h
  src/meta/processors/admin/VerifyClientVersionProcessor.cpp
Labels: ready-for-testing, type/bug, cherry-pick-v3.1

#4162 optimizer path
  src/graph/executor/algo/BFSShortestPathExecutor.cpp
  src/graph/executor/algo/MultiShortestPathExecutor.cpp
  src/graph/executor/algo/MultiShortestPathExecutor.h
  src/graph/executor/algo/ProduceAllPathsExecutor.cpp
  src/graph/executor/test/FindPathTest.cpp
  src/graph/service/GraphFlags.cpp
Labels: ready-for-testing, ready for review, cherry-pick-v3.1

#4177 skip heartbeat for tool
  src/clients/meta/MetaClient.cpp
Labels: ready-for-testing, cherry-pick-v3.1

#4180 Fix/null pattern expression input
  src/graph/validator/MatchValidator.cpp
  tests/tck/features/bugfix/AggPatternExpression.feature
Labels: ready-for-testing, type/bug, cherry-pick-v3.1

#4182 fix wrong space key after dropping hosts
  src/meta/processors/zone/DropHostsProcessor.cpp
  src/meta/processors/zone/DropHostsProcessor.h
Labels: ready-for-testing, cherry-pick-v3.1

#4189 fix vertex is missing from snapshot
  src/common/utils/NebulaKeyUtils.cpp
Labels: ready-for-testing, cherry-pick-v3.1

#4190 Expression is stateful to store the result of evaluation, so we can't…
  src/storage/query/ScanEdgeProcessor.cpp
  src/storage/query/ScanVertexProcessor.cpp
Labels: ready-for-testing, type/bug, cherry-pick-v3.1

#4183 Cherry pick v3.1.0 (0414-0420)
  src/clients/meta/MetaClient.cpp
  src/clients/meta/MetaClient.h
  src/common/utils/NebulaKeyUtils.cpp
  src/graph/executor/algo/BFSShortestPathExecutor.cpp
  src/graph/executor/algo/MultiShortestPathExecutor.cpp
  src/graph/executor/algo/MultiShortestPathExecutor.h
  src/graph/executor/algo/ProduceAllPathsExecutor.cpp
  src/graph/executor/test/FindPathTest.cpp
  src/graph/planner/match/MatchPlanner.cpp
  src/graph/service/GraphFlags.cpp
  src/graph/service/GraphService.cpp
  src/graph/session/GraphSessionManager.cpp
  src/graph/validator/MatchValidator.cpp
  src/interface/meta.thrift
  src/meta/CMakeLists.txt
  src/meta/MetaServiceHandler.cpp
  src/meta/MetaServiceHandler.h
  src/meta/processors/admin/SaveGraphVersionProcessor.cpp
  src/meta/processors/admin/SaveGraphVersionProcessor.h
  src/meta/processors/admin/VerifyClientVersionProcessor.cpp
  src/meta/processors/zone/DropHostsProcessor.cpp
  src/meta/processors/zone/DropHostsProcessor.h
  src/storage/query/ScanEdgeProcessor.cpp
  src/storage/query/ScanVertexProcessor.cpp
  tests/tck/features/bugfix/AggPatternExpression.feature
  tests/tck/features/match/MultiLineMultiQueryParts.feature
Labels: ready-for-testing

#3926 Memory lock in raft
  src/kvstore/CMakeLists.txt
  src/kvstore/Common.h
  src/kvstore/KVStore.h
  src/kvstore/NebulaStore.cpp
  src/kvstore/NebulaStore.h
  src/kvstore/Part.cpp
  src/kvstore/Part.h
  src/kvstore/raftex/CMakeLists.txt
  src/kvstore/raftex/RaftPart.cpp
  src/kvstore/raftex/RaftPart.h
  src/kvstore/raftex/test/LogCASTest.cpp
  src/kvstore/raftex/test/LogCommandTest.cpp
  src/kvstore/raftex/test/RaftexTestBase.cpp
  src/kvstore/raftex/test/TestShard.cpp
  src/kvstore/test/NebulaStoreTest.cpp
  src/storage/mutate/AddEdgesProcessor.cpp
  src/storage/mutate/AddEdgesProcessor.h
  src/storage/mutate/AddVerticesProcessor.cpp
  src/storage/mutate/AddVerticesProcessor.h
  src/storage/test/IndexTestUtil.h
  src/storage/test/RebuildIndexTest.cpp
  src/storage/test/StatsTaskTest.cpp
Labels: ready-for-testing, ready for review, cherry-pick-v3.1

#4195 Cherry pick v3.1.0 (0421)
  src/kvstore/CMakeLists.txt
  src/kvstore/Common.h
  src/kvstore/KVStore.h
  src/kvstore/NebulaStore.cpp
  src/kvstore/NebulaStore.h
  src/kvstore/Part.cpp
  src/kvstore/Part.h
  src/kvstore/raftex/CMakeLists.txt
  src/kvstore/raftex/RaftPart.cpp
  src/kvstore/raftex/RaftPart.h
  src/kvstore/raftex/test/LogCASTest.cpp
  src/kvstore/raftex/test/LogCommandTest.cpp
  src/kvstore/raftex/test/RaftexTestBase.cpp
  src/kvstore/raftex/test/TestShard.cpp
  src/kvstore/test/NebulaStoreTest.cpp
  src/storage/mutate/AddEdgesProcessor.cpp
  src/storage/mutate/AddEdgesProcessor.h
  src/storage/mutate/AddVerticesProcessor.cpp
  src/storage/mutate/AddVerticesProcessor.h
  src/storage/test/IndexTestUtil.h
  src/storage/test/RebuildIndexTest.cpp
  src/storage/test/StatsTaskTest.cpp
Labels: ready-for-testing

#4141 Enhancement/pattern planner
  src/graph/context/ast/CypherAstContext.h
  src/graph/planner/CMakeLists.txt
  src/graph/planner/match/ArgumentFinder.cpp
  src/graph/planner/match/LabelIndexSeek.cpp
  src/graph/planner/match/MatchClausePlanner.cpp
  src/graph/planner/match/MatchClausePlanner.h
  src/graph/planner/match/MatchPathPlanner.cpp
  src/graph/planner/match/MatchPathPlanner.h
  src/graph/planner/match/MatchPlanner.cpp
  src/graph/planner/match/PropIndexSeek.cpp
  src/graph/planner/match/ReturnClausePlanner.cpp
  src/graph/planner/match/ScanSeek.cpp
  src/graph/planner/match/SegmentsConnector.cpp
  src/graph/planner/match/SegmentsConnector.h
  src/graph/planner/match/UnwindClausePlanner.cpp
  src/graph/planner/match/VertexIdSeek.cpp
  src/graph/planner/match/WhereClausePlanner.cpp
  src/graph/planner/match/WithClausePlanner.cpp
  src/graph/planner/match/YieldClausePlanner.cpp
  src/graph/planner/plan/PlanNode.cpp
  src/graph/planner/plan/PlanNode.h
  src/graph/scheduler/Scheduler.h
  src/graph/validator/MatchValidator.cpp
  src/graph/validator/MatchValidator.h
Labels: ready-for-testing

#4196 fix a bug: I guess storage may core
  src/storage/mutate/AddVerticesProcessor.cpp
  src/storage/mutate/AddVerticesProcessor.h
Labels: ready-for-testing, ready for review, cherry-pick-v3.1

#4204 Cherry pick v3.1.0 (0422-0423)
  src/storage/mutate/AddVerticesProcessor.cpp
  src/storage/mutate/AddVerticesProcessor.h
Labels: ready-for-testing

#4201 Add comments of error code
  src/interface/common.thrift
Labels: ready-for-testing

#4208 fix two-level file directory after OSS copy
  .github/workflows/release.yml
Labels: ready-for-testing

#4207 fix error message
  src/clients/meta/MetaClient.cpp
  src/meta/processors/job/AdminJobProcessor.cpp
  src/meta/processors/job/DataBalanceJobExecutor.cpp
  src/meta/processors/job/JobManager.h
  src/meta/processors/job/ZoneBalanceJobExecutor.cpp
Labels: ready-for-testing

#4149 fix tck compare in order
  tests/common/comparator.py
  tests/tck/conftest.py
  tests/tck/features/go/Orderby.feature
  tests/tck/features/match/MultiLineMultiQueryParts.feature
  tests/tck/features/match/MultiQueryParts.feature
  tests/tck/features/optimizer/PrunePropertiesRule.feature
Labels: ready-for-testing

#4206 Add id to worker name.
  src/common/thread/GenericThreadPool.cpp
Labels: ready-for-testing

#4151 fix bug：Using the same statement to return same vertex different properties, the results show BAD TYPE.
  src/graph/context/ast/CypherAstContext.h
  src/graph/util/ExpressionUtils.cpp
  src/graph/util/ExpressionUtils.h
  src/graph/validator/MatchValidator.cpp
  src/graph/visitor/CMakeLists.txt
  src/graph/visitor/ExtractGroupSuiteVisitor.cpp
  src/graph/visitor/ExtractGroupSuiteVisitor.h
  src/graph/visitor/test/CMakeLists.txt
  src/graph/visitor/test/ExtractGroupSuiteVisitorTest.cpp
  src/graph/visitor/test/VisitorTestBase.h
  tests/tck/features/aggregate/Agg.feature
  tests/tck/features/bugfix/AggPatternExpression.feature
Labels: ready-for-testing, ready for review

#4210 Fix/plan compare
  src/graph/planner/plan/Admin.cpp
  src/graph/planner/plan/Algo.cpp
  src/graph/planner/plan/Maintain.cpp
  src/graph/planner/plan/Mutate.cpp
  src/graph/planner/plan/Query.cpp
  src/graph/util/ToJson.cpp
  src/graph/util/ToJson.h
  tests/common/plan_differ.py
  tests/common/utils.py
  tests/nebula-test-run.py
  tests/requirements.txt
  tests/tck/features/optimizer/PrunePropertiesRule.feature
Labels: ready-for-testing

#4212 Enhancement/prune properties root node
  src/graph/visitor/PrunePropertiesVisitor.cpp
  src/graph/visitor/PrunePropertiesVisitor.h
Labels: ready-for-testing
