Repository vesoft-inc/nebula, pull requests merged in 2022-08, with the labels that each got.

#4460 make 'stop job' work as expected
  src/meta/processors/job/BalanceJobExecutor.cpp
  src/meta/processors/job/BalanceJobExecutor.h
  src/meta/processors/job/DownloadJobExecutor.cpp
  src/meta/processors/job/DownloadJobExecutor.h
  src/meta/processors/job/JobDescription.h
  src/meta/processors/job/JobManager.cpp
  src/meta/processors/job/JobManager.h
  src/meta/processors/job/MetaJobExecutor.cpp
  src/meta/processors/job/RebuildFTJobExecutor.h
  src/meta/processors/job/SimpleConcurrentJobExecutor.cpp
  src/meta/processors/job/SimpleConcurrentJobExecutor.h
  src/meta/processors/job/StorageJobExecutor.h
  src/meta/test/JobManagerTest.cpp
Labels: ready-for-testing, ready for review

#4471 fix wrong image path for architecture
  README-CN.md
Labels: ready-for-testing

#4481 doc: Community in Badges
  README-CN.md
  README.md
Labels: ready-for-testing, ready for review

#4517 Add case for bugfix https://github.com/vesoft-inc/nebula/issues/4417
  tests/tck/features/match/SeekById.feature
Labels: ready-for-testing, ready for review

#4498 Feature/pattern expression ref local variable
  src/common/expression/MatchPathPatternExpression.cpp
  src/common/expression/MatchPathPatternExpression.h
  src/common/function/FunctionManager.cpp
  src/graph/util/AnonVarGenerator.h
  src/graph/util/ParserUtil.cpp
  src/graph/validator/MatchValidator.cpp
  src/graph/visitor/CMakeLists.txt
  src/graph/visitor/ExprVisitorImpl.cpp
  src/graph/visitor/FindVisitor.cpp
  src/graph/visitor/RewriteSymExprVisitor.cpp
  src/graph/visitor/ValidatePatternExpressionVisitor.cpp
  src/graph/visitor/ValidatePatternExpressionVisitor.h
  src/parser/MatchPath.h
  src/parser/parser.yy
  tests/data/ldbc_v0_3_3/config.yaml
  tests/tck/features/match/PathExprRefLocalVariable.feature
  tests/tck/features/optimizer/PushFilterDownGetNbrsRule.feature
  tests/tck/ldbc/interactive_workload/ComplexReads.feature
Labels: ready-for-testing

#4500 Some minor enhancement
  src/clients/meta/MetaClient.cpp
  src/graph/executor/admin/SubmitJobExecutor.cpp
  src/interface/common.thrift
  src/meta/processors/schema/CreateEdgeProcessor.cpp
  src/meta/processors/schema/DropEdgeProcessor.cpp
  src/meta/processors/schema/DropTagProcessor.cpp
  src/meta/processors/zone/DropHostsProcessor.cpp
  src/meta/processors/zone/DropZoneProcessor.cpp
  src/meta/test/IndexProcessorTest.cpp
  src/meta/test/ProcessorTest.cpp
  src/storage/admin/StatsTask.cpp
  src/storage/admin/StatsTask.h
Labels: ready-for-testing, ready for review

#4522 Fix some pointer partial specializations are missing in hash and equal_to in Value and Row
  src/common/datatypes/List.h
  src/common/datatypes/Value.h
  src/common/datatypes/test/ValueTest.cpp
  src/graph/context/Iterator.h
Labels: ready-for-testing, ready for review

#4526 datetime2timestamp and timestamp2datetime
  src/common/function/FunctionManager.cpp
  src/common/function/test/FunctionManagerTest.cpp
  src/common/time/TimeUtils.cpp
Labels: ready-for-testing

#4533 remove useless datacollect plan node
  src/graph/planner/SequentialPlanner.cpp
  src/graph/planner/SequentialPlanner.h
  src/graph/validator/test/FetchEdgesTest.cpp
  src/graph/validator/test/FetchVerticesTest.cpp
  src/graph/validator/test/MatchValidatorTest.cpp
  src/graph/validator/test/QueryValidatorTest.cpp
  src/graph/validator/test/YieldValidatorTest.cpp
  tests/tck/features/lookup/LookUpLimit.feature
  tests/tck/features/lookup/LookUpTopN.feature
  tests/tck/features/optimizer/CollapseProjectRule.feature
  tests/tck/features/optimizer/PrunePropertiesRule.feature
  tests/tck/features/optimizer/PushFilterDownAggregateRule.feature
  tests/tck/features/optimizer/PushFilterDownProjectRule.feature
  tests/tck/features/optimizer/RemoveUselessProjectRule.feature
  tests/tck/features/optimizer/TopNRule.feature
Labels: ready-for-testing

#4552 fix lookup crash
  src/graph/optimizer/rule/OptimizeEdgeIndexScanByFilterRule.cpp
  tests/tck/features/lookup/LookUp.feature
Labels: ready-for-testing, ready for review, affects-v3.2

#4516 optimize multi-hop go stmt
  src/clients/storage/StorageClient.cpp
  src/clients/storage/StorageClient.h
  src/graph/context/ast/QueryAstContext.h
  src/graph/executor/CMakeLists.txt
  src/graph/executor/Executor.cpp
  src/graph/executor/StorageAccessExecutor.cpp
  src/graph/executor/StorageAccessExecutor.h
  src/graph/executor/query/GetDstBySrcExecutor.cpp
  src/graph/executor/query/GetDstBySrcExecutor.h
  src/graph/executor/test/StorageServerStub.cpp
  src/graph/planner/ngql/GoPlanner.cpp
  src/graph/planner/ngql/GoPlanner.h
  src/graph/planner/plan/PlanNode.cpp
  src/graph/planner/plan/PlanNode.h
  src/graph/planner/plan/Query.cpp
  src/graph/planner/plan/Query.h
  src/graph/validator/test/QueryValidatorTest.cpp
  src/storage/GraphStorageLocalServer.cpp
  src/storage/GraphStorageLocalServer.h
  tests/tck/features/go/SimpleCase.feature
Labels: ready-for-testing

#4555 optimize count(*)
  src/graph/executor/query/AggregateExecutor.cpp
  tests/tck/features/aggregate/Agg.feature
Labels: ready-for-testing

#4556 [k-hop]Remove useless inner join for go in simple case
  src/graph/executor/query/GetDstBySrcExecutor.cpp
  src/graph/planner/ngql/GoPlanner.cpp
  tests/tck/features/go/SimpleCase.feature
Labels: ready-for-testing

#4550 Fix stats log print to console when we start process.
  src/daemons/MetaDaemon.cpp
  src/daemons/StorageDaemon.cpp
Labels: ready-for-testing

#4527 sync thrift modification of incremental backup and restore
  src/clients/meta/MetaClient.cpp
  src/interface/common.thrift
  src/interface/meta.thrift
  src/kvstore/NebulaStore.cpp
  src/meta/MetaServiceHandler.cpp
  src/meta/MetaServiceHandler.h
  src/meta/processors/admin/CreateBackupProcessor.h
  src/meta/processors/admin/DropSnapshotProcessor.cpp
  src/meta/processors/admin/RestoreProcessor.h
  src/meta/test/AdminClientTest.cpp
  src/meta/test/CreateBackupProcessorTest.cpp
Labels: ready-for-testing, incompatible, ready for review

#4448 Fix/twice timezone conversion
  src/common/function/FunctionManager.cpp
  src/common/function/test/CMakeLists.txt
  src/common/function/test/TwiceTimezoneConversionTest.cpp
  src/common/time/TimeUtils.cpp
  src/common/time/TimeUtils.h
  src/common/time/parser/DatetimeReader.cpp
  src/common/time/parser/DatetimeReader.h
  src/common/time/parser/Result.h
  src/common/time/parser/datetime_parser.yy
  src/common/time/parser/test/DateTimeParserTest.cpp
  src/common/time/test/TimeUtilsTest.cpp
  src/meta/test/MetaClientTest.cpp
Labels: ready-for-testing, type/bug, ready for review

#4562 doc: improve star conversion rate for README
  README-CN.md
  README.md
Labels: ready-for-testing

#4568 fix invalid filter in GetProp make storage crashed
  src/storage/exec/QueryUtils.h
  src/storage/test/GetPropTest.cpp
Labels: ready-for-testing, ready for review

#4553 Disable count(distinct *)
  src/parser/parser.yy
  src/parser/test/ParserTest.cpp
Labels: ready-for-testing, ready for review

#4577 replace spinlock with sharedmutex
  src/clients/meta/MetaClient.cpp
  src/clients/meta/MetaClient.h
Labels: ready-for-testing

#4515 refactor recover job
  src/clients/meta/MetaClient.cpp
  src/meta/processors/job/AdminJobProcessor.cpp
  src/meta/processors/job/JobManager.cpp
  src/meta/processors/job/JobManager.h
  src/meta/test/JobManagerTest.cpp
Labels: ready-for-testing

#4582 fix dedup for GetDstBySrc
  src/graph/executor/algo/BFSShortestPathExecutor.cpp
  src/graph/executor/algo/BFSShortestPathExecutor.h
  src/graph/executor/algo/BatchShortestPath.cpp
  src/graph/executor/algo/BatchShortestPath.h
  src/graph/executor/algo/MultiShortestPathExecutor.h
  src/graph/executor/algo/ProduceAllPathsExecutor.cpp
  src/graph/executor/algo/ProduceAllPathsExecutor.h
  src/graph/executor/algo/ShortestPathBase.h
  src/graph/executor/algo/ShortestPathExecutor.cpp
  src/graph/executor/algo/ShortestPathExecutor.h
  src/graph/executor/algo/SingleShortestPath.cpp
  src/graph/executor/algo/SingleShortestPath.h
  src/graph/executor/algo/SubgraphExecutor.cpp
  src/graph/executor/algo/SubgraphExecutor.h
  src/graph/executor/query/MinusExecutor.cpp
  src/storage/query/GetDstBySrcProcessor.cpp
Labels: ready-for-testing

#4578 fix scan vertex/edge do not handle ttl
  src/storage/exec/ScanNode.h
  src/storage/query/ScanEdgeProcessor.cpp
  src/storage/query/ScanVertexProcessor.cpp
  src/storage/test/ScanEdgeTest.cpp
  src/storage/test/ScanVertexTest.cpp
Labels: ready-for-testing, ready for review

#4523 Prune properties
  src/graph/context/Iterator.cpp
  src/graph/executor/query/AppendVerticesExecutor.cpp
  src/graph/executor/query/AppendVerticesExecutor.h
  src/graph/planner/match/MatchSolver.cpp
  src/graph/planner/match/MatchSolver.h
  src/graph/planner/ngql/PathPlanner.cpp
  src/graph/planner/plan/Algo.cpp
  src/graph/planner/plan/Algo.h
  src/graph/planner/plan/PlanNodeVisitor.h
  src/graph/planner/plan/Query.cpp
  src/graph/planner/plan/Query.h
  src/graph/service/GraphFlags.cpp
  src/graph/service/GraphFlags.h
  src/graph/visitor/PropertyTrackerVisitor.cpp
  src/graph/visitor/PropertyTrackerVisitor.h
  src/graph/visitor/PrunePropertiesVisitor.cpp
  src/graph/visitor/PrunePropertiesVisitor.h
  tests/tck/features/optimizer/PrunePropertiesRule.feature
Labels: type/enhancement, ready-for-testing, priority/hi-pri, ready for review

#4524 fix datetime format
  src/common/time/TimeUtils.cpp
  src/common/time/TimeUtils.h
  src/common/time/parser/datetime_parser.yy
  src/common/time/parser/datetime_scanner.lex
  src/common/time/parser/test/DateTimeParserTest.cpp
Labels: ready-for-testing

#4583 Change input vid format
  src/clients/storage/StorageClient.cpp
  src/clients/storage/StorageClient.h
  src/common/expression/CaseExpression.cpp
  src/graph/context/Iterator.cpp
  src/graph/context/Result.h
  src/graph/executor/StorageAccessExecutor.cpp
  src/graph/executor/StorageAccessExecutor.h
  src/graph/executor/algo/BatchShortestPath.cpp
  src/graph/executor/algo/ShortestPathBase.h
  src/graph/executor/algo/ShortestPathExecutor.cpp
  src/graph/executor/algo/SingleShortestPath.cpp
  src/graph/executor/query/GetDstBySrcExecutor.cpp
  src/graph/executor/query/GetDstBySrcExecutor.h
  src/graph/executor/query/GetNeighborsExecutor.cpp
  src/graph/executor/query/GetNeighborsExecutor.h
  src/graph/executor/query/TraverseExecutor.cpp
  src/graph/executor/query/TraverseExecutor.h
  src/graph/executor/test/GetNeighborsTest.cpp
  src/graph/validator/GoValidator.cpp
  src/interface/storage.thrift
  src/storage/query/GetNeighborsProcessor.cpp
  src/storage/query/GetNeighborsProcessor.h
  src/storage/test/QueryTestUtils.h
  src/tools/storage-perf/StoragePerfTool.cpp
  tests/tck/features/match/SingleShorestPath.feature
Labels: ready-for-testing, priority/hi-pri, ready for review

#4600 thirdparty 3.x
  cmake/nebula/ThirdPartyConfig.cmake
Labels: ready-for-testing
