Repository vesoft-inc/nebula, pull requests merged in 2022-05, with the labels that each got.

#4226 modify subgraph loop condition
  src/graph/planner/ngql/SubgraphPlanner.cpp
Labels: type/enhancement, ready-for-testing, ready for review

#4234 fix lookup crash when has nullable cols
  src/common/meta/NebulaSchemaProvider.h
  src/storage/exec/IndexEdgeScanNode.cpp
  src/storage/exec/IndexEdgeScanNode.h
  src/storage/exec/IndexScanNode.cpp
  src/storage/exec/IndexScanNode.h
  src/storage/exec/IndexVertexScanNode.cpp
  src/storage/exec/IndexVertexScanNode.h
  src/storage/index/LookupProcessor.cpp
  src/storage/index/LookupProcessor.h
  src/storage/test/IndexTest.cpp
  tests/tck/features/index/Index.feature
Labels: ready-for-testing, ready for review

#4245 fix listener can't receive snapshot anymore
  src/kvstore/Listener.cpp
  src/kvstore/raftex/RaftPart.h
  src/kvstore/raftex/SnapshotManager.cpp
Labels: ready-for-testing

#4249 Eliminate vid predication Filter.
  src/graph/context/ast/CypherAstContext.h
  src/graph/planner/match/LabelIndexSeek.cpp
  src/graph/planner/match/MatchClausePlanner.cpp
  src/graph/planner/match/MatchPathPlanner.cpp
  src/graph/planner/match/MatchPathPlanner.h
  src/graph/planner/match/PropIndexSeek.cpp
  src/graph/planner/match/SegmentsConnector.cpp
  src/graph/planner/match/VertexIdSeek.cpp
  src/graph/planner/match/WhereClausePlanner.cpp
  src/graph/util/ExpressionUtils.cpp
  src/graph/util/ExpressionUtils.h
  src/graph/validator/test/QueryValidatorTest.cpp
  tests/tck/features/match/SeekById.feature
  tests/tck/features/match/SeekById.intVid.feature
  tests/tck/features/optimizer/PrunePropertiesRule.feature
Labels: type/enhancement, ready-for-testing, ready for review

#4235 Update AtomicLogBufferTest.cpp
  src/kvstore/wal/test/AtomicLogBufferTest.cpp
Labels: ready-for-testing

#4236 Update RaftPart.cpp
  src/kvstore/raftex/RaftPart.cpp
Labels: ready-for-testing

#4257 CNCF Landscape enrichment in README
  README.md
Labels: ready-for-testing

#4268 Fix sharing filter expression inter threads.
  src/storage/query/GetPropProcessor.cpp
Labels: ready-for-testing, type/bug

#4176 Move input rows of Traverse and AppendVertices.
  src/graph/context/Iterator.h
  src/graph/executor/Executor.cpp
  src/graph/executor/Executor.h
  src/graph/executor/query/AppendVerticesExecutor.cpp
  src/graph/executor/query/TraverseExecutor.cpp
Labels: ready-for-testing, ready for review

#4269 Fix restart failed
  src/clients/meta/MetaClient.cpp
  src/clients/meta/MetaClient.h
  src/storage/StorageServer.cpp
Labels: ready-for-testing

#4288 Repair some problems in query_concurrently mode
  src/storage/exec/IndexSelectionNode.cpp
  src/storage/exec/IndexTopNNode.cpp
  src/storage/exec/IndexTopNNode.h
  src/storage/index/LookupProcessor.cpp
Labels: ready-for-testing, ready for review

#4280 Fix the format of explain of input variables of Join.
  src/graph/planner/plan/Query.cpp
Labels: type/enhancement, ready-for-testing

#4277 Remove useless AppendVertices.
  src/graph/optimizer/CMakeLists.txt
  src/graph/optimizer/rule/EliminateAppendVerticesRule.cpp
  src/graph/optimizer/rule/EliminateAppendVerticesRule.h
  src/graph/optimizer/rule/GetEdgesTransformRule.cpp
  src/graph/optimizer/rule/PushLimitDownScanEdgesRule.cpp
  src/graph/optimizer/rule/PushLimitDownScanEdgesRule.h
  src/graph/util/AnonVarGenerator.h
  tests/tck/features/optimizer/EliminateAppendVerticesRule.feature
  tests/tck/features/optimizer/PrunePropertiesRule.feature
Labels: type/enhancement, ready-for-testing
