Repository vesoft-inc/nebula, pull requests merged in 2022-02, with the labels that each got.

#3855 skip heartbeat when role in meta client is not set
  src/clients/meta/MetaClient.cpp
  src/clients/meta/MetaClient.h
Labels: ready-for-testing, priority/hi-pri, cherry-pick-v3.0

#3845 Remove unused code.
  src/common/time/TimeUtils.cpp
  src/common/time/parser/DatetimeReader.cpp
  src/common/time/parser/DatetimeReader.h
  src/common/time/parser/datetime_parser.yy
  src/common/time/parser/test/DateTimeParserTest.cpp
Labels: ready-for-testing

#3857 Try to improve the performance of appendVertices
  src/graph/executor/query/AppendVerticesExecutor.cpp
  tests/tck/features/match/Base.feature
Labels: ready-for-testing

#3859 keep consistent with 2.6.x
  .github/workflows/rc.yml
Labels: cherry-pick-v3.0

#3453 Unique ID: UUID
  src/common/id/CMakeLists.txt
  src/common/id/UUID.cpp
  src/common/id/UUID.h
Labels: ready-for-testing, ready for review

#3863 Remove discarded flag
  src/daemons/MetaDaemon.cpp
  src/meta/http/MetaHttpIngestHandler.cpp
Labels: ready-for-testing

#3856 cherry pick: 0208
  .github/workflows/rc.yml
  src/clients/meta/MetaClient.cpp
  src/clients/meta/MetaClient.h
  src/graph/executor/query/AppendVerticesExecutor.cpp
  tests/tck/features/match/Base.feature
Labels: ready-for-testing

#3867 delete src/common/encryption src/common/base/stringunorderedmap
  src/common/CMakeLists.txt
  src/common/base/StringUnorderedMap.h
  src/common/encryption/Base64.cpp
  src/common/encryption/Base64.h
  src/common/encryption/CMakeLists.txt
  src/common/encryption/MD5Utils.cpp
  src/common/encryption/MD5Utils.h
  src/common/expression/test/CMakeLists.txt
  src/common/plugin/fulltext/FTUtils.h
  src/common/plugin/fulltext/test/CMakeLists.txt
  src/common/plugin/fulltext/test/FulltextPluginTest.cpp
  src/common/utils/test/CMakeLists.txt
  src/daemons/CMakeLists.txt
  src/graph/context/test/CMakeLists.txt
  src/graph/executor/admin/ChangePasswordExecutor.cpp
  src/graph/executor/admin/CreateUserExecutor.cpp
  src/graph/executor/admin/UpdateUserExecutor.cpp
  src/graph/executor/test/CMakeLists.txt
  src/graph/optimizer/test/CMakeLists.txt
  src/graph/service/CloudAuthenticator.cpp
  src/graph/service/GraphService.cpp
  src/graph/util/test/CMakeLists.txt
  src/graph/validator/test/CMakeLists.txt
  src/graph/visitor/test/CMakeLists.txt
  src/kvstore/test/CMakeLists.txt
  src/meta/CMakeLists.txt
  src/meta/RootUserMan.h
  src/parser/test/CMakeLists.txt
  src/storage/test/CMakeLists.txt
  src/tools/db-dump/CMakeLists.txt
  src/tools/db-upgrade/CMakeLists.txt
  src/tools/meta-dump/CMakeLists.txt
  src/tools/simple-kv-verify/CMakeLists.txt
  src/tools/storage-perf/CMakeLists.txt
Labels: ready-for-testing

#3848 remove concurrent base/stringvalue, use boost::barrier instead
  src/common/CMakeLists.txt
  src/common/base/CMakeLists.txt
  src/common/base/ObjectPool.h
  src/common/base/StringValue.cpp
  src/common/base/StringValue.h
  src/common/concurrent/Barrier.cpp
  src/common/concurrent/Barrier.h
  src/common/concurrent/CMakeLists.txt
  src/common/concurrent/Latch.cpp
  src/common/concurrent/Latch.h
  src/common/concurrent/test/BarrierTest.cpp
  src/common/concurrent/test/CMakeLists.txt
  src/common/concurrent/test/LatchTest.cpp
  src/common/cpp/helpers.h
  src/common/thread/GenericThreadPool.h
  src/common/thread/GenericWorker.h
  src/common/thread/test/CMakeLists.txt
  src/daemons/CMakeLists.txt
  src/graph/executor/Executor.h
  src/graph/executor/test/CMakeLists.txt
  src/graph/optimizer/OptContext.h
  src/graph/optimizer/test/CMakeLists.txt
  src/graph/planner/test/CMakeLists.txt
  src/graph/scheduler/Scheduler.h
  src/graph/service/QueryEngine.h
  src/graph/service/QueryInstance.h
  src/graph/service/RequestContext.h
  src/graph/util/test/CMakeLists.txt
  src/graph/util/test/IdGeneratorTest.cpp
  src/kvstore/LogEncoder.h
  src/meta/processors/job/JobManager.h
  src/storage/GraphStorageLocalServer.h
  src/webservice/Router.h
Labels: ready-for-testing

#3868 Forbid grant root user
  src/clients/meta/MetaClient.cpp
  src/clients/meta/MetaClient.h
  src/daemons/SetupBreakpad.cpp
  src/graph/validator/ACLValidator.cpp
  src/graph/validator/test/ACLValidatorTest.cpp
  tests/tck/features/admin/Authentication.feature
Labels: ready-for-testing, ready for review

#3808 Add http port for show
  src/graph/executor/admin/ShowHostsExecutor.cpp
  src/graph/executor/admin/ShowHostsExecutor.h
  src/graph/executor/test/CMakeLists.txt
  src/graph/validator/MatchValidator.cpp
  tests/admin/test_show_hosts.py
  tests/tck/features/admin/Hosts.feature
  tests/tck/features/parser/Example.feature
Labels: ready-for-testing, ready for review

#3887 Fix image sync issue
  .github/workflows/release.yml
Labels: ready-for-testing

#2518 Release the variable used by condition and loop branch.
  src/graph/context/Symbols.h
  src/graph/executor/Executor.cpp
  src/graph/executor/Executor.h
  src/graph/executor/logic/LoopExecutor.cpp
  src/graph/executor/logic/LoopExecutor.h
  src/graph/executor/logic/SelectExecutor.cpp
  src/graph/executor/logic/SelectExecutor.h
  src/graph/planner/plan/PlanNode.h
  src/graph/scheduler/Scheduler.cpp
  src/graph/scheduler/Scheduler.h
Labels: ready-for-testing

#3805 Print fields of plan node when null.
  src/graph/planner/plan/Query.cpp
Labels: ready-for-testing

#3878 comment the graph::session module (Part 1)
  src/graph/service/GraphService.cpp
  src/graph/session/ClientSession.cpp
  src/graph/session/ClientSession.h
  src/graph/session/GraphSessionManager.cpp
  src/graph/session/GraphSessionManager.h
Labels: ready-for-testing, ready for review

#3881 Remove max hop
  src/graph/validator/MatchValidator.cpp
  tests/tck/features/match/ZeroStep.feature
  tests/tck/features/match/ZeroStep2.feature
Labels: ready-for-testing, doc affected, ready for review

#3897 Fix CI feature file format checking failure caused by setuptools upgrading
  tests/Makefile
  tests/requirements.txt
Labels: ready-for-testing, cherry-pick-v3.0

#3894 fix issue 3869
  src/common/stats/StatsManager.cpp
  src/common/stats/StatsManager.h
Labels: ready-for-testing, cherry-pick-v3.0

#3893 fix crash when schema version is greater than 255
  src/clients/meta/MetaClient.cpp
Labels: ready-for-testing, cherry-pick-v2.6, cherry-pick-v3.0

#3898 Cherry pick v3.0.0 0215
  src/clients/meta/MetaClient.cpp
  src/common/stats/StatsManager.cpp
  src/common/stats/StatsManager.h
  tests/Makefile
  tests/requirements.txt
Labels: ready-for-testing

#3899 fix match multiple id error
  src/graph/planner/match/VertexIdSeek.cpp
  src/graph/visitor/VidExtractVisitor.cpp
  tests/tck/features/match/MatchById.feature
Labels: ready-for-testing, type/bug, priority/hi-pri, cherry-pick-v3.0, ready for review

#3900 cherry pick: fix match multiple id error (#3899)
  src/graph/planner/match/VertexIdSeek.cpp
  src/graph/visitor/VidExtractVisitor.cpp
  tests/tck/features/match/MatchById.feature
Labels: ready-for-testing

#3888 fix: replace http::// with http://
  src/storage/http/StorageHttpPropertyHandler.cpp
Labels: ready-for-testing

#3901 add more testcase
  tests/tck/features/match/MatchById.IntVid.feature
  tests/tck/features/match/MatchById.feature
Labels: ready-for-testing, ready for review

#3886 Fix deref null pointer.
  src/graph/planner/plan/Query.cpp
Labels: ready-for-testing, type/bug

#3879 Update config about KV separation threshold
  conf/nebula-storaged.conf.default
  conf/nebula-storaged.conf.production
  src/kvstore/RocksEngineConfig.cpp
Labels: ready-for-testing

#3880 if leader changed during raft::appendLog() RPC, use a different error code
  src/interface/common.thrift
  src/kvstore/raftex/RaftPart.cpp
Labels: ready-for-testing

#3913 set auto_remove_invalid_space default true
  src/kvstore/NebulaStore.cpp
Labels: ready-for-testing

#3915 Fix crash of null path expression.
  src/graph/planner/match/MatchClausePlanner.cpp
  tests/tck/features/bugfix/CrashWhenNullPathExpr.feature
Labels: ready-for-testing, type/bug

#3890 Expose rocksdb feature of disabling OS page cache
  conf/nebula-storaged.conf.production
  src/kvstore/RocksEngineConfig.cpp
Labels: ready-for-testing

#3839 Feature/getprops limit push down
  src/graph/planner/plan/Query.h
  src/storage/exec/GetPropNode.h
  src/storage/query/GetPropProcessor.cpp
  src/storage/query/GetPropProcessor.h
  src/storage/test/GetPropTest.cpp
Labels: ready-for-testing

#3920 fix ingest 0 file error in upgrade tool 3.0
  src/tools/db-upgrade/DbUpgrader.cpp
Labels: ready-for-testing, ready for review

#3921 Remove some useless include instructions
  src/clients/storage/GeneralStorageClient.h
  src/clients/storage/InternalStorageClient.h
  src/clients/storage/StorageClient.h
  src/meta/ActiveHostsMan.h
  src/meta/processors/admin/CreateBackupProcessor.h
  src/meta/processors/admin/CreateSnapshotProcessor.h
  src/meta/processors/admin/DropSnapshotProcessor.h
  src/meta/processors/admin/RestoreProcessor.h
  src/meta/processors/admin/SnapShot.h
  src/storage/query/GetPropProcessor.h
Labels: ready-for-testing

#3917 use rcu in DiskManager
  src/kvstore/DiskManager.cpp
  src/kvstore/DiskManager.h
Labels: ready-for-testing

#3740 Add code comments of validators.
  src/graph/validator/AdminValidator.cpp
  src/graph/validator/AssignmentValidator.cpp
  src/graph/validator/DownloadValidator.cpp
  src/graph/validator/ExplainValidator.cpp
  src/graph/validator/FetchEdgesValidator.cpp
  src/graph/validator/FetchVerticesValidator.cpp
  src/graph/validator/FindPathValidator.cpp
  src/graph/validator/GetSubgraphValidator.cpp
  src/graph/validator/GoValidator.cpp
  src/graph/validator/GroupByValidator.cpp
  src/graph/validator/IngestValidator.cpp
  src/graph/validator/LimitValidator.cpp
  src/graph/validator/LookupValidator.cpp
  src/graph/validator/MaintainValidator.cpp
  src/graph/validator/MatchValidator.cpp
  src/graph/validator/MutateValidator.cpp
  src/graph/validator/OrderByValidator.cpp
  src/graph/validator/PipeValidator.cpp
  src/graph/validator/ReportError.h
  src/graph/validator/SequentialValidator.cpp
  src/graph/validator/SetValidator.cpp
  src/graph/validator/UseValidator.cpp
  src/graph/validator/Validator.cpp
  src/graph/validator/YieldValidator.cpp
Labels: ready-for-testing

#3931 [Optimizer] enhance ColumnPruning
  src/graph/optimizer/rule/CollapseProjectRule.cpp
  tests/tck/features/match/With.feature
  tests/tck/features/optimizer/CollapseProjectRule.feature
Labels: ready-for-testing, ready for review

#3933 [SIMPLE]Fix prune properties
  src/graph/planner/plan/PlanNodeVisitor.h
  src/graph/planner/plan/Query.cpp
  src/graph/planner/plan/Query.h
  src/graph/visitor/PropertyTrackerVisitor.cpp
  src/graph/visitor/PrunePropertiesVisitor.cpp
  src/graph/visitor/PrunePropertiesVisitor.h
Labels: ready-for-testing

#3939 Support the ARM platform of docker image
  .github/workflows/nightly.yml
  .github/workflows/rc.yml
Labels: ready-for-testing

#3932 Modify ldbc cases.
  tests/tck/ldbc/business_intelligence_workload/Read.feature
  tests/tck/ldbc/interactive_workload/ComplexReads.feature
Labels: ready-for-testing

#3918 Meta index/parts/schema log and comments
  src/meta/processors/index/CreateEdgeIndexProcessor.cpp
  src/meta/processors/index/CreateEdgeIndexProcessor.h
  src/meta/processors/index/CreateTagIndexProcessor.cpp
  src/meta/processors/index/CreateTagIndexProcessor.h
  src/meta/processors/index/DropEdgeIndexProcessor.cpp
  src/meta/processors/index/DropEdgeIndexProcessor.h
  src/meta/processors/index/DropTagIndexProcessor.cpp
  src/meta/processors/index/DropTagIndexProcessor.h
  src/meta/processors/index/FTIndexProcessor.cpp
  src/meta/processors/index/FTIndexProcessor.h
  src/meta/processors/index/GetEdgeIndexProcessor.cpp
  src/meta/processors/index/GetEdgeIndexProcessor.h
  src/meta/processors/index/GetTagIndexProcessor.cpp
  src/meta/processors/index/GetTagIndexProcessor.h
  src/meta/processors/index/ListEdgeIndexesProcessor.cpp
  src/meta/processors/index/ListEdgeIndexesProcessor.h
  src/meta/processors/index/ListTagIndexesProcessor.cpp
  src/meta/processors/index/ListTagIndexesProcessor.h
  src/meta/processors/parts/AlterSpaceProcessor.h
  src/meta/processors/parts/CreateSpaceAsProcessor.cpp
  src/meta/processors/parts/CreateSpaceAsProcessor.h
  src/meta/processors/parts/CreateSpaceProcessor.cpp
  src/meta/processors/parts/CreateSpaceProcessor.h
  src/meta/processors/parts/DropSpaceProcessor.cpp
  src/meta/processors/parts/DropSpaceProcessor.h
  src/meta/processors/parts/GetPartsAllocProcessor.cpp
  src/meta/processors/parts/GetPartsAllocProcessor.h
  src/meta/processors/parts/GetSpaceProcessor.cpp
  src/meta/processors/parts/GetSpaceProcessor.h
  src/meta/processors/parts/ListHostsProcessor.cpp
  src/meta/processors/parts/ListHostsProcessor.h
  src/meta/processors/parts/ListPartsProcessor.cpp
  src/meta/processors/parts/ListPartsProcessor.h
  src/meta/processors/parts/ListSpacesProcessor.cpp
  src/meta/processors/parts/ListSpacesProcessor.h
  src/meta/processors/schema/AlterEdgeProcessor.cpp
  src/meta/processors/schema/AlterEdgeProcessor.h
  src/meta/processors/schema/AlterTagProcessor.cpp
  src/meta/processors/schema/AlterTagProcessor.h
  src/meta/processors/schema/CreateEdgeProcessor.cpp
  src/meta/processors/schema/CreateEdgeProcessor.h
  src/meta/processors/schema/CreateTagProcessor.cpp
  src/meta/processors/schema/CreateTagProcessor.h
  src/meta/processors/schema/DropEdgeProcessor.cpp
  src/meta/processors/schema/DropEdgeProcessor.h
  src/meta/processors/schema/DropTagProcessor.cpp
  src/meta/processors/schema/DropTagProcessor.h
  src/meta/processors/schema/GetEdgeProcessor.cpp
  src/meta/processors/schema/GetEdgeProcessor.h
  src/meta/processors/schema/GetTagProcessor.cpp
  src/meta/processors/schema/GetTagProcessor.h
  src/meta/processors/schema/ListEdgesProcessor.cpp
  src/meta/processors/schema/ListEdgesProcessor.h
  src/meta/processors/schema/ListTagsProcessor.cpp
  src/meta/processors/schema/ListTagsProcessor.h
  src/meta/processors/schema/SchemaUtil.cpp
  src/meta/processors/schema/SchemaUtil.h
Labels: ready-for-testing, ready for review

#3700 add comments and change some log level for storage root / http / kv ..
  src/storage/StorageServer.h
  src/storage/http/StorageHttpDownloadHandler.h
  src/storage/http/StorageHttpIngestHandler.h
  src/storage/http/StorageHttpStatsHandler.h
  src/storage/index/LookupProcessor.h
Labels: ready-for-testing, ready for review

#3896 Add permission checking for kill queries.
  src/graph/executor/admin/KillQueryExecutor.cpp
  src/graph/service/PermissionCheck.cpp
  tests/Makefile
  tests/tck/slowquery/permissionViaDifferentService.feature
  tests/tck/slowquery/permissionViaSameService.feature
  tests/tck/steps/test_kill_permission_via_different_service.py
  tests/tck/steps/test_kill_permission_via_same_service.py
Labels: ready-for-testing, ready for review

#3698 Add comments and change log level for storage: admin/content/query/stat directories
  src/storage/admin/AdminProcessor.h
  src/storage/admin/AdminTask.h
  src/storage/admin/AdminTaskManager.cpp
  src/storage/admin/AdminTaskManager.h
  src/storage/admin/AdminTaskProcessor.h
  src/storage/admin/CompactTask.h
  src/storage/admin/CreateCheckpointProcessor.cpp
  src/storage/admin/CreateCheckpointProcessor.h
  src/storage/admin/DropCheckpointProcessor.h
  src/storage/admin/FlushTask.h
  src/storage/admin/RebuildEdgeIndexTask.cpp
  src/storage/admin/RebuildEdgeIndexTask.h
  src/storage/admin/RebuildFTIndexTask.cpp
  src/storage/admin/RebuildFTIndexTask.h
  src/storage/admin/RebuildIndexTask.cpp
  src/storage/admin/RebuildIndexTask.h
  src/storage/admin/RebuildTagIndexTask.cpp
  src/storage/admin/RebuildTagIndexTask.h
  src/storage/admin/SendBlockSignProcessor.h
  src/storage/admin/StatsTask.cpp
  src/storage/admin/StatsTask.h
  src/storage/admin/StopAdminTaskProcessor.h
  src/storage/context/StorageExpressionContext.h
  src/storage/query/GetNeighborsProcessor.cpp
  src/storage/query/GetNeighborsProcessor.h
  src/storage/query/GetPropProcessor.cpp
  src/storage/query/GetPropProcessor.h
  src/storage/query/QueryBaseProcessor-inl.h
  src/storage/query/QueryBaseProcessor.h
  src/storage/query/ScanEdgeProcessor.h
  src/storage/query/ScanVertexProcessor.h
  src/storage/stats/StorageStats.h
Labels: ready-for-testing, ready for review
