Repository vesoft-inc/nebula, pull requests merged in 2023-04, with the labels that each got.

#5464 refactor traverse output
  src/common/function/FunctionManager.cpp
  src/graph/context/ast/CypherAstContext.h
  src/graph/executor/query/TraverseExecutor.cpp
  src/graph/executor/query/TraverseExecutor.h
  src/graph/optimizer/rule/RemoveAppendVerticesBelowJoinRule.cpp
  src/graph/planner/match/MatchPathPlanner.cpp
  src/graph/planner/match/MatchSolver.cpp
  src/graph/planner/plan/Query.cpp
  src/graph/planner/plan/Query.h
  src/graph/validator/MatchValidator.cpp
  src/graph/visitor/PrunePropertiesVisitor.cpp
  tests/tck/features/optimizer/PrunePropertiesRule.feature
  tests/tck/features/optimizer/RemoveAppendVerticesBelowJoinRule.feature
Labels: ready-for-testing, ready for review

#5447 Change the compaction filter logic to let periodic compaction go through custom compaction filter, to gc expired data
  resources/gflags.json
  src/common/meta/GflagsManager.cpp
  src/kvstore/Common.h
  src/kvstore/CompactionFilter.h
  src/kvstore/NebulaStore.cpp
  src/storage/CompactionFilter.h
  src/storage/test/CompactionTest.cpp
  src/storage/test/IndexWithTTLTest.cpp
  tests/admin/test_configs.py
Labels: ready-for-testing

#5473 Push filter down cross join
  src/graph/executor/algo/CartesianProductExecutor.cpp
  src/graph/optimizer/CMakeLists.txt
  src/graph/optimizer/rule/PushFilterDownCrossJoinRule.cpp
  src/graph/optimizer/rule/PushFilterDownCrossJoinRule.h
  src/graph/planner/match/MatchSolver.cpp
  src/graph/planner/match/StartVidFinder.h
  src/graph/planner/plan/Algo.cpp
  src/graph/planner/plan/Algo.h
  src/graph/planner/plan/Query.cpp
  src/graph/planner/plan/Query.h
  tests/tck/features/optimizer/PushFilterDownCrossJoinRule.feature
Labels: ready-for-testing

#5472 Fix shortest path crash
  src/graph/executor/algo/BatchShortestPath.cpp
  src/graph/executor/algo/SingleShortestPath.cpp
  src/graph/validator/MatchValidator.cpp
  tests/tck/features/match/AllShortestPaths.feature
  tests/tck/features/match/SingleShorestPath.feature
Labels: ready-for-testing, ready for review, cherry-pick-v3.5

#5475 fix crash of geo
  src/graph/optimizer/rule/GeoPredicateIndexScanBaseRule.cpp
  src/graph/optimizer/rule/PushEFilterDownRule.cpp
  src/graph/optimizer/rule/PushFilterDownNodeRule.cpp
  src/graph/optimizer/rule/UnionAllIndexScanBaseRule.cpp
  tests/tck/features/geo/GeoBase.feature
Labels: ready-for-testing

#5470 Split optimizer rules
  src/common/expression/Expression.h
  src/common/expression/PropertyExpression.h
  src/graph/optimizer/CMakeLists.txt
  src/graph/optimizer/rule/PushFilterDownTraverseRule.cpp
  src/graph/optimizer/rule/PushFilterThroughAppendVerticesRule.cpp
  src/graph/optimizer/rule/PushFilterThroughAppendVerticesRule.h
  tests/tck/features/bugfix/LackFilterGetEdges.feature
  tests/tck/features/match/SeekById.feature
  tests/tck/features/optimizer/CollapseProjectRule.feature
  tests/tck/features/optimizer/PrunePropertiesRule.feature
  tests/tck/features/optimizer/PushFilterDownBugFixes.feature
  tests/tck/features/optimizer/PushFilterDownCrossJoinRule.feature
  tests/tck/features/optimizer/PushFilterDownTraverseRule.feature
  tests/tck/features/optimizer/PushLimitDownProjectRule.feature
  tests/tck/features/optimizer/RemoveAppendVerticesBelowJoinRule.feature
Labels: ready-for-testing, ready for review

#5481 Enhancement/optimize edge all predicate
  src/common/meta/SchemaManager.h
  src/graph/executor/query/TraverseExecutor.cpp
  src/graph/optimizer/CMakeLists.txt
  src/graph/optimizer/rule/EmbedEdgeAllPredIntoTraverseRule.cpp
  src/graph/optimizer/rule/EmbedEdgeAllPredIntoTraverseRule.h
  src/graph/optimizer/rule/GeoPredicateIndexScanBaseRule.cpp
  src/graph/util/ExpressionUtils.cpp
  src/graph/util/ExpressionUtils.h
  src/graph/visitor/ExtractFilterExprVisitor.cpp
  src/graph/visitor/ExtractFilterExprVisitor.h
  tests/tck/features/optimizer/CollapseProjectRule.feature
  tests/tck/features/optimizer/EmbedEdgeAllPredIntoTraverseRule.feature
Labels: ready-for-testing

#5487 Fix expression util function
  src/graph/util/ExpressionUtils.cpp
  tests/tck/features/optimizer/EmbedEdgeAllPredIntoTraverseRule.feature
Labels: ready-for-testing, ready for review

#5477 add standalone build&tck to nightly
  .github/workflows/nightly.yml
Labels: ready-for-testing

#5489 fix ContainsFilter random fail
  tests/tck/features/bugfix/ContainsFilter.feature
Labels: ready-for-testing, ready for review

#5494 fix pruneproperties
  src/graph/visitor/PropertyTrackerVisitor.cpp
  src/graph/visitor/PrunePropertiesVisitor.cpp
  tests/tck/features/match/MatchGroupBy.feature
Labels: ready-for-testing, type/bug, ready for review

#5502 Stop the pushing down of not expressions that are not rewritten to pr…
  src/graph/visitor/ExtractFilterExprVisitor.cpp
  src/graph/visitor/ExtractFilterExprVisitor.h
Labels: ready-for-testing, ready for review

#5503 Fix edge all predicate with function predicate
  src/graph/optimizer/rule/EmbedEdgeAllPredIntoTraverseRule.cpp
  tests/tck/features/match/MultiLineMultiQueryParts.feature
Labels: ready-for-testing, ready for review

#5500 rewrite param in subgraph & path
  src/graph/validator/FindPathValidator.cpp
  src/graph/validator/GetSubgraphValidator.cpp
  tests/tck/features/yield/parameter.feature
Labels: ready-for-testing, type/bug

#5507 Fix regex expression
  src/common/expression/RelationalExpression.cpp
  tests/tck/features/expression/RelationalExpr.feature
Labels: ready-for-testing, ready for review

#5512 Update requirements.txt
  tests/requirements.txt
Labels: ready-for-testing

#5513 fixed yapf version
  tests/requirements.txt
Labels: ready-for-testing

#5514 Add salt when generating cluster id to reduce duplication
  src/meta/KVBasedClusterIdMan.h
Labels: ready-for-testing, ready for review

#5486 Support variable when seeking by id in match clause
  src/graph/context/ast/CypherAstContext.h
  src/graph/executor/logic/ArgumentExecutor.cpp
  src/graph/optimizer/Optimizer.cpp
  src/graph/planner/CMakeLists.txt
  src/graph/planner/PlannersRegister.cpp
  src/graph/planner/match/StartVidFinder.h
  src/graph/planner/match/VariableVertexIdSeek.cpp
  src/graph/planner/match/VariableVertexIdSeek.h
  src/graph/planner/ngql/GoPlanner.cpp
  src/graph/planner/plan/Logic.cpp
  src/graph/planner/plan/Logic.h
  src/graph/validator/MatchValidator.cpp
  tests/tck/features/match/MatchByVariable.feature
  tests/tck/features/match/PathExpr.feature
  tests/tck/features/match/PathExprRefLocalVariable.feature
  tests/tck/features/match/With.feature
Labels: ready-for-testing

#5517 Fix meta's cleanup
  src/kvstore/Part.cpp
Labels: ready-for-testing

#5522 Revert "Change the compaction filter logic to let periodic compaction…
  resources/gflags.json
  src/common/meta/GflagsManager.cpp
  src/kvstore/Common.h
  src/kvstore/CompactionFilter.h
  src/kvstore/NebulaStore.cpp
  src/storage/CompactionFilter.h
  src/storage/test/CompactionTest.cpp
  src/storage/test/IndexWithTTLTest.cpp
  tests/admin/test_configs.py
Labels: ready-for-testing

#5527 update unsupported action syntax
  .github/actions/tagname-action/action.yml
Labels: cherry-pick-v3.5

#5530 Cherry pick 3.5 (0420-0427)
  .github/actions/tagname-action/action.yml
  src/graph/context/ast/QueryAstContext.h
  src/graph/executor/algo/AllPathsExecutor.cpp
  src/graph/executor/algo/AllPathsExecutor.h
  src/graph/executor/query/ExpandExecutor.cpp
  src/graph/planner/ngql/GoPlanner.cpp
  src/graph/planner/ngql/GoPlanner.h
  src/graph/validator/GoValidator.cpp
  src/graph/validator/GoValidator.h
  tests/requirements.txt
  tests/tck/features/go/SimpleCase.feature
  tests/tck/features/optimizer/PushFilterDownHashLeftJoinRule.feature
Labels: ready-for-testing

#5531 fix allpath limit
  src/graph/executor/algo/AllPathsExecutor.cpp
  tests/tck/features/path/AllPath.feature
Labels: ready-for-testing, ready for review

#5532 Cherry pick 3.5.0 (0428)
  src/graph/executor/algo/AllPathsExecutor.cpp
  tests/tck/features/path/AllPath.feature
Labels: ready-for-testing
