Repository vesoft-inc/nebula, pull requests merged in 2023-01, with the labels that each got.

#5176 optimize match node label
  src/graph/executor/query/TraverseExecutor.cpp
  src/graph/executor/query/TraverseExecutor.h
Labels: ready-for-testing, ready for review, cherry-pick-v3.4

#5183 revert strange return
  src/parser/parser.yy
  tests/tck/features/set/Set.feature
  tests/tck/features/yield/return.feature
Labels: ready-for-testing, cherry-pick-v3.4

#5180 fix processor_test timeout
  src/meta/MetaServiceUtils.cpp
  src/meta/processors/schema/AlterEdgeProcessor.cpp
  src/meta/processors/schema/AlterTagProcessor.cpp
  src/meta/test/ProcessorTest.cpp
Labels: ready-for-testing, ready for review, cherry-pick-v3.4

#5186 fix error code
  src/interface/common.thrift
Labels: ready-for-testing, ready for review, cherry-pick-v3.4

#5197 rename the "test" space to "ngdata".
  tests/conftest.py
  tests/data/ngdata/Edge_label_limits.csv
  tests/data/ngdata/Edge_ttl_0.csv
  tests/data/ngdata/Label_0.csv
  tests/data/ngdata/Label_1.csv
  tests/data/ngdata/Label_10.csv
  tests/data/ngdata/Label_11.csv
  tests/data/ngdata/Label_2.csv
  tests/data/ngdata/Label_3.csv
  tests/data/ngdata/Label_4.csv
  tests/data/ngdata/Label_5.csv
  tests/data/ngdata/Label_6.csv
  tests/data/ngdata/Label_7.csv
  tests/data/ngdata/Label_8.csv
  tests/data/ngdata/Label_9.csv
  tests/data/ngdata/Label_same_prop_0.csv
  tests/data/ngdata/Label_same_prop_1.csv
  tests/data/ngdata/Label_ttl_0.csv
  tests/data/ngdata/README.md
  tests/data/ngdata/Rel_0.csv
  tests/data/ngdata/Rel_1.csv
  tests/data/ngdata/Rel_2.csv
  tests/data/ngdata/Rel_3.csv
  tests/data/ngdata/Rel_4.csv
  tests/data/ngdata/Rel_5.csv
  tests/data/ngdata/config.yaml
  tests/data/ngdata/gen_graph.sh
  tests/tck/conftest.py
  tests/tck/features/expression/Attribute1.feature
  tests/tck/features/match/Path.feature
  tests/tck/features/optimizer/CasesUsingTestSpace.feature
Labels: ready-for-testing, ready for review

#5174 Meta upgrade
  src/clients/meta/MetaClient.h
  src/daemons/MetaDaemonInit.cpp
  src/meta/MetaVersionMan.cpp
  src/meta/MetaVersionMan.h
  src/tools/meta-dump/MetaDumpTool.cpp
Labels: ready-for-testing, cherry-pick-v3.4

#5192 Fix pattern expression with same edge variable
  src/common/function/FunctionManager.cpp
  src/graph/planner/match/SegmentsConnector.cpp
  src/graph/validator/MatchValidator.cpp
  tests/tck/features/bugfix/AliasTypeDeduce.feature
  tests/tck/features/match/PathExpr.feature
  tests/tck/features/match/PathExprRefLocalVariable.feature
Labels: ready-for-testing, ready for review

#5204 Fix memory leak, remove toss gflag
  src/graph/executor/mutate/DeleteExecutor.cpp
  src/graph/executor/mutate/InsertExecutor.cpp
  src/graph/executor/mutate/UpdateExecutor.cpp
  src/graph/service/GraphFlags.cpp
  src/graph/service/GraphFlags.h
  src/graph/validator/MutateValidator.cpp
  src/meta/processors/index/FTIndexProcessor.cpp
  tests/tck/conftest.py
Labels: ready-for-testing, cherry-pick-v3.4

#5207 [Simple] Add `max_sessions_per_ip_per_user` to default config file
  conf/nebula-graphd.conf.default
Labels: ready-for-testing, ready for review, cherry-pick-v3.4

#5175 modify jobmanager ut
  src/meta/processors/job/JobDescription.cpp
  src/meta/processors/job/JobExecutor.h
  src/meta/processors/job/JobManager.cpp
  src/meta/processors/job/JobManager.h
  src/meta/processors/job/JobStatus.cpp
  src/meta/processors/job/JobStatus.h
  src/meta/test/JobManagerTest.cpp
Labels: ready-for-testing, cherry-pick-v3.4

#5189 Add more match test cases on paths.
  tests/tck/features/match/Path.feature
Labels: ready-for-testing, ready for review

#5214 fix bug
  src/kvstore/listener/elasticsearch/ESListener.cpp
  tests/Makefile
Labels: ready-for-testing, cherry-pick-v3.4

#5212 handle rpc error task status
  src/meta/processors/job/StorageJobExecutor.cpp
Labels: ready-for-testing, ready for review, cherry-pick-v3.4

#5202 chore: community badges refined
  README-CN.md
  README.md
Labels: ready-for-testing

#5213 Fix extend whtie space char.
  src/parser/scanner.lex
  src/parser/test/ParserTest.cpp
  src/parser/test/ScannerTest.cpp
  tests/tck/features/basic/Parser.feature
Labels: ready-for-testing

#5196 Add lack tests of no role user.
  tests/admin/test_permission.py
  tests/common/utils.py
Labels: ready-for-testing

#5224 remove memtracker DLOG
  src/common/memory/MemoryTracker.cpp
Labels: ready-for-testing, ready for review

#5220 Add tck cases for DDL
  tests/tck/features/ddl/Ddl.feature
  tests/tck/utils/table.py
Labels: ready-for-testing, ready for review

#5215 more TCK tests for variable pattern match clause
  tests/Makefile
  tests/tck/features/match/Base.feature
  tests/tck/features/match/VariableLengthPattern.feature
Labels: ready-for-testing

#5229 Resumed the evaluation fo vertices in AttributeExpression (UTs included)
  src/common/expression/AttributeExpression.cpp
  src/common/expression/test/AttributeExpressionTest.cpp
  src/common/expression/test/ExpressionContextMock.h
  src/common/expression/test/ListComprehensionExpressionTest.cpp
  src/common/expression/test/PredicateExpressionTest.cpp
  tests/tck/features/expression/Attribute1.feature
  tests/tck/features/expression/ListComprehension.feature
  tests/tck/features/expression/Predicate.feature
  tests/tck/features/expression/Reduce.feature
Labels: ready-for-testing

#5231 add memtracker flags to conf
  conf/nebula-graphd.conf.default
  conf/nebula-graphd.conf.production
  conf/nebula-storaged.conf.default
  conf/nebula-storaged.conf.production
Labels: ready-for-testing, ready for review, cherry-pick-v3.4

#5228 add balance job type to filter when create backup
  src/meta/processors/admin/CreateBackupProcessor.cpp
  src/meta/processors/job/JobManager.cpp
  src/meta/test/CreateBackupProcessorTest.cpp
Labels: ready-for-testing

#5225 Fix update sessions when leader change happens
  src/graph/session/GraphSessionManager.cpp
  src/meta/processors/session/SessionManagerProcessor.cpp
Labels: ready-for-testing, ready for review, cherry-pick-v3.4

#5216 fix match step range
  src/common/expression/MatchPathPatternExpression.h
  src/graph/context/ast/CypherAstContext.h
  src/graph/executor/algo/ShortestPathBase.h
  src/graph/executor/query/TraverseExecutor.cpp
  src/graph/executor/query/TraverseExecutor.h
  src/graph/optimizer/rule/GetEdgesTransformAppendVerticesLimitRule.cpp
  src/graph/optimizer/rule/GetEdgesTransformRule.cpp
  src/graph/planner/match/MatchPathPlanner.cpp
  src/graph/planner/match/ShortestPathPlanner.cpp
  src/graph/planner/plan/Algo.cpp
  src/graph/planner/plan/Algo.h
  src/graph/planner/plan/Query.cpp
  src/graph/planner/plan/Query.h
  src/graph/validator/MatchValidator.cpp
  src/graph/validator/MatchValidator.h
  src/parser/MatchPath.h
  tests/tck/features/match/PathExpr.feature
  tests/tck/features/match/PathExprRefLocalVariable.feature
  tests/tck/features/match/VariableLengthPattern.feature
Labels: ready-for-testing, ready for review, cherry-pick-v3.4

#5227 Update response message when adding schema historically existed
  src/clients/meta/MetaClient.cpp
  src/common/graph/Response.h
  src/interface/common.thrift
  src/meta/MetaServiceUtils.cpp
  tests/tck/features/ddl/Ddl.feature
  tests/tck/features/schema/Schema.feature
Labels: ready-for-testing, ready for review, cherry-pick-v3.4

#5233 fix stop job error code
  src/meta/processors/job/RebuildJobExecutor.cpp
  src/meta/processors/job/StatsJobExecutor.cpp
Labels: ready-for-testing

#5234 print memory stats default to false
  conf/nebula-graphd.conf.default
  conf/nebula-graphd.conf.production
  conf/nebula-storaged.conf.default
  conf/nebula-storaged.conf.production
  src/common/memory/MemoryUtils.cpp
Labels: ready-for-testing, ready for review

#5238 fix extract props visitor
  src/graph/validator/GoValidator.cpp
  src/graph/validator/GoValidator.h
  src/graph/visitor/ExtractPropExprVisitor.cpp
  src/graph/visitor/ExtractPropExprVisitor.h
  tests/tck/features/go/GO.feature
Labels: ready-for-testing

#5242 forbid invalid prop expr used in cypher
  src/graph/executor/algo/BFSShortestPathExecutor.cpp
  src/graph/executor/algo/ProduceAllPathsExecutor.cpp
  src/graph/executor/maintain/EdgeExecutor.cpp
  src/graph/executor/maintain/EdgeIndexExecutor.cpp
  src/graph/validator/MatchValidator.cpp
  tests/tck/features/match/Base.feature
Labels: ready-for-testing

#5241 Fix mistake push down limit with skip.
  src/graph/optimizer/rule/GetEdgesTransformAppendVerticesLimitRule.cpp
  src/graph/optimizer/rule/GetEdgesTransformRule.cpp
  tests/tck/features/match/Scan.feature
Labels: ready-for-testing

#5239 fix delete fulltext index
  src/kvstore/listener/elasticsearch/ESListener.cpp
Labels: ready-for-testing

#5230 Enhance attribute-accessing expression to ensure self-consistency
  src/common/datatypes/Value.cpp
  src/common/datatypes/Value.h
  src/common/expression/AttributeExpression.cpp
  src/common/expression/test/AttributeExpressionTest.cpp
  src/common/expression/test/ListComprehensionExpressionTest.cpp
  src/common/expression/test/PredicateExpressionTest.cpp
  src/graph/validator/MatchValidator.cpp
  tests/tck/features/expression/Attribute.feature
  tests/tck/features/expression/Attribute1.feature
  tests/tck/features/expression/ListComprehension.feature
  tests/tck/features/expression/Predicate.feature
  tests/tck/features/expression/Reduce.feature
  tests/tck/features/match/Base.IntVid.feature
  tests/tck/features/match/Base.feature
  tests/tck/features/match/Path.feature
  tests/tck/features/match/With.feature
  tests/tck/features/optimizer/PrunePropertiesRule.feature
Labels: ready-for-testing, doc affected, ready for review

#5251 fix ft index of fixed string
  src/meta/processors/index/FTIndexProcessor.cpp
Labels: ready-for-testing

#5253 Add tck test
  tests/tck/features/go/GO.feature
  tests/tck/features/path/AllPath.feature
  tests/tck/features/path/ShortestPath.feature
  tests/tck/features/subgraph/subgraph.feature
Labels: ready-for-testing, ready for review

#5256 Add more session tests
  tests/job/test_session.py
Labels: ready-for-testing, ready for review, cherry-pick-v3.4

#5266 Revert "do not check term for leader info by default para"
  src/meta/ActiveHostsMan.cpp
Labels: ready-for-testing

#5260 modify ft index default limit size
  src/common/expression/TextSearchExpression.h
  src/graph/util/test/FTindexUtilsTest.cpp
Labels: ready-for-testing, cherry-pick-v3.4

#5267 Test/yield
  tests/tck/features/yield/yield.IntVid.feature
  tests/tck/features/yield/yield.feature
Labels: ready-for-testing, cherry-pick-v3.4

#5247 Add another cert to test CA don't match.
  tests/cert/test.2.crt
  tests/cert/test.2.csr
  tests/cert/test.2.key
  tests/cert/test.2.password
Labels: ready-for-testing, cherry-pick-v3.4

#5269 fix baton miss reset in StorageJobExecutor
  src/meta/processors/job/StorageJobExecutor.cpp
Labels: ready-for-testing

#5273 report errors on where clauses in optional match queries.
  src/parser/parser.yy
  tests/tck/features/match/MatchById.feature
  tests/tck/features/match/MultiLineMultiQueryParts.feature
  tests/tck/features/match/MultiQueryParts.feature
  tests/tck/features/optimizer/PrunePropertiesRule.feature
  tests/tck/ldbc/business_intelligence_workload/Read.feature
  tests/tck/ldbc/interactive_workload/ComplexReads.feature
Labels: ready-for-testing, incompatible, doc affected, ready for review, cherry-pick-v3.4

#5264 [test case] Check DML cases
  tests/tck/features/delete/DeleteEdge.IntVid.feature
  tests/tck/features/delete/DeleteEdge.feature
  tests/tck/features/delete/DeleteTag.IntVid.feature
  tests/tck/features/delete/DeleteTag.feature
  tests/tck/features/delete/DeleteVertex.feature
  tests/tck/features/insert/Insert.IntVid.feature
  tests/tck/features/insert/Insert.feature
  tests/tck/features/insert/InsertEdgeOnDiffParts.feature
Labels: ready-for-testing, ready for review, cherry-pick-v3.4

#5281 fix third party version in package.sh
  package/package.sh
Labels: ready-for-testing, cherry-pick-v3.3, cherry-pick-v3.4

#5139 Test/user
  tests/tck/conftest.py
  tests/tck/features/user/User.feature
Labels: ready-for-testing, cherry-pick-v3.4

#5283 fix https
  src/common/http/HttpClient.cpp
  src/common/http/HttpClient.h
Labels: ready-for-testing

#5287 rewrite none_direct_dst(e) to e._dst
  src/common/function/FunctionManager.cpp
  src/graph/util/ExpressionUtils.cpp
  src/graph/util/ExpressionUtils.h
  src/graph/validator/MatchValidator.cpp
  src/graph/visitor/DeduceTypeVisitor.cpp
  tests/tck/features/optimizer/PushFilterDownTraverseRule.feature
Labels: ready-for-testing

#5284 remove unnecessary check when print error log
  src/common/memory/MemoryUtils.cpp
Labels: ready-for-testing, ready for review

#5218 More lookup TCK tests
  tests/tck/conftest.py
  tests/tck/features/geo/GeoBase.feature
  tests/tck/features/lookup/ByIndex.feature
  tests/tck/features/lookup/ByIndex.intVid.feature
  tests/tck/features/lookup/EdgeIndexFullScan.feature
  tests/tck/features/lookup/LookUp.feature
  tests/tck/features/lookup/LookUpLimit.feature
  tests/tck/features/lookup/LookupEdge.feature
  tests/tck/features/lookup/LookupEdge2.feature
  tests/tck/features/lookup/LookupTag.feature
  tests/tck/features/lookup/LookupTag2.feature
  tests/tck/features/lookup/Output.feature
  tests/tck/features/lookup/TagIndexFullScan.feature
  tests/tck/features/lookup/WithYield.feature
  tests/tck/features/lookup/WithYield.intVid.feature
  tests/tck/features/user/User.feature
  tests/tck/slowquery/PermissionViaDifferentService.feature
  tests/tck/slowquery/PermissionViaSameService.feature
Labels: ready-for-testing, cherry-pick-v3.4

#5261 log enhance
  src/meta/processors/job/JobManager.cpp
  src/storage/admin/AdminTaskManager.cpp
  src/storage/admin/RebuildIndexTask.cpp
Labels: ready-for-testing

#5294 Don't rewrite vid in list expr to or expr
  src/graph/planner/match/LabelIndexSeek.cpp
  src/graph/planner/match/MatchClausePlanner.cpp
  src/graph/planner/match/PropIndexSeek.cpp
  src/graph/planner/match/VertexIdSeek.cpp
  src/graph/util/ExpressionUtils.cpp
  src/graph/util/ExpressionUtils.h
  src/graph/validator/MatchValidator.cpp
  src/graph/visitor/VidExtractVisitor.cpp
  tests/tck/features/basic/data.feature
  tests/tck/features/match/SeekById.feature
  tests/tck/features/optimizer/CasesUsingTestSpace.feature
  tests/tck/features/optimizer/PushFilterDownTraverseRule.feature
  tests/tck/features/yield/parameter.feature
Labels: ready-for-testing
