Repository vesoft-inc/nebula, pull requests merged in 2023-03, with the labels that each got.

#5383 Fix crash of list related functions
  src/common/function/FunctionManager.cpp
  tests/tck/features/yield/return.feature
Labels: ready-for-testing, ready for review, cherry-pick-v3.4, affects/v3.4

#5387 Cherry pick v3.4.1 （from release 3.4.0 to 03.05)
  src/common/function/FunctionManager.cpp
  src/graph/validator/LookupValidator.cpp
  src/storage/ExprVisitorBase.cpp
  tests/tck/features/yield/parameter.feature
  tests/tck/features/yield/return.feature
Labels: ready-for-testing

#5388 Fix client ip format in show sessions command
  src/graph/service/GraphService.cpp
  tests/tck/features/admin/Sessions.feature
Labels: ready-for-testing, ready for review

#5386 fix getneighbors edge direction showed in plan
  src/graph/executor/test/JoinTest.cpp
  src/graph/planner/ngql/GoPlanner.cpp
  src/graph/planner/ngql/PathPlanner.cpp
  tests/tck/features/go/GO.feature
Labels: ready-for-testing

#5391 feat: optimized udf build
  udf/.gitignore
  udf/Makefile
Labels: ready-for-testing, doc affected, ready for review

#5390 Fix use switch space combine with match
  src/graph/visitor/PropertyTrackerVisitor.cpp
  tests/tck/features/bugfix/UseSpaceAndMatch.feature
Labels: ready-for-testing, type/bug, ready for review

#5395 remove EliminateAppendVerticesRule
  src/graph/optimizer/CMakeLists.txt
  tests/tck/features/optimizer/EliminateAppendVerticesRule.feature
  tests/tck/features/optimizer/PrunePropertiesRule.feature
  tests/tck/features/optimizer/PushEFilterDownRule.feature
  tests/tck/features/optimizer/PushFilterDownNodeRule.feature
Labels: ready-for-testing

#5393 Fix `addSessionCount()` in multu-thread case
  src/graph/session/GraphSessionManager.cpp
  src/graph/session/GraphSessionManager.h
Labels: ready-for-testing, type/bug, ready for review

#5381 Remove virtual function in RowReader
  src/codec/CMakeLists.txt
  src/codec/NebulaCodecImpl.cpp
  src/codec/NebulaCodecImpl.h
  src/codec/RowReader.cpp
  src/codec/RowReader.h
  src/codec/RowReaderV1.cpp
  src/codec/RowReaderV1.h
  src/codec/RowReaderV2.cpp
  src/codec/RowReaderV2.h
  src/codec/RowReaderWrapper.cpp
  src/codec/RowReaderWrapper.h
  src/codec/RowWriterV2.cpp
  src/codec/RowWriterV2.h
  src/codec/test/CMakeLists.txt
  src/codec/test/RowReaderBenchmark.cpp
  src/codec/test/RowReaderV1Test.cpp
  src/codec/test/RowReaderV2Test.cpp
  src/common/utils/IndexKeyUtils.cpp
  src/common/utils/IndexKeyUtils.h
  src/common/utils/test/CMakeLists.txt
  src/storage/CommonUtils.cpp
  src/storage/CommonUtils.h
  src/storage/CompactionFilter.h
  src/storage/context/StorageExpressionContext.h
  src/storage/exec/AggregateNode.h
  src/storage/exec/EdgeNode.h
  src/storage/exec/GetPropNode.h
  src/storage/exec/HashJoinNode.h
  src/storage/exec/MultiTagNode.h
  src/storage/exec/QueryUtils.h
  src/storage/exec/RelNode.h
  src/storage/exec/ScanNode.h
  src/storage/exec/StorageIterator.h
  src/storage/exec/TagNode.h
  src/storage/exec/UpdateNode.h
  src/storage/mutate/AddEdgesProcessor.cpp
  src/storage/mutate/AddEdgesProcessor.h
  src/storage/mutate/AddVerticesProcessor.cpp
  src/storage/mutate/AddVerticesProcessor.h
  src/storage/query/GetNeighborsProcessor.h
  src/storage/test/CMakeLists.txt
  src/storage/test/IndexScanLimitTest.cpp
  src/storage/test/IndexScanTopNTest.cpp
  src/storage/test/QueryStatsTest.cpp
  src/storage/test/ScanEdgePropBenchmark.cpp
  src/storage/test/StorageClientTest.cpp
  src/storage/test/StorageLookupBenchmark.cpp
  src/storage/test/UpdateVertexTest.cpp
  src/tools/db-dump/DbDumper.cpp
  src/tools/db-dump/DbDumper.h
  src/tools/db-upgrade/DbUpgrader.cpp
  src/tools/db-upgrade/DbUpgrader.h
  src/tools/storage-perf/StorageIntegrityTool.cpp
Labels: ready-for-testing, ready for review

#5370 Backport some enhancement from poc branch
  src/meta/http/MetaHttpReplaceHostHandler.cpp
  src/meta/http/MetaHttpReplaceHostHandler.h
  src/meta/http/test/MetaHttpReplaceHandlerTest.cpp
  src/storage/exec/GetDstBySrcNode.h
  src/storage/mutate/AddEdgesProcessor.cpp
  src/storage/mutate/AddEdgesProcessor.h
  src/storage/mutate/AddVerticesProcessor.cpp
  src/storage/mutate/AddVerticesProcessor.h
  src/storage/query/GetDstBySrcProcessor.cpp
Labels: ready-for-testing, ready for review

#5268 Disable edgelist join
  src/graph/context/ast/CypherAstContext.h
  src/graph/planner/match/MatchSolver.cpp
  src/graph/validator/MatchValidator.cpp
  tests/tck/features/match/PathExpr.feature
  tests/tck/features/match/PathExprRefLocalVariable.feature
Labels: ready-for-testing, doc affected, ready for review

#5404 Fix undefined parameter
  src/graph/optimizer/rule/GeoPredicateIndexScanBaseRule.cpp
  src/graph/util/ExpressionUtils.cpp
  src/graph/util/ExpressionUtils.h
  src/graph/validator/LookupValidator.cpp
  src/graph/validator/MatchValidator.cpp
  tests/tck/features/ttl/TTL.feature
  tests/tck/features/yield/parameter.feature
  tests/tck/ldbc/interactive_workload/ComplexReads.feature
Labels: ready-for-testing, ready for review, auto-sync, cherry-pick-v3.4

#5410 Remove virtual interface in SchemaProviderIf
  src/codec/NebulaCodecImpl.cpp
  src/codec/RowReaderV2.cpp
  src/codec/RowReaderV2.h
  src/codec/RowReaderWrapper.cpp
  src/codec/RowReaderWrapper.h
  src/codec/RowWriterV2.cpp
  src/codec/RowWriterV2.h
  src/codec/include/NebulaCodec.h
  src/codec/test/CMakeLists.txt
  src/codec/test/NebulaCodecTest.cpp
  src/codec/test/ResultSchemaProvider.cpp
  src/codec/test/ResultSchemaProvider.h
  src/codec/test/RowReaderV2Test.cpp
  src/codec/test/RowWriterBenchmark.cpp
  src/codec/test/RowWriterV1.cpp
  src/codec/test/RowWriterV1.h
  src/codec/test/RowWriterV2Test.cpp
  src/codec/test/SchemaWriter.cpp
  src/codec/test/SchemaWriter.h
  src/common/meta/NebulaSchemaProvider.cpp
  src/common/meta/NebulaSchemaProvider.h
  src/common/meta/SchemaProviderIf.cpp
  src/common/utils/IndexKeyUtils.cpp
  src/common/utils/IndexKeyUtils.h
  src/common/utils/test/CMakeLists.txt
  src/graph/validator/FetchEdgesValidator.h
  src/graph/validator/FetchVerticesValidator.h
  src/graph/validator/MutateValidator.h
  src/kvstore/plugins/hbase/HBaseStore.cpp
  src/kvstore/plugins/hbase/HBaseStore.h
  src/meta/test/BalanceIntegrationTest.cpp
  src/mock/AdHocSchemaManager.h
  src/storage/BaseProcessor-inl.h
  src/storage/BaseProcessor.h
  src/storage/CommonUtils.cpp
  src/storage/CommonUtils.h
  src/storage/CompactionFilter.h
  src/storage/exec/IndexScanNode.cpp
  src/storage/exec/IndexScanNode.h
  src/storage/exec/QueryUtils.h
  src/storage/exec/UpdateNode.h
  src/storage/mutate/AddEdgesProcessor.cpp
  src/storage/mutate/AddEdgesProcessor.h
  src/storage/mutate/AddVerticesProcessor.cpp
  src/storage/mutate/AddVerticesProcessor.h
  src/storage/query/GetNeighborsProcessor.cpp
  src/storage/query/QueryBaseProcessor-inl.h
  src/storage/query/QueryBaseProcessor.h
  src/storage/test/CMakeLists.txt
  src/storage/test/QueryStatsTest.cpp
  src/storage/test/StorageClientTest.cpp
  src/tools/db-upgrade/DbUpgrader.cpp
  src/tools/db-upgrade/DbUpgrader.h
Labels: ready-for-testing, ready for review

#5424 Pattern expression supports reference local edge variable
  src/common/function/FunctionManager.cpp
  src/graph/util/ParserUtil.cpp
  src/graph/validator/MatchValidator.cpp
  src/graph/visitor/ValidatePatternExpressionVisitor.cpp
  src/parser/MatchPath.h
  src/storage/query/GetNeighborsProcessor.h
  tests/tck/features/match/Base.feature
  tests/tck/features/match/PathExprRefLocalVariable.feature
Labels: ready-for-testing

#5420 fix GetSnaphot will return nullptr
  src/kvstore/KVStore.h
  src/kvstore/NebulaStore.cpp
  src/kvstore/NebulaStore.h
  src/kvstore/plugins/hbase/HBaseStore.h
  src/storage/test/IndexTestUtil.h
Labels: ready-for-testing, ready for review

#5416 Enable scan in match.
  src/graph/executor/query/JoinExecutor.cpp
  src/graph/executor/query/JoinExecutor.h
  src/graph/executor/query/ScanEdgesExecutor.cpp
  src/graph/executor/query/ScanVerticesExecutor.cpp
  tests/tck/features/bugfix/GetEdgesTransformLimitRule.feature
  tests/tck/features/bugfix/LackFilterGetEdges.feature
  tests/tck/features/match/AllShortestPaths.feature
  tests/tck/features/match/Base.IntVid.feature
  tests/tck/features/match/Base.feature
  tests/tck/features/match/MatchById.IntVid.feature
  tests/tck/features/match/MatchById.feature
  tests/tck/features/match/MultiQueryParts.feature
  tests/tck/features/match/Path.feature
  tests/tck/features/match/Scan.feature
  tests/tck/features/match/SeekByEdge.feature
  tests/tck/features/match/SeekById.feature
  tests/tck/features/match/SeekById.intVid.feature
  tests/tck/features/match/SingleShorestPath.feature
Labels: ready-for-testing, doc affected

#5430 support ttl in ms
  src/storage/CommonUtils.cpp
Labels: ready-for-testing, doc affected, ready for review

#5409 Refactor all path
  src/graph/executor/CMakeLists.txt
  src/graph/executor/Executor.cpp
  src/graph/executor/StorageAccessExecutor.cpp
  src/graph/executor/StorageAccessExecutor.h
  src/graph/executor/algo/AllPathsExecutor.cpp
  src/graph/executor/algo/AllPathsExecutor.h
  src/graph/executor/algo/BatchShortestPath.cpp
  src/graph/executor/algo/ProduceAllPathsExecutor.cpp
  src/graph/executor/algo/ProduceAllPathsExecutor.h
  src/graph/executor/algo/ShortestPathExecutor.cpp
  src/graph/executor/test/FindPathTest.cpp
  src/graph/optimizer/CMakeLists.txt
  src/graph/optimizer/rule/PushFilterDownAllPathsRule.cpp
  src/graph/optimizer/rule/PushFilterDownAllPathsRule.h
  src/graph/optimizer/rule/PushLimitDownAllPathsRule.cpp
  src/graph/optimizer/rule/PushLimitDownAllPathsRule.h
  src/graph/optimizer/rule/RemoveNoopProjectRule.cpp
  src/graph/planner/ngql/PathPlanner.cpp
  src/graph/planner/ngql/PathPlanner.h
  src/graph/planner/plan/Algo.cpp
  src/graph/planner/plan/Algo.h
  src/graph/planner/plan/PlanNode.cpp
  src/graph/planner/plan/PlanNode.h
  src/graph/service/GraphFlags.cpp
  src/graph/service/GraphFlags.h
  src/graph/validator/test/FindPathValidatorTest.cpp
Labels: ready-for-testing, ready for review

#5435 Small Refactoring for expression visitor impl class
  src/common/expression/CMakeLists.txt
  src/common/expression/ExprVisitorImpl.cpp
  src/common/expression/ExprVisitorImpl.h
  src/graph/visitor/CMakeLists.txt
  src/graph/visitor/DeducePropsVisitor.h
  src/graph/visitor/EvaluableExprVisitor.h
  src/graph/visitor/ExtractFilterExprVisitor.h
  src/graph/visitor/ExtractGroupSuiteVisitor.h
  src/graph/visitor/ExtractPropExprVisitor.h
  src/graph/visitor/FindVisitor.h
  src/graph/visitor/PropertyTrackerVisitor.h
  src/graph/visitor/RewriteVisitor.h
  src/graph/visitor/ValidatePatternExpressionVisitor.cpp
  src/graph/visitor/ValidatePatternExpressionVisitor.h
  src/storage/CMakeLists.txt
  src/storage/ExprVisitorBase.cpp
  src/storage/ExprVisitorBase.h
  src/storage/exec/IndexSelectionNode.h
Labels: ready-for-testing, ready for review

#5422 Fix ExtractFilterExprVisitor.
  src/common/expression/LogicalExpression.cpp
  src/graph/visitor/ExtractFilterExprVisitor.cpp
  src/graph/visitor/ExtractFilterExprVisitor.h
  tests/tck/features/optimizer/PushFilterDownBugFixes.feature
Labels: ready-for-testing, ready for review

#5433 Fix the comparisions involving EMPTY.
  src/common/datatypes/Value.cpp
  src/common/expression/test/RelationalExpressionTest.cpp
  src/graph/executor/logic/LoopExecutor.cpp
  tests/tck/features/expression/BugFixWithngdata.feature
Labels: ready-for-testing, doc affected, ready for review

#5439 [Minor] Delete some fatals and comment some CHECKs
  src/graph/visitor/DeduceTypeVisitor.cpp
  src/graph/visitor/ExtractPropExprVisitor.cpp
  src/graph/visitor/PrunePropertiesVisitor.cpp
  src/graph/visitor/PrunePropertiesVisitor.h
Labels: ready-for-testing, ready for review

#5443 Avoid duplicate columns in return
  src/graph/validator/MatchValidator.cpp
  tests/tck/features/match/With.feature
Labels: ready-for-testing, ready for review

#5444 Fix the == operator of Path
  src/common/datatypes/Path.h
  tests/tck/features/match/Path.feature
Labels: ready-for-testing, ready for review

#5440 Allow the expressions like 'v.tag' in return
  src/graph/visitor/PropertyTrackerVisitor.cpp
  src/graph/visitor/PrunePropertiesVisitor.cpp
  tests/tck/features/match/Base.IntVid.feature
  tests/tck/features/match/Base.feature
Labels: ready-for-testing, ready for review

#5437 Generate an plan base on the output
  src/graph/planner/ngql/GoPlanner.cpp
  src/graph/validator/GoValidator.cpp
  src/graph/validator/GoValidator.h
Labels: ready-for-testing, ready for review

#5455 fix standalone version's compile
  src/daemons/StandAloneDaemon.cpp
  src/storage/StorageServer.cpp
Labels: ready-for-testing

#5457 Support subscript in update.
  src/common/function/FunctionManager.cpp
  src/graph/validator/MutateValidator.cpp
  src/storage/query/QueryBaseProcessor-inl.h
  tests/tck/features/bugfix/SubscriptInUpdate.feature
Labels: ready-for-testing

#5451 remove some raft lock for higer performance
  src/kvstore/raftex/RaftPart.h
Labels: ready-for-testing

#5414 Support the tck format for the output of EXPLAIN
  src/graph/validator/ExplainValidator.cpp
  tests/tck/features/explain/ExplainAndProfile.feature
Labels: ready-for-testing

#5460 Add the type check when inserting geography value
  src/codec/RowWriterV2.cpp
  src/codec/RowWriterV2.h
  tests/tck/features/geo/GeoBase.feature
Labels: ready-for-testing

#5458 fix path result without prop
  src/graph/planner/ngql/PathPlanner.cpp
Labels: ready-for-testing, ready for review

#5462 Add salt when generating cluster id to reduce duplication
  src/clients/meta/MetaClient.h
  src/common/meta/ClusterIdManBase.h
Labels: type/enhancement, ready-for-testing, ready for review

#5463 Add some graph performance options in configure file
  conf/nebula-graphd.conf.default
  conf/nebula-graphd.conf.production
Labels: ready-for-testing
