Repository vesoft-inc/nebula, pull requests merged in 2023-02, with the labels that each got.

#5291 Fix the crash caused by failed downcast of iter
  src/graph/executor/algo/SubgraphExecutor.cpp
  src/graph/executor/query/DataCollectExecutor.cpp
  tests/tck/features/bugfix/FixIterCrash.feature
Labels: ready-for-testing, ready for review

#5298 cherry pick 3.4.0 （0201）
  src/graph/executor/algo/SubgraphExecutor.cpp
  src/graph/executor/query/DataCollectExecutor.cpp
  tests/tck/features/bugfix/FixIterCrash.feature
Labels: ready-for-testing

#5271 fix heartbeat handling update old time
  src/kvstore/raftex/RaftPart.cpp
Labels: ready-for-testing

#5301 Enhance property pruner for aggregate
  src/graph/visitor/PropertyTrackerVisitor.cpp
  src/graph/visitor/PropertyTrackerVisitor.h
  src/graph/visitor/PrunePropertiesVisitor.cpp
  tests/tck/features/optimizer/PrunePropertiesRule.feature
Labels: ready-for-testing

#5304 fix meta crashed in #5303
  src/meta/processors/zone/DropHostsProcessor.cpp
  src/meta/processors/zone/MergeZoneProcessor.cpp
Labels: ready-for-testing, ready for review, cherry-pick-v3.4

#5305 Cherry pick 3.4 (0202)
  src/meta/processors/zone/DropHostsProcessor.cpp
  src/meta/processors/zone/MergeZoneProcessor.cpp
Labels: ready-for-testing

#5279 Added TODOs badge to README.md
  README.md
Labels: ready-for-testing

#5306 Cherry pick 3.4 (0130-0131)
  src/common/memory/MemoryUtils.cpp
  tests/tck/conftest.py
  tests/tck/features/geo/GeoBase.feature
  tests/tck/features/lookup/ByIndex.feature
  tests/tck/features/lookup/ByIndex.intVid.feature
  tests/tck/features/lookup/EdgeIndexFullScan.feature
  tests/tck/features/lookup/LookUp.feature
  tests/tck/features/lookup/LookUpLimit.feature
  tests/tck/features/lookup/LookupEdge.feature
  tests/tck/features/lookup/LookupEdge2.feature
  tests/tck/features/lookup/LookupTag.feature
  tests/tck/features/lookup/LookupTag2.feature
  tests/tck/features/lookup/Output.feature
  tests/tck/features/lookup/TagIndexFullScan.feature
  tests/tck/features/lookup/WithYield.feature
  tests/tck/features/lookup/WithYield.intVid.feature
  tests/tck/features/user/User.feature
  tests/tck/slowquery/PermissionViaDifferentService.feature
  tests/tck/slowquery/PermissionViaSameService.feature
Labels: ready-for-testing

#5307 Fix total rpc time in stats
  src/graph/context/Iterator.cpp
  src/graph/executor/algo/BatchShortestPath.cpp
  src/graph/executor/algo/BatchShortestPath.h
  src/graph/executor/algo/ShortestPathBase.cpp
  src/graph/executor/algo/ShortestPathBase.h
  src/graph/executor/algo/ShortestPathExecutor.cpp
  src/graph/executor/algo/SingleShortestPath.cpp
  src/graph/executor/algo/SingleShortestPath.h
  src/graph/executor/query/TraverseExecutor.cpp
  src/graph/executor/query/TraverseExecutor.h
  src/graph/util/Utils.cpp
  src/graph/util/Utils.h
Labels: ready-for-testing

#5299 fix desc subgraph inputVar
  src/graph/planner/plan/Algo.cpp
Labels: ready-for-testing, ready for review

#5308 Improve the traverse executor performance
  src/clients/storage/StorageClientBase.h
  src/common/base/Base.h
  src/common/datatypes/List.h
  src/common/datatypes/Value.cpp
  src/common/datatypes/Value.h
  src/common/datatypes/Vertex.h
  src/graph/context/CMakeLists.txt
  src/graph/context/iterator/GetNbrsRespDataSetIter.cpp
  src/graph/context/iterator/GetNbrsRespDataSetIter.h
  src/graph/executor/query/TraverseExecutor.cpp
  src/graph/executor/query/TraverseExecutor.h
  tests/tck/features/optimizer/PushFilterDownTraverseRule.feature
Labels: ready-for-testing

#5312 Split the graph iterator implementation into different files
  src/graph/context/CMakeLists.txt
  src/graph/context/Iterator.h
  src/graph/context/iterator/DefaultIter.h
  src/graph/context/iterator/GetNeighborsIter.cpp
  src/graph/context/iterator/GetNeighborsIter.h
  src/graph/context/iterator/Iterator.cpp
  src/graph/context/iterator/Iterator.h
  src/graph/context/iterator/PropIter.cpp
  src/graph/context/iterator/PropIter.h
  src/graph/context/iterator/SequentialIter.cpp
  src/graph/context/iterator/SequentialIter.h
  src/graph/gc/GC.cpp
Labels: ready-for-testing

#5290 Remove glr parser
  src/parser/MatchPath.h
  src/parser/parser.yy
  src/parser/scanner.lex
  tests/tck/features/match/Base.feature
  tests/tck/features/match/Unwind.feature
  tests/tck/features/yield/return.feature
  tests/tck/features/yield/yield.IntVid.feature
  tests/tck/features/yield/yield.feature
Labels: ready-for-testing, doc affected, ready for review

#5314 Traverse executor in parallel
  src/graph/context/iterator/GetNbrsRespDataSetIter.h
  src/graph/executor/query/TraverseExecutor.cpp
  src/graph/executor/query/TraverseExecutor.h
Labels: ready-for-testing

#5321 Fix meta's cleanup not work as expected
  src/kvstore/Part.cpp
  src/kvstore/Part.h
Labels: ready-for-testing, ready for review

#5319 support upgrade from V2 to V3.4
  src/daemons/MetaDaemonInit.cpp
  src/meta/MetaVersionMan.cpp
  src/meta/MetaVersionMan.h
Labels: ready-for-testing, cherry-pick-v3.4

#5325 Change leftjoin to hashleftjoin
  src/graph/executor/Executor.cpp
  src/graph/executor/logic/ArgumentExecutor.cpp
  src/graph/executor/test/JoinTest.cpp
  src/graph/optimizer/CMakeLists.txt
  src/graph/optimizer/Optimizer.cpp
  src/graph/optimizer/Optimizer.h
  src/graph/optimizer/rule/PushFilterDownHashLeftJoinRule.cpp
  src/graph/optimizer/rule/PushFilterDownHashLeftJoinRule.h
  src/graph/optimizer/rule/PushFilterDownLeftJoinRule.cpp
  src/graph/optimizer/rule/PushFilterDownLeftJoinRule.h
  src/graph/optimizer/rule/RemoveNoopProjectRule.cpp
  src/graph/planner/ngql/GoPlanner.cpp
  src/graph/planner/plan/PlanNode.cpp
  src/graph/planner/plan/PlanNode.h
  src/graph/planner/plan/Query.cpp
  src/graph/planner/plan/Query.h
  src/graph/validator/test/GroupByValidatorTest.cpp
  src/graph/validator/test/QueryValidatorTest.cpp
  tests/tck/features/go/SimpleCase.feature
  tests/tck/features/match/With.feature
  tests/tck/features/optimizer/PushFilterDownHashLeftJoinRule.feature
  tests/tck/features/optimizer/PushFilterDownLeftJoinRule.feature
  tests/tck/features/optimizer/PushSampleDownRule.feature
Labels: ready-for-testing, ready for review

#5326 fix meta update
  src/daemons/MetaDaemonInit.cpp
  src/meta/MetaVersionMan.cpp
  src/meta/MetaVersionMan.h
  src/meta/processors/admin/HBProcessor.cpp
  src/tools/meta-dump/MetaDumpTool.cpp
Labels: ready-for-testing

#5327 Cherry pick 3.4 （0203-0209）
  src/daemons/MetaDaemonInit.cpp
  src/kvstore/Part.cpp
  src/kvstore/Part.h
  src/meta/MetaVersionMan.cpp
  src/meta/MetaVersionMan.h
  src/meta/processors/admin/HBProcessor.cpp
  src/tools/meta-dump/MetaDumpTool.cpp
Labels: ready-for-testing

#5330 Fix the check of query plan nodes
  src/common/graph/Response.h
  src/graph/planner/plan/PlanNode.h
Labels: ready-for-testing

#5331 Support mold linker
  cmake/ClangTidy.cmake
  cmake/FindMoldLinker.cmake
  cmake/nebula/LinkerConfig.cmake
Labels: ready-for-testing

#5328 DML support parameters
  src/codec/RowWriterV2.cpp
  src/graph/util/SchemaUtil.cpp
  src/graph/util/SchemaUtil.h
  src/graph/validator/MutateValidator.cpp
  src/storage/query/QueryBaseProcessor-inl.h
  tests/tck/features/yield/parameter.feature
Labels: ready-for-testing

#4804 UDF based on existing function infra
  conf/nebula-graphd.conf.default
  src/common/function/CMakeLists.txt
  src/common/function/FunctionManager.cpp
  src/common/function/FunctionManager.h
  src/common/function/FunctionUdfManager.cpp
  src/common/function/FunctionUdfManager.h
  src/common/function/GraphFunction.h
  src/graph/service/GraphFlags.h
  udf/Makefile
  udf/standard_deviation.cpp
  udf/standard_deviation.h
Labels: ready-for-testing

#5336 Fix the crash when lookup parameter expression eval in storage
  src/graph/validator/LookupValidator.cpp
  src/storage/ExprVisitorBase.cpp
  tests/tck/features/yield/parameter.feature
Labels: ready-for-testing, ready for review, affects/v3.4

#5338 Remove the lock from collectResponse in storage client
  src/clients/storage/InternalStorageClient.cpp
  src/clients/storage/StorageClientBase-inl.h
  src/clients/storage/StorageClientBase.h
  src/graph/context/iterator/PropIter.cpp
  src/graph/executor/Executor.h
  src/graph/executor/StorageAccessExecutor.h
  src/graph/executor/query/AppendVerticesExecutor.cpp
  src/graph/executor/query/GetEdgesExecutor.cpp
  src/graph/executor/query/GetVerticesExecutor.cpp
  src/graph/executor/query/IndexScanExecutor.cpp
  src/graph/executor/query/ScanEdgesExecutor.cpp
  src/graph/executor/query/ScanVerticesExecutor.cpp
  src/graph/executor/query/TraverseExecutor.cpp
Labels: ready-for-testing

#5333 add mold linker
  .github/workflows/pull_request.yml
Labels: ready-for-testing

#5345 If user does not exist `desc user xxx` will be raise "User not existed!"
  src/meta/processors/user/AuthenticationProcessor.cpp
  tests/tck/features/user/User.feature
Labels: ready-for-testing

#5360 Support match from id Set and fix some related issues
  src/common/datatypes/Set.cpp
  src/common/datatypes/Set.h
  src/common/function/FunctionManager.cpp
  src/graph/context/ast/CypherAstContext.h
  src/graph/executor/query/FulltextIndexScanExecutor.cpp
  src/graph/planner/match/VertexIdSeek.cpp
  src/graph/planner/match/VertexIdSeek.h
  src/graph/validator/MatchValidator.cpp
  src/graph/visitor/FoldConstantExprVisitor.cpp
  src/graph/visitor/VidExtractVisitor.cpp
  src/graph/visitor/VidExtractVisitor.h
  src/graph/visitor/test/ExtractFilterExprVisitorTest.cpp
  src/graph/visitor/test/FoldConstantExprVisitorTest.cpp
  tests/tck/features/match/MatchById.feature
Labels: ready-for-testing, doc affected, ready for review

#5371 Small fix for parameter tck
  tests/tck/features/yield/parameter.feature
Labels: ready-for-testing, ready for review, auto-sync
