Repository vesoft-inc/nebula, pull requests merged in 2024-10, with the labels that each got.

#5955 fix cmake error in pr #5846
  src/common/base/test/CMakeLists.txt
  src/common/datatypes/test/CMakeLists.txt
  src/common/expression/test/CMakeLists.txt
  src/common/function/FunctionManager.cpp
  src/common/function/test/CMakeLists.txt
  src/common/function/test/FunctionManagerTest.cpp
  src/common/geo/test/CMakeLists.txt
  src/common/utils/test/CMakeLists.txt
Labels: ready-for-testing, ready for review

#5958 option to enable build-in log rotation enabled leveraging glog #5688
  conf/nebula-graphd.conf.default
  conf/nebula-metad.conf.default
  conf/nebula-standalone.conf.default
  conf/nebula-storaged-listener.conf.default
  conf/nebula-storaged.conf.default
  src/daemons/SetupLogging.cpp
Labels: ready-for-testing, hacktoberfest

#5914 Added support for the List/Set type
  src/codec/RowReaderV2.cpp
  src/codec/RowWriterV2.cpp
  src/codec/RowWriterV2.h
  src/common/datatypes/List.h
  src/common/datatypes/Set.h
  src/common/expression/test/AggregateExpressionTest.cpp
  src/common/function/FunctionManager.cpp
  src/common/meta/NebulaSchemaProvider.cpp
  src/common/utils/IndexKeyUtils.h
  src/graph/executor/algo/AllPathsExecutor.cpp
  src/graph/util/SchemaUtil.cpp
  src/graph/validator/SetValidator.cpp
  src/interface/common.thrift
  src/meta/processors/index/CreateEdgeIndexProcessor.cpp
  src/meta/processors/index/CreateTagIndexProcessor.cpp
  src/meta/processors/schema/SchemaUtil.cpp
  src/meta/upgrade/v2/meta.thrift
  src/parser/parser.yy
  src/parser/test/ParserTest.cpp
  tests/tck/features/ddl/Ddl.feature
  tests/tck/features/fetch/FetchEmpty.feature
  tests/tck/features/fetch/FetchVertices.strVid.feature
  tests/tck/features/insert/Insert.feature
  tests/tck/features/insert/InsertIfNotExists.feature
  tests/tck/features/match/Base.feature
  tests/tck/features/schema/Schema.feature
  tests/tck/features/update/Update.feature
Labels: ready-for-testing, doc affected, ready for review

#5953 Enable MULTIUPDATE and LOOKUP | UPDATE
  src/graph/executor/mutate/DeleteExecutor.cpp
  src/graph/executor/mutate/UpdateExecutor.cpp
  src/graph/executor/mutate/UpdateExecutor.h
  src/graph/planner/plan/Mutate.cpp
  src/graph/planner/plan/Mutate.h
  src/graph/service/PermissionCheck.cpp
  src/graph/validator/MutateValidator.cpp
  src/graph/validator/MutateValidator.h
  src/graph/validator/test/MutateValidatorTest.cpp
  src/parser/EdgeKey.h
  src/parser/MutateSentences.cpp
  src/parser/MutateSentences.h
  src/parser/parser.yy
  tests/tck/features/delete/DeleteVertex.IntVid.feature
  tests/tck/features/lookup/LookUpUpdate.feature
  tests/tck/features/update/MultiUpdate.feature
Labels: ready-for-testing
